import type { AppealCapsuleRecord, AuditEvent, BlindAnchorCalibrationRecord, Committee, Competition, CompetitionBlackBoxRecord, FairnessConstitutionalCourtRecord, IntegrityEntropySignalRecord, JudgeProfile, MizanIntegrityPassportRecord, MultiRiwayahRoutingDecisionRecord, Participant, QuranSourceManifestRecord, RecitationDigitalTwinRecord, ResultRecord, ScientificCircuitBreakerRecord, VariantLocusRecord, AcousticVenuePassportRecord, MutashabihatTrapRecord } from '../types';
import { canonicalStringify, hashCanonical } from './trust-protocol';
import { newId, sha256 } from './crypto';
import { resolveReading } from './scientific-core';

export const MIZAN_GLOBAL_INTEGRITY_PROTOCOL_VERSION='MGIP-1.0';

export async function buildCompetitionBlackBox(input:{competitionId:string;events:(AuditEvent|{id:string;timestamp:string;action:string;entityType?:string;entityId?:string;currentStateHash?:string;previousStateHash?:string})[];assurance:CompetitionBlackBoxRecord['assurance']}){
 const ordered=[...input.events].sort((a,b)=>String(a.timestamp).localeCompare(String(b.timestamp))||a.id.localeCompare(b.id));let previous='GENESIS';const streams=new Set<string>();
 for(const e of ordered){streams.add((e as any).entityType||'audit');previous=await sha256(`${previous}|${canonicalStringify({id:e.id,timestamp:e.timestamp,action:e.action,entityType:(e as any).entityType,entityId:(e as any).entityId,currentStateHash:(e as any).currentStateHash})}`)}
 const record:CompetitionBlackBoxRecord={id:newId('blackbox'),competitionId:input.competitionId,createdAt:new Date().toISOString(),eventCount:ordered.length,streams:[...streams].sort(),genesisHash:'GENESIS',headHash:previous,timelineHash:await hashCanonical(ordered.map(e=>({id:e.id,timestamp:e.timestamp,action:e.action,currentStateHash:(e as any).currentStateHash}))),verificationState:'VERIFIED',assurance:input.assurance};return record;
}

const rankResults=(rows:{participantId:string;score:number}[])=>[...rows].sort((a,b)=>b.score-a.score||a.participantId.localeCompare(b.participantId)).map(x=>x.participantId);
export function runFairnessConstitutionalCourt(input:{competitionId:string;results:ResultRecord[];judgeContributions?:{participantId:string;judgeId:string;score:number}[];allowDropExtreme?:boolean;allowedTieBreakAlternative?:boolean}){
 const baseRows=input.results.filter(r=>r.competitionId===input.competitionId).map(r=>({participantId:r.participantId,score:r.finalScore}));const baselineRank=rankResults(baseRows),scenarios:FairnessConstitutionalCourtRecord['scenarios']=[];
 if(input.judgeContributions?.length){const judges=[...new Set(input.judgeContributions.map(x=>x.judgeId))];for(const judgeId of judges){const rows=baseRows.map(row=>{const vals=input.judgeContributions!.filter(x=>x.participantId===row.participantId&&x.judgeId!==judgeId).map(x=>x.score);return {participantId:row.participantId,score:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:row.score}});const scenarioRank=rankResults(rows);const changes=baselineRank.filter((id,i)=>scenarioRank[i]!==id).length;scenarios.push({id:`remove-${judgeId}`,label:'Remove one judge contribution',kind:'REMOVE_JUDGE',baselineRank,scenarioRank,rankChanges:changes,winnerChanged:scenarioRank[0]!==baselineRank[0],notes:'Non-official sensitivity test. It does not alter the sealed result.'})}}
 if(input.allowDropExtreme&&input.judgeContributions?.length){const rows=baseRows.map(row=>{const vals=input.judgeContributions!.filter(x=>x.participantId===row.participantId).map(x=>x.score).sort((a,b)=>a-b);const kept=vals.length>=3?vals.slice(1,-1):vals;return {participantId:row.participantId,score:kept.length?kept.reduce((a,b)=>a+b,0)/kept.length:row.score}});const scenarioRank=rankResults(rows);scenarios.push({id:'drop-extreme',label:'Drop highest and lowest contribution',kind:'DROP_EXTREME',baselineRank,scenarioRank,rankChanges:baselineRank.filter((id,i)=>scenarioRank[i]!==id).length,winnerChanged:scenarioRank[0]!==baselineRank[0],notes:'Applied only because the caller marked this policy variant as permitted.'})}
 if(input.allowedTieBreakAlternative&&baselineRank.length>1){const tied=[...baseRows].sort((a,b)=>b.score-a.score||b.participantId.localeCompare(a.participantId));const scenarioRank=tied.map(x=>x.participantId);scenarios.push({id:'tiebreak-alt',label:'Permitted alternate tie-break ordering',kind:'TIEBREAK_VARIANT',baselineRank,scenarioRank,rankChanges:baselineRank.filter((id,i)=>scenarioRank[i]!==id).length,winnerChanged:scenarioRank[0]!==baselineRank[0],notes:'Sensitivity only; no sealed outcome is mutated.'})}
 const maxMove=Math.max(0,...scenarios.flatMap(s=>s.scenarioRank.map((id,i)=>Math.abs(i-baselineRank.indexOf(id)))));const winnerChanged=scenarios.some(s=>s.winnerChanged);const record:FairnessConstitutionalCourtRecord={id:newId('faircourt'),competitionId:input.competitionId,createdAt:new Date().toISOString(),resultSetHash:'pending',status:winnerChanged||maxMove>1?'REVIEW':'STABLE',scenarios,maximumRankMovement:maxMove,winnerChangedInAnyPermittedScenario:winnerChanged,nonOfficial:true};return record;
}

export function issueAcousticVenuePassport(input:{competitionId:string;venueZone:string;deviceId?:string;createdBy:string;policyVersion:string;measurements:AcousticVenuePassportRecord['measurements'];thresholds:{noiseFloorDbMax?:number;clippingPercentMax?:number;packetLossPercentMax?:number;sampleRateMin?:number;echoScoreMax?:number;snrDbMin?:number}}){
 const checks:AcousticVenuePassportRecord['checks']=[];const add=(id:string,label:string,observed:number|undefined,threshold:number|undefined,pass:(a:number,b:number)=>boolean,unit:string)=>{if(observed===undefined||threshold===undefined)return;checks.push({id,label,observed,threshold,unit,status:pass(observed,threshold)?'PASS':'FAIL'})};
 add('noise','Noise floor',input.measurements.noiseFloorDb,input.thresholds.noiseFloorDbMax,(a,b)=>a<=b,'dB');add('clip','Clipping',input.measurements.clippingPercent,input.thresholds.clippingPercentMax,(a,b)=>a<=b,'%');add('loss','Packet loss',input.measurements.packetLossPercent,input.thresholds.packetLossPercentMax,(a,b)=>a<=b,'%');add('rate','Sample rate',input.measurements.sampleRate,input.thresholds.sampleRateMin,(a,b)=>a>=b,'Hz');add('echo','Echo',input.measurements.echoScore,input.thresholds.echoScoreMax,(a,b)=>a<=b,'score');add('snr','SNR',input.measurements.snrDb,input.thresholds.snrDbMin,(a,b)=>a>=b,'dB');
 if(!checks.length)checks.push({id:'policy',label:'Scientific audio thresholds',status:'REVIEW'});const status=checks.some(x=>x.status==='FAIL')?'FAIL':checks.some(x=>x.status==='REVIEW')?'PASS_WITH_WARNINGS':'PASS';return {id:newId('acoustic'),competitionId:input.competitionId,venueZone:input.venueZone,deviceId:input.deviceId,createdAt:new Date().toISOString(),createdBy:input.createdBy,policyVersion:input.policyVersion,measurements:input.measurements,checks,status,scopeNote:'This passport validates the configured acoustic/device operating envelope only. It is not a health or judge-performance assessment.'} satisfies AcousticVenuePassportRecord;
}

export async function buildRecitationDigitalTwin(input:{competitionId:string;source:QuranSourceManifestRecord;qiraah:string;rawi:string;tariq?:string;wajh?:string;surah:number;ayahStart:number;ayahEnd:number;variantLoci:VariantLocusRecord[];allowedWujuh:string[];phonemeSchemaVersion?:string}){
 if(input.source.certificationState!=='CERTIFIED'||!input.source.packageHash)throw new Error('DIGITAL_TWIN_CERTIFIED_SOURCE_REQUIRED');const loci=input.variantLoci.filter(v=>v.sourceManifestId===input.source.id&&v.surah===input.surah&&v.ayah>=input.ayahStart&&v.ayah<=input.ayahEnd&&v.qiraah===input.qiraah&&v.rawi===input.rawi&&(!input.tariq||v.tariq===input.tariq));const expectedSequenceHash=await hashCanonical({sourcePackageHash:input.source.packageHash,qiraah:input.qiraah,rawi:input.rawi,tariq:input.tariq,wajh:input.wajh,surah:input.surah,ayahStart:input.ayahStart,ayahEnd:input.ayahEnd,loci:loci.map(x=>x.id),allowedWujuh:[...input.allowedWujuh].sort(),phonemeSchemaVersion:input.phonemeSchemaVersion});return {id:newId('twin'),competitionId:input.competitionId,sourceManifestId:input.source.id,sourcePackageHash:input.source.packageHash,qiraah:input.qiraah,rawi:input.rawi,tariq:input.tariq,wajh:input.wajh,surah:input.surah,ayahStart:input.ayahStart,ayahEnd:input.ayahEnd,variantLocusIds:loci.map(x=>x.id),allowedWujuh:[...input.allowedWujuh],phonemeSchemaVersion:input.phonemeSchemaVersion,expectedSequenceHash,createdAt:new Date().toISOString(),state:input.phonemeSchemaVersion?'SOURCE_BOUND':'PENDING_SCIENTIFIC_ENRICHMENT'} satisfies RecitationDigitalTwinRecord;
}

export function mapMutashabihatTrap(input:Omit<MutashabihatTrapRecord,'id'|'createdAt'|'status'> & {approvedBy?:string}){if(input.expected.surah===input.possible.surah&&input.expected.ayah===input.possible.ayah)throw new Error('MUTASHABIHAT_DISTINCT_LOCUS_REQUIRED');return {id:newId('trap'),...input,createdAt:new Date().toISOString(),status:input.approvedBy?'APPROVED':'REVIEW_MAP'} satisfies MutashabihatTrapRecord}

export function multiRiwayahSmartRoute(input:{competitionId:string;participant:Participant;committees:Committee[];judges:JudgeProfile[];queueCounts:Map<string,number>;audioReadyCommitteeIds?:Set<string>;aiCompatibleCommitteeIds?:Set<string>;requireAudio?:boolean;requireAi?:boolean}){
 const reading=resolveReading({riwaya:input.participant.riwaya});const participantReading=reading?`${reading.qiraah} / ${reading.rawi}`:input.participant.riwaya;const candidates=input.committees.filter(c=>c.competitionId===input.competitionId&&c.status!=='offline').map(c=>{const panel=input.judges.filter(j=>c.judgeIds.includes(j.id)||c.judgeIds.includes(j.userId));const readingOk=panel.length>0&&panel.every(j=>j.certifiedRiwayat.some(r=>r.toLowerCase().includes((reading?.rawi||input.participant.riwaya).toLowerCase().split(' ')[0])));const audioOk=!input.requireAudio||input.audioReadyCommitteeIds?.has(c.id)===true;const aiOk=!input.requireAi||input.aiCompatibleCommitteeIds?.has(c.id)===true;const reasons:string[]=[];if(!readingOk)reasons.push('Reading-qualified panel unavailable');if(!audioOk)reasons.push('Approved audio path unavailable');if(!aiOk)reasons.push('Configured AI scope unavailable');const queue=input.queueCounts.get(c.id)||0;const score=readingOk&&audioOk&&aiOk?100-Math.min(60,queue*5)-Math.min(20,c.averageSessionMinutes):0;return {committeeId:c.id,eligible:readingOk&&audioOk&&aiOk,score,reasons:reasons.length?reasons:[`Eligible; operational load ${queue}`]}}).sort((a,b)=>b.score-a.score||a.committeeId.localeCompare(b.committeeId));const selected=candidates.find(x=>x.eligible);return {id:newId('route'),competitionId:input.competitionId,participantId:input.participant.id,participantReading,createdAt:new Date().toISOString(),candidates,selectedCommitteeId:selected?.committeeId,status:selected?'ROUTED':'NO_ELIGIBLE_COMMITTEE',explanation:selected?'Best eligible committee by reading qualification and configured operational requirements.':'No committee satisfies the exact configured reading and operational scope.'} satisfies MultiRiwayahRoutingDecisionRecord;
}

export async function buildAppealCapsule(input:{competitionId:string;participantId:string;appealId?:string;createdBy:string;evidence:{kind:string;ref:string;private?:boolean}[]}){const included=input.evidence.filter(x=>!x.private),excluded=input.evidence.filter(x=>x.private);const capsuleHash=await hashCanonical({competitionId:input.competitionId,participantId:input.participantId,appealId:input.appealId,evidence:included.map(x=>({kind:x.kind,ref:x.ref}))});return {id:newId('appealcap'),competitionId:input.competitionId,participantId:input.participantId,appealId:input.appealId,createdAt:new Date().toISOString(),createdBy:input.createdBy,privacyScope:'APPEAL_PANEL_ONLY',evidenceRefs:included.map(x=>x.ref),includedKinds:[...new Set(included.map(x=>x.kind))],excludedKinds:[...new Set(excluded.map(x=>x.kind))],capsuleHash,status:'READY'} satisfies AppealCapsuleRecord}

export function blindAnchorCalibration(input:{competitionId:string;rehearsalId?:string;anchorSetVersion:string;samples:{committeeId:string;judgeId:string;judgeScore:number;expertScore:number;tolerance:number}[]}){const by=new Map<string,typeof input.samples>();for(const s of input.samples)by.set(s.committeeId,[...(by.get(s.committeeId)||[]),s]);const summaries=[...by.entries()].map(([committeeId,rows])=>{const deviations=rows.map(x=>Math.abs(x.judgeScore-x.expertScore)).sort((a,b)=>a-b);const mid=Math.floor(deviations.length/2),median=deviations.length%2?deviations[mid]:(deviations[mid-1]+deviations[mid])/2;const agreement=rows.filter(x=>Math.abs(x.judgeScore-x.expertScore)<=x.tolerance).length/Math.max(1,rows.length);return {committeeId,sampleCount:rows.length,medianDeviation:Number(median.toFixed(3)),agreementRate:Number(agreement.toFixed(3)),status:(agreement>=.8?'CALIBRATED':'REVIEW') as BlindAnchorCalibrationRecord['committeeSummaries'][number]['status']}});const allDev=input.samples.map(x=>Math.abs(x.judgeScore-x.expertScore)).sort((a,b)=>a-b);const mid=Math.floor(allDev.length/2),med=allDev.length?(allDev.length%2?allDev[mid]:(allDev[mid-1]+allDev[mid])/2):0,agree=input.samples.length?input.samples.filter(x=>Math.abs(x.judgeScore-x.expertScore)<=x.tolerance).length/input.samples.length:0;return {id:newId('anchor'),competitionId:input.competitionId,rehearsalId:input.rehearsalId,anchorSetVersion:input.anchorSetVersion,createdAt:new Date().toISOString(),nonOfficial:true,judgeCount:new Set(input.samples.map(x=>x.judgeId)).size,aggregateMedianDeviation:Number(med.toFixed(3)),aggregateAgreementRate:Number(agree.toFixed(3)),committeeSummaries:summaries,individualRankingProhibited:true} satisfies BlindAnchorCalibrationRecord}

export function integrityEntropyRadar(input:{competitionId:string;windowStart:string;windowEnd:string;events:{kind:IntegrityEntropySignalRecord['signals'][number]['kind'];entityRef:string}[];reviewThresholds:Partial<Record<IntegrityEntropySignalRecord['signals'][number]['kind'],number>>;highThresholds?:Partial<Record<IntegrityEntropySignalRecord['signals'][number]['kind'],number>>}){const counts=new Map<string,{kind:IntegrityEntropySignalRecord['signals'][number]['kind'];entityRef:string;count:number}>();for(const e of input.events){const k=`${e.kind}|${e.entityRef}`,x=counts.get(k)||{...e,count:0};x.count++;counts.set(k,x)}const signals=[...counts.values()].flatMap(x=>{const review=input.reviewThresholds[x.kind];if(review===undefined||x.count<review)return [];const high=input.highThresholds?.[x.kind];return [{...x,severity:(high!==undefined&&x.count>=high?'HIGH':'REVIEW') as IntegrityEntropySignalRecord['signals'][number]['severity'],explanation:'Operational pattern exceeds the configured review threshold. This is not an accusation or finding of misconduct.'}]});return {id:newId('entropy'),competitionId:input.competitionId,createdAt:new Date().toISOString(),windowStart:input.windowStart,windowEnd:input.windowEnd,signals,status:signals.length?'REVIEW':'CLEAR',accusationProhibited:true} satisfies IntegrityEntropySignalRecord}

export function tripScientificCircuitBreaker(input:Omit<ScientificCircuitBreakerRecord,'id'|'createdAt'|'historicalRecordsRewritten'|'status'>){return {id:newId('breaker'),...input,createdAt:new Date().toISOString(),historicalRecordsRewritten:false,status:'ACTIVE'} satisfies ScientificCircuitBreakerRecord}

export async function issueMizanIntegrityPassport(input:{competition:Competition;quranSource?:QuranSourceManifestRecord;fairDrawAlgorithm?:string;fairDrawCommitment?:string;rehearsalStatus?:string;quorumPolicy?:string;resultRootHash?:string;certificateVerifier?:string;auditAssurance?:string}){const claims={quranSourceAuthority:input.quranSource?.sourceAuthority,quranSourcePackageHash:input.quranSource?.packageHash,fairDrawAlgorithm:input.fairDrawAlgorithm,fairDrawCommitment:input.fairDrawCommitment,rehearsalStatus:input.rehearsalStatus,quorumPolicy:input.quorumPolicy,resultRootHash:input.resultRootHash,certificateVerifier:input.certificateVerifier,auditAssurance:input.auditAssurance};const passportHash=await hashCanonical({competitionId:input.competition.id,protocolVersion:MIZAN_GLOBAL_INTEGRITY_PROTOCOL_VERSION,claims,privacy:{participantIdentities:false,judgeScores:false,rawAudio:false}});return {id:newId('integritypassport'),competitionId:input.competition.id,createdAt:new Date().toISOString(),competitionName:input.competition.nameArabic||input.competition.name,protocolVersion:MIZAN_GLOBAL_INTEGRITY_PROTOCOL_VERSION,publicClaims:claims,privacy:{participantIdentities:false,judgeScores:false,rawAudio:false},passportHash,status:'ISSUED'} satisfies MizanIntegrityPassportRecord}

export type MgipControlState='READY'|'REVIEW'|'BLOCKED';
export interface MgipControlAssessment{id:string;order:number;titleArabic:string;titleEnglish:string;state:MgipControlState;evidenceRefs:string[];reasonArabic:string;reasonEnglish:string;required:boolean}
export interface MgipProtocolAssessment{version:string;competitionId:string;createdAt:string;overall:'READY'|'READY_WITH_REVIEW'|'BLOCKED';controls:MgipControlAssessment[];readyCount:number;reviewCount:number;blockedCount:number;protocolHash:string}
export async function assessMizanGlobalIntegrityProtocol(input:{competitionId:string;certifiedQuranSource:boolean;policyVersion?:string;fairDrawVerified:boolean;secureQuestionRuntime:boolean;presenceQuorumEvidence:boolean;independentJudgeLocks:boolean;continuityEvidence:boolean;blackBoxEvidence:boolean;sealedResult:boolean;proofCertificate:boolean;appealEvidence:boolean;aiAdvisoryOnly:boolean;integrityPassportIssued:boolean;evidenceRefs?:Partial<Record<string,string[]>>}):Promise<MgipProtocolAssessment>{
 const refs=(id:string)=>input.evidenceRefs?.[id]||[];const row=(id:string,order:number,ar:string,en:string,ok:boolean,review:boolean,arReason:string,enReason:string,required=true):MgipControlAssessment=>({id,order,titleArabic:ar,titleEnglish:en,state:ok?'READY':review?'REVIEW':'BLOCKED',evidenceRefs:refs(id),reasonArabic:arReason,reasonEnglish:enReason,required});
 const c=[
  row('source',1,'المصدر القرآني','Quran provenance',input.certifiedQuranSource,false,input.certifiedQuranSource?'مصدر معتمد ومحدد النسخة.':'لا يوجد مصدر قرآني معتمد محدد النسخة.',input.certifiedQuranSource?'Certified immutable Quran source is bound.':'No certified immutable Quran source is bound.'),
  row('policy',2,'القواعد','Policy',!!input.policyVersion,false,input.policyVersion?`نسخة السياسة ${input.policyVersion}`:'نسخة السياسة غير محددة.',input.policyVersion?`Policy version ${input.policyVersion}`:'Policy version is not fixed.'),
  row('fairdraw',3,'السحب','FairDraw',input.fairDrawVerified,false,input.fairDrawVerified?'إثبات السحب متحقق.':'لا يوجد إثبات FairDraw متحقق.',input.fairDrawVerified?'Verified FairDraw proof exists.':'No verified FairDraw proof exists.'),
  row('question',4,'عهدة السؤال','Question custody',input.secureQuestionRuntime,false,input.secureQuestionRuntime?'السؤال يبقى خادميًا حتى الحضور والنصاب.':'مسار السؤال الخادمي غير مثبت.',input.secureQuestionRuntime?'Question plaintext remains server-held until presence + quorum.':'Server-held question custody is not proven.'),
  row('quorum',5,'الحضور والنصاب','Presence & quorum',input.presenceQuorumEvidence,true,input.presenceQuorumEvidence?'يوجد دليل كشف بعد الحضور والنصاب.':'لا يوجد كشف بعد في هذه المرحلة؛ يبقى للمراقبة.',input.presenceQuorumEvidence?'Reveal evidence proves presence + quorum.':'No reveal has occurred yet; this remains a live control.'),
  row('independence',6,'استقلال المحكم','Independent judgment',input.independentJudgeLocks,true,input.independentJudgeLocks?'أحكام مستقلة مقفلة.':'لم تكتمل أقفال المحكمين بعد.',input.independentJudgeLocks?'Independent human locks are evidenced.':'Independent judge locks are not complete yet.'),
  row('continuity',7,'الاستمرارية','Continuity',input.continuityEvidence,true,input.continuityEvidence?'يوجد checkpoint/استعادة موثقة.':'لا يوجد حادث يتطلب استعادة، أو لم تُنشأ نقطة استمرارية بعد.',input.continuityEvidence?'Continuity evidence exists.':'No recovery event exists, or no checkpoint has been created yet.',false),
  row('blackbox',8,'الصندوق الأسود','Black box',input.blackBoxEvidence,true,input.blackBoxEvidence?'لقطة سجل أدلة موجودة.':'لم تُلتقط لقطة الصندوق الأسود بعد.',input.blackBoxEvidence?'Evidence timeline snapshot exists.':'Black-box snapshot has not been captured yet.'),
  row('result',9,'ختم النتيجة','Result seal',input.sealedResult,true,input.sealedResult?'النتيجة مختومة.':'النتيجة لم تصل مرحلة الختم بعد.',input.sealedResult?'Result seal exists.':'Result has not reached sealing yet.'),
  row('proof',10,'الإثبات المحمول','Portable proof',input.proofCertificate,true,input.proofCertificate?'شهادة/إثبات قابل للتحقق موجود.':'لم تصدر شهادة إثبات بعد.',input.proofCertificate?'Proof-carrying certificate exists.':'No proof-carrying certificate has been issued yet.'),
  row('appeal',11,'حق الاعتراض','Appeal evidence',input.appealEvidence,true,input.appealEvidence?'دليل اعتراض محفوظ عند الحاجة.':'لا توجد قضية اعتراض حالية.',input.appealEvidence?'Appeal evidence capsule exists where needed.':'No current appeal evidence case.',false),
  row('ai',12,'حدود الذكاء الاصطناعي','AI boundary',input.aiAdvisoryOnly,false,input.aiAdvisoryOnly?'AI استشاري ولا يحكم رسميًا.':'حدود AI غير مثبتة.',input.aiAdvisoryOnly?'AI remains advisory and cannot produce the official score.':'AI advisory boundary is not proven.'),
  row('passport',13,'جواز النزاهة','Integrity passport',input.integrityPassportIssued,true,input.integrityPassportIssued?'جواز النزاهة صادر.':'جواز النزاهة يصدر عند اكتمال أدلة المسابقة.',input.integrityPassportIssued?'Integrity passport is issued.':'Integrity passport is issued after competition evidence matures.',false)
 ];
 const blocked=c.filter(x=>x.required&&x.state==='BLOCKED').length,review=c.filter(x=>x.state==='REVIEW').length,ready=c.filter(x=>x.state==='READY').length;const overall=blocked?'BLOCKED':review?'READY_WITH_REVIEW':'READY';const protocolHash=await hashCanonical({version:MIZAN_GLOBAL_INTEGRITY_PROTOCOL_VERSION,competitionId:input.competitionId,controls:c.map(x=>({id:x.id,state:x.state,evidenceRefs:x.evidenceRefs}))});return {version:MIZAN_GLOBAL_INTEGRITY_PROTOCOL_VERSION,competitionId:input.competitionId,createdAt:new Date().toISOString(),overall,controls:c,readyCount:ready,reviewCount:review,blockedCount:blocked,protocolHash};
}
