import type { AuditEvent, CertifiedVenueSealRecord, IntegrityCinemaRecord, IntegrityCinemaScene } from '../types';
import {newId} from './crypto';
import {hashCanonical} from './trust-protocol';

const kindOf=(action:string):IntegrityCinemaScene['kind']=>/check.?in|arrival|gate/i.test(action)?'ARRIVAL':/queue|transfer|route/i.test(action)?'QUEUE':/question|reveal|fairdraw/i.test(action)?'QUESTION':/judge|score|lock/i.test(action)?'JUDGING':/power|network|recover|checkpoint|continuity/i.test(action)?'CONTINUITY':/result|seal|certificate/i.test(action)?'RESULT':/incident|exception/i.test(action)?'INCIDENT':'AUDIT';
export async function buildIntegrityCinema(input:{competitionId:string;events:Pick<AuditEvent,'id'|'timestamp'|'action'|'entityType'|'entityId'>[];blackBoxHeadHash?:string}){
 const ordered=[...input.events].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.id.localeCompare(b.id));const scenes:IntegrityCinemaScene[]=[];
 for(const e of ordered){const kind=kindOf(e.action),sceneHash=await hashCanonical({competitionId:input.competitionId,eventId:e.id,timestamp:e.timestamp,action:e.action,entityType:e.entityType,entityId:e.entityId});scenes.push({id:`scene-${e.id}`,timestamp:e.timestamp,kind,titleArabic:arabicTitle(kind),titleEnglish:englishTitle(kind),evidenceRefs:[e.id],sceneHash})}
 const cinemaHash=await hashCanonical({competitionId:input.competitionId,blackBoxHeadHash:input.blackBoxHeadHash,scenes:scenes.map(s=>({id:s.id,sceneHash:s.sceneHash}))});return {id:newId('cinema'),competitionId:input.competitionId,createdAt:new Date().toISOString(),blackBoxHeadHash:input.blackBoxHeadHash,sceneCount:scenes.length,scenes,cinemaHash,privacySafe:true,status:scenes.length?'READY':'REVIEW'} satisfies IntegrityCinemaRecord;
}
function arabicTitle(k:IntegrityCinemaScene['kind']){return ({ARRIVAL:'الوصول',QUEUE:'الدور',QUESTION:'عهدة السؤال',JUDGING:'التحكيم المستقل',CONTINUITY:'الاستمرارية',RESULT:'النتيجة',AUDIT:'دليل تشغيلي',INCIDENT:'حادث موثق'} as Record<string,string>)[k]}
function englishTitle(k:IntegrityCinemaScene['kind']){return ({ARRIVAL:'Arrival',QUEUE:'Queue',QUESTION:'Question custody',JUDGING:'Independent judging',CONTINUITY:'Continuity',RESULT:'Result',AUDIT:'Operational evidence',INCIDENT:'Documented incident'} as Record<string,string>)[k]}

export async function certifyVenue(input:{competitionId:string;venueZone:string;createdBy:string;acousticPassport?:{id:string;status:string};devices:{id:string;status:string;softwareVersion:string;role?:string;zone?:string}[];sourcePackageHash?:string;edgeReady:boolean;offlinePassReady:boolean;recoveryTested:boolean;printerReady?:boolean;audioDeviceFingerprint?:string}){
 const checks:CertifiedVenueSealRecord['checks']=[
  {id:'acoustic',labelArabic:'البيئة الصوتية',labelEnglish:'Acoustic envelope',status:input.acousticPassport?.status==='PASS'?'PASS':input.acousticPassport?.status==='PASS_WITH_WARNINGS'?'REVIEW':'FAIL',evidence:input.acousticPassport?.id},
  {id:'devices',labelArabic:'الأجهزة الحرجة',labelEnglish:'Critical devices',status:input.devices.some(d=>d.status==='offline'||d.status==='revoked')?'FAIL':input.devices.some(d=>d.status==='degraded')?'REVIEW':'PASS',evidence:`${input.devices.length} devices`},
  {id:'edge',labelArabic:'الاستمرارية المحلية',labelEnglish:'Local continuity',status:input.edgeReady?'PASS':'FAIL'},
  {id:'pass',labelArabic:'التحقق دون اتصال',labelEnglish:'Offline pass verification',status:input.offlinePassReady?'PASS':'FAIL'},
  {id:'recovery',labelArabic:'اختبار الاستعادة',labelEnglish:'Recovery test',status:input.recoveryTested?'PASS':'FAIL'},
  {id:'source',labelArabic:'مصدر القرآن',labelEnglish:'Quran source',status:input.sourcePackageHash?'PASS':'FAIL',evidence:input.sourcePackageHash?.slice(0,20)},
  {id:'printer',labelArabic:'الطباعة الاحتياطية',labelEnglish:'Fallback printing',status:input.printerReady===false?'REVIEW':'PASS'},
 ];
 const deviceFingerprint=await hashCanonical(input.devices.map(d=>({id:d.id,status:d.status,softwareVersion:d.softwareVersion,role:d.role,zone:d.zone})).sort((a,b)=>a.id.localeCompare(b.id))),softwareFingerprint=await hashCanonical(input.devices.map(d=>({id:d.id,softwareVersion:d.softwareVersion})).sort((a,b)=>a.id.localeCompare(b.id)));const baseline={deviceFingerprint,softwareFingerprint,audioFingerprint:input.audioDeviceFingerprint,sourcePackageHash:input.sourcePackageHash,edgeCheckpoint:input.edgeReady?'EDGE_READY':undefined};const status=checks.some(c=>c.status==='FAIL')?'NOT_READY':checks.some(c=>c.status==='REVIEW')?'READY_WITH_REVIEW':'CERTIFIED_READY';const sealHash=await hashCanonical({competitionId:input.competitionId,venueZone:input.venueZone,checks,baseline});return {id:newId('venue-seal'),competitionId:input.competitionId,venueZone:input.venueZone,createdAt:new Date().toISOString(),createdBy:input.createdBy,acousticPassportId:input.acousticPassport?.id,checks,status,baseline,sealHash} satisfies CertifiedVenueSealRecord;
}

export async function verifyVenueBaseline(seal:CertifiedVenueSealRecord,input:{devices:{id:string;status:string;softwareVersion:string;role?:string;zone?:string}[];audioDeviceFingerprint?:string;sourcePackageHash?:string}){const deviceFingerprint=await hashCanonical(input.devices.map(d=>({id:d.id,status:d.status,softwareVersion:d.softwareVersion,role:d.role,zone:d.zone})).sort((a,b)=>a.id.localeCompare(b.id))),softwareFingerprint=await hashCanonical(input.devices.map(d=>({id:d.id,softwareVersion:d.softwareVersion})).sort((a,b)=>a.id.localeCompare(b.id)));const changes:string[]=[];if(deviceFingerprint!==seal.baseline.deviceFingerprint)changes.push('DEVICE_BASELINE_CHANGED');if(softwareFingerprint!==seal.baseline.softwareFingerprint)changes.push('SOFTWARE_BASELINE_CHANGED');if(seal.baseline.audioFingerprint&&input.audioDeviceFingerprint!==seal.baseline.audioFingerprint)changes.push('AUDIO_DEVICE_CHANGED');if(seal.baseline.sourcePackageHash&&input.sourcePackageHash!==seal.baseline.sourcePackageHash)changes.push('QURAN_SOURCE_CHANGED');return {valid:changes.length===0,changes}}
