/*
 * مُولَّد — لا يُحرَّر بيد. `npm run quran:crosswalk-coverage`
 *
 * ملخّصُ تغطية الجسر لكلّ رواية، محسوبٌ من جدول الأدلّة الكامل وقتَ البناء. يقرؤه
 * المتصفّح فلا يحمل الأدلّة نفسها، ويقارنه اختبارٌ بمصدره فلا يفترقان.
 */

import type { CrosswalkCoverage } from './quran-locus-crosswalk';

export const GENERATED_CROSSWALK_COVERAGE: Readonly<Record<string, CrosswalkCoverage>> = Object.freeze({
  "qalun": {
    "rawiId": "qalun",
    "countSystem": "MADANI_AKHIR",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "warsh": {
    "rawiId": "warsh",
    "countSystem": "MADANI_AKHIR",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "al-bazzi": {
    "rawiId": "al-bazzi",
    "countSystem": "MAKKI_IBN_KATHIR_DELIVERY",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 2550,
    "unresolvedLoci": 3686,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [
      2,
      4,
      5,
      6,
      8,
      9,
      11,
      13,
      14,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      26,
      27,
      30,
      31,
      36,
      38,
      39,
      40,
      41,
      42,
      44,
      45,
      46,
      47,
      52,
      53,
      55,
      56,
      57,
      58,
      67,
      71,
      74,
      75,
      78,
      79,
      89,
      96,
      97,
      99,
      101,
      106,
      107,
      112,
      114
    ],
    "mappingComplete": false,
    "questionSafe": false,
    "blockers": [
      "CROSSWALK_UNRESOLVED_LOCI:3686"
    ]
  },
  "qunbul": {
    "rawiId": "qunbul",
    "countSystem": "MAKKI_IBN_KATHIR_DELIVERY",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 2550,
    "unresolvedLoci": 3686,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [
      2,
      4,
      5,
      6,
      8,
      9,
      11,
      13,
      14,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      26,
      27,
      30,
      31,
      36,
      38,
      39,
      40,
      41,
      42,
      44,
      45,
      46,
      47,
      52,
      53,
      55,
      56,
      57,
      58,
      67,
      71,
      74,
      75,
      78,
      79,
      89,
      96,
      97,
      99,
      101,
      106,
      107,
      112,
      114
    ],
    "mappingComplete": false,
    "questionSafe": false,
    "blockers": [
      "CROSSWALK_UNRESOLVED_LOCI:3686"
    ]
  },
  "al-duri-abu-amr": {
    "rawiId": "al-duri-abu-amr",
    "countSystem": "BASRI_ABU_AMR_DELIVERY",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 3074,
    "unresolvedLoci": 3162,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [
      2,
      4,
      5,
      6,
      8,
      9,
      11,
      13,
      14,
      17,
      18,
      20,
      21,
      22,
      23,
      24,
      27,
      31,
      36,
      38,
      39,
      40,
      41,
      42,
      44,
      45,
      46,
      47,
      52,
      53,
      55,
      56,
      57,
      71,
      75,
      79,
      86,
      89,
      91,
      96,
      101,
      106,
      107
    ],
    "mappingComplete": false,
    "questionSafe": false,
    "blockers": [
      "CROSSWALK_UNRESOLVED_LOCI:3162"
    ]
  },
  "al-susi": {
    "rawiId": "al-susi",
    "countSystem": "BASRI_ABU_AMR_DELIVERY",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 3074,
    "unresolvedLoci": 3162,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [
      2,
      4,
      5,
      6,
      8,
      9,
      11,
      13,
      14,
      17,
      18,
      20,
      21,
      22,
      23,
      24,
      27,
      31,
      36,
      38,
      39,
      40,
      41,
      42,
      44,
      45,
      46,
      47,
      52,
      53,
      55,
      56,
      57,
      71,
      75,
      79,
      86,
      89,
      91,
      96,
      101,
      106,
      107
    ],
    "mappingComplete": false,
    "questionSafe": false,
    "blockers": [
      "CROSSWALK_UNRESOLVED_LOCI:3162"
    ]
  },
  "hisham": {
    "rawiId": "hisham",
    "countSystem": "DIMASHQI",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "ibn-dhakwan": {
    "rawiId": "ibn-dhakwan",
    "countSystem": "DIMASHQI",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "shubah": {
    "rawiId": "shubah",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_MIRROR_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "hafs": {
    "rawiId": "hafs",
    "countSystem": "KUFIC",
    "countAssurance": "CANONICAL_BY_DEFINITION",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "khalaf-hamzah": {
    "rawiId": "khalaf-hamzah",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "khallad": {
    "rawiId": "khallad",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "abu-al-harith": {
    "rawiId": "abu-al-harith",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "al-duri-kisai": {
    "rawiId": "al-duri-kisai",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "ibn-wardan": {
    "rawiId": "ibn-wardan",
    "countSystem": "MADANI_AWWAL",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "ibn-jammaz": {
    "rawiId": "ibn-jammaz",
    "countSystem": "MADANI_AWWAL",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "ruways": {
    "rawiId": "ruways",
    "countSystem": "BASRI_YAQUB_RUWAYS",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "rawh": {
    "rawiId": "rawh",
    "countSystem": "BASRI_YAQUB_RAWH",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 2436,
    "unresolvedLoci": 3800,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [
      2,
      4,
      5,
      6,
      7,
      8,
      9,
      11,
      13,
      14,
      17,
      18,
      20,
      21,
      22,
      23,
      26,
      27,
      32,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      44,
      45,
      46,
      47,
      52,
      53,
      55,
      56,
      65,
      69,
      71,
      73,
      75,
      78,
      79,
      80,
      89,
      98,
      99,
      101
    ],
    "mappingComplete": false,
    "questionSafe": false,
    "blockers": [
      "CROSSWALK_UNRESOLVED_LOCI:3800"
    ]
  },
  "ishaq": {
    "rawiId": "ishaq",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  },
  "idris": {
    "rawiId": "idris",
    "countSystem": "KUFIC",
    "countAssurance": "VERIFIED_FROM_PINNED_ARTIFACT",
    "canonicalAyahTotal": 6236,
    "resolvedLoci": 6236,
    "unresolvedLoci": 0,
    "assumedLoci": 0,
    "surahsRequiringEvidence": [],
    "mappingComplete": true,
    "questionSafe": true,
    "blockers": []
  }
});

export const GENERATED_CROSSWALK_COVERAGE_RAWI_IDS: readonly string[] = Object.freeze(["qalun","warsh","al-bazzi","qunbul","al-duri-abu-amr","al-susi","hisham","ibn-dhakwan","shubah","hafs","khalaf-hamzah","khallad","abu-al-harith","al-duri-kisai","ibn-wardan","ibn-jammaz","ruways","rawh","ishaq","idris"]);
