import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Check, CircleDot, CornerDownLeft, RotateCcw, SkipForward, Sparkles, Volume2, Mic, MicOff, LockKeyhole, UserCheck, UsersRound, ShieldCheck, Square } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { getCompetitionPolicy, getEnabledJudgeActions } from '../../lib/competition-config';
import { openingAudioWindow, selectApprovedOpeningAudio } from '../../lib/judging-integrity';
import { certifiedCapabilityFor, resolveReading } from '../../lib/scientific-core';
import { Button } from '../design-system/Button';
import { Badge } from '../design-system/Badge';

const iconFor=(kind?:string)=> kind==='error'?AlertTriangle:kind==='open'?CornerDownLeft:kind==='repeat'?RotateCcw:kind==='tajweed'?Sparkles:kind==='stop'?CircleDot:AlertTriangle;

export const JudgeOS: React.FC = () => {
 const store=useAppStore();
 const {language,competition,activeSession,recordJudgeEvent,undoLastJudgeEvent,lockAndSubmitAssessment,nextQuestion,participants,startSessionForParticipant,registerAudioRecording}=store;
 const ar=language==='ar'; const policy=getCompetitionPolicy(competition); const actions=getEnabledJudgeActions(competition);
 const participant=activeSession.participant; const q=activeSession.questionSelection?.questions[activeSession.currentQuestionIndex];
 const gate=store.questionRevealGates.find(g=>g.sessionId===activeSession.sessionId&&g.questionIndex===activeSession.currentQuestionIndex);
 const questionRevealed=gate?.status==='REVEALED';
 const ruleSet=useMemo(()=>competition.ruleSets?.find(r=>r.id===competition.categories.find(c=>c.id===participant?.categoryId)?.ruleSetId)||competition.ruleSet,[competition,participant?.categoryId]);
 const judge=store.judges.find(j=>j.userId===store.currentUser.id || j.id===store.currentUser.id);
 const visibleCriteria=ruleSet.criteria.filter(c=> policy.judging.mode==='all_judges_all_criteria' || !judge || judge.specialty==='all' || c.assignedJudgeType===judge.specialty || (policy.judging.mode==='hybrid' && c.assignedJudgeType==='all'));
 const [directScores,setDirectScores]=useState<Record<string,number>>({});
 const [audioState,setAudioState]=useState<'not_ready'|'requesting'|'ready'|'failed'>(policy.judging.requireAudioRecording?'not_ready':'ready');
 const [openingAudioState,setOpeningAudioState]=useState<'idle'|'playing'|'unavailable'|'failed'>('idle');
 const recorderRef=useRef<MediaRecorder|null>(null); const streamRef=useRef<MediaStream|null>(null); const chunksRef=useRef<Blob[]>([]); const audioStartedAt=useRef<string>(''); const promptAudioRef=useRef<HTMLAudioElement|null>(null); const transitionAudioRef=useRef<HTMLAudioElement|null>(null);
 useEffect(()=>{setDirectScores(Object.fromEntries(visibleCriteria.map(c=>[c.id,c.maxScore])))},[activeSession.sessionId,ruleSet.id,judge?.id]);
 useEffect(()=>{ if(recorderRef.current?.state==='recording')recorderRef.current.stop(); streamRef.current?.getTracks().forEach(t=>t.stop()); recorderRef.current=null;streamRef.current=null;chunksRef.current=[];promptAudioRef.current?.pause();promptAudioRef.current=null;transitionAudioRef.current?.pause();transitionAudioRef.current=null;setOpeningAudioState('idle');setAudioState(policy.judging.requireAudioRecording?'not_ready':'ready'); },[activeSession.sessionId,policy.judging.requireAudioRecording]);
 useEffect(()=>{promptAudioRef.current?.pause();promptAudioRef.current=null;setOpeningAudioState('idle')},[activeSession.currentQuestionIndex]);
 const prepareAudio=async()=>{ if(!policy.judging.requireAudioRecording){setAudioState('ready');return;} if(!navigator.mediaDevices?.getUserMedia){setAudioState('failed');return;} setAudioState('requesting'); try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});streamRef.current=stream;const mime=['audio/webm;codecs=opus','audio/webm','audio/ogg'].find(m=>typeof MediaRecorder!=='undefined'&&MediaRecorder.isTypeSupported(m));const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorderRef.current=recorder;chunksRef.current=[];audioStartedAt.current=new Date().toISOString();recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.start(1500);setAudioState('ready');}catch{setAudioState('failed')}};
 const finalizeAudio=async()=>{const recorder=recorderRef.current;if(!policy.judging.requireAudioRecording||!recorder||recorder.state!=='recording')return;await new Promise<void>(resolve=>{recorder.onstop=async()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);await registerAudioRecording({sessionId:activeSession.sessionId,participantId:participant?.id||'',status:'completed',mimeType:blob.type,startedAt:audioStartedAt.current||new Date().toISOString(),stoppedAt:new Date().toISOString(),sizeBytes:blob.size,localObjectUrl:url,quality:blob.size>2048?'good':'degraded',checksumSource:`${activeSession.sessionId}|${blob.size}|${audioStartedAt.current}`});streamRef.current?.getTracks().forEach(t=>t.stop());resolve()};recorder.stop()})};
 const submitAndLock=async()=>{if(policy.judging.requireAudioRecording&&audioState!=='ready')return;await finalizeAudio();lockAndSubmitAssessment(directScores)};
 const isLastQuestion=activeSession.currentQuestionIndex >= (activeSession.questionSelection?.questions.length||1)-1;
 const nextQueued=[...participants].filter(p=>p.status==='in_queue' && p.id!==participant?.id).sort((a,b)=>(a.queueOrderKey??a.queueNumber??999999)-(b.queueOrderKey??b.queueNumber??999999))[0];
 const deductions=activeSession.events.filter(e=>!e.reversed).reduce((s,e)=>s+e.penalty,0);
 const displayName=policy.judging.identityVisibility==='code_only' ? participant?.code : ar?participant?.fullNameArabic:participant?.fullName;
 const judgeActions=actions.filter(a=> policy.judging.mode==='all_judges_all_criteria' || !judge || judge.specialty==='all' || a.criterion===judge.specialty || a.criterion==='custom');
 const directMode=policy.judging.scoreEntryMode==='direct_score'||policy.judging.scoreEntryMode==='hybrid';
 const calibrationBlocked=policy.judging.calibrationRequired && !!judge && !judge.isReady;
 const reviewAvailable=activeSession.isLocked&&policy.aiPolicy.revealOnlyAfterJudgeLock&&policy.aiPolicy.mode!=='AI_DISABLED'&&policy.aiPolicy.mode!=='AI_RESEARCH_SHADOW_MODE'&&store.reviewCases.some(r=>r.sessionId===activeSession.sessionId&&r.status==='pending'&&r.reason==='ai_high_confidence_alert');
 const reading=participant?resolveReading({riwaya:participant.riwaya}):undefined;
 const openingReference=q&&reading?selectApprovedOpeningAudio({references:store.quranReferenceAudio,qiraah:activeSession.questionSelection?.qiraah||reading.qiraah,rawi:activeSession.questionSelection?.rawi||reading.rawi,tariq:activeSession.questionSelection?.tariq,preferredReciter:policy.questions.openingPrompt?.preferredReciter,surah:q.surahNumber,ayah:q.startAyah}):undefined;
 const certifiedPosition=reading?certifiedCapabilityFor(store.aiCapabilityValidations,{capability:'quran_position',qiraah:reading.qiraah,rawi:reading.rawi,tariq:activeSession.questionSelection?.tariq}):undefined;
 const assignedJudgeId=judge?.userId||store.currentUser.id; const approvedByMe=!!gate?.approvals.some(a=>a.judgeId===assignedJudgeId); const required=gate?.requiredJudgeIds.length||activeSession.committee?.judgeIds.length||0; const approved=gate?.approvals.length||0;

 const playOpeningAudio=async()=>{if(!questionRevealed||!q||!openingReference?.audioUrl){setOpeningAudioState('unavailable');return false;}const window=openingAudioWindow(openingReference,q.startAyah);if(!window){setOpeningAudioState('unavailable');return false;}try{promptAudioRef.current?.pause();const player=new Audio(openingReference.audioUrl);promptAudioRef.current=player;player.currentTime=window.startMs/1000;setOpeningAudioState('playing');if(window.endMs!==undefined){const stop=()=>{if(player.currentTime*1000>=window.endMs!){player.pause();player.removeEventListener('timeupdate',stop);setOpeningAudioState('idle')}};player.addEventListener('timeupdate',stop);}player.onended=()=>setOpeningAudioState('idle');await player.play();store.markOpeningAudioPlayed(openingReference.id);return true}catch{setOpeningAudioState('failed');return false}};
 const approveReveal=async()=>{const result=await store.approveQuestionReveal();if(result.ok&&result.revealed&&policy.questions.openingPrompt?.autoplay!==false)window.setTimeout(()=>void playOpeningAudio(),30)};
 const speakTransition=()=>{if(!store.finishCurrentQuestionSegment())return;const cue=policy.questions.transitionCue;const delay=cue?.autoAdvanceDelayMs??700;const proceed=()=>{if(!isLastQuestion)nextQuestion()};const afterCue=()=>window.setTimeout(proceed,delay);if(cue?.enabled===false){afterCue();return;}let fallbackUsed=false;const speakFallback=()=>{if(fallbackUsed)return;fallbackUsed=true;if(typeof window!=='undefined'&&'speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(ar?(cue?.phraseArabic||'حسبك، جزاك الله خيرًا'):(cue?.phraseEnglish||'Thank you. Please stop here.'));u.lang=ar?'ar-SA':'en-US';u.rate=.88;u.pitch=.92;u.onend=afterCue;u.onerror=afterCue;window.speechSynthesis.speak(u);}else afterCue()};if(cue?.audioUrl&&/^https:\/\//i.test(cue.audioUrl)&&typeof Audio!=='undefined'){try{transitionAudioRef.current?.pause();const player=new Audio(cue.audioUrl);transitionAudioRef.current=player;player.onended=afterCue;player.onerror=speakFallback;void player.play().catch(speakFallback);return}catch{}}speakFallback()};

 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||activeSession.questionPhase!=='RECITING')return;if(e.key.toLowerCase()==='z'){undoLastJudgeEvent();return;}const action=judgeActions.find(a=>a.shortcut===e.key);if(action){e.preventDefault();recordJudgeEvent(action.eventType)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[judgeActions,activeSession.isLocked,activeSession.questionPhase]);
 useEffect(()=>{if(!certifiedPosition)return;const handler=(event:Event)=>{const detail=(event as CustomEvent<{sessionId?:string;questionIndex?:number;validationId?:string}>).detail;if(detail?.sessionId!==activeSession.sessionId||detail.questionIndex!==activeSession.currentQuestionIndex||detail.validationId!==certifiedPosition.id)return;speakTransition()};window.addEventListener('mizan:certified-passage-end',handler);return()=>window.removeEventListener('mizan:certified-passage-end',handler)},[certifiedPosition?.id,activeSession.sessionId,activeSession.currentQuestionIndex,isLastQuestion]);

 if(calibrationBlocked) return <div className="max-w-2xl mx-auto px-4 py-20"><div className="mizan-surface p-7 text-center"><div className="mizan-kicker">{ar?'جاهزية المحكم':'JUDGE READINESS'}</div><h1 className="text-2xl font-black mt-2">{ar?'المعايرة قبل التحكيم':'Calibrate before judging'}</h1><p className="text-xs text-[#777e79] mt-3">{ar?'هذه المسابقة تشترط معايرة المحكم. التدريب لا يغيّر أي درجة؛ إنه فحص جاهزية فقط.':'This competition requires judge calibration. Training never alters contestant scores; it is a readiness gate only.'}</p><div className="mt-5 rounded-2xl bg-[#f3f1eb] p-4"><div className="text-3xl font-black">{judge?.calibrationScore||0}%</div><div className="text-[10px] text-[#7b827d] mt-1">{ar?'التوافق الحالي':'Current agreement'}</div></div><Button className="mt-5" onClick={()=>store.completeJudgeCalibration(judge!.id,92)}>{ar?'تشغيل تدريب المعايرة':'Run calibration training'}</Button><div className="text-[10px] text-[#8a908c] mt-3">{ar?'في الإنتاج تستخدم تلاوات مرجعية يعتمدها المجلس العلمي.':'Production uses scholarly approved reference recitations.'}</div></div></div>;
 if(!participant) return <div className="max-w-3xl mx-auto px-4 py-20 text-center"><HeadphonesEmpty/><h1 className="text-2xl font-black mt-4">{ar?'لا توجد جلسة الآن':'No active session'}</h1>{nextQueued&&<Button className="mt-5" onClick={()=>startSessionForParticipant(nextQueued.id)}>{ar?'استقبال المتسابق التالي':'Call next participant'}</Button>}</div>;

 return <div className="min-h-[calc(100vh-64px)] bg-[#fbfaf6]"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-5 sm:py-7">
  <div className="flex items-center justify-between gap-4 mb-5"><div className="min-w-0"><div className="mizan-kicker">{ar?'منصة التحكيم':'JUDGING'}</div><div className="flex items-center gap-2 mt-1"><h1 className="text-xl sm:text-2xl font-black truncate">{displayName||'—'}</h1><Badge variant={activeSession.isLocked?'neutral':questionRevealed?'emerald':'amber'}>{activeSession.isLocked?(ar?'مقفل':'Locked'):questionRevealed?(ar?'التلاوة جارية':'Reciting'):(ar?'السؤال مختوم':'Question sealed')}</Badge></div><div className="text-[11px] text-[#7b827d] mt-1">{judge?`${ar?judge.nameArabic:judge.name} · ${ar?specialtyAr(judge.specialty):judge.specialty}`:''}</div></div><div className="flex items-center gap-3 text-xs text-[#68706b]"><span className="hidden sm:inline">{activeSession.committee?.code}</span><span className="flex items-center gap-1.5"><span className={`w-2 h-2 rounded-full ${audioState==='ready'?'bg-[#2F6555]':audioState==='failed'?'bg-[#A34D43]':'bg-[#9B7542]'}`}/>{audioState==='ready'?(ar?'الصوت جاهز':'Audio ready'):audioState==='requesting'?(ar?'فحص الصوت':'Checking audio'):(ar?'الصوت مطلوب':'Audio required')}</span></div></div>
  <section className="mizan-surface p-5 sm:p-8">
   <div className="flex items-center justify-between gap-4 border-b border-[#e5e3dc] pb-4 mb-6"><div><div className="text-[11px] font-black text-[#7c827e]">{ar?'الموضع':'QUESTION'} {activeSession.currentQuestionIndex+1} / {activeSession.questionSelection?.questions.length||0}</div><div className="text-sm font-bold mt-1">{questionRevealed&&q?`${q.surahNameArabic} · ${q.startAyah}–${q.endAyah}`:(ar?'محجوب حتى حضور المتسابق وموافقة اللجنة':'Hidden until presence and panel approval')}</div></div><div className="text-end"><div className="text-2xl font-black tabular-nums">{formatTime(activeSession.durationSeconds)}</div><div className="text-[10px] text-[#7c827e]">{ar?'زمن الجلسة':'Session time'}</div></div></div>

   {!questionRevealed&&!activeSession.isLocked&&<div className="py-3 sm:py-7"><div className="mx-auto max-w-xl text-center"><div className="w-16 h-16 rounded-2xl bg-[#f0eee7] text-[#313a35] grid place-items-center mx-auto"><LockKeyhole className="w-7 h-7"/></div><h2 className="text-2xl font-black mt-4">{ar?'السؤال لم يُكشف':'Question remains sealed'}</h2><p className="text-xs leading-6 text-[#747b76] mt-2">{ar?'لا يظهر اسم السورة أو الآيات قبل وجود المتسابق أمام اللجنة وموافقة المحكمين المكلّفين.':'No passage details appear until the participant is present and assigned judges approve the reveal.'}</p>
    <div className="grid grid-cols-2 gap-3 mt-6"><GateState icon={UserCheck} ok={!!gate?.participantPresence.verified} title={ar?'المتسابق أمام اللجنة':'Participant present'} value={gate?.participantPresence.verified?(ar?'تم التحقق':'Verified'):(ar?'مطلوب':'Required')}/><GateState icon={UsersRound} ok={required>0&&approved>=required} title={ar?'موافقة المحكمين':'Judge approvals'} value={`${approved} / ${required}`}/></div>
    {!gate?.participantPresence.verified?<Button className="mt-5" icon={<UserCheck className="w-4 h-4"/>} onClick={()=>void store.verifyParticipantPresenceForQuestion('manual_visual_confirmation')}>{ar?'المتسابق أمامي — تأكيد الحضور':'Participant is here — confirm presence'}</Button>:<Button className="mt-5" disabled={approvedByMe||store.currentUser.role!=='judge'} icon={<ShieldCheck className="w-4 h-4"/>} onClick={()=>void approveReveal()}>{approvedByMe?(ar?'تم تسجيل موافقتي':'My approval recorded'):(ar?'أوافق على فتح السؤال':'Approve question reveal')}</Button>}
    <div className="mt-3 text-[10px] text-[#8a908c]">{ar?(gate?.revealAssurance==='production_server_escrow'?'الكشف مربوط بحجز خادمي فعلي.':gate?.revealAssurance==='operational_panel_gate'?'بوابة اللجنة تمنع الكشف المبكر داخل التشغيل، لكن منع فحص السؤال تقنيًا من الجهاز نفسه يتطلب حجزًا خادميًا منفصلًا.':'بوابة تطوير محلية؛ قبل الإنتاج يلزم حجز السؤال خارج جهاز المحكم لمنع التسرب التقني.'):(gate?.revealAssurance==='production_server_escrow'?'Server-held question escrow is active.':gate?.revealAssurance==='operational_panel_gate'?'Panel gate blocks early operational reveal; adversarial device inspection still requires server-held escrow.':'Development client gate; production secrecy requires server-held escrow.')}</div>
   </div></div>}

   {policy.judging.requireAudioRecording&&audioState!=='ready'&&<div className={`rounded-2xl p-4 mb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${audioState==='failed'?'bg-[#F4E6E3] text-[#88473f]':'bg-[#F2EADC] text-[#725630]'}`}><div className="flex items-center gap-3">{audioState==='failed'?<MicOff className="w-5 h-5"/>:<Mic className="w-5 h-5"/>}<div><div className="text-sm font-black">{audioState==='failed'?(ar?'تعذر تجهيز الميكروفون':'Microphone unavailable'):(ar?'تحقق من الصوت قبل البدء':'Verify audio before judging')}</div><div className="text-[10px] mt-1 opacity-80">{ar?'إذا كان التسجيل إلزاميًا، لا تبدأ أدوات التحكيم قبل نجاح الفحص.':'When recording is required, judging tools stay locked until audio is ready.'}</div></div></div><Button size="sm" onClick={prepareAudio} disabled={audioState==='requesting'}>{audioState==='requesting'?'…':(ar?'تجهيز الميكروفون':'Prepare microphone')}</Button></div>}

   {questionRevealed&&q&&<div className="text-center py-3 sm:py-6"><div className="font-quran text-2xl sm:text-3xl leading-[2.1] text-[#202622] max-w-3xl mx-auto">{q.expectedTextArabic}</div><div className="mt-5 flex flex-col sm:flex-row items-center justify-center gap-2">{openingReference?<Button size="sm" variant="outline" icon={<Volume2 className="w-4 h-4"/>} onClick={()=>void playOpeningAudio()} disabled={openingAudioState==='playing'}>{openingAudioState==='playing'?(ar?'تلاوة أول آية…':'Playing first ayah…'):(ar?`تلاوة أول آية — ${openingReference.reciter}`:`First ayah — ${openingReference.reciter}`)}</Button>:<Badge variant="amber">{ar?'لا يوجد صوت مرجعي معتمد مطابق لهذه القراءة':'No approved reading-matched opening audio'}</Badge>}<Badge variant={certifiedPosition?'emerald':'neutral'}>{certifiedPosition?(ar?'تتبّع نهاية الموضع معتمد للنطاق':'Certified passage-end signal available'):(ar?'إنهاء الموضع يدوي':'Manual passage end')}</Badge></div><div className="mt-3 text-[10px] text-[#7c827e]">{ar?'الصوت القرآني لا يُنشأ آليًا؛ يُشغّل فقط من خزنة المراجع الصوتية المعتمدة.':'Quran audio is never synthesized here; only approved reference audio may play.'}</div></div>}

   {questionRevealed&&!activeSession.isLocked&&(!policy.judging.requireAudioRecording||audioState==='ready')?activeSession.questionPhase==='TRANSITION'?<div className="rounded-2xl bg-[#eef2ef] p-7 text-center"><Square className="w-6 h-6 mx-auto text-[#214C40]"/><div className="font-black mt-3">{isLastQuestion?(ar?'انتهى آخر موضع. اعتمد تقييمك عندما تكون جاهزًا.':'Final passage ended. Submit when ready.'):(ar?'تم إيقاف الموضع. جاري الانتقال…':'Passage stopped. Preparing transition…')}</div>{isLastQuestion&&<Button className="mt-4" onClick={submitAndLock} icon={<Check className="w-4 h-4"/>}>{ar?'اعتماد وقفل':'Submit & lock'}</Button>}</div>:<>
    {policy.judging.scoreEntryMode!=='direct_score'&&<div className={`grid gap-3 mt-4 ${judgeActions.length<=4?'grid-cols-2 sm:grid-cols-4':'grid-cols-2 sm:grid-cols-3'}`}>{judgeActions.map(a=>{const Icon=iconFor(a.icon);return <button key={a.id} onClick={()=>recordJudgeEvent(a.eventType)} className="group min-h-24 rounded-2xl border border-[#deddd6] bg-[#fffefb] hover:border-[#bfc9c3] hover:bg-[#f7faf8] transition px-4 py-4 text-start active:scale-[.99]"><div className="flex items-start justify-between"><span className="w-9 h-9 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><Icon className="w-4 h-4"/></span>{a.shortcut&&<kbd className="text-[10px] text-[#8a908c] border border-[#dfded7] rounded-md px-1.5 py-1">{a.shortcut}</kbd>}</div><div className="mt-3 text-base font-black">{ar?a.shortArabic:a.shortEnglish}</div><div className="text-[10px] text-[#7b827d] mt-1">−{a.penalty}</div></button>})}</div>}
    {directMode&&<div className="mt-5 border-t border-[#e5e3dc] pt-5"><div className="text-[11px] font-black text-[#747b76] mb-3">{ar?'درجات اختصاصك':'YOUR CRITERIA'}</div><div className="grid sm:grid-cols-2 gap-3">{visibleCriteria.map(c=><label key={c.id} className="rounded-2xl border border-[#deddd6] bg-[#fffefb] p-4 flex items-center justify-between gap-4"><span><span className="block text-sm font-black">{ar?c.nameArabic:c.name}</span><span className="text-[10px] text-[#7b827d]">{ar?'من':'of'} {c.maxScore}</span></span><input aria-label={ar?c.nameArabic:c.name} type="number" min="0" max={c.maxScore} step={policy.judging.directScoreStep||.25} value={directScores[c.id]??c.maxScore} onChange={e=>setDirectScores(v=>({...v,[c.id]:Math.min(c.maxScore,Math.max(0,Number(e.target.value)))}))} className="w-24 rounded-xl border border-[#d9d7d0] bg-white px-3 py-2 text-center text-xl font-black"/></label>)}</div><div className="text-[10px] text-[#858b87] mt-2">{ar?'تبقى هذه الدرجات مستقلة ولا يراها بقية المحكمين قبل القفل.':'These values remain an independent judge assessment until lock.'}</div></div>}
    <div className="mt-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-t border-[#e5e3dc] pt-5"><div className="flex items-center gap-2"><button onClick={undoLastJudgeEvent} disabled={!activeSession.events.length} className="w-10 h-10 rounded-xl grid place-items-center border border-[#deddd6] text-[#626a65] hover:bg-[#f1efe9] disabled:opacity-30" title={ar?'تراجع Z':'Undo Z'}><RotateCcw className="w-4 h-4"/></button><span className="text-xs text-[#777e79]">{activeSession.events.length} {ar?'ملاحظات':'events'} · −{deductions.toFixed(2)}</span></div><div className="flex gap-2"><Button variant="outline" onClick={speakTransition} icon={<Square className="w-4 h-4"/>}>{isLastQuestion?(ar?'إنهاء آخر موضع':'End final passage'):(ar?'إنهاء الموضع':'End passage')}</Button></div></div>
   </>:activeSession.isLocked?<div className="rounded-2xl bg-[#E7EEE9] text-[#214C40] p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-full bg-white grid place-items-center"><Check className="w-5 h-5"/></span><div><div className="font-black">{ar?'تم اعتماد تقييمك':'Assessment locked'}</div><div className="text-xs mt-1 opacity-80">{ar?'تقييم بقية المحكمين يبقى مخفيًا.':'Other judge assessments remain hidden.'}</div>{reviewAvailable&&<div className="mt-2 text-[10px] font-black tracking-[.14em]">{ar?'مراجعة متاحة':'REVIEW AVAILABLE'}</div>}</div></div>{nextQueued&&<Button onClick={()=>startSessionForParticipant(nextQueued.id)}>{ar?'المتسابق التالي':'Next participant'}</Button>}</div>:null}
  </section>
  <div className="mt-4 flex items-center justify-center gap-3 text-[10px] text-[#8a908c]"><Volume2 className="w-3.5 h-3.5"/><span>{policy.judging.silentAiGuardian?(ar?'المراقب الآلي صامت ولا يخصم أي درجة':'Integrity AI is silent and cannot deduct a score'):(ar?'المراقبة الآلية غير مفعلة لهذه المسابقة':'AI integrity is disabled')}</span></div>
 </div></div>
}

const GateState=({icon:Icon,ok,title,value}:{icon:React.ComponentType<{className?:string}>;ok:boolean;title:string;value:string})=><div className={`rounded-2xl p-4 text-start ${ok?'bg-[#E7EEE9] text-[#214C40]':'bg-[#f2f0ea] text-[#626a65]'}`}><Icon className="w-5 h-5"/><div className="text-xs font-black mt-3">{title}</div><div className="text-[10px] mt-1 opacity-75">{value}</div></div>;
const specialtyAr=(v:string)=>({memorization:'الحفظ',tajweed:'التجويد',waqf_ibtida:'الوقف والابتداء',all:'شامل'} as Record<string,string>)[v]||v;
const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const HeadphonesEmpty=()=> <div className="w-14 h-14 rounded-2xl bg-[#E7EEE9] text-[#214C40] grid place-items-center mx-auto"><Volume2 className="w-6 h-6"/></div>;
