import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CircleDot, CornerDownLeft, RotateCcw, SkipForward, Sparkles, Volume2 } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { getCompetitionPolicy, getEnabledJudgeActions } from '../../lib/competition-config';
import { Button } from '../design-system/Button';
import { Badge } from '../design-system/Badge';

const iconFor=(kind?:string)=> kind==='error'?AlertTriangle:kind==='open'?CornerDownLeft:kind==='repeat'?RotateCcw:kind==='tajweed'?Sparkles:kind==='stop'?CircleDot:AlertTriangle;

export const JudgeOS: React.FC = () => {
 const store=useAppStore();
 const {language,competition,activeSession,recordJudgeEvent,undoLastJudgeEvent,lockAndSubmitAssessment,nextQuestion,participants,startSessionForParticipant}=store;
 const ar=language==='ar'; const policy=getCompetitionPolicy(competition); const actions=getEnabledJudgeActions(competition);
 const ruleSet=useMemo(()=>competition.ruleSets?.find(r=>r.id===competition.categories.find(c=>c.id===activeSession.participant?.categoryId)?.ruleSetId)||competition.ruleSet,[competition,activeSession.participant?.categoryId]);
 const judge=store.judges.find(j=>j.userId===store.currentUser.id || j.id===store.currentUser.id);
 const visibleCriteria=ruleSet.criteria.filter(c=> policy.judging.mode==='all_judges_all_criteria' || !judge || judge.specialty==='all' || c.assignedJudgeType===judge.specialty || (policy.judging.mode==='hybrid' && c.assignedJudgeType==='all'));
 const [directScores,setDirectScores]=useState<Record<string,number>>({});
 useEffect(()=>{setDirectScores(Object.fromEntries(visibleCriteria.map(c=>[c.id,c.maxScore])))},[activeSession.sessionId,ruleSet.id,judge?.id]);
 const q=activeSession.questionSelection?.questions[activeSession.currentQuestionIndex]; const isLastQuestion=activeSession.currentQuestionIndex >= (activeSession.questionSelection?.questions.length||1)-1;
 const participant=activeSession.participant; const nextQueued=participants.find(p=>p.status==='in_queue' && p.id!==participant?.id);
 const deductions=activeSession.events.filter(e=>!e.reversed).reduce((s,e)=>s+e.penalty,0);
 const displayName=policy.judging.identityVisibility==='code_only' ? participant?.code : ar?participant?.fullNameArabic:participant?.fullName;
 const judgeActions=actions.filter(a=> policy.judging.mode==='all_judges_all_criteria' || !judge || judge.specialty==='all' || a.criterion===judge.specialty || a.criterion==='custom');
 const directMode=policy.judging.scoreEntryMode==='direct_score'||policy.judging.scoreEntryMode==='hybrid';

 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key.toLowerCase()==='z'){undoLastJudgeEvent();return;}const action=judgeActions.find(a=>a.shortcut===e.key);if(action){e.preventDefault();recordJudgeEvent(action.eventType)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[judgeActions,activeSession.isLocked]);

 if(!participant) return <div className="max-w-3xl mx-auto px-4 py-20 text-center"><HeadphonesEmpty/><h1 className="text-2xl font-black mt-4">{ar?'لا توجد جلسة الآن':'No active session'}</h1>{nextQueued&&<Button className="mt-5" onClick={()=>startSessionForParticipant(nextQueued.id)}>{ar?'استقبال التالي':'Call next'}</Button>}</div>;

 return <div className="min-h-[calc(100vh-64px)] bg-[#fbfaf6]"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-5 sm:py-7">
  <div className="flex items-center justify-between gap-4 mb-5"><div className="min-w-0"><div className="mizan-kicker">JUDGEOS</div><div className="flex items-center gap-2 mt-1"><h1 className="text-xl sm:text-2xl font-black truncate">{displayName||'—'}</h1><Badge variant={activeSession.isLocked?'neutral':'emerald'}>{activeSession.isLocked?(ar?'مقفل':'Locked'):(ar?'يستمع':'Listening')}</Badge></div><div className="text-[11px] text-[#7b827d] mt-1">{judge?`${ar?judge.nameArabic:judge.name} · ${judge.specialty}`:''}</div></div><div className="flex items-center gap-3 text-xs text-[#68706b]"><span className="hidden sm:inline">{activeSession.committee?.code}</span><span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-[#2F6555]"/>{ar?'الصوت جيد':'Audio good'}</span></div></div>
  <section className="mizan-surface p-5 sm:p-8"><div className="flex items-center justify-between gap-4 border-b border-[#e5e3dc] pb-4 mb-6"><div><div className="text-[11px] font-black text-[#7c827e]">{ar?'السؤال':'QUESTION'} {activeSession.currentQuestionIndex+1} / {activeSession.questionSelection?.questions.length||0}</div><div className="text-sm font-bold mt-1">{q?`${q.surahNameArabic} · ${q.startAyah}–${q.endAyah}`:'—'}</div></div><div className="text-end"><div className="text-2xl font-black tabular-nums">{formatTime(activeSession.durationSeconds)}</div><div className="text-[10px] text-[#7c827e]">{ar?'زمن الجلسة':'Session time'}</div></div></div>
   {q&&<div className="text-center py-3 sm:py-6"><div className="font-quran text-2xl sm:text-3xl leading-[2.1] text-[#202622] max-w-3xl mx-auto">{q.expectedTextArabic}</div><div className="mt-4 text-[11px] text-[#7c827e]">{policy.questions.drawMode==='fairdraw'?(ar?'حزمة معتمدة ضمن قيود FairDraw':'FairDraw set within competition constraints'):(ar?'وفق سياسة هذه المسابقة':'Selected by this competition policy')}</div></div>}
   {!activeSession.isLocked?<>
    {policy.judging.scoreEntryMode!=='direct_score'&&<div className={`grid gap-3 mt-4 ${judgeActions.length<=4?'grid-cols-2 sm:grid-cols-4':'grid-cols-2 sm:grid-cols-3'}`}>{judgeActions.map(a=>{const Icon=iconFor(a.icon);return <button key={a.id} onClick={()=>recordJudgeEvent(a.eventType)} className="group min-h-24 rounded-2xl border border-[#deddd6] bg-[#fffefb] hover:border-[#bfc9c3] hover:bg-[#f7faf8] transition px-4 py-4 text-start active:scale-[.99]"><div className="flex items-start justify-between"><span className="w-9 h-9 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><Icon className="w-4 h-4"/></span>{a.shortcut&&<kbd className="text-[10px] text-[#8a908c] border border-[#dfded7] rounded-md px-1.5 py-1">{a.shortcut}</kbd>}</div><div className="mt-3 text-base font-black">{ar?a.shortArabic:a.shortEnglish}</div><div className="text-[10px] text-[#7b827d] mt-1">−{a.penalty}</div></button>})}</div>}
    {directMode&&<div className="mt-5 border-t border-[#e5e3dc] pt-5"><div className="text-[11px] font-black text-[#747b76] mb-3">{ar?'درجات اختصاصك':'YOUR CRITERIA'}</div><div className="grid sm:grid-cols-2 gap-3">{visibleCriteria.map(c=><label key={c.id} className="rounded-2xl border border-[#deddd6] bg-[#fffefb] p-4 flex items-center justify-between gap-4"><span><span className="block text-sm font-black">{ar?c.nameArabic:c.name}</span><span className="text-[10px] text-[#7b827d]">{ar?'من':'of'} {c.maxScore}</span></span><input aria-label={ar?c.nameArabic:c.name} type="number" min="0" max={c.maxScore} step={policy.judging.directScoreStep||.25} value={directScores[c.id]??c.maxScore} onChange={e=>setDirectScores(v=>({...v,[c.id]:Math.min(c.maxScore,Math.max(0,Number(e.target.value)))}))} className="w-24 rounded-xl border border-[#d9d7d0] bg-white px-3 py-2 text-center text-xl font-black"/></label>)}</div><div className="text-[10px] text-[#858b87] mt-2">{ar?'تُحفظ هذه الدرجات كتقييم مستقل لهذا المحكم فقط حتى القفل.':'These values remain an independent judge assessment until lock.'}</div></div>}
    <div className="mt-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-t border-[#e5e3dc] pt-5"><div className="flex items-center gap-2"><button onClick={undoLastJudgeEvent} disabled={!activeSession.events.length} className="w-10 h-10 rounded-xl grid place-items-center border border-[#deddd6] text-[#626a65] hover:bg-[#f1efe9] disabled:opacity-30" title={ar?'تراجع Z':'Undo Z'}><RotateCcw className="w-4 h-4"/></button><span className="text-xs text-[#777e79]">{activeSession.events.length} {ar?'أحداث':'events'} · −{deductions.toFixed(2)}</span></div><Button onClick={isLastQuestion?()=>lockAndSubmitAssessment(directScores):nextQuestion} icon={isLastQuestion?<Check className="w-4 h-4"/>:<SkipForward className="w-4 h-4"/>}>{isLastQuestion?(ar?'اعتماد وقفل':'Submit & lock'):(ar?'السؤال التالي':'Next question')}</Button></div>
   </>:<div className="rounded-2xl bg-[#E7EEE9] text-[#214C40] p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-full bg-white grid place-items-center"><Check className="w-5 h-5"/></span><div><div className="font-black">{ar?'تم اعتماد تقييمك':'Assessment locked'}</div><div className="text-xs mt-1 opacity-80">{ar?'تقييم بقية المحكمين يبقى مخفيًا.':'Other judge assessments remain hidden.'}</div></div></div>{nextQueued&&<Button onClick={()=>startSessionForParticipant(nextQueued.id)}>{ar?'المتسابق التالي':'Next participant'}</Button>}</div>}
  </section><div className="mt-4 flex items-center justify-center gap-3 text-[10px] text-[#8a908c]"><Volume2 className="w-3.5 h-3.5"/><span>{policy.judging.silentAiGuardian?(ar?'النزاهة الآلية صامتة ولا تخصم درجة':'Integrity AI is silent and cannot deduct a score'):(ar?'AI غير مفعّل لهذه المسابقة':'AI integrity is disabled')}</span></div>
 </div></div>
}
const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const HeadphonesEmpty=()=> <div className="w-14 h-14 rounded-2xl bg-[#E7EEE9] text-[#214C40] grid place-items-center mx-auto"><Volume2 className="w-6 h-6"/></div>;
