import React,{useEffect,useState} from 'react';
import {FileCheck2,FileSearch,ShieldCheck} from 'lucide-react';
import {fetchOfficialMushafPage,loadKfgqpcOfficialQuranFont} from '../../lib/kfgqpc-library';
import {Badge} from '../design-system/Badge';
import {resolveReading} from '../../lib/scientific-core';
import {qiraahLabel,rawiLabel,tariqLabel} from '../../lib/arabic-labels';

export interface MushafSurfaceQuestion{expectedTextArabic:string;surahNameArabic?:string;surahNameEnglish?:string;startAyah:number;endAyah:number;quranSourcePackageId?:string;quranSourcePackageHash?:string;pageNumber?:number;lineStart?:number;lineEnd?:number;officialSurfaceAuthority?:string;officialSurfaceMode?:string;rawi?:string;qiraah?:string;tariq?:string}
export const OfficialMushafSurface:React.FC<{question:MushafSurfaceQuestion;ar:boolean}>=({question:q,ar})=>{const reading=resolveReading({qiraah:q.qiraah,rawi:q.rawi,riwaya:q.rawi});const readingText=reading?`${qiraahLabel(reading,ar)} · ${rawiLabel(reading,ar)}${q.tariq?` · ${tariqLabel(q.tariq,ar)}`:''}`:[q.rawi,q.qiraah,q.tariq].filter(Boolean).join(' · ');const [pageUrl,setPageUrl]=useState<string|null>(null);const [checked,setChecked]=useState(false);const [officialFont,setOfficialFont]=useState(false);useEffect(()=>{let live=true,url:string|null=null;setPageUrl(null);setChecked(false);if(!q.quranSourcePackageId||!q.pageNumber){setChecked(true);return}void fetchOfficialMushafPage(q.quranSourcePackageId,q.pageNumber).then(x=>{if(!live){if(x)URL.revokeObjectURL(x);return}url=x;setPageUrl(x);setChecked(true)});return()=>{live=false;if(url)URL.revokeObjectURL(url)}},[q.quranSourcePackageId,q.pageNumber]);
 return <div className="relative overflow-hidden rounded-[30px] border border-[#dad7cd] bg-[#fdfbf5] shadow-[0_18px_55px_rgba(25,39,33,.055)]"><div className="flex items-center justify-between gap-3 px-4 sm:px-5 py-3 border-b border-[#e5e1d7] bg-[#f7f4ec]"><div className="flex items-center gap-2 min-w-0"><span className="w-8 h-8 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><FileCheck2 className="w-4 h-4"/></span><div className="min-w-0"><div className="text-[10px] font-black truncate">{ar?'سطح المصحف الرسمي':'OFFICIAL MUSHAF SURFACE'}</div><div className="text-[9px] text-[#7a817c] truncate">{readingText||'—'}</div></div></div><div className="flex items-center gap-2"><Badge variant="emerald">{ar?'المصدر: مجمع الملك فهد':'KFGQPC SOURCE'}</Badge>{q.pageNumber&&<span className="text-[10px] font-black tabular-nums text-[#59615c]">{ar?'ص':'p.'} {q.pageNumber}</span>}</div></div>
 {pageUrl?<div className="relative bg-[#efede6] p-3 sm:p-5"><div className="relative mx-auto w-fit"><img src={pageUrl} alt={ar?'صفحة المصحف الرسمية':'Official Mushaf page'} className="max-h-[58vh] w-auto rounded-[2px] shadow-[0_12px_28px_rgba(0,0,0,.08)]"/>{q.lineStart&&<FocusLens lineStart={q.lineStart} lineEnd={q.lineEnd||q.lineStart} ar={ar}/>}</div><div className="absolute bottom-4 start-4 rounded-xl bg-[#202924]/90 text-white px-3 py-2 text-[9px] font-black flex items-center gap-2"><FileSearch className="w-3.5 h-3.5"/>{ar?'أصل الصفحة الرسمي المستورد':'Imported official page asset'}</div></div>:<div className="px-5 sm:px-10 py-8 sm:py-12"><div className="max-w-4xl mx-auto"><div className="flex items-center justify-between gap-3 mb-7 text-[9px] font-black text-[#7c827e]"><span>{q.surahNameArabic||q.surahNameEnglish||'—'} · {q.startAyah}–{q.endAyah}</span><span>{q.lineStart?`${ar?'الأسطر':'lines'} ${q.lineStart}${q.lineEnd&&q.lineEnd!==q.lineStart?`–${q.lineEnd}`:''}`:''}</span></div><div className="font-quran text-center text-2xl sm:text-[2.05rem] leading-[2.25] text-[#202622]" style={officialFont?{fontFamily:'\"MIZAN KFGQPC Official\"'}:undefined}>{q.expectedTextArabic}</div><div className="mt-8 flex items-center justify-center gap-2 text-[9px] text-[#7d837f]"><ShieldCheck className="w-3.5 h-3.5 text-[#2F6555]"/><span>{checked?(ar?'النص من حزمة المصدر الرسمية؛ أصل الصفحة البصري غير مستورد على هذا الخادم.':'Text is from the official source package; the visual page master is not imported on this server.'):(ar?'جارٍ التحقق من أصل الصفحة…':'Checking official page master…')}</span></div></div></div>}
 <div className="px-4 sm:px-5 py-3 border-t border-[#e5e1d7] flex items-center justify-between gap-3 text-[9px] text-[#818782]"><span className="font-mono truncate">{q.quranSourcePackageHash?`SHA-256 ${q.quranSourcePackageHash.slice(0,18)}…`:ar?'مصدر تطوير محلي':'Development source'}</span><span>{pageUrl?(ar?'صفحة رسمية':'OFFICIAL PAGE'):officialFont?(ar?'نص وخط رسميان':'OFFICIAL TEXT + FONT'):(ar?'نص عثماني رسمي':'OFFICIAL UTHMANIC TEXT')}</span></div></div>}

const FocusLens:React.FC<{lineStart:number;lineEnd:number;ar:boolean}>=({lineStart,lineEnd,ar})=>{const total=15,start=Math.max(1,Math.min(total,lineStart)),end=Math.max(start,Math.min(total,lineEnd)),top=((start-1)/total)*100,height=Math.max(5,((end-start+1)/total)*100);return <div aria-label={ar?'عدسة موضع الاختبار':'Passage focus lens'} className="pointer-events-none absolute inset-y-0 -end-5 w-4"><div className="absolute end-0 w-[3px] rounded-full bg-[#2F6555] shadow-[0_0_0_4px_rgba(47,101,85,.08)]" style={{top:`${top}%`,height:`${height}%`}}/><div className="absolute end-2 w-2 border-e border-y border-[#2F6555]/35 rounded-e-md" style={{top:`${top}%`,height:`${height}%`}}/></div>}
