import React,{useEffect,useMemo,useState} from 'react';
import {FileCheck2,FileSearch,MapPin,ShieldCheck} from 'lucide-react';
import {fetchOfficialMushafPage,loadKfgqpcOfficialQuranFont} from '../../lib/kfgqpc-library';
import type {QuranAlignmentResult,QuranPageLocus} from '../../lib/quran-intelligence';
import {Badge} from '../design-system/Badge';
import {resolveReading} from '../../lib/scientific-core';
import {qiraahLabel,rawiLabel,tariqLabel} from '../../lib/arabic-labels';

export interface MushafSurfaceQuestion{
 expectedTextArabic:string;surahNameArabic?:string;surahNameEnglish?:string;startAyah:number;endAyah:number;quranSourcePackageId?:string;quranSourcePackageHash?:string;pageNumber?:number;lineStart?:number;lineEnd?:number;pageLoci?:QuranPageLocus[];locationAssurance?:string;officialSurfaceAuthority?:string;officialSurfaceMode?:string;rawi?:string;qiraah?:string;tariq?:string
}

export const OfficialMushafSurface:React.FC<{question:MushafSurfaceQuestion;ar:boolean;tracking?:QuranAlignmentResult|null}>=({question:q,ar,tracking})=>{
 const reading=resolveReading({qiraah:q.qiraah,rawi:q.rawi,riwaya:q.rawi});const readingText=reading?`${qiraahLabel(reading,ar)} · ${rawiLabel(reading,ar)}${q.tariq?` · ${tariqLabel(q.tariq,ar)}`:''}`:[q.rawi,q.qiraah,q.tariq].filter(Boolean).join(' · ');
 const loci=useMemo<QuranPageLocus[]>(()=>q.pageLoci?.length?q.pageLoci:(q.pageNumber&&q.lineStart?[{page:q.pageNumber,lineStart:q.lineStart,lineEnd:q.lineEnd||q.lineStart,lineCount:undefined}]:[]),[q.pageLoci,q.pageNumber,q.lineStart,q.lineEnd]);
 const [pages,setPages]=useState<Record<number,string>>({});const [checked,setChecked]=useState(false);const [officialFont,setOfficialFont]=useState(false);
 useEffect(()=>{let live=true;const urls:string[]=[];setPages({});setChecked(false);if(!q.quranSourcePackageId||!loci.length){setChecked(true);return}void Promise.all(loci.map(async locus=>{const url=await fetchOfficialMushafPage(q.quranSourcePackageId!,locus.page);if(url)urls.push(url);return [locus.page,url] as const})).then(results=>{if(!live){urls.forEach(URL.revokeObjectURL);return}setPages(Object.fromEntries(results.filter((x):x is readonly [number,string]=>!!x[1])));setChecked(true)});return()=>{live=false;urls.forEach(URL.revokeObjectURL)}},[q.quranSourcePackageId,loci.map(x=>`${x.page}:${x.lineStart}:${x.lineEnd}`).join('|')]);
 useEffect(()=>{let live=true;void loadKfgqpcOfficialQuranFont(q.quranSourcePackageId||'primary').then(ok=>{if(live)setOfficialFont(ok)});return()=>{live=false}},[q.quranSourcePackageId]);
 const loadedLoci=loci.filter(x=>!!pages[x.page]);const hasOfficialPage=loadedLoci.length>0;const trackingLost=tracking?.alignmentState==='LOST'||tracking?.alignmentState==='REACQUIRING';
 return <div className="relative overflow-hidden rounded-[30px] border border-[#dad7cd] bg-[#fdfbf5] shadow-[0_18px_55px_rgba(25,39,33,.055)]">
  <div className="flex items-center justify-between gap-3 px-4 sm:px-5 py-3 border-b border-[#e5e1d7] bg-[#f7f4ec]"><div className="flex items-center gap-2 min-w-0"><span className="w-8 h-8 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><FileCheck2 className="w-4 h-4"/></span><div className="min-w-0"><div className="text-[10px] font-black truncate">{ar?'سطح المصحف الرسمي':'OFFICIAL MUSHAF SURFACE'}</div><div className="text-[9px] text-[#7a817c] truncate">{readingText||'—'}</div></div></div><div className="flex items-center gap-2"><Badge variant="emerald">{ar?'المصدر: مجمع الملك فهد':'KFGQPC SOURCE'}</Badge>{loci.length>1?<Badge variant="neutral">{ar?`${loci.length} صفحات رسمية`:`${loci.length} official pages`}</Badge>:loci[0]&&<span className="text-[10px] font-black tabular-nums text-[#59615c]">{ar?'ص':'p.'} {loci[0].page}</span>}</div></div>
  {hasOfficialPage?<div className="relative bg-[#efede6] p-3 sm:p-5"><div className={`mx-auto grid gap-4 ${loadedLoci.length>1?'lg:grid-cols-2':'grid-cols-1'}`}>{loci.map(locus=>pages[locus.page]?<OfficialPage key={locus.page} url={pages[locus.page]} locus={locus} ar={ar} tracking={tracking}/>:<MissingPage key={locus.page} page={locus.page} ar={ar}/>)}</div><div className="mt-3 flex items-center justify-between gap-3"><div className="rounded-xl bg-[#202924]/90 text-white px-3 py-2 text-[9px] font-black flex items-center gap-2"><FileSearch className="w-3.5 h-3.5"/>{ar?'أصل الصفحة الرسمي المستورد دون تعديل':'Imported official page master — unmodified'}</div>{tracking&&<div className={`rounded-xl px-3 py-2 text-[9px] font-black flex items-center gap-2 ${trackingLost?'bg-[#F2EADC] text-[#725630]':'bg-[#E7EEE9] text-[#214C40]'}`}><MapPin className="w-3.5 h-3.5"/>{trackingLost?(ar?'جارٍ إعادة تحديد الموضع — المؤشر ثابت':'Reacquiring — pointer held'):(ar?`تتبّع حي · آية ${tracking.ayah||'—'}`:`Live tracking · ayah ${tracking.ayah||'—'}`)}</div>}</div></div>:<div className="px-5 sm:px-10 py-8 sm:py-12"><div className="max-w-4xl mx-auto"><div className="flex items-center justify-between gap-3 mb-7 text-[9px] font-black text-[#7c827e]"><span>{q.surahNameArabic||q.surahNameEnglish||'—'} · {q.startAyah}–{q.endAyah}</span><span>{loci.map(x=>`${ar?'ص':'p.'}${x.page} · ${ar?'س':'L'}${x.lineStart}${x.lineEnd!==x.lineStart?`–${x.lineEnd}`:''}`).join(' | ')}</span></div><div className="font-quran text-center text-2xl sm:text-[2.05rem] leading-[2.25] text-[#202622]" style={officialFont?{fontFamily:'"MIZAN KFGQPC Official"'}:undefined}>{q.expectedTextArabic}</div><div className="mt-8 flex items-center justify-center gap-2 text-[9px] text-[#7d837f]"><ShieldCheck className="w-3.5 h-3.5 text-[#2F6555]"/><span>{checked?(ar?'النص من الحزمة الرسمية؛ أصل الصفحة البصري غير مستورد على هذا الخادم.':'Text is from the official package; the visual page master is not imported on this server.'):(ar?'جارٍ التحقق من أصل الصفحة…':'Checking official page master…')}</span></div></div></div>}
  <div className="px-4 sm:px-5 py-3 border-t border-[#e5e1d7] flex items-center justify-between gap-3 text-[9px] text-[#818782]"><span className="font-mono truncate">{q.quranSourcePackageHash?`SHA-256 ${q.quranSourcePackageHash.slice(0,18)}…`:ar?'مصدر تطوير محلي':'Development source'}</span><span>{hasOfficialPage?(ar?'صفحة رسمية + عدسة منفصلة':'OFFICIAL PAGE + SEPARATE LENS'):officialFont?(ar?'نص وخط رسميان':'OFFICIAL TEXT + FONT'):(ar?'نص عثماني رسمي':'OFFICIAL UTHMANIC TEXT')}</span></div>
 </div>
}

const OfficialPage:React.FC<{url:string;locus:QuranPageLocus;ar:boolean;tracking?:QuranAlignmentResult|null}>=({url,locus,ar,tracking})=>{const live=tracking?.visualLocation?.page===locus.page?tracking.visualLocation:null;const liveLocus=live?.loci?.find(x=>x.page===locus.page);const focus=liveLocus||locus;const word=tracking?.wordVector?.page===locus.page&&tracking.wordVector.resolution==='VERIFIED_WORD_MAPPING'?tracking.wordVector.normalizedBBox:undefined;return <figure className="relative mx-auto w-fit"><div className="relative inline-block"><img src={url} alt={ar?`صفحة المصحف الرسمية ${locus.page}`:`Official Mushaf page ${locus.page}`} className="block max-h-[60vh] w-auto rounded-[2px] shadow-[0_12px_28px_rgba(0,0,0,.08)]"/>{focus.lineCount&&focus.lineCount>=focus.lineEnd?<FocusLens lineStart={focus.lineStart} lineEnd={focus.lineEnd} lineCount={focus.lineCount} ar={ar}/>:null}{word&&<WordVectorLens bbox={word}/>}</div><figcaption className="mt-2 text-center text-[9px] font-black text-[#6e756f]">{ar?'الصفحة':'Page'} {locus.page}{!focus.lineCount?<span className="ms-2 font-normal text-[#8a908c]">{ar?'هندسة الأسطر غير متاحة — بلا تخمين':'line geometry unavailable — no guess'}</span>:null}</figcaption></figure>}
const MissingPage:React.FC<{page:number;ar:boolean}>=({page,ar})=><div className="min-h-44 rounded-2xl border border-dashed border-[#d1cec5] bg-[#f8f6f0] grid place-items-center text-center p-6"><div><FileSearch className="w-5 h-5 mx-auto text-[#777e79]"/><div className="text-xs font-black mt-2">{ar?`الصفحة الرسمية ${page} غير مستوردة`:`Official page ${page} is not imported`}</div><div className="text-[9px] text-[#858b87] mt-1">{ar?'لا يُستخدم بديل من رواية أخرى.':'No cross-riwayah visual fallback.'}</div></div></div>;

const FocusLens:React.FC<{lineStart:number;lineEnd:number;lineCount:number;ar:boolean}>=({lineStart,lineEnd,lineCount,ar})=>{const total=Math.max(1,lineCount),start=Math.max(1,Math.min(total,lineStart)),end=Math.max(start,Math.min(total,lineEnd));const textTop=8.5,textHeight=83;const top=textTop+((start-1)/total)*textHeight,height=Math.max(2.4,((end-start+1)/total)*textHeight);return <div aria-label={ar?'عدسة موضع الاختبار':'Passage focus lens'} className="pointer-events-none absolute inset-0"><div className="absolute start-[7%] end-[7%] rounded-md border-y border-[#2F6555]/25 bg-[#2F6555]/[0.035] transition-all duration-300" style={{top:`${top}%`,height:`${height}%`}}/><div className="absolute end-[3.5%] w-[3px] rounded-full bg-[#2F6555] shadow-[0_0_0_4px_rgba(47,101,85,.08)] transition-all duration-300" style={{top:`${top}%`,height:`${height}%`}}/></div>}
const WordVectorLens:React.FC<{bbox:{x:number;y:number;width:number;height:number}}>=({bbox})=><div aria-hidden className="pointer-events-none absolute rounded-sm border-2 border-[#2F6555]/55 bg-[#2F6555]/[0.025] transition-all duration-200" style={{left:`${bbox.x*100}%`,top:`${bbox.y*100}%`,width:`${bbox.width*100}%`,height:`${bbox.height*100}%`}}/>;
