import React from 'react';
import {CircleDot,FileCheck2,MapPin,Radio,ShieldCheck,Sparkles} from 'lucide-react';
import type {QuranAlignmentResult,QuranPassageIntelligence} from '../../lib/quran-intelligence';
import {Badge} from '../design-system/Badge';

export const QuranIntelligenceDock:React.FC<{ar:boolean;data?:QuranPassageIntelligence|null;tracking?:QuranAlignmentResult|null;alignmentConfigured:boolean;educationMode:boolean;onEducationMode:(v:boolean)=>void}>=({ar,data,tracking,alignmentConfigured,educationMode,onEducationMode})=>{
 const currentAyah=tracking?.ayah||data?.startAyah;const current=data?.ayahs.find(x=>x.ayah===currentAyah)||data?.ayahs[0];const waqf=current?.waqf||[];const tajweed=current?.tajweed;
 const vectorReady=data?.knowledge.vector.status==='VERIFIED'&&data.knowledge.vector.verifiedWordMappings>0;
 const stages=[
  {id:'line',label:ar?'الآية والسطر':'Ayah + line',ready:!!data,detail:ar?'موضع رسمي من بيانات القراءة':'Official reading metadata'},
  {id:'waqf',label:ar?'الوقف':'Waqf',ready:data?.knowledge.waqf.status==='VERIFIED'&&data?.knowledge.waqfScience?.status==='VERIFIED',detail:ar?'علامات مطبوعة موثقة':'Verified printed signs'},
  {id:'tajweed',label:ar?'التجويد':'Tajweed',ready:data?.knowledge.tajweed.status==='VERIFIED',detail:ar?'قواعد ومواضع موثقة':'Verified rules + loci'},
  {id:'vector',label:ar?'الكلمة':'Word geometry',ready:vectorReady,detail:ar?'SVG / Adobe AI رسمي':'Official SVG / Adobe AI'},
  {id:'live',label:ar?'التتبع الحي':'Live tracking',ready:alignmentConfigured,detail:ar?'محرك مجتاز للمعيار':'Benchmarked aligner'}
 ];
 const completed=stages.filter(x=>x.ready).length;
 return <section className="mt-4 overflow-hidden rounded-[26px] border border-[#dcd8cd] bg-[linear-gradient(145deg,#fbfaf6_0%,#f5f4ee_54%,#eef3ef_100%)] shadow-[0_18px_48px_rgba(31,58,49,.07)]">
  <div className="relative px-4 py-4 sm:px-5 sm:py-5">
   <div className="pointer-events-none absolute -top-20 end-[-80px] h-44 w-44 rounded-full bg-[#dfeae4]/55 blur-3xl"/>
   <div className="relative flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
    <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl border border-[#d9e3dd] bg-white/85 text-[#214C40] shadow-sm"><Sparkles className="h-4.5 w-4.5"/></span><div><div className="text-[12px] font-black tracking-tight text-[#1f2a25]">{ar?'طبقة ذكاء القرآن':'QURAN INTELLIGENCE'}</div><div className="mt-0.5 text-[9px] font-semibold text-[#7a827d]">{ar?'وعي بالموضع · مصدر موثوق · القرار للحكم':'Position-aware · source-grounded · judge remains authority'}</div></div></div>
    <div className="flex flex-wrap items-center gap-2"><Badge variant={data?.knowledge.waqf.status==='VERIFIED'&&data?.knowledge.waqfScience?.status==='VERIFIED'?'emerald':'neutral'}>{ar?'الوقف':'WAQF'} · {waqfStatusLabel(data?.knowledge.waqf.status,data?.knowledge.waqfScience?.status,ar)}</Badge><Badge variant={data?.knowledge.tajweed.status==='VERIFIED'?'emerald':'neutral'}>{ar?'التجويد':'TAJWEED'} · {statusLabel(data?.knowledge.tajweed.status,ar)}</Badge><Badge variant={vectorReady?'emerald':'neutral'}>{ar?'هندسة الكلمات':'WORD VECTOR'} · {vectorReady?(ar?'موثّقة':'VERIFIED'):(ar?'بانتظار الأصل':'PENDING MASTER')}</Badge></div>
   </div>

   <div className="relative mt-4 rounded-2xl border border-white/90 bg-white/60 p-3 shadow-[inset_0_1px_0_rgba(255,255,255,.8)] backdrop-blur-sm">
    <div className="mb-2 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-[9px] font-black text-[#59645e]"><MapPin className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'سلسلة الجاهزية لهذا الموضع':'READINESS CHAIN'}</div><span className="text-[9px] font-black tabular-nums text-[#2F6555]">{completed}/{stages.length}</span></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{stages.map((s,i)=><div key={s.id} className={`relative min-h-[68px] rounded-xl border px-2.5 py-2.5 transition-colors ${s.ready?'border-[#cfe0d6] bg-[#edf5f0]':'border-[#e3e0d7] bg-[#faf9f5]'}`}><div className="flex items-center gap-1.5"><span className={`h-1.5 w-1.5 rounded-full ${s.ready?'bg-[#2F6555]':'bg-[#c7c2b6]'}`}/><span className={`text-[9px] font-black ${s.ready?'text-[#214C40]':'text-[#747b76]'}`}>{s.label}</span></div><div className="mt-1.5 text-[8px] leading-3.5 text-[#8a8f8b]">{s.detail}</div>{i<stages.length-1&&<span className="pointer-events-none absolute top-1/2 -end-[7px] hidden h-px w-3 bg-[#d7d4cb] sm:block"/>}</div>)}</div>
   </div>

   <div className="mt-3 grid gap-3 lg:grid-cols-[1.08fr_.96fr_.96fr]">
    <div className="rounded-2xl border border-[#e4e1d8] bg-white/78 p-3.5 shadow-sm"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[10px] font-black text-[#29342f]"><Radio className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'التتبع الحي':'LIVE ALIGNMENT'}</span><Badge variant={tracking&&['LOCKED','REACQUIRED'].includes(tracking.alignmentState)?'emerald':tracking&&['LOST','REACQUIRING'].includes(tracking.alignmentState)?'amber':'neutral'}>{tracking?alignmentLabel(tracking.alignmentState,ar):(alignmentConfigured?(ar?'جاهز — ظل':'SHADOW READY'):(data?.alignmentBenchmark?.status!=='VERIFIED'?(ar?'المعيار بانتظار الاعتماد':'BENCHMARK PENDING'):(ar?'المحرك غير موصول':'BACKEND OFF')))}</Badge></div>
     {tracking?<><div className="mt-3 flex items-end gap-2"><span className="text-2xl font-black tabular-nums text-[#214C40]">{Math.round(tracking.smoothedConfidence*100)}%</span><span className="pb-1 text-[9px] font-bold text-[#7d847f]">{ar?'ثقة التتبع':'tracking confidence'}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e9ece9]"><div className="h-full rounded-full bg-[#2F6555] transition-all duration-300" style={{width:`${Math.max(0,Math.min(100,tracking.smoothedConfidence*100))}%`}}/></div><div className="mt-2 flex flex-wrap gap-1.5 text-[9px]"><span className="rounded-lg bg-[#f4f5f1] px-2 py-1 font-black">{ar?'آية':'Ayah'} {tracking.ayah||'—'}</span><span className="rounded-lg bg-[#f4f5f1] px-2 py-1 font-black">{ar?'كلمة':'Word'} {tracking.wordIndex||'—'}</span><span className="rounded-lg bg-[#f4f5f1] px-2 py-1 font-black">{recoveryLabel(tracking.recoveryState,ar)}</span></div><div className="mt-2 text-[8px] font-black tracking-wide text-[#8a908c]">SHADOW ONLY · HUMAN SCORE AUTHORITY</div></>:<div className="mt-3 flex items-start gap-2 text-[10px] leading-5 text-[#737a75]"><MapPin className="mt-1 h-3.5 w-3.5 shrink-0"/><span>{alignmentConfigured?(ar?'المحرك معتمد وجاهز لبدء الميكروفون في وضع الظل.':'The approved engine is ready for microphone shadow tracking.'):(ar?'واجهة الصوت، التثبيت وإعادة التقاط الموضع جاهزة؛ التشغيل ينتظر محركًا مجتازًا لمعيار الرواية.':'Audio transport, smoothing and reacquisition are ready; activation waits for a reading-benchmarked aligner.')}</span></div>}
    </div>

    <div className="rounded-2xl border border-[#e4e1d8] bg-white/78 p-3.5 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-black text-[#29342f]"><CircleDot className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'الوقف في الآية الحالية':'WAQF · CURRENT AYAH'}</div>{waqf.length?<div className="mt-3 flex flex-wrap gap-2">{waqf.slice(0,8).map((x,i)=><span key={`${x.evidenceId}-${i}`} title={x.officialMeaning} className="group rounded-xl border border-[#ddd9ce] bg-[#f8f6ef] px-2.5 py-1.5"><span className="text-[13px] font-black text-[#2b3933]">{x.displayLabel||x.symbol}</span><span className="ms-1.5 text-[8px] font-semibold text-[#747b76]">{x.officialMeaning}</span></span>)}</div>:<div className="mt-3 flex items-start gap-2 text-[10px] leading-5 text-[#7d837f]"><ShieldCheck className="mt-1 h-3.5 w-3.5 shrink-0"/><span>{data?.knowledge.waqf.status==='VERIFIED'?(ar?'لا توجد علامة وقف مطبوعة موثقة في الآية الحالية.':'No verified printed waqf sign in the current ayah.'):(ar?'المشتق البرمجي جاهز، وسيُملأ تلقائيًا من النص الرسمي عند وصول حزمة المجمع.':'The derivation pipeline is ready and will populate automatically from the official text package.')}</span></div>}</div>

    <div className="rounded-2xl border border-[#e4e1d8] bg-white/78 p-3.5 shadow-sm"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[10px] font-black text-[#29342f]"><FileCheck2 className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'مرجع التجويد':'TAJWEED REFERENCE'}</span><button type="button" onClick={()=>onEducationMode(!educationMode)} className={`rounded-lg border px-2 py-1 text-[8px] font-black transition-colors ${educationMode?'border-[#c8dbd1] bg-[#eaf3ee] text-[#214C40]':'border-[#dad7ce] bg-white text-[#6f7671] hover:bg-[#f3f1ea]'}`}>{educationMode?(ar?'التعليم ظاهر':'EDUCATION ON'):(ar?'إظهار التعليم':'EDUCATION')}</button></div>{educationMode&&tajweed?.rules.length?<div className="mt-3 space-y-2">{tajweed.rules.slice(0,3).map(r=><div key={r.id} className="rounded-xl bg-[#f7f6f1] px-2.5 py-2"><div className="text-[10px] font-black text-[#2b3731]">{r.nameArabic}</div><div className="mt-1 text-[8px] leading-4 text-[#777e79]">{r.summaryArabic}</div></div>)}</div>:<div className="mt-3 text-[10px] leading-5 text-[#7d837f]">{educationMode?(data?.knowledge.tajweed.status==='VERIFIED'?(ar?'لا يوجد حكم موضعي موثق لهذه الآية ضمن البيانات المستوردة.':'No verified localized Tajweed occurrence for this ayah.'):(ar?'البنية جاهزة؛ لا نعرض حكمًا مستنتجًا قبل استيراد مادة المجمع وربط evidence.':'The layer is ready; no rule is inferred before official material and evidence are imported.')):(ar?'الوضع التعليمي مغلق افتراضيًا ليبقى سطح الحكم هادئًا.':'Education stays off by default to keep the judging surface calm.')}</div>}</div>
   </div>

   <div className="mt-3 flex items-start gap-2 rounded-xl border border-[#e3e0d8] bg-white/45 px-3 py-2.5 text-[8.5px] leading-4 text-[#7c837e]"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2F6555]"/><span>{ar?'المصدر القرآني مقفول على مجمع الملك فهد: لا OCR، لا TTS قرآني، لا تخمين هندسي للكلمة، ولا fallback بين الروايات. الميزات التي تنتظر الأصل الرسمي تبقى ظاهرة كـ «بانتظار المصدر» بدل ملئها ببيانات غير موثقة.':'Quran authority is locked to KFGQPC: no OCR, no Quran TTS, no guessed word geometry, and no cross-riwayah fallback. Features waiting on official masters remain explicitly pending rather than being filled with unverified data.'}</span></div>
  </div>
 </section>
}

function waqfStatusLabel(signs:string|undefined,science:string|undefined,ar:boolean){if(signs==='VERIFIED'&&science==='VERIFIED')return ar?'موثّق كامل':'VERIFIED';if(signs==='VERIFIED')return ar?'العلامات جاهزة':'SIGNS READY';return ar?'بانتظار المصدر':'SOURCE PENDING'}
function statusLabel(v:string|undefined,ar:boolean){if(v==='VERIFIED')return ar?'موثّق':'VERIFIED';if(v==='QUARANTINED')return ar?'محجور':'QUARANTINED';if(v==='UNVERIFIED')return ar?'غير معتمد':'UNVERIFIED';return ar?'بانتظار المصدر':'SOURCE PENDING'}
function alignmentLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={LOCKED:['ثابت','LOCKED'],PROBABLE:['مرجح','PROBABLE'],UNCERTAIN:['غير مؤكد','UNCERTAIN'],LOST:['فقد الموضع','LOST'],REACQUIRING:['يعيد التحديد','REACQUIRING'],REACQUIRED:['استعاد الموضع','REACQUIRED']};return (x[v]||[v,v])[ar?0:1]}
function recoveryLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={NONE:['متصل','Continuous'],REPEAT:['تكرار','Repeat'],BACKTRACK:['رجوع','Backtrack'],SKIP:['تجاوز','Skip'],SILENCE:['سكون','Silence'],RESTART:['إعادة بدء','Restart'],MID_PASSAGE_START:['بدء من المنتصف','Mid-passage']};return (x[v]||[v,v])[ar?0:1]}
