import React,{useMemo,useState} from 'react';
import {Activity,ChevronDown,CircleDot,Clock3,FileCheck2,MapPin,Play,Radio,ShieldCheck,Sparkles,TriangleAlert} from 'lucide-react';
import type {QuranAlignmentResult,QuranPassageIntelligence,QuranReadingGuard,QuranSessionEvidence} from '../../lib/quran-intelligence';
import {Badge} from '../design-system/Badge';

interface Props{ar:boolean;data?:QuranPassageIntelligence|null;tracking?:QuranAlignmentResult|null;alignmentConfigured:boolean;educationMode:boolean;onEducationMode:(v:boolean)=>void;sessionEvidence?:QuranSessionEvidence|null;readingGuard?:QuranReadingGuard|null;replayAvailable?:boolean;onReplay?:(offsetMs:number)=>void}
export const QuranIntelligenceDock:React.FC<Props>=({ar,data,tracking,alignmentConfigured,educationMode,onEducationMode,sessionEvidence,readingGuard,replayAvailable,onReplay})=>{
 const [details,setDetails]=useState(false);const [timelineOpen,setTimelineOpen]=useState(false);
 const currentAyah=tracking?.ayah||data?.startAyah,current=data?.ayahs.find(x=>x.ayah===currentAyah)||data?.ayahs[0],waqf=current?.waqf||[],tajweed=current?.tajweed;
 const vectorReady=data?.knowledge.vector.status==='VERIFIED'&&data.knowledge.vector.verifiedWordMappings>0,guardBlocked=readingGuard?.status==='BLOCKED',attention=guardBlocked||tracking?.alignmentState==='LOST'||tracking?.alignmentState==='REACQUIRING';
 const stages=useMemo(()=>[
  {id:'line',label:ar?'الموضع':'Position',ready:!!data},
  {id:'waqf',label:ar?'الوقف':'Waqf',ready:data?.knowledge.waqf.status==='VERIFIED'&&data?.knowledge.waqfScience?.status==='VERIFIED'},
  {id:'tajweed',label:ar?'التجويد':'Tajweed',ready:data?.knowledge.tajweed.status==='VERIFIED'},
  {id:'vector',label:ar?'الكلمة':'Word',ready:vectorReady},
  {id:'live',label:ar?'التتبع':'Tracking',ready:alignmentConfigured}
 ],[ar,data,vectorReady,alignmentConfigured]);const completed=stages.filter(x=>x.ready).length;
 const events=sessionEvidence?.events||[],recent=events.slice(-12).reverse();
 return <section className={`mt-4 overflow-hidden rounded-[28px] border shadow-[0_18px_52px_rgba(31,58,49,.065)] transition ${attention?'border-[#d8c9aa] bg-[#fbf7ef]':'border-[#ddd9cf] bg-[linear-gradient(145deg,#fbfaf6_0%,#f4f5ef_52%,#eef3ef_100%)]'}`}>
  <div className="relative p-4 sm:p-5">
   <div className="pointer-events-none absolute -top-20 end-[-70px] h-44 w-44 rounded-full bg-[#dfeae4]/55 blur-3xl"/>
   <div className="relative flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl border border-[#d9e3dd] bg-white/85 text-[#214C40] shadow-sm"><Sparkles className="h-4.5 w-4.5"/></span><div className="min-w-0"><div className="text-[12px] font-black text-[#1f2a25]">{ar?'ذكاء القرآن':'QURAN INTELLIGENCE'}</div><div className="mt-0.5 truncate text-[9px] font-semibold text-[#646b67]">{ar?'هادئ أثناء التحكيم · يتوسع فقط عند الحاجة':'Calm by default · expands only when needed'}</div></div></div><div className="flex items-center gap-2"><Badge variant={guardBlocked?'rose':attention?'amber':'emerald'}>{guardBlocked?(ar?'تعارض رواية محجوب':'READING BLOCKED'):attention?(ar?'يستعيد الموضع':'REACQUIRING'):(ar?'الحالة مستقرة':'STABLE')}</Badge><button type="button" onClick={()=>setDetails(v=>!v)} className="grid h-8 w-8 place-items-center rounded-xl border border-[#ddd9d0] bg-white/80 text-[#66706a]" aria-label={ar?'تفاصيل':'Details'}>{details?<ChevronDown className="h-4 w-4 rotate-180"/>:<ChevronDown className="h-4 w-4"/>}</button></div></div>

   {guardBlocked&&<div className="relative mt-3 flex items-start gap-2 rounded-2xl border border-[#e2c8c2] bg-[#fff8f6] px-3 py-2.5 text-[10px] leading-5 text-[#7c4f48]"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0"/><span>{ar?'تم حجب أي دمج بين الروايات. لا fallback صامت، ولا وقف/تجويد/هندسة من حزمة مختلفة.':'Cross-reading composition is blocked. No silent fallback and no Waqf, Tajweed or geometry from a different reading.'}</span></div>}

   <div className="relative mt-3 grid gap-3 lg:grid-cols-[1.12fr_.88fr]">
    <div className="rounded-2xl border border-white/90 bg-white/72 p-3.5 backdrop-blur-sm"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[10px] font-black text-[#29342f]"><Radio className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'التتبع الحي الصامت':'SILENT SHADOW TRACKING'}</span><Badge variant={tracking&&['LOCKED','REACQUIRED'].includes(tracking.alignmentState)?'emerald':tracking&&['LOST','REACQUIRING'].includes(tracking.alignmentState)?'amber':'neutral'}>{tracking?alignmentLabel(tracking.alignmentState,ar):(alignmentConfigured?(ar?'جاهز':'READY'):(ar?'بانتظار المحرك':'ENGINE PENDING'))}</Badge></div>
     {tracking?<><div className="mt-3 flex items-end gap-2"><span className="text-3xl font-black tabular-nums text-[#214C40]">{Math.round(tracking.smoothedConfidence*100)}%</span><span className="pb-1 text-[9px] font-bold text-[#666b67]">{ar?'ثقة':'confidence'}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e8ece9]"><div className="h-full rounded-full bg-[#2F6555] transition-all duration-300" style={{width:`${Math.max(0,Math.min(100,tracking.smoothedConfidence*100))}%`}}/></div><div className="mt-2 flex flex-wrap gap-1.5 text-[9px]"><Soft>{ar?'آية':'Ayah'} {tracking.ayah||'—'}</Soft><Soft>{ar?'كلمة':'Word'} {tracking.wordIndex||'—'}</Soft><Soft>{recoveryLabel(tracking.recoveryState,ar)}</Soft></div></>:<p className="mt-3 text-[10px] leading-5 text-[#646965]">{ar?'طبقة الظل لا تغيّر الدرجة مطلقًا؛ عند وصول محرك مجتاز للمعيار تسجل الموضع والثقة للاستدلال والمراجعة فقط.':'Shadow mode never changes the score. Once a benchmarked aligner is connected, it records locus and confidence for evidence only.'}</p>}
     <div className="mt-3 flex items-center gap-2 text-[8px] font-black tracking-wide text-[#696f6b]"><ShieldCheck className="h-3 w-3"/>HUMAN SCORE AUTHORITY · SCORE Δ 0</div>
    </div>
    <div className="rounded-2xl border border-white/90 bg-white/72 p-3.5"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-[10px] font-black text-[#29342f]"><Activity className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'سلسلة الجاهزية':'READINESS'}</span><span className="text-[10px] font-black tabular-nums text-[#2F6555]">{completed}/{stages.length}</span></div><div className="mt-3 flex items-center gap-1.5">{stages.map(s=><div key={s.id} title={s.label} className={`h-2 flex-1 rounded-full ${s.ready?'bg-[#2F6555]':'bg-[#dedbd2]'}`}/>)}</div><div className="mt-2 flex justify-between gap-2 text-[8px] font-bold text-[#686d6a]">{stages.map(s=><span key={s.id} className="truncate">{s.label}</span>)}</div></div>
   </div>

   {(waqf.length>0||educationMode||details)&&<div className="relative mt-3 grid gap-3 lg:grid-cols-2">
    <div className="rounded-2xl border border-[#e3e0d7] bg-white/68 p-3.5"><div className="flex items-center gap-2 text-[10px] font-black"><CircleDot className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'الوقف في الموضع الحالي':'WAQF · CURRENT LOCUS'}</div>{waqf.length?<div className="mt-3 flex flex-wrap gap-2">{waqf.slice(0,6).map((x,i)=><span key={`${x.evidenceId}-${i}`} className="rounded-xl border border-[#ddd9ce] bg-[#f8f6ef] px-2.5 py-1.5"><b className="text-[13px]">{x.displayLabel||x.symbol}</b><span className="ms-1.5 text-[8px] text-[#636864]">{x.officialMeaning}</span></span>)}</div>:<p className="mt-3 text-[10px] leading-5 text-[#666b68]">{ar?'لا توجد علامة موثقة معروضة لهذا الموضع، ولا يتم التخمين.':'No verified sign is displayed for this locus; nothing is inferred.'}</p>}</div>
    <div className="rounded-2xl border border-[#e3e0d7] bg-white/68 p-3.5"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[10px] font-black"><FileCheck2 className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'التجويد':'TAJWEED'}</span><button type="button" onClick={()=>onEducationMode(!educationMode)} className={`rounded-lg border px-2 py-1 text-[8px] font-black ${educationMode?'border-[#c8dbd1] bg-[#eaf3ee] text-[#214C40]':'border-[#dad7ce] bg-white text-[#616762]'}`}>{educationMode?(ar?'إخفاء':'HIDE'):(ar?'تعليم':'EDUCATION')}</button></div>{educationMode&&tajweed?.rules.length?<div className="mt-3 space-y-2">{tajweed.rules.slice(0,2).map(r=><div key={r.id} className="rounded-xl bg-[#f7f6f1] px-2.5 py-2"><div className="text-[10px] font-black">{r.nameArabic}</div><div className="mt-1 text-[8px] leading-4 text-[#646965]">{r.summaryArabic}</div></div>)}</div>:<p className="mt-3 text-[10px] leading-5 text-[#666b68]">{educationMode?(ar?'لا تُعرض قاعدة غير موثقة قبل استيراد Evidence الرسمي.':'No rule is shown before official evidence is imported.'):(ar?'مخفي افتراضيًا لتجنب التلوث البصري.':'Hidden by default to avoid visual noise.')}</p>}</div>
   </div>}

   {details&&<div className="relative mt-3 rounded-2xl border border-[#e3e0d8] bg-white/58 p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant={data?.knowledge.waqf.status==='VERIFIED'?'emerald':'neutral'}>{ar?'علامات الوقف':'WAQF SIGNS'} · {statusLabel(data?.knowledge.waqf.status,ar)}</Badge><Badge variant={data?.knowledge.waqfScience?.status==='VERIFIED'?'emerald':'neutral'}>{ar?'علم الوقف':'WAQF SCIENCE'} · {statusLabel(data?.knowledge.waqfScience?.status,ar)}</Badge><Badge variant={data?.knowledge.tajweed.status==='VERIFIED'?'emerald':'neutral'}>{ar?'التجويد':'TAJWEED'} · {statusLabel(data?.knowledge.tajweed.status,ar)}</Badge><Badge variant={vectorReady?'emerald':'neutral'}>{ar?'هندسة الكلمة':'WORD VECTOR'} · {vectorReady?(ar?'موثقة':'VERIFIED'):(ar?'بانتظار الأصل':'MASTER PENDING')}</Badge></div></div>}

   <div className="relative mt-3 overflow-hidden rounded-2xl border border-[#e3e0d8] bg-white/56"><button type="button" onClick={()=>setTimelineOpen(v=>!v)} className="flex w-full items-center justify-between gap-3 px-3.5 py-3 text-start"><span className="flex items-center gap-2 text-[10px] font-black"><Clock3 className="h-3.5 w-3.5 text-[#2F6555]"/>{ar?'خط الأدلة وإعادة المشاهدة':'EVIDENCE TIMELINE & REPLAY'}</span><span className="flex items-center gap-2 text-[9px] font-black text-[#616763]">{events.length} {ar?'حدث':'events'} {timelineOpen?<ChevronDown className="h-3.5 w-3.5 rotate-180"/>:<ChevronDown className="h-3.5 w-3.5"/>}</span></button>{timelineOpen&&<div className="border-t border-[#e6e3db] px-3.5 py-3">{recent.length?<div className="space-y-1.5">{recent.map(e=><button key={e.id} type="button" onClick={()=>replayAvailable&&onReplay?.(e.offsetMs)} disabled={!replayAvailable} className="flex w-full items-center gap-3 rounded-xl px-2.5 py-2 text-start hover:bg-[#f5f4ef] disabled:cursor-default"><span className={`h-2 w-2 shrink-0 rounded-full ${e.kind==='HUMAN_MARKER'?'bg-[#846d43]':e.alignmentState==='LOST'?'bg-[#a96956]':'bg-[#2F6555]'}`}/><div className="min-w-0 flex-1"><div className="truncate text-[9px] font-black">{eventLabel(e,ar)}</div><div className="mt-0.5 text-[8px] text-[#686d6a]">{formatOffset(e.offsetMs)}{e.confidence!==undefined?` · ${Math.round(e.confidence*100)}%`:''}</div></div>{replayAvailable&&<Play className="h-3 w-3 text-[#66706a]"/>}</button>)}</div>:<div className="flex items-center gap-2 py-2 text-[9px] text-[#656b66]"><FileCheck2 className="h-3.5 w-3.5"/>{ar?'يبدأ الخط الزمني تلقائيًا مع أول نتيجة من محرك الظل.':'The timeline begins automatically with the first shadow result.'}</div>}<div className="mt-2 text-[8px] leading-4 text-[#696f6b]">{replayAvailable?(ar?'يمكن تشغيل التسجيل من نفس لحظة الحدث.':'Replay seeks to the exact event offset in the session recording.'):(ar?'إعادة الصوت تظهر بعد حفظ تسجيل الجلسة المصرح به.':'Audio replay appears after the consented session recording is saved.')}</div></div>}</div>

   <div className="relative mt-3 flex items-start gap-2 text-[8.5px] leading-4 text-[#666b67]"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2F6555]"/><span>{ar?'المصدر القرآني مقفول على مجمع الملك فهد: لا OCR، لا TTS قرآني، لا تخمين هندسي للكلمة، ولا fallback بين الروايات.':'Quran authority is locked to KFGQPC: no OCR, no Quran TTS, no guessed word geometry, and no cross-reading fallback.'}</span></div>
  </div>
 </section>
}
const Soft=({children}:{children:React.ReactNode})=><span className="rounded-lg bg-[#f3f4ef] px-2 py-1 font-black">{children}</span>;
function statusLabel(v:string|undefined,ar:boolean){if(v==='VERIFIED')return ar?'موثّق':'VERIFIED';if(v==='QUARANTINED')return ar?'محجور':'QUARANTINED';if(v==='UNVERIFIED')return ar?'غير معتمد':'UNVERIFIED';return ar?'بانتظار المصدر':'PENDING'}
function alignmentLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={LOCKED:['ثابت','LOCKED'],PROBABLE:['مرجح','PROBABLE'],UNCERTAIN:['غير مؤكد','UNCERTAIN'],LOST:['فقد الموضع','LOST'],REACQUIRING:['يعيد التحديد','REACQUIRING'],REACQUIRED:['استعاد الموضع','REACQUIRED']};return (x[v]||[v,v])[ar?0:1]}
function recoveryLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={NONE:['متصل','Continuous'],REPEAT:['تكرار','Repeat'],BACKTRACK:['رجوع','Backtrack'],SKIP:['تجاوز','Skip'],SILENCE:['سكون','Silence'],RESTART:['إعادة بدء','Restart'],MID_PASSAGE_START:['بدء من المنتصف','Mid-passage']};return (x[v]||[v,v])[ar?0:1]}
function formatOffset(ms:number){const s=Math.floor(ms/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function eventLabel(e:QuranSessionEvidence['events'][number],ar:boolean){if(e.kind==='HUMAN_MARKER')return ar?`قرار حكم · ${e.humanEventType||'—'}`:`Judge marker · ${e.humanEventType||'—'}`;if(e.kind==='SESSION_RESET')return ar?'إغلاق مسار التتبع':'Tracking stream reset';const locus=e.ayah?`${ar?'آية':'Ayah'} ${e.ayah}${e.wordIndex?` · ${ar?'كلمة':'Word'} ${e.wordIndex}`:''}`:(ar?'موضع غير مثبت':'Unresolved locus');return `${locus} · ${alignmentLabel(e.alignmentState||'UNCERTAIN',ar)}`}
