import React from 'react';
import {FileCheck2,Sparkles,MapPin,CircleDot,ShieldCheck} from 'lucide-react';
import type {QuranAlignmentResult,QuranPassageIntelligence} from '../../lib/quran-intelligence';
import {Badge} from '../design-system/Badge';

export const QuranIntelligenceDock:React.FC<{ar:boolean;data?:QuranPassageIntelligence|null;tracking?:QuranAlignmentResult|null;alignmentConfigured:boolean;educationMode:boolean;onEducationMode:(v:boolean)=>void}>=({ar,data,tracking,alignmentConfigured,educationMode,onEducationMode})=>{
 const currentAyah=tracking?.ayah||data?.startAyah;const current=data?.ayahs.find(x=>x.ayah===currentAyah)||data?.ayahs[0];const waqf=current?.waqf||[];const tajweed=current?.tajweed;
 return <div className="mt-4 rounded-2xl border border-[#e1ded5] bg-[#faf8f2] px-4 py-4">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><span className="w-8 h-8 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><Sparkles className="w-4 h-4"/></span><div><div className="text-[11px] font-black">{ar?'طبقة ذكاء القرآن':'QURAN INTELLIGENCE'}</div><div className="text-[9px] text-[#7c827e]">{ar?'مرجع مساعد للحكم — لا يغيّر الدرجة':'Judge assistance only — never changes score'}</div></div></div><div className="flex flex-wrap gap-2"><Badge variant={data?.knowledge.waqf.status==='VERIFIED'?'emerald':'neutral'}>{ar?'الوقف':'WAQF'} · {statusLabel(data?.knowledge.waqf.status,ar)}</Badge><Badge variant={data?.knowledge.tajweed.status==='VERIFIED'?'emerald':'neutral'}>{ar?'التجويد':'TAJWEED'} · {statusLabel(data?.knowledge.tajweed.status,ar)}</Badge><Badge variant={data?.knowledge.vector.status==='VERIFIED'?'emerald':'neutral'}>{ar?'المتجهات':'VECTOR'} · {statusLabel(data?.knowledge.vector.status,ar)}</Badge></div></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-3">
   <div className="rounded-xl bg-white/70 border border-[#e8e5dc] p-3"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[10px] font-black"><MapPin className="w-3.5 h-3.5"/>{ar?'التتبع الحي':'LIVE ALIGNMENT'}</span><Badge variant={tracking&&['LOCKED','REACQUIRED'].includes(tracking.alignmentState)?'emerald':tracking&&['LOST','REACQUIRING'].includes(tracking.alignmentState)?'amber':'neutral'}>{tracking?alignmentLabel(tracking.alignmentState,ar):(alignmentConfigured?(ar?'ظلّ جاهز':'SHADOW READY'):(data?.alignmentBenchmark?.status!=='VERIFIED'?(ar?'المعيار غير معتمد':'BENCHMARK PENDING'):(ar?'المحرك غير موصول':'BACKEND OFF')))}</Badge></div><div className="mt-2 text-[10px] text-[#737a75] leading-5">{tracking?(ar?`آية ${tracking.ayah||'—'} · كلمة ${tracking.wordIndex||'—'} · ثقة ${Math.round(tracking.smoothedConfidence*100)}%`:`Ayah ${tracking.ayah||'—'} · word ${tracking.wordIndex||'—'} · confidence ${Math.round(tracking.smoothedConfidence*100)}%`):(ar?'يبدأ التتبع فقط إذا وُصل محرك المحاذاة القرآني واجتاز معيار الرواية.':'Tracking starts only when the Quran aligner is connected and the reading benchmark is approved.')}</div>{tracking&&<div className="mt-1 text-[9px] font-black text-[#8a908c]">SHADOW ONLY · HUMAN SCORE AUTHORITY</div>}</div>
   <div className="rounded-xl bg-white/70 border border-[#e8e5dc] p-3"><div className="flex items-center gap-2 text-[10px] font-black"><CircleDot className="w-3.5 h-3.5"/>{ar?'علامات الوقف للموضع الحالي':'WAQF AT CURRENT LOCUS'}</div>{waqf.length?<div className="mt-2 flex flex-wrap gap-2">{waqf.slice(0,6).map((x,i)=><span key={`${x.evidenceId}-${i}`} title={x.officialMeaning} className="rounded-lg border border-[#ddd9ce] bg-[#f8f6ef] px-2 py-1 text-[11px] font-black">{x.symbol}<span className="ms-1 text-[9px] font-normal text-[#747b76]">{x.officialMeaning}</span></span>)}</div>:<div className="mt-2 text-[10px] text-[#7d837f]">{data?.knowledge.waqf.status==='VERIFIED'?(ar?'لا توجد علامة موثقة لهذا الموضع في البيانات المستوردة.':'No verified waqf marker for this locus.'):(ar?'لا تُعرض علامات غير مستوردة من المصدر الرسمي.':'No marker is inferred without imported official data.')}</div>}</div>
   <div className="rounded-xl bg-white/70 border border-[#e8e5dc] p-3"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[10px] font-black"><FileCheck2 className="w-3.5 h-3.5"/>{ar?'الوضع التعليمي للتجويد':'TAJWEED EDUCATION'}</span><button type="button" onClick={()=>onEducationMode(!educationMode)} className="rounded-lg border border-[#dad7ce] px-2 py-1 text-[9px] font-black hover:bg-[#f3f1ea]">{educationMode?(ar?'إيقاف':'OFF'):(ar?'تشغيل':'ON')}</button></div>{educationMode&&tajweed?.rules.length?<div className="mt-2 space-y-2">{tajweed.rules.slice(0,3).map(r=><div key={r.id}><div className="text-[10px] font-black">{r.nameArabic}</div><div className="text-[9px] leading-4 text-[#777e79]">{r.summaryArabic}</div></div>)}</div>:<div className="mt-2 text-[10px] text-[#7d837f]">{educationMode?(data?.knowledge.tajweed.status==='VERIFIED'?(ar?'لا يوجد occurrence موثق لهذا الموضع.':'No verified occurrence at this locus.'):(ar?'لا تُستنتج أحكام آية/كلمة بلا evidence موثوق.':'No word/ayah rule is inferred without trusted evidence.')):(ar?'مغلق حتى لا تغرق شاشة الحكم بالألوان.':'Off to keep JudgeOS visually quiet.')}</div>}</div>
  </div>
  <div className="mt-3 flex items-center gap-2 text-[9px] text-[#858b87]"><ShieldCheck className="w-3.5 h-3.5"/><span>{ar?'المصدر القرآني: KFGQPC فقط عند توفر الأصل · لا OCR · لا TTS · لا fallback بين الروايات.':'Quran source: KFGQPC whenever official data exists · no OCR · no Quran TTS · no cross-riwayah fallback.'}</span></div>
 </div>
}

function statusLabel(v:string|undefined,ar:boolean){if(v==='VERIFIED')return ar?'موثّق':'VERIFIED';if(v==='QUARANTINED')return ar?'محجور':'QUARANTINED';if(v==='UNVERIFIED')return ar?'غير معتمد':'UNVERIFIED';return ar?'غير متاح رسميًا':'OFFICIAL DATA UNAVAILABLE'}
function alignmentLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={LOCKED:['ثابت','LOCKED'],PROBABLE:['مرجح','PROBABLE'],UNCERTAIN:['غير مؤكد','UNCERTAIN'],LOST:['فقد الموضع','LOST'],REACQUIRING:['يعيد التحديد','REACQUIRING'],REACQUIRED:['استعاد الموضع','REACQUIRED']};return (x[v]||[v,v])[ar?0:1]}
