import React,{useEffect,useMemo,useState} from 'react';
import { Award, Search, UserRound, X } from 'lucide-react';
import { useAppStore } from '../../lib/store';

export const CommandPalette:React.FC<{open?:boolean;onOpenChange?:(v:boolean)=>void}>=({open:controlled,onOpenChange})=>{
 const s=useAppStore();const ar=s.language==='ar';const [internal,setInternal]=useState(false);const [q,setQ]=useState('');const open=controlled??internal;const setOpen=(v:boolean)=>{setInternal(v);onOpenChange?.(v);if(!v)setQ('')};
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(!open)}if(e.key==='Escape'&&open)setOpen(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[open]);
 const results=useMemo(()=>{const x=q.trim().toLowerCase();if(!x)return[] as {id:string;kind:string;title:string;meta:string}[];return [
  ...s.participants.filter(p=>`${p.code} ${p.fullName} ${p.fullNameArabic} ${p.email}`.toLowerCase().includes(x)).slice(0,5).map(p=>({id:p.id,kind:'participant',title:ar?p.fullNameArabic:p.fullName,meta:`${p.code} · ${p.status}`})),
  ...s.competitions.filter(c=>`${c.name} ${c.nameArabic} ${c.edition}`.toLowerCase().includes(x)).slice(0,3).map(c=>({id:c.id,kind:'competition',title:ar?c.nameArabic:c.name,meta:c.edition})),
  ...s.certificates.filter(c=>`${c.certificateNumber} ${c.participantName} ${c.participantNameArabic}`.toLowerCase().includes(x)).slice(0,3).map(c=>({id:c.id,kind:'certificate',title:c.certificateNumber,meta:ar?c.participantNameArabic:c.participantName}))
 ].slice(0,9)},[q,s.participants,s.competitions,s.certificates,ar]);
 if(!open)return null;
 return <div className="fixed inset-0 z-[80] bg-black/20 p-4 sm:p-12" onMouseDown={()=>setOpen(false)}><div className="mx-auto max-w-xl mizan-surface overflow-hidden shadow-lg" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-[#e5e3dc] px-4"><Search className="w-4 h-4 text-[#758079]"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث عن متسابق، مسابقة، شهادة…':'Search participant, competition, certificate…'} className="min-w-0 flex-1 bg-transparent py-4 text-sm outline-none"/><kbd className="hidden sm:block text-[9px] border border-[#ddd] rounded-md px-1.5 py-1 text-[#777]">⌘K</kbd><button onClick={()=>setOpen(false)} aria-label={ar?'إغلاق':'Close'} className="w-8 h-8 rounded-lg grid place-items-center hover:bg-[#efede7]"><X className="w-4 h-4"/></button></div><div className="p-2 max-h-[420px] overflow-y-auto">{!q?<div className="p-8 text-center text-xs text-[#858c87]">{ar?'اكتب للبحث. النتائج مقيدة بصلاحيات وسياق الجهة الحالية.':'Type to search. Results stay within the current tenant context.'}</div>:results.length?results.map(r=><button key={`${r.kind}-${r.id}`} onClick={()=>{if(r.kind==='competition')s.selectCompetition(r.id);setOpen(false)}} className="w-full rounded-xl p-3 hover:bg-[#f2f0ea] text-start flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center">{r.kind==='participant'?<UserRound className="w-4 h-4"/>:r.kind==='certificate'?<Award className="w-4 h-4"/>:<Search className="w-4 h-4"/>}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold truncate">{r.title}</span><span className="block text-[10px] text-[#7b827d] mt-1">{r.meta}</span></span></button>):<div className="p-8 text-center text-xs text-[#858c87]">{ar?'لا نتائج':'No results'}</div>}</div></div></div>
}
