import { chromium } from 'playwright';
const BASE='http://localhost:4173';
const OUT='/tmp/claude-0/-home-user-Mizan/7e757f93-6fe8-50f9-8a39-09c4e17ceff0/scratchpad/probe';
const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM});
const p=await b.newPage({viewport:{width:1440,height:1000}});
await p.goto(BASE,{waitUntil:'networkidle'});
const e=p.locator('button[aria-label="استعراض النظام ببيانات تجريبية"]').first();
await e.waitFor({state:'visible',timeout:20000}); await e.click(); await p.waitForTimeout(3500);
await p.locator('button:visible',{hasText:'النطاق والأسئلة'}).first().click(); await p.waitForTimeout(1200);
// the script clicks a ROLE=TAB, not a button
const tab=p.locator('[role="tab"]:visible',{hasText:'النماذج والعدالة'});
console.log('role=tab count:', await tab.count());
await tab.first().click().catch(e=>console.log('tab click failed:', String(e).slice(0,80)));
await p.waitForTimeout(2500);
const txt=(await p.locator('body').innerText()).replace(/\s+/g,' ');
console.log('models body (900):', txt.slice(0, 900));
console.log('ولّد دفعة count:', await p.locator('button:visible',{hasText:'ولّد دفعة'}).count());
console.log('all buttons:', JSON.stringify((await p.locator('button:visible').allInnerTexts()).map(t=>t.replace(/\s+/g,' ').trim()).filter(Boolean)));
await p.screenshot({path:`${OUT}/f-models-tab.png`,fullPage:true});
await b.close();
