import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { IdentityGovernanceRepository, type GovernanceRole } from '../server/identity-governance';
import { SEED_QUORUM_ACTIONS, SEED_USERS } from '../src/lib/seed-data';
const source=(p:string)=>fs.readFileSync(p,'utf8');
const orgAdmin=(uid='org-admin')=>({uid,email:`${uid}@example.org`,role:'org_admin' as const,organizationId:'org-1',competitionId:'comp-1'});
const retiredRole='scientific_admin' as unknown as GovernanceRole; // intentional legacy input boundary
function withRepo(fn:(repo:IdentityGovernanceRepository,dir:string)=>void){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mizan-final-'));try{fn(new IdentityGovernanceRepository(dir),dir)}finally{fs.rmSync(dir,{recursive:true,force:true})}}

test('retired authority is absent from active role and UI surfaces',()=>{for(const p of ['src/types/index.ts','src/lib/permissions.ts','src/lib/useMizanAuth.ts','server.ts','src/components/admin/IdentityGovernance.tsx','src/components/admin/CompetitionOverview.tsx','src/components/design-system/RoleSwitcher.tsx','src/lib/ui-language.ts','src/lib/seed-data.ts'])assert.doesNotMatch(source(p),/scientific_admin/,p);assert.doesNotMatch(source('src/types/index.ts'),/reviewerRole:[^;]*scientific_admin/)});

test('legacy invitation grant and session are revoked in place without remapping',()=>withRepo((repo,dir)=>{const file=path.join(dir,'identity-governance.json');const now=new Date();const later=new Date(now.getTime()+3600_000).toISOString();fs.writeFileSync(file,JSON.stringify({version:1,invitations:[{id:'legacy-inv',organizationId:'org-1',competitionId:'comp-1',email:'legacy@example.org',displayName:'Legacy',requestedRole:'scientific_admin',reason:'pre-upgrade row',status:'READY',createdAt:now.toISOString(),createdBy:'old',expiresAt:later,activationTokenHash:'must-disappear'}],accounts:[{id:'legacy-acct',uid:'legacy-uid',organizationId:'org-1',email:'legacy@example.org',displayName:'Legacy',status:'ACTIVE',createdAt:now.toISOString(),activatedFromInvitationId:'legacy-inv'}],grants:[{id:'legacy-grant',accountId:'legacy-acct',organizationId:'org-1',competitionId:'comp-1',role:'scientific_admin',status:'ACTIVE',createdAt:now.toISOString(),createdBy:'old'}],sessions:[{id:'legacy-session',uid:'legacy-uid',accountId:'legacy-acct',organizationId:'org-1',competitionId:'comp-1',role:'scientific_admin',deviceId:'old-device',authenticationAssurance:'MFA',openedAt:now.toISOString(),lastSeenAt:now.toISOString(),expiresAt:later,status:'ACTIVE'}]},null,2));assert.equal(repo.identityForUid('legacy-uid','comp-1'),null);const migrated=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(migrated.invitations[0].status,'REVOKED');assert.equal('activationTokenHash' in migrated.invitations[0],false);assert.equal(migrated.grants[0].status,'REVOKED');assert.equal(migrated.grants[0].role,'scientific_admin');assert.equal(migrated.sessions[0].status,'REVOKED');assert.match(migrated.sessions[0].revocationReason,/Retired identity authority/);assert.equal(migrated.sessions[0].role,'scientific_admin')}));

test('retired role cannot be newly invited and activation QR is one-time',()=>withRepo(repo=>{assert.throws(()=>repo.createInvitation(orgAdmin(),{email:'legacy@example.org',displayName:'Legacy',requestedRole:retiredRole,competitionId:'comp-1',reason:'Legacy role attempt'}),/ROLE_RETIRED/);const inv=repo.createInvitation(orgAdmin(),{email:'judge@example.org',displayName:'Judge',requestedRole:'judge',competitionId:'comp-1',reason:'Official judging assignment'});repo.activate({uid:'judge-uid',email:'judge@example.org'},inv.activationToken!);assert.throws(()=>repo.activate({uid:'judge-uid',email:'judge@example.org'},inv.activationToken!),/ACTIVATION_TOKEN_INVALID/)}));

test('ceremony quorum contains only actual seeded competition authorities',()=>{const ids=new Set(SEED_USERS.map(u=>u.id));const q=SEED_QUORUM_ACTIONS.find(x=>x.action==='ceremony_reveal');assert.ok(q);assert.deepEqual(q!.requiredRoleGroups,[['head_judge'],['comp_admin'],['org_admin']]);assert.deepEqual(q!.authorizedRoles,['head_judge','comp_admin','org_admin']);assert.equal(q!.distinctActorsRequired,true);for(const a of q!.approvals)assert.equal(ids.has(a.actorId),true,`dangling actor ${a.actorId}`);assert.doesNotMatch(source('src/lib/seed-data.ts'),/usr-scientific-1/)});

test('role header shows the full desktop name and appeals have no compatibility branch',()=>{const roles=source('src/components/design-system/RoleSwitcher.tsx');const appeals=source('src/components/admin/CompetitionOverview.tsx');assert.doesNotMatch(roles,/max-w-32 truncate/);assert.match(roles,/whitespace-nowrap/);assert.match(appeals,/value=\{policy\.appeals\.reviewerRole\}/);assert.doesNotMatch(appeals,/reviewerRole===/)});

test('scientific governance functionality remains under actual authorities',()=>{const store=source('src/lib/store.ts');for(const name of ['registerQuranSourceManifest','reviewQuranSource','certifyQuranSource','runQuranSourceCrossCheck','registerVariantLocus','registerQuranReferenceAudio','registerAiValidation','registerScientificDataset','registerBenchmarkRun','openScientificAdjudication'])assert.match(store,new RegExp(name),name);assert.match(store,/\['comp_admin','org_admin'\]\.includes\(globalState\.currentUser\.role\)/);assert.match(store,/\[\['head_judge'\],\['comp_admin'\],\['org_admin'\]\]/)});

test('organization admin lands on competitions before organization details and access',()=>{const portals=source('src/components/admin/RolePortals.tsx');const start=portals.indexOf('export const OrganizationHome');const end=portals.indexOf('export const DelegationPortal',start);const home=portals.slice(start,end);assert.match(home,/useState<'competitions'\|'organization'>\('competitions'\)/);assert.match(home,/page==='competitions'/);assert.match(home,/page==='organization'/);assert.ok(home.indexOf("page==='competitions'")<home.indexOf('<TenantBrandStudio'));assert.match(home,/<IdentityGovernance competitionId=\{competition\.id\}\/>/)});

test('live support is prominent for every role including broadcast',()=>{const header=source('src/components/layout/Header.tsx');const app=source('src/App.tsx');assert.match(header,/export const LiveSupportControl/);assert.match(header,/الدعم المباشر/);assert.match(header,/requestSupportSession/);assert.match(header,/<LiveSupportControl\/>/);assert.match(app,/isBroadcast&&<LiveSupportControl floating\/>/)});
