import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { passageTransitionPlan, TRANSITION_PHRASES_AR } from '../src/lib/judging-integrity';
import { COMPETITION_TEMPLATES } from '../src/lib/competition-config';
const text=(p:string)=>fs.readFileSync(p,'utf8');

test('stop cues are built-in selectable phrases with deterministic rotation',()=>{const a=passageTransitionPlan({isLastQuestion:false,ar:true,cue:{enabled:true,phraseArabic:'',phraseEnglish:'',selectedPhraseIndexes:[2,5],autoAdvanceDelayMs:800},variantSeed:0});const b=passageTransitionPlan({isLastQuestion:false,ar:true,cue:{enabled:true,phraseArabic:'',phraseEnglish:'',selectedPhraseIndexes:[2,5],autoAdvanceDelayMs:800},variantSeed:1});assert.equal(a.phrase,TRANSITION_PHRASES_AR[2]);assert.equal(a.variantIndex,2);assert.equal(b.phrase,TRANSITION_PHRASES_AR[5]);assert.equal(b.variantIndex,5);assert.equal(a.audioUrl,'')});
test('competition DNA has no manual cue upload and uses dynamic criteria',()=>{const src=text('src/components/admin/CompetitionOverview.tsx');assert.match(src,/selectedPhraseIndexes/);assert.match(src,/TRANSITION_PHRASES_AR/);assert.doesNotMatch(src,/Professional recorded cue|تسجيل بشري احترافي/);assert.match(src,/r\.criteria\.map\(c=><option/);assert.match(src,/criterion-\$\{Date\.now\(\)\}/);assert.match(src,/Remove criterion|حذف المعيار/)});
test('judge runtime does not play arbitrary manual cue URLs',()=>{const src=text('src/components/judge/JudgeOS.tsx');assert.doesNotMatch(src,/if\(transition\.audioUrl\)/);assert.match(src,/\/audio\/cues\/cue-\$\{transition\.variantIndex\}\.wav/)});
test('enterprise UI is self-service, avoids developer-only consoles, and uses clear admin-tool language',()=>{const src=text('src/components/admin/EnterpriseWorkspace.tsx');assert.match(src,/اربط خدمات الجهة من هنا/);assert.doesNotMatch(src,/تكاملات الويب|Webhooks/);assert.match(src,/النسخ الاحتياطي والاستعادة/);assert.match(src,/إنشاء مسابقة جديدة بنفس الإعدادات/);assert.match(src,/إنهاء المسابقة وإغلاقها/);assert.doesNotMatch(src,/سلامة بيانات المسابقة|إصدار جديد من المسابقة/)});
test('new edition resets operational state instead of cloning live residue',()=>{const src=text('src/lib/store.ts');assert.match(src,/COMPETITION_NEW_EDITION_CREATED/);assert.match(src,/base\.edition=''/);assert.match(src,/base\.startDate=''/);assert.match(src,/ruleSetFrozen:false/);assert.doesNotMatch(src,/— نسخة|— Copy/)});
test('certificate surfaces use human verification language, not fake hashes',()=>{const brand=text('src/components/admin/TenantBrandStudio.tsx');const dna=text('src/components/admin/CompetitionOverview.tsx');assert.doesNotMatch(brand,/VERIFIED-HASH-SEAL/);assert.match(brand,/قابلة للتحقق/);assert.match(dna,/قابلة للتحقق رقميًا/);assert.match(dna,/RealQRCode/)});
test('no starter competition templates are injected',()=>{assert.deepEqual(COMPETITION_TEMPLATES,[])});
test('super admin has one canonical tenant-management surface',()=>{const src=text('src/components/admin/RolePortals.tsx');assert.match(src,/<TenantConsole\/>/);assert.doesNotMatch(src,/setProvisioning|orgName/)});
