import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { passageTransitionPlan, TRANSITION_PHRASES_AR } from '../src/lib/judging-integrity';
import { COMPETITION_TEMPLATES } from '../src/lib/competition-config';
const text=(p:string)=>fs.readFileSync(p,'utf8');

test('stop cue is fixed to «حسبك» for everyone, no rotation',()=>{const a=passageTransitionPlan({isLastQuestion:false,ar:true,cue:{enabled:true,autoAdvanceDelayMs:800}});assert.equal(a.phrase,'حسبك');assert.deepEqual(TRANSITION_PHRASES_AR,['حسبك']);assert.equal(a.delayMs,800);assert.equal(passageTransitionPlan({isLastQuestion:false,ar:true,cue:{enabled:false}}).enabled,false)});
test('competition DNA has no manual cue upload and uses dynamic criteria',()=>{const src=text('src/components/admin/CompetitionOverview.tsx');/* قائمة عبارات الإنهاء حُذفت (قرار المالك ٢٦‑٩): العبارة ثابتة «حسبك» ويبقى مفتاح الصوت وحده. */assert.doesNotMatch(src,/selectedPhraseIndexes/);assert.doesNotMatch(src,/TRANSITION_PHRASES_AR/);assert.match(src,/FIXED_END_PHRASE/);assert.match(src,/التنبيه الصوتي/);assert.doesNotMatch(src,/Professional recorded cue|تسجيل بشري احترافي/);assert.match(src,/r\.criteria\.map\(c=><option/);assert.match(src,/criterion-\$\{Date\.now\(\)\}/);assert.match(src,/Remove criterion|حذف المعيار/)});
test('judge runtime does not play arbitrary manual cue URLs',()=>{const src=text('src/components/judge/JudgeOS.tsx');assert.doesNotMatch(src,/if\(transition\.audioUrl\)/);assert.doesNotMatch(src,/variantIndex|variantSeed|\/audio\/cues\/cue-/);assert.match(src,/cue-audio\?text=\$\{encodeURIComponent\(transition\.phrase\)\}/)});
test('enterprise UI is self-service and has no webhook console',()=>{const src=text('src/components/admin/EnterpriseWorkspace.tsx');assert.match(src,/اربط خدمات الجهة من هنا/);assert.doesNotMatch(src,/تكاملات الويب|Webhooks/);assert.match(src,/سلامة بيانات المسابقة/);assert.match(src,/إصدار جديد من المسابقة/)});
test('new edition resets operational state instead of cloning live residue',()=>{const src=text('src/lib/store.ts');assert.match(src,/COMPETITION_NEW_EDITION_CREATED/);assert.match(src,/base\.edition=''/);assert.match(src,/base\.startDate=''/);assert.match(src,/ruleSetFrozen:false/);assert.doesNotMatch(src,/— نسخة|— Copy/)});
test('certificate surfaces use human verification language, not fake hashes',()=>{const brand=text('src/components/admin/TenantBrandStudio.tsx');const dna=text('src/components/admin/CompetitionOverview.tsx');assert.doesNotMatch(brand,/VERIFIED-HASH-SEAL/);assert.match(brand,/قابلة للتحقق/);assert.match(dna,/قابلة للتحقق رقميًا/);assert.match(dna,/RealQRCode/)});
test('no starter competition templates are injected',()=>{assert.deepEqual(COMPETITION_TEMPLATES,[])});
test('super admin has one canonical commercial organization surface',()=>{const src=text('src/components/admin/RolePortals.tsx');assert.match(src,/<SaaSCommercialConsole\/>/);assert.doesNotMatch(src,/<TenantConsole\/>|Advanced domain routing|إعدادات النطاقات التقنية المتقدمة/)});
test('launch placeholders can never republish as real public competition data',()=>{const store=text('src/lib/store.ts'),rules=text('firestore.rules');assert.match(store,/launchPlaceholderActive/);assert.match(rules,/competitionId != 'comp-pending-setup'/);assert.match(rules,/organizationId != 'org-pending-setup'/)});
test('judge buttons show the configured name, criterion and value, in order, enabled only',async()=>{const {getEnabledJudgeActions}=await import('../src/lib/competition-config');const criteria=[{id:'crit-mem',name:'Memorization',nameArabic:'الحفظ',maxScore:80,assignedJudgeType:'memorization'},{id:'crit-perf',name:'Performance',nameArabic:'الأداء',maxScore:20,assignedJudgeType:'performance'}];const mk=(id:string,labelArabic:string,criterion:string,penalty:number,enabled=true)=>({id,eventType:id,labelArabic,labelEnglish:id,shortArabic:'قديم',shortEnglish:'old',criterion,penalty,enabled});const actions=[mk('a','تنبيه','crit-mem',.5),mk('b','فتح','crit-mem',1),mk('c','تردد','crit-mem',.25),mk('x','معطّل','crit-mem',1,false),mk('d','الأحكام الأصلية','crit-mem',.5),mk('e','الأحكام الفرعية','crit-mem',.25),mk('f','الأداء','crit-perf',1)];const out=getEnabledJudgeActions({ruleSet:{criteria},policy:{judging:{actions}}} as any);assert.deepEqual(out.map(a=>[a.shortArabic,a.criterion,a.penalty]),[['تنبيه','crit-mem',.5],['فتح','crit-mem',1],['تردد','crit-mem',.25],['الأحكام الأصلية','crit-mem',.5],['الأحكام الفرعية','crit-mem',.25],['الأداء','crit-perf',1]])});
test('passage length in page quarters is measured by mushaf lines, not a fixed ayah window',async()=>{const {ayahCountForPageQuarters}=await import('../server/kfgqpc-fairdraw-generative');const rows=Array.from({length:30},(_,i)=>({sora:2,aya_no:i+1,page:2+Math.floor(i/5),line_start:(i%5)*3+1,line_end:(i%5)*3+3,jozz:1}));assert.equal(ayahCountForPageQuarters(rows,2,1,4),5);assert.equal(ayahCountForPageQuarters(rows,2,1,2),3);assert.equal(ayahCountForPageQuarters(rows,2,1,3),4);assert.equal(ayahCountForPageQuarters(rows,2,1,1),1);assert.equal(ayahCountForPageQuarters(rows,2,1,5),6);assert.equal(ayahCountForPageQuarters(rows.map(r=>({...r,line_start:undefined})),2,1,3),null);const {pageQuarterLabel,categoryPageQuarterUnits}=await import('../src/lib/scope-engine');assert.equal(pageQuarterLabel(3,true),'ثلاثة أرباع وجه');assert.equal(pageQuarterLabel(5,true),'وجه وربع');assert.equal(categoryPageQuarterUnits({passageMode:'page_quarters',pageQuarterUnits:3} as any),3)});
