import React, { useMemo, useState } from 'react';
import { Activity, BadgeCheck, Clock3, Fingerprint, Gauge, QrCode, RadioTower, ShieldCheck, UsersRound, WandSparkles } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Badge } from '../design-system/Badge';
import { Button } from '../design-system/Button';
import { Pictogram } from '../design-system/Pictogram';
import { RealQRCode, makeMizanPassPayload } from '../design-system/RealQRCode';

type Tool='mission'|'flight'|'twin'|'chaos'|'envelope'|'access'|'elasticity'|'pass';
const tools:[Tool,any,string,string][]=[
 ['mission',Gauge,'التحكم','Mission'],['flight',Clock3,'المسجل','Recorder'],['twin',Activity,'التوأم','Twin'],['chaos',WandSparkles,'الاختبار','Chaos'],
 ['envelope',Fingerprint,'الظرف','Envelope'],['access',BadgeCheck,'الوصول','Access'],['elasticity',UsersRound,'اللجان','Elasticity'],['pass',QrCode,'الرحلة','One Pass']
];

export const BeyondLab:React.FC=()=>{
 const s=useAppStore();const ar=s.language==='ar';const [tool,setTool]=useState<Tool>('mission');
 return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{tools.map(([id,Icon,a,e])=><button key={id} onClick={()=>setTool(id)} className={`shrink-0 min-h-11 px-3 rounded-xl border inline-flex items-center gap-2 text-xs font-black ${tool===id?'bg-[#202924] text-white border-[#202924]':'bg-white border-[#dedcd5] text-[#606862]'}`}><Icon className="w-4 h-4"/>{ar?a:e}</button>)}</div>
 {tool==='mission'&&<Mission s={s} ar={ar}/>} {tool==='flight'&&<Flight s={s} ar={ar}/>} {tool==='twin'&&<Twin s={s} ar={ar}/>} {tool==='chaos'&&<Chaos s={s} ar={ar}/>} {tool==='envelope'&&<Envelope s={s} ar={ar}/>} {tool==='access'&&<Access s={s} ar={ar}/>} {tool==='elasticity'&&<Elasticity s={s} ar={ar}/>} {tool==='pass'&&<OnePass s={s} ar={ar}/>}</div>
}

const Mission=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const activeIncidents=s.incidents.filter(i=>i.status!=='resolved').length,failed=s.notifications.filter(n=>n.status==='failed').length,offline=s.devices.filter(d=>d.status==='offline'||d.status==='degraded').length,pendingReview=s.reviewCases.filter(r=>r.status==='pending').length;const exceptions=activeIncidents+failed+offline+pendingReview;return <section className="mizan-surface p-6 sm:p-8"><div className="flex items-center gap-4"><Pictogram icon={ShieldCheck} size="lg" tone={exceptions?'amber':'emerald'}/><div><div className="mizan-kicker">{ar?'مركز قيادة ميزان':'MIZAN MISSION CONTROL'}</div><h2 className="text-2xl sm:text-3xl font-black mt-1">{exceptions?(ar?`${exceptions} حالات تحتاج قرارًا`:`${exceptions} exceptions need a decision`):(ar?'كل شيء يعمل طبيعيًا':'Everything is operating normally')}</h2></div></div>{!exceptions&&<p className="text-sm text-[#717873] mt-5">{ar?'لا تدخل مطلوب.':'No intervention required.'}</p>}{exceptions>0&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-5"><Mini n={activeIncidents} t={ar?'حوادث':'Incidents'}/><Mini n={pendingReview} t={ar?'مراجعة':'Review'}/><Mini n={failed} t={ar?'إشعارات':'Notify'}/><Mini n={offline} t={ar?'أجهزة':'Devices'}/></div>}</section>};

const Flight=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const rows=s.flightRecorderEntries.slice(-12).reverse();return <section className="mizan-surface p-5 sm:p-6"><Head icon={Clock3} title={ar?'مسجل الرحلة':'Competition Flight Recorder'} sub={ar?'خط زمني قابل لإعادة البناء من الأحداث الفعلية.':'A reconstructable timeline from actual recorded events.'}/><Button className="mt-4" onClick={()=>void s.buildFlightRecorder()}>{ar?'إعادة بناء':'Rebuild'}</Button><div className="mt-5 divide-y divide-[#e4e2db]">{rows.map(x=><div key={x.id} className="py-3 grid grid-cols-[82px_1fr_auto] gap-3 items-center"><span className="text-[10px] font-mono text-[#7b827d]">{new Date(x.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><span className="text-xs font-bold">{ar?x.summaryArabic:x.summaryEnglish}</span><Badge variant="neutral">{x.stream}</Badge></div>)}{!rows.length&&<Empty ar={ar}/>}</div></section>};

const Twin=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [panels,setPanels]=useState(Math.max(1,s.committees.length));const [arrivals,setArrivals]=useState(30);const sim=useMemo(()=>s.runSimulation(panels,arrivals),[panels,arrivals,s.participants.length,s.committees.length]);return <section className="mizan-surface p-5 sm:p-6"><Head icon={Activity} title={ar?'التوأم التشغيلي للقاعات':'Venue Digital Twin'} sub={ar?'اختبر القاعات والتدفق قبل يوم المسابقة. هذه المحاكاة غير رسمية ولا تمس النتائج.':'Test venue capacity before event day. NON-OFFICIAL.'}/><div className="grid sm:grid-cols-2 gap-3 mt-5"><Field label={ar?'اللجان':'Committees'} value={panels} set={setPanels}/><Field label={ar?'وصول/ساعة':'Arrivals / hour'} value={arrivals} set={setArrivals}/></div><div className="grid grid-cols-3 gap-2 mt-4"><Mini n={sim.averageWaitMinutes} t={ar?'د انتظار':'min wait'}/><Mini n={sim.maxWaitMinutes} t={ar?'د أقصى':'max wait'}/><MiniText n={sim.projectedFinishTime} t={ar?'النهاية':'finish'}/></div><p className="text-xs text-[#69716c] mt-4">{ar?sim.optimizationAdviceArabic:sim.optimizationAdviceEnglish}</p></section>};

const Chaos=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const d=s.chaosDrills[0];return <section className="mizan-surface p-5 sm:p-6"><Head icon={WandSparkles} title="MIZAN Chaos Drill" sub={ar?'فشل اصطناعي لا يلمس النتائج الرسمية.':'Synthetic failure rehearsal; official outcomes are untouched.'}/><Button className="mt-4" onClick={()=>s.runChaosDrill()}>{ar?'شغّل التدريب':'Run drill'}</Button>{d&&<><div className="mt-5 flex items-end gap-3"><div className="text-5xl font-black">{d.readinessScore}%</div><Badge variant="neutral">NON-OFFICIAL</Badge></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-4">{d.scenarios.map(x=><div key={x.id} className="mizan-surface-soft p-3 flex items-center gap-3"><span className={`w-2.5 h-2.5 rounded-full ${x.passed?'bg-[#2F6555]':'bg-[#A34D43]'}`}/><div className="text-xs font-bold">{ar?x.titleArabic:x.titleEnglish}</div></div>)}</div></>}</section>};

const Envelope=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [pid,setPid]=useState(s.participants[0]?.id||'');const [verified,setVerified]=useState<boolean|null>(null);const item=s.integrityEnvelopes.find(x=>x.participantId===pid);return <section className="mizan-surface p-5 sm:p-6"><Head icon={Fingerprint} title={ar?'غلاف النزاهة':'Integrity Envelope'} sub={ar?'يربط الجلسة والتقييم والختم والأثر في بصمة واحدة.':'Binds session, submissions, seal and audit into one digest.'}/><select className="mizan-input mt-5" value={pid} onChange={e=>{setPid(e.target.value);setVerified(null)}}>{s.participants.map(p=><option key={p.id} value={p.id}>{p.code} · {ar?p.fullNameArabic:p.fullName}</option>)}</select><div className="flex flex-wrap gap-2 mt-3"><Button onClick={()=>void s.createIntegrityEnvelope(pid)}>{ar?'إغلاق الظرف':'Seal envelope'}</Button>{item&&<Button variant="outline" onClick={async()=>setVerified((await s.verifyIntegrityEnvelope(item)).valid)}>{ar?'تحقق':'Verify'}</Button>}{verified!==null&&<Badge variant={verified?'emerald':'rose'}>{verified?'VERIFIED':'FAILED'}</Badge>}</div>{item&&<div className="mizan-proof-code mt-4 rounded-xl bg-[#202924] text-white/70 p-4">{item.envelopeHash}</div>}</section>};

const Access=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const profile=s.accessibilityProfiles.find(x=>x.userId===s.currentUser.id)||{textScale:'normal' as const,touchScale:'normal' as const,contrast:'system' as const,motion:'system' as const,audioCues:false};return <section className="mizan-surface p-5 sm:p-6"><Head icon={BadgeCheck} title={ar?'إتاحة هادئة':'Invisible Accessibility'} sub={ar?'تكيّف هادئ بلا تصنيف للمستخدم.':'Quiet adaptation without labeling the person.'}/><div className="grid sm:grid-cols-2 gap-2 mt-5"><Choice active={profile.textScale==='large'} onClick={()=>s.updateAccessibilityProfile({textScale:profile.textScale==='large'?'normal':'large'})} title={ar?'نص أكبر':'Larger text'}/><Choice active={profile.touchScale==='xl'} onClick={()=>s.updateAccessibilityProfile({touchScale:profile.touchScale==='xl'?'normal':'xl'})} title={ar?'لمس أكبر':'Larger touch'}/><Choice active={profile.contrast==='high'} onClick={()=>s.updateAccessibilityProfile({contrast:profile.contrast==='high'?'system':'high'})} title={ar?'تباين أعلى':'High contrast'}/><Choice active={profile.motion==='reduced'} onClick={()=>s.updateAccessibilityProfile({motion:profile.motion==='reduced'?'system':'reduced'})} title={ar?'حركة أقل':'Reduced motion'}/></div></section>};

const Elasticity=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const r=s.elasticityRecommendations[0];return <section className="mizan-surface p-5 sm:p-6"><Head icon={UsersRound} title={ar?'مرونة توزيع اللجان':'Committee Elasticity'} sub={ar?'اقتراح فقط؛ لا نقل صامتًا.':'Recommendation only; never a silent move.'}/><Button className="mt-4" onClick={()=>s.recommendCommitteeElasticity()}>{ar?'حلل الحمل':'Analyze load'}</Button>{r&&<div className="mt-4 mizan-surface-soft p-4"><div className="text-sm font-black">{ar?r.reasonArabic:r.reasonEnglish}</div><div className="text-[10px] text-[#777e79] mt-2">{r.constraintsChecked.join(' · ')}</div>{r.status==='proposed'&&<div className="flex gap-2 mt-4"><Button onClick={()=>s.decideCommitteeElasticity(r.id,true)}>{ar?'اعتماد':'Approve'}</Button><Button variant="outline" onClick={()=>s.decideCommitteeElasticity(r.id,false)}>{ar?'رفض':'Dismiss'}</Button></div>}{r.status!=='proposed'&&<Badge variant={r.status==='approved'?'emerald':'neutral'}>{r.status.toUpperCase()}</Badge>}</div>}</section>};

const OnePass=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [pid,setPid]=useState(s.participants[0]?.id||'');const p=s.participants.find(x=>x.id===pid);const pass=s.journeyPasses.find(x=>x.participantId===pid&&x.status==='active');return <section className="mizan-surface p-5 sm:p-6"><Head icon={QrCode} title={ar?'رمز واحد للرحلة كاملة':'One QR. Whole Journey.'} sub={ar?'هوية تشغيل واحدة من البوابة حتى الشهادة.':'One operational identity from gate to certificate.'}/><div className="grid md:grid-cols-[1fr_auto] gap-5 items-center mt-5"><div><select className="mizan-input" value={pid} onChange={e=>setPid(e.target.value)}>{s.participants.map(x=><option key={x.id} value={x.id}>{x.code} · {ar?x.fullNameArabic:x.fullName}</option>)}</select><div className="flex gap-2 mt-3"><Button onClick={()=>void s.issueJourneyPass(pid)}>{pass?(ar?'نشط':'Active'):(ar?'إصدار':'Issue')}</Button>{pass&&<Button variant="outline" onClick={()=>s.revokeJourneyPass(pass.id)}>{ar?'إلغاء':'Revoke'}</Button>}</div>{pass&&<div className="mizan-proof-code mt-3 text-[#777e79]">{pass.checksum.slice(0,24)}…</div>}</div>{p&&<div className="w-40 h-40 rounded-2xl border border-[#deddd6] bg-white grid place-items-center overflow-hidden"><RealQRCode value={pass?.payload||makeMizanPassPayload(p.code)} size={148}/></div>}</div></section>};

const Head=({icon,title,sub}:{icon:any;title:string;sub:string})=>{const Icon=icon;return <div className="flex items-start gap-3"><Pictogram icon={Icon}/><div><h2 className="text-lg font-black">{title}</h2><p className="text-xs text-[#777e79] mt-1 max-w-2xl">{sub}</p></div></div>};
const Mini=({n,t}:{n:number;t:string})=><div className="mizan-surface-soft p-3"><div className="text-2xl font-black">{n}</div><div className="text-[10px] text-[#777e79]">{t}</div></div>;
const MiniText=({n,t}:{n:string;t:string})=><div className="mizan-surface-soft p-3"><div className="text-xl font-black">{n}</div><div className="text-[10px] text-[#777e79]">{t}</div></div>;
const Field=({label,value,set}:{label:string;value:number;set:(n:number)=>void})=><label className="text-[10px] font-black text-[#777e79]">{label}<input className="mizan-input mt-1" type="number" min="1" value={value} onChange={e=>set(Math.max(1,Number(e.target.value)||1))}/></label>;
const Choice=({active,onClick,title}:{active:boolean;onClick:()=>void;title:string})=><button onClick={onClick} className={`min-h-14 rounded-xl border px-4 text-start text-xs font-black flex items-center justify-between ${active?'bg-[#E7EEE9] border-[#9db5ab] text-[#214C40]':'bg-white border-[#dedcd5]'}`}><span>{title}</span><span className={`w-3 h-3 rounded-full ${active?'bg-[#2F6555]':'bg-[#d2d0c9]'}`}/></button>;
const Empty=({ar}:{ar:boolean})=><div className="py-8 text-center text-xs text-[#858c87]">{ar?'لا يوجد سجل بعد':'No records yet'}</div>;
