import React, {useMemo, useState} from 'react';
import { Check, HardDrive, Printer, QrCode, Server, ScanLine, Sparkles, RadioTower, WalletCards, Settings2, Wifi, FileCheck2 } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { buildDeploymentPlan, composeVenue, DeploymentProfile, VenueInventory } from '../../lib/deployment-planner';
import { uiToken } from '../../lib/ui-language';

const iconFor=(id:string)=>({gate:HardDrive,scanner:QrCode,ticket:WalletCards,judge:ScanLine,display:RadioTower,edge:Server,printer:Printer}[id]||HardDrive);

export const DeploymentStudio:React.FC=()=>{
  const s=useAppStore(); const ar=s.language==='ar'; const p=s.competition.policy!; const profile=p.operations.deploymentProfile;
  const plan=useMemo(()=>buildDeploymentPlan(s.competition,profile),[s.competition,profile]);
  const [inventory,setInventory]=useState<VenueInventory>({laptops:6,desktops:0,tablets:2,tvs:3,printers:1,usbScanners:0,edgeMiniPcs:0,wifi:true,participantByod:true});
  const composition=useMemo(()=>composeVenue(s.competition,inventory),[s.competition,inventory]);
  const choose=(v:DeploymentProfile)=>s.updateCompetitionPolicy(pol=>({...pol,operations:{...pol.operations,deploymentProfile:v,hardwareStrategy:v==='lean'?'reuse_existing':v==='balanced'?'mixed':'dedicated',gateStationMode:v==='lean'?'computer_only':'touch_kiosk',ticketMode:v==='premium'?'print_optional':'screen_number'}}));
  const profiles:[DeploymentProfile,string,string][]=[['lean',ar?'اقتصادي':'Lean',ar?'استخدم الموجود أولًا':'Reuse first'],['balanced',ar?'متوازن':'Balanced',ar?'راحة أعلى بلا هدر':'Comfort without waste'],['premium',ar?'موسّع':'Premium',ar?'احتياط أكبر':'Higher redundancy']];
  const setN=(k:keyof VenueInventory,v:number|boolean)=>setInventory(x=>({...x,[k]:v}));
  return <div className="space-y-4">
    <div className="mizan-surface p-5 sm:p-6">
      <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="mizan-kicker">{ar?'مخطط موقع المسابقة':'VENUE COMPOSER'}</div><h2 className="text-xl sm:text-2xl font-black mt-1">{ar?'شغّل ميزان بما لديك':'Run MIZAN with what you own'}</h2><p className="text-xs text-[#626965] mt-2">{ar?'أدخل الموجود. ميزان يوزعه على الأدوار ويكشف المطلوب فقط.':'Enter available resources. MIZAN assigns roles and exposes only real gaps.'}</p></div><div className={`rounded-2xl px-4 py-3 ${composition.missingRequired?'bg-[#F4E6E3] text-[#89453d]':'bg-[#E7EEE9] text-[#214C40]'}`}><div className="text-[10px] font-black opacity-60">{ar?'الخلاصة':'VENUE FIT'}</div><div className="text-sm font-black mt-1">{ar?composition.summaryAr:composition.summaryEn}</div></div></div>
      <div className="grid md:grid-cols-3 gap-2 mt-5">{profiles.map(([id,title,sub])=><button key={id} onClick={()=>choose(id)} className={`text-start rounded-2xl border p-3.5 ${profile===id?'border-[#214C40] bg-[#eef3ef]':'border-[#dedcd5]'}`}><div className="flex items-center justify-between"><div className="font-black text-sm">{title}</div>{profile===id&&<Check className="w-4 h-4 text-[#214C40]"/>}</div><div className="text-[11px] text-[#616763] mt-1">{sub}</div></button>)}</div>
    </div>

    <div className="grid xl:grid-cols-[.72fr_1.28fr] gap-4">
      <section className="mizan-surface p-5"><div className="flex items-center gap-2"><Settings2 className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'الموجود لديك':'Available now'}</h3></div><div className="grid grid-cols-2 gap-2 mt-4"><Inventory icon={HardDrive} label={ar?'لابتوب':'Laptops'} value={inventory.laptops} onChange={v=>setN('laptops',v)}/><Inventory icon={HardDrive} label={ar?'كمبيوتر':'Desktops'} value={inventory.desktops} onChange={v=>setN('desktops',v)}/><Inventory icon={ScanLine} label={ar?'تابلت':'Tablets'} value={inventory.tablets} onChange={v=>setN('tablets',v)}/><Inventory icon={RadioTower} label={ar?'شاشات العرض':'TVs'} value={inventory.tvs} onChange={v=>setN('tvs',v)}/><Inventory icon={Printer} label={ar?'طابعات':'Printers'} value={inventory.printers} onChange={v=>setN('printers',v)}/><Inventory icon={QrCode} label={ar?'قارئ رمز الاستجابة السريعة':'QR scanners'} value={inventory.usbScanners} onChange={v=>setN('usbScanners',v)}/></div><button onClick={()=>setN('wifi',!inventory.wifi)} className="mt-3 w-full rounded-xl bg-[#f3f1eb] p-3 flex items-center justify-between text-xs font-bold"><span className="flex items-center gap-2"><Wifi className="w-4 h-4"/>{ar?'شبكة لاسلكية متوفرة':'Wi‑Fi available'}</span><span>{inventory.wifi?'✓':'—'}</span></button><button onClick={()=>setN('participantByod',!inventory.participantByod)} className="mt-2 w-full rounded-xl bg-[#f3f1eb] p-3 flex items-center justify-between text-xs font-bold"><span>{ar?'السماح باستخدام أجهزة المشاركين الشخصية':'Participant BYOD'}</span><span>{inventory.participantByod?'✓':'—'}</span></button></section>
      <section className="mizan-surface p-5"><div className="flex items-center gap-2"><Sparkles className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'التوزيع الأمثل':'Optimal assignment'}</h3></div><div className="mt-4 divide-y divide-[#e7e5df]">{composition.assignments.map(a=><div key={a.id} className="py-3 flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#f1efe9] grid place-items-center"><HardDrive className="w-4 h-4 text-[#59625d]"/></span><div className="flex-1 min-w-0"><div className="text-sm font-black">{a.role}</div><div className="text-[11px] text-[#656b66] mt-1">{a.source}</div></div><span className={`text-[9px] font-black ${a.status==='REQUIRED'?'text-[#9b4b43]':a.status==='RECOMMENDED'?'text-[#89673a]':'text-[#2F6555]'}`}>{uiToken(a.status,ar)}</span></div>)}</div></section>
    </div>

    <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-4">
      <section className="mizan-surface p-5"><div className="flex items-center gap-2"><RadioTower className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'متطلبات الملف المختار':'Profile requirements'}</h3></div><div className="mt-3 grid sm:grid-cols-2 gap-x-5">{plan.items.map(item=>{const Icon=iconFor(item.id);return <div key={item.id} className="py-3 flex gap-3 items-start border-b border-[#eceae4]"><Icon className="w-4 h-4 mt-.5 text-[#626b66]"/><div className="flex-1"><div className="text-xs font-extrabold">{ar?item.labelAr:item.labelEn}</div><div className="text-[10px] text-[#656b66] mt-1">{ar?item.noteAr:item.noteEn}</div></div><b className="text-lg">{item.quantity}</b></div>})}</div></section>
      <section className="mizan-surface p-5"><div className="flex items-center gap-2"><FileCheck2 className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'خطة الفني':'Technician plan'}</h3></div><ol className="mt-4 space-y-3">{(ar?composition.checklistAr:composition.checklistEn).map((x,i)=><li key={x} className="flex gap-3 text-xs font-semibold"><span className="text-[#69716c] font-black">0{i+1}</span><span>{x}</span></li>)}</ol><button onClick={()=>window.print()} className="mt-5 text-xs font-black text-[#214C40]">{ar?'طباعة الخطة':'Print plan'}</button></section>
    </div>
  </div>
}
const Inventory=({icon:Icon,label,value,onChange}:{icon:React.ComponentType<{className?:string}>;label:string;value:number;onChange:(v:number)=>void})=><label className="rounded-xl border border-[#e2e0d9] p-3"><span className="flex items-center gap-2 text-[10px] font-black text-[#616763]"><Icon className="w-3.5 h-3.5"/>{label}</span><input type="number" min="0" value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)))} className="mt-2 w-full bg-transparent text-2xl font-black outline-none"/></label>;
