import React,{useMemo,useState} from 'react';
import {HardDrive,Printer,QrCode,ScanLine,RadioTower,Settings2,Wifi,FileCheck2} from 'lucide-react';
import {useAppStore} from '../../lib/store';
import {composeVenue,VenueInventory} from '../../lib/deployment-planner';
import {uiToken} from '../../lib/ui-language';

export const DeploymentStudio:React.FC=()=>{
 const s=useAppStore(); const ar=s.language==='ar';
 // المدير يكتب الأجهزة الموجودة فعلًا، وميزان يحسب الفجوة بلا طبقة اختيار إضافية.
 const [inventory,setInventory]=useState<VenueInventory>({laptops:0,desktops:0,tablets:0,tvs:0,printers:0,usbScanners:0,edgeMiniPcs:0,wifi:true});
 const composition=useMemo(()=>composeVenue(s.competition,inventory),[s.competition,inventory]);
 const setN=(k:keyof VenueInventory,v:number|boolean)=>setInventory(x=>({...x,[k]:v}));
 return <div className="space-y-4">
  <div className="mizan-surface p-5 sm:p-6">
   <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="mizan-kicker">{ar?'مخطط موقع المسابقة':'VENUE COMPOSER'}</div><h2 className="text-xl sm:text-2xl font-black mt-1">{ar?'شغّل ميزان بما لديك':'Run MIZAN with what you own'}</h2><p className="text-xs text-[#626965] mt-2 max-w-2xl">{ar?'أدخل أجهزتك كما هي. لا يوجد نمط تجهيز تختاره؛ ميزان يوزّع المتاح ويبيّن الإلزامي والموصى به فقط.':'Enter the hardware you actually have. There is no deployment tier to choose; MIZAN assigns what exists and shows only real requirements and recommendations.'}</p></div><div className={`rounded-2xl px-4 py-3 ${composition.missingRequired?'bg-[#F4E6E3] text-[#89453d]':'bg-[#E7EEE9] text-[#214C40]'}`}><div className="text-[10px] font-black opacity-60">{ar?'الخلاصة':'VENUE FIT'}</div><div className="text-sm font-black mt-1">{ar?composition.summaryAr:composition.summaryEn}</div></div></div>
  </div>
  <div className="grid xl:grid-cols-[.72fr_1.28fr] gap-4">
   <section className="mizan-surface p-5"><div className="flex items-center gap-2"><Settings2 className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'الموجود لديك':'Available now'}</h3></div><div className="grid grid-cols-2 gap-2 mt-4"><Inventory icon={HardDrive} label={ar?'لابتوب':'Laptops'} value={inventory.laptops} onChange={v=>setN('laptops',v)}/><Inventory icon={HardDrive} label={ar?'كمبيوتر':'Desktops'} value={inventory.desktops} onChange={v=>setN('desktops',v)}/><Inventory icon={ScanLine} label={ar?'تابلت':'Tablets'} value={inventory.tablets} onChange={v=>setN('tablets',v)}/><Inventory icon={RadioTower} label={ar?'شاشات العرض':'TVs'} value={inventory.tvs} onChange={v=>setN('tvs',v)}/><Inventory icon={Printer} label={ar?'طابعات':'Printers'} value={inventory.printers} onChange={v=>setN('printers',v)}/><Inventory icon={QrCode} label={ar?'قارئ QR خارجي':'USB QR scanners'} value={inventory.usbScanners} onChange={v=>setN('usbScanners',v)}/><Inventory icon={HardDrive} label={ar?'Mini PC للاستمرارية':'Edge mini PCs'} value={inventory.edgeMiniPcs} onChange={v=>setN('edgeMiniPcs',v)}/></div><button onClick={()=>setN('wifi',!inventory.wifi)} className="mt-3 w-full rounded-xl bg-[#f3f1eb] p-3 flex items-center justify-between text-xs font-bold"><span className="flex items-center gap-2"><Wifi className="w-4 h-4"/>{ar?'شبكة لاسلكية متوفرة':'Wi-Fi available'}</span><span>{inventory.wifi?'✓':'—'}</span></button></section>
   <section className="mizan-surface p-5"><div className="flex items-center gap-2"><RadioTower className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'توزيع ميزان المقترح':'MIZAN assignment'}</h3></div><div className="mt-4 divide-y divide-[#e7e5df]">{composition.assignments.map(a=><div key={a.id} className="py-3 flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#f1efe9] grid place-items-center"><HardDrive className="w-4 h-4 text-[#59625d]"/></span><div className="flex-1 min-w-0"><div className="text-sm font-black">{a.role}</div><div className="text-[11px] text-[#656b66] mt-1 break-words">{a.source}</div></div><span className={`text-[9px] font-black ${a.status==='REQUIRED'?'text-[#9b4b43]':a.status==='RECOMMENDED'?'text-[#89673a]':'text-[#2F6555]'}`}>{uiToken(a.status,ar)}</span></div>)}</div></section>
  </div>
  <section className="mizan-surface p-5"><div className="flex items-center gap-2"><FileCheck2 className="w-4 h-4 text-[#2F6555]"/><h3 className="font-extrabold">{ar?'خطة الفني':'Technician plan'}</h3></div><ol className="mt-4 grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{(ar?composition.checklistAr:composition.checklistEn).map((x,i)=><li key={x} className="rounded-xl bg-[#f7f5ef] p-3 flex gap-3 text-xs font-semibold"><span className="text-[#69716c] font-black">0{i+1}</span><span>{x}</span></li>)}</ol><button onClick={()=>window.print()} className="mt-5 text-xs font-black text-[#214C40]">{ar?'طباعة الخطة':'Print plan'}</button></section>
 </div>;
};
const Inventory=({icon:Icon,label,value,onChange}:{icon:React.ComponentType<{className?:string}>;label:string;value:number;onChange:(v:number)=>void})=><label className="rounded-xl border border-[#e2e0d9] p-3"><span className="flex items-center gap-2 text-[10px] font-black text-[#616763]"><Icon className="w-3.5 h-3.5"/>{label}</span><input type="number" min="0" value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)||0))} className="mt-2 w-full bg-transparent text-2xl font-black outline-none"/></label>;
