import React, {useState} from 'react';
import { HardDrive, Plus, ShieldCheck, Wifi, WifiOff, XCircle, RefreshCcw, ArrowRightLeft } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Button } from '../design-system/Button';
import { Badge } from '../design-system/Badge';
import { DeviceRecord } from '../../types';

const roles:NonNullable<DeviceRecord['role']>[]=['Gate','Kiosk','JudgeOS','Head Judge','Operations','Waiting Display','Committee Display','Exception Host','Ceremony','Broadcast','Edge'];
export const DeviceCenter:React.FC=()=>{
 const s=useAppStore(); const ar=s.language==='ar'; const [adding,setAdding]=useState(false); const [name,setName]=useState('');
 const add=()=>{if(!name.trim())return;s.registerDevice(name,'judge_tablet','Main venue','JudgeOS');setName('');setAdding(false)};
 const latestProposal=s.deviceReassignments.find(x=>x.status==='PROPOSED'||x.status==='BLOCKED');
 return <section className="mizan-surface p-5"><div className="flex items-center justify-between gap-4"><div><div className="mizan-kicker">{ar?'مركز الأجهزة':'DEVICE CENTER'}</div><h2 className="font-extrabold mt-1">{ar?'أجهزة التشغيل':'Operational appliances'}</h2></div><Button size="sm" variant="outline" onClick={()=>setAdding(v=>!v)} icon={<Plus className="w-4 h-4"/>}>{ar?'جهاز':'Device'}</Button></div>
 {adding&&<div className="mt-4 flex gap-2"><input autoFocus value={name} onChange={e=>setName(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-[#ddd] px-3 py-2.5 text-sm" placeholder={ar?'اسم الجهاز':'Device name'}/><Button size="sm" disabled={!name.trim()} onClick={add}>{ar?'اعتماد':'Add'}</Button></div>}
 <div className="mt-4 divide-y divide-[#e6e4dd]">{s.devices.map(d=><div key={d.id} className="py-3.5 grid md:grid-cols-[1.1fr_.8fr_.7fr_auto] gap-3 items-center"><div className="flex items-center gap-3 min-w-0"><span className="w-9 h-9 rounded-xl bg-[#f2f0ea] grid place-items-center">{d.status==='offline'?<WifiOff className="w-4 h-4 text-[#8a5f55]"/>:<HardDrive className="w-4 h-4 text-[#5f6963]"/>}</span><div className="min-w-0"><input value={d.name} onChange={e=>s.updateDevice(d.id,{name:e.target.value})} className="w-full bg-transparent text-xs font-black outline-none truncate"/><div className="text-[10px] text-[#686d6a] mt-1">{d.zone||'—'} · v{d.softwareVersion}</div></div></div><select value={d.role||''} onChange={e=>s.updateDevice(d.id,{role:e.target.value as DeviceRecord['role']})} disabled={d.status==='revoked'} className="rounded-xl border border-[#ddd] bg-white px-2.5 py-2 text-xs font-bold"><option value="">{ar?'اختر الدور':'Assign role'}</option>{roles.map(r=><option key={r}>{r}</option>)}</select><div className="text-[10px] text-[#626965]"><div>{ar?'آخر نشاط':'Last seen'}: {new Date(d.lastSeenAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><div className="mt-1">{ar?'المزامنة':'Sync'}: {d.lastSyncAt?new Date(d.lastSyncAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}</div></div><div className="flex items-center justify-end gap-1">{d.status==='offline'&&<button onClick={()=>s.proposeDeviceHealing(d.id)} title={ar?'اقتراح بديل':'Find compatible spare'} className="w-9 h-9 rounded-xl grid place-items-center hover:bg-[#e8eee9]"><RefreshCcw className="w-4 h-4 text-[#2F6555]"/></button>}<button onClick={()=>s.updateDeviceStatus(d.id,d.status==='online'?'offline':'online')} disabled={d.status==='revoked'} title={ar?'تبديل الحالة':'Toggle status'} className="w-9 h-9 rounded-xl grid place-items-center hover:bg-[#efede7] disabled:opacity-30">{d.status==='online'?<Wifi className="w-4 h-4 text-[#2F6555]"/>:<WifiOff className="w-4 h-4"/>}</button><button onClick={()=>s.revokeDevice(d.id)} disabled={d.status==='revoked'} title={ar?'سحب التفويض':'Revoke'} className="w-9 h-9 rounded-xl grid place-items-center hover:bg-[#F4E6E3] disabled:opacity-30"><XCircle className="w-4 h-4"/></button><Badge variant={d.status==='online'?'emerald':'neutral'}>{d.status}</Badge></div></div>)}</div>
 {latestProposal&&<div className={`mt-4 rounded-2xl border p-4 ${latestProposal.status==='BLOCKED'?'border-[#e4c7c2] bg-[#fbf5f3]':'border-[#d8ded9] bg-[#f7f8f4]'}`}><div className="flex items-start gap-3"><span className="w-9 h-9 rounded-xl bg-white grid place-items-center"><ArrowRightLeft className="w-4 h-4 text-[#53655d]"/></span><div className="flex-1"><div className="text-xs font-black">{latestProposal.status==='BLOCKED'?(ar?'إعادة التعيين محمية':'Reassignment protected'):(ar?'بديل تشغيلي مقترح':'Compatible spare proposed')}</div><div className="text-[10px] text-[#626965] mt-1">{latestProposal.reason}</div><div className="text-[10px] font-mono text-[#686d6a] mt-1">{s.devices.find(d=>d.id===latestProposal.spareDeviceId)?.name||latestProposal.spareDeviceId} → {latestProposal.toRole}</div></div>{latestProposal.status==='PROPOSED'&&<div className="flex gap-1"><Button size="sm" onClick={()=>s.decideDeviceHealing(latestProposal.id,true)}>{ar?'اعتماد':'Approve'}</Button><Button size="sm" variant="outline" onClick={()=>s.decideDeviceHealing(latestProposal.id,false)}>{ar?'تجاهل':'Dismiss'}</Button></div>}</div></div>}
 <div className="mt-4 flex items-center gap-2 text-[10px] text-[#656b66]"><ShieldCheck className="w-3.5 h-3.5"/>{ar?'لا تُعرض مفاتيح أو أسرار الأجهزة هنا. كل إعادة تعيين أو سحب صلاحية تُسجل.':'No device secrets are exposed. Reassignment and revocation are audited.'}</div></section>
}
