import React, {useEffect, useMemo, useState} from 'react';
import { KeyRound, ShieldCheck, UsersRound, UserPlus, Laptop2, RefreshCcw, Trash2, QrCode, Copy, XCircle } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { auth } from '../../lib/firebase';
import { Button } from '../design-system/Button';
import { Badge } from '../design-system/Badge';
import { Modal } from '../design-system/Modal';
import { RealQRCode } from '../design-system/RealQRCode';
import { uiToken } from '../../lib/ui-language';
import type { Role } from '../../types';

const ORG_STAFF:Role[]=['comp_admin','head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator','auditor','guardian','support_agent'];
const COMP_STAFF:Role[]=['head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator','guardian'];
const OWNER_STAFF:Role[]=['org_admin','support_agent'];
const arRole=(r:Role)=>({super_admin:'مدير المنصة',org_admin:'مدير الجهة',comp_admin:'مدير المسابقة',head_judge:'رئيس التحكيم',judge:'محكم',ops_manager:'مدير التشغيل',exception_host:'مكتب الاستثناء',delegation_manager:'مسؤول وفد',participant:'متسابق',broadcast_operator:'مشغل الحفل',auditor:'مدقق',guardian:'ولي أمر',support_agent:'دعم'} as Partial<Record<Role,string>>)[r]||r;
type RemoteData={accounts:any[];grants:any[];invitations:any[];sessions:any[]};

/** QR v4-L is intentionally compact. Most tenant URLs fit; compact payload remains a safe fallback. */
export const activationQrValue=(token:string,origin?:string)=>{
 const base=(origin||window.location.origin).replace(/\/$/,'');
 const link=`${base}/#a=${encodeURIComponent(token)}`;
 return new TextEncoder().encode(link).length<=78?link:`MZI1|${token}`;
};

export const IdentityGovernance:React.FC<{competitionId?:string}>=({competitionId})=>{
 const s=useAppStore();const ar=s.language==='ar';const production=import.meta.env.VITE_REQUIRE_AUTH==='true'; const competitionScoped=Boolean(competitionId);
 const [email,setEmail]=useState('');const [name,setName]=useState('');const [role,setRole]=useState<Role|''>('');const [message,setMessage]=useState('');const [oneTimeToken,setOneTimeToken]=useState('');const [remote,setRemote]=useState<RemoteData|null>(null);const [loading,setLoading]=useState(false);const [deleteTarget,setDeleteTarget]=useState<any|null>(null);const [deleting,setDeleting]=useState(false);
 const availableRoles=useMemo<Role[]>(()=>s.currentUser.role==='super_admin'?OWNER_STAFF:s.currentUser.role==='comp_admin'?COMP_STAFF:ORG_STAFF,[s.currentUser.role]);
 const api=async(path:string,init:RequestInit={})=>{const u=auth.currentUser;if(!u)throw new Error('IDENTITY_REQUIRED');const token=await u.getIdToken();return fetch(path,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(init.headers||{})}})};
 const loadRemote=async()=>{if(!production)return;setLoading(true);try{const params=new URLSearchParams();if(s.currentUser.role==='super_admin')params.set('organizationId',s.organization.id);if(competitionId)params.set('competitionId',competitionId);const target=params.size?`?${params.toString()}`:'';const r=await api(`/api/identity/governance${target}`);const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.code||'IDENTITY_GOVERNANCE_UNAVAILABLE'));setRemote(null)}else setRemote(body)}catch{setMessage(ar?'تعذر الاتصال بمستودع الهوية الخادمي.':'Server identity repository unavailable.');setRemote(null)}finally{setLoading(false)}};
 useEffect(()=>{void loadRemote()},[production,s.organization.id,s.competition.id]);

 const devGrants=useMemo(()=>s.roleGrants.filter(g=>g.organizationId===s.organization.id&&g.role!=='scientific_admin'&&(!competitionId||g.competitionId===competitionId)),[s.roleGrants,s.organization.id,competitionId]);
 const devAccountIds=useMemo(()=>new Set(devGrants.map(g=>g.accountId)),[devGrants]);
 const devAccounts=useMemo(()=>s.identityAccounts.filter(a=>a.organizationId===s.organization.id&&devAccountIds.has(a.id)&&!s.roleGrants.some(g=>g.accountId===a.id&&g.role==='super_admin'&&g.status==='ACTIVE')),[s.identityAccounts,s.roleGrants,s.organization.id,devAccountIds]);
 const accounts=production?(remote?.accounts||[]):devAccounts;
 const invitations=production?(remote?.invitations||[]):s.identityInvitations.filter(i=>i.organizationId===s.organization.id&&i.requestedRole!=='scientific_admin'&&(!competitionId||i.competitionId===competitionId));
 const grants=production?(remote?.grants||[]):devGrants;
 const sessions=production?(remote?.sessions||[]):s.authSessions.filter(x=>x.organizationId===s.organization.id&&(!competitionId||(x as any).competitionId===competitionId));
 const qrValue=oneTimeToken?activationQrValue(oneTimeToken):'';
 const qrIsLink=qrValue.startsWith('http');

 const create=async()=>{
  setMessage('');setOneTimeToken('');if(!role)return;
  if(production){try{if(s.currentUser.role!=='super_admin'&&!competitionId){setMessage('COMPETITION_SCOPE_REQUIRED');return;}const r=await api('/api/identity/invitations',{method:'POST',body:JSON.stringify({email,displayName:name,requestedRole:role,organizationId:s.currentUser.role==='super_admin'?s.organization.id:undefined,competitionId:s.currentUser.role==='super_admin'?undefined:competitionId,reason:'Authorized competition role provisioning'})});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.code||'INVITATION_FAILED'));return;}setEmail('');setName('');setRole('');if(body.activationToken)setOneTimeToken(body.activationToken);setMessage(ar?'الدعوة جاهزة فورًا. سلّم QR للشخص المعني فقط.':'Invitation is ready. Give the one-time QR only to the intended person.');await loadRemote();return}catch{setMessage('IDENTITY_SERVER_UNAVAILABLE');return}}
  if(!competitionId){setMessage('COMPETITION_SCOPE_REQUIRED');return;}const r=await s.createIdentityInvitation({email,displayName:name,requestedRole:role,competitionId,reason:'Authorized competition role provisioning'});if(!r.ok){setMessage(r.reason);return;}setEmail('');setName('');setRole('');if(r.activationToken)setOneTimeToken(r.activationToken);setMessage(ar?'الدعوة جاهزة للتفعيل.':'Invitation is ready for activation.');
 };

 const migrateLegacy=async(id:string)=>{setOneTimeToken('');if(!production)return;const r=await api(`/api/identity/invitations/${encodeURIComponent(id)}/approve`,{method:'POST',body:'{}'});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.code||'MIGRATION_FAILED'));return;}if(body.activationToken)setOneTimeToken(body.activationToken);setMessage(ar?'حُوّلت الدعوة القديمة إلى QR تفعيل مباشر.':'Legacy pending invitation upgraded to direct QR activation.');await loadRemote()};
 const grantFor=(account:any)=>grants.find((g:any)=>g.accountId===account.id&&['ACTIVE','SUSPENDED'].includes(g.status));
 const suspend=async(account:any)=>{const reason=ar?'تعليق صلاحية المستخدم في هذه المسابقة':'Competition access suspended by authorized manager';if(production){const grant=grantFor(account);if(competitionScoped&&grant){const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/suspend`,{method:'POST',body:JSON.stringify({reason})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(ar?'تم تعليق الصلاحية في هذه المسابقة فقط.':'Access suspended for this competition only.'):String(body.code||'SUSPEND_FAILED'));await loadRemote();return;}const r=await api(`/api/identity/accounts/${encodeURIComponent(account.id)}/suspend`,{method:'POST',body:JSON.stringify({reason})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(ar?'تم تعليق الحساب.':'Account suspended.'):String(body.code||'SUSPEND_FAILED'));await loadRemote();return}s.suspendIdentityAccount(account.id,reason)};
 const revokeSessions=async(account:any)=>{if(!production)return;const grant=grantFor(account);const path=competitionScoped&&grant?`/api/identity/grants/${encodeURIComponent(grant.id)}/revoke-sessions`:`/api/identity/accounts/${encodeURIComponent(account.id)}/revoke-sessions`;const r=await api(path,{method:'POST',body:JSON.stringify({reason:ar?'تسليم آمن لجهاز بديل':'Secure handover to a replacement device'})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(ar?`أُغلقت ${body.count||0} جلسة تخص هذا النطاق.`:`${body.count||0} scoped session(s) revoked.`):String(body.code||'SESSION_REVOKE_FAILED'));await loadRemote()};
 const remove=async()=>{if(!deleteTarget||!production)return;setDeleting(true);try{const grant=grantFor(deleteTarget);const path=competitionScoped&&grant?`/api/identity/grants/${encodeURIComponent(grant.id)}`:`/api/identity/accounts/${encodeURIComponent(deleteTarget.id)}`;const r=await api(path,{method:'DELETE',body:JSON.stringify({reason:competitionScoped?'Competition access removed by authorized manager':'User removed by authorized tenant administrator'})});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(String(body.code||'REMOVE_FAILED'));return;}setMessage(competitionScoped?(ar?'أُلغيت صلاحية المستخدم في هذه المسابقة فقط، وبقيت صلاحياته الأخرى كما هي.':'User access to this competition was removed; other competition access is unchanged.'):(ar?'تم حذف وصول المستخدم من الجهة مع حفظ الأثر التدقيقي.':'User access removed while preserving the audit trail.'));setDeleteTarget(null);await loadRemote()}finally{setDeleting(false)}};
 const copyActivation=async()=>{try{await navigator.clipboard.writeText(qrValue);setMessage(ar?'تم نسخ رابط/رمز التفعيل الاحتياطي.':'Activation link/payload copied.')}catch{setMessage(ar?'تعذر النسخ التلقائي. استخدم QR مباشرة.':'Automatic copy failed; use the QR directly.')}};

 return <section className="mizan-surface p-5 sm:p-6">
  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><div className="mizan-kicker">{ar?'الهوية والصلاحيات':'IDENTITY & ACCESS'}</div><h2 className="text-xl font-black mt-1">{competitionScoped?(ar?'فريق هذه المسابقة فقط':'This competition team only'):(ar?'كل شخص بحسابه. مدير الجهة يدير فريقه.':'Named accounts. Delegated tenant authority.')}</h2><p className="text-xs leading-6 text-[#636864] mt-2 max-w-2xl">{competitionScoped?(ar?'أي محكم أو مدير أو موظف تضيفه هنا تُربط صلاحيته بهذه المسابقة وحدها، ولا تنتقل تلقائيًا إلى أي مسابقة أخرى للجهة.':'Every role created here is bound to this competition only and never carries over to another competition.'):(ar?'اعتماد مالك ميزان لمدير الجهة هو التفويض. بعدها يدير مدير الجهة فريق مسابقاته من داخل كل مسابقة.':'The platform owner delegates the tenant administrator once; competition teams are then managed inside each competition.')}</p></div><div className="grid grid-cols-3 gap-2 min-w-72"><Mini n={accounts.filter((a:any)=>a.status==='ACTIVE').length} t={ar?'نشط':'Active'}/><Mini n={invitations.filter((i:any)=>i.status==='READY').length} t={ar?'دعوات':'Invites'}/><Mini n={sessions.filter((x:any)=>x.status==='ACTIVE').length} t={ar?'جلسات':'Sessions'}/></div></div>
  {production&&<div className="mt-4 rounded-xl bg-[#E7EEE9] text-[#214C40] px-4 py-3 flex items-center gap-3"><ShieldCheck className="w-4 h-4"/><div className="text-[11px] font-bold flex-1">{ar?'وضع إنتاجي: العزل والصلاحيات والحذف والتعليق تُفرض من الخادم، وليس بإخفاء الأزرار فقط.':'Production mode: tenant isolation, provisioning, removal and suspension are server-enforced.'}</div><button onClick={()=>void loadRemote()} title={ar?'تحديث':'Refresh'} aria-label={ar?'تحديث':'Refresh'}><RefreshCcw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>}

  <div className="mt-5 grid lg:grid-cols-[1fr_.9fr] gap-4">
   <div className="rounded-2xl border border-[#dfddd6] p-4"><div className="flex items-center gap-2"><UserPlus className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'إضافة مستخدم':'Invite user'}</div></div><div className="grid sm:grid-cols-2 gap-2 mt-4"><input value={name} onChange={e=>setName(e.target.value)} className="mizan-input" aria-label={ar?'الاسم الحقيقي':'Legal/display name'} placeholder={ar?'الاسم الحقيقي':'Legal/display name'}/><input value={email} onChange={e=>setEmail(e.target.value)} className="mizan-input" aria-label={ar?'البريد الشخصي':'Personal work email'} placeholder={ar?'البريد الشخصي':'Personal work email'}/><select aria-label={ar?'الدور المطلوب':'Requested role'} value={role} onChange={e=>setRole(e.target.value as Role| '')} className="mizan-input sm:col-span-2"><option value="" disabled>{ar?'اختر الدور':'Choose role'}</option>{availableRoles.map(r=><option key={r} value={r}>{ar?arRole(r):r.replaceAll('_',' ')}</option>)}</select></div><Button className="mt-3" disabled={!email.includes('@')||!name.trim()||!role} onClick={()=>void create()} icon={<KeyRound className="w-4 h-4"/>}>{ar?'إنشاء QR التفعيل':'Create activation QR'}</Button>{message&&<div className="mt-3 rounded-xl bg-[#f3f1eb] p-3 text-xs font-bold break-words">{message}</div>}
    {oneTimeToken&&<div className="mt-4 rounded-2xl border border-[#d9e4de] bg-[#F7FAF8] p-4"><div className="flex items-center gap-2 text-[#214C40]"><QrCode className="w-4 h-4"/><div className="text-xs font-black">{ar?'QR تفعيل — يظهر مرة واحدة':'ONE-TIME ACTIVATION QR'}</div></div><div className="mt-4 flex justify-center"><div className="rounded-2xl bg-white p-3 border border-[#e3e5e1] shadow-sm"><RealQRCode value={qrValue} size={184} label={ar?'رمز تفعيل مستخدم ميزان':'MIZAN user activation QR'}/></div></div><p className="mt-3 text-[10px] leading-5 text-center text-[#626964]">{qrIsLink?(ar?'يمسحه المستخدم بكاميرا الهاتف؛ يفتح ميزان ثم يربط حسابه تلقائيًا بعد تسجيل الدخول بالبريد المدعو.':'Scan with the phone camera; MIZAN opens and binds the invited account after sign-in.'):(ar?'امسح QR داخل قارئ يدعم نص MZI1. استُخدم هذا الشكل لأن عنوان هذه الجهة طويل جدًا على سعة QR المختصرة.':'Scan in a reader that supports MZI1; this compact form is used because the tenant URL exceeds the QR payload limit.')}</p><div className="mt-3 flex justify-center"><Button size="sm" variant="ghost" onClick={()=>void copyActivation()} icon={<Copy className="w-3.5 h-3.5"/>}>{ar?'نسخ بديل':'Copy fallback'}</Button></div></div>}
   </div>

   <div className="rounded-2xl border border-[#dfddd6] overflow-hidden"><div className="px-4 py-3 border-b border-[#e5e3dc] flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'دعوات التفعيل':'Activation invitations'}</div></div><div className="divide-y divide-[#e5e3dc]">{invitations.filter((i:any)=>['PENDING_APPROVAL','READY'].includes(i.status)).slice(0,8).map((i:any)=><div key={i.id} className="p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-xs font-black truncate">{i.displayName}</div><div className="text-[10px] text-[#666a67] mt-1 break-all">{i.email} · {ar?arRole(i.requestedRole):i.requestedRole}</div></div><Badge variant={i.status==='READY'?'emerald':'amber'}>{i.status==='READY'?(ar?'جاهزة':'Ready'):(ar?'دعوة قديمة':'Legacy')}</Badge></div>{i.status==='PENDING_APPROVAL'&&production&&<Button size="sm" variant="outline" className="mt-3" onClick={()=>void migrateLegacy(i.id)}>{ar?'تحويل إلى التفعيل المباشر':'Upgrade to direct activation'}</Button>}</div>)}{!invitations.some((i:any)=>['PENDING_APPROVAL','READY'].includes(i.status))&&<div className="p-6 text-center text-xs text-[#686d6a]">{ar?'لا توجد دعوات معلقة':'No pending invitations'}</div>}</div></div>
  </div>

  <div className="mt-5 border-t border-[#e5e3dc]"><div className="py-3 text-[10px] font-black tracking-[.13em] text-[#6a706c]">{competitionScoped?(ar?'مستخدمو هذه المسابقة فقط':'THIS COMPETITION ONLY'):(ar?'مستخدمو هذه الجهة فقط':'THIS TENANT ONLY')}</div><div className="divide-y divide-[#e5e3dc]">{accounts.slice(0,20).map((a:any)=>{const grant=grants.find((g:any)=>g.accountId===a.id&&['ACTIVE','SUSPENDED'].includes(g.status));const activeSessions=sessions.filter((x:any)=>x.accountId===a.id&&x.status==='ACTIVE').length;const uid=a.uid||a.firebaseUid;const self=uid===s.currentUser.id;return <div key={a.id} className="py-3 flex items-center gap-3"><span className={`w-9 h-9 rounded-xl grid place-items-center ${a.status==='ACTIVE'?'bg-[#E7EEE9] text-[#214C40]':'bg-[#F4E6E3] text-[#88473f]'}`}><UsersRound className="w-4 h-4"/></span><div className="flex-1 min-w-0"><div className="text-xs font-black truncate">{a.displayName}</div><div className="text-[10px] text-[#656b66] mt-1 truncate">{a.email} · {grant?(ar?arRole(grant.role):grant.role):'—'} · {grant?.committeeId||grant?.competitionId||(ar?'الجهة':'organization')}</div></div>{activeSessions>0&&<Badge variant="neutral"><Laptop2 className="w-3 h-3 me-1"/>{activeSessions}</Badge>}<Badge variant={a.status==='ACTIVE'?'emerald':'neutral'}>{uiToken(a.status,ar)}</Badge>{production&&a.status==='ACTIVE'&&activeSessions>0&&!self&&<button onClick={()=>void revokeSessions(a)} className="w-11 h-11 rounded-xl border border-[#e0ded7] grid place-items-center text-[#6e716f] hover:bg-[#f4f2ec]" title={ar?'إغلاق الجلسات':'Revoke sessions'} aria-label={ar?'إغلاق الجلسات':'Revoke sessions'}><Laptop2 className="w-4 h-4"/></button>}{a.status==='ACTIVE'&&!self&&<button onClick={()=>void suspend(a)} className="w-11 h-11 rounded-xl border border-[#e0ded7] grid place-items-center text-[#8a6a45] hover:bg-[#F7F1E7]" title={ar?'تعليق الحساب':'Suspend account'} aria-label={ar?'تعليق الحساب':'Suspend account'}><XCircle className="w-4 h-4"/></button>}{production&&!self&&<button onClick={()=>setDeleteTarget(a)} className="w-11 h-11 rounded-xl border border-[#ead7d3] grid place-items-center text-[#9a5048] hover:bg-[#F9F0EE]" title={ar?'حذف المستخدم':'Remove user'} aria-label={ar?'حذف المستخدم':'Remove user'}><Trash2 className="w-4 h-4"/></button>}</div>})}{accounts.length===0&&<div className="py-8 text-center text-xs text-[#686d6a]">{ar?'لا يوجد مستخدمون تابعون لهذه الجهة بعد.':'No tenant users yet.'}</div>}</div></div>

  <Modal isOpen={!!deleteTarget} onClose={()=>!deleting&&setDeleteTarget(null)} title={competitionScoped?(ar?'إلغاء الصلاحية من هذه المسابقة':'Remove competition access'):(ar?'حذف المستخدم من الجهة':'Remove user from tenant')} subtitle={deleteTarget?.displayName||deleteTarget?.email} maxWidth="sm"><div className="space-y-4"><div className="rounded-2xl bg-[#F9F0EE] p-4 text-xs leading-6 text-[#7e443e] font-semibold">{competitionScoped?(ar?'ستُلغى صلاحية هذا المستخدم في هذه المسابقة فقط. لن تتأثر أي صلاحية أخرى له في مسابقات الجهة.':'Only this competition grant will be revoked. Access to other competitions remains unchanged.'):(ar?'سيُلغى وصول هذا المستخدم وصلاحياته وجلساته فورًا، مع بقاء الأثر التدقيقي والسجل التاريخي.':'This revokes tenant access while preserving audit/history.')}</div><div className="flex justify-end gap-2"><Button variant="ghost" disabled={deleting} onClick={()=>setDeleteTarget(null)}>{ar?'إلغاء':'Cancel'}</Button><Button variant="danger" disabled={deleting} onClick={()=>void remove()} icon={<Trash2 className="w-4 h-4"/>}>{deleting?'…':ar?'حذف المستخدم':'Remove user'}</Button></div></div></Modal>
 </section>;
};

const Mini=({n,t}:{n:number;t:string})=><div className="rounded-xl bg-[#f3f1eb] p-3"><div className="text-xl font-black">{n}</div><div className="text-[10px] text-[#656b66] mt-1">{t}</div></div>;
