import React,{useEffect,useMemo,useState} from 'react';
import {KeyRound,ShieldCheck,UserPlus,Laptop2,RefreshCcw,Trash2,QrCode,Copy,Pause,Play,Layers3,ChevronDown,LockKeyhole} from 'lucide-react';
import {useAppStore} from '../../lib/store';
import {auth} from '../../lib/firebase';
import {Button} from '../design-system/Button';
import {Badge} from '../design-system/Badge';
import {Modal} from '../design-system/Modal';
import {RealQRCode} from '../design-system/RealQRCode';
import type {Role} from '../../types';
import {isEmail,normalizeEmail,normalizeSpaces} from '../../lib/input-validation';
import {featureLabel} from '../../lib/ui-language';

const ORG_STAFF:Role[]=['comp_admin','head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator','auditor'];
const COMP_STAFF:Role[]=['head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator'];
const OWNER_STAFF:Role[]=['org_admin','support_agent'];
const arRole=(r:Role)=>({super_admin:'مدير المنصة',org_admin:'مدير الجهة',comp_admin:'مدير المسابقة',head_judge:'رئيس التحكيم',judge:'محكم',ops_manager:'مدير التشغيل',exception_host:'مكتب الاستثناء',delegation_manager:'مسؤول وفد',participant:'متسابق',broadcast_operator:'مشغل الحفل',auditor:'مدقق',guardian:'ولي أمر',support_agent:'دعم'} as Partial<Record<Role,string>>)[r]||r;
type RemoteData={accounts:any[];grants:any[];invitations:any[];sessions:any[]};
type AccessTab='grants'|'invite'|'sessions';

export const activationQrValue=(token:string,origin?:string)=>{
 const base=(origin||window.location.origin).replace(/\/$/,'');
 const link=`${base}/#a=${encodeURIComponent(token)}`;
 return new TextEncoder().encode(link).length<=78?link:`MZI1|${token}`;
};

export const IdentityGovernance:React.FC<{competitionId?:string;organizationId?:string}>=({competitionId,organizationId})=>{
 const s=useAppStore(); const ar=s.language==='ar'; const production=import.meta.env.VITE_REQUIRE_AUTH==='true';
 const competitionScoped=Boolean(competitionId); const scopeOrgId=organizationId||s.organization.id;
 const [tab,setTab]=useState<AccessTab>('grants'); const [invitesOpen,setInvitesOpen]=useState(false);
 const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState<Role|''>('');
 const [message,setMessage]=useState(''); const [oneTimeToken,setOneTimeToken]=useState('');
 const [remote,setRemote]=useState<RemoteData|null>(null); const [licensedModules,setLicensedModules]=useState<string[]>([]); const [loading,setLoading]=useState(false);
 const [deleteTarget,setDeleteTarget]=useState<{account:any;grant:any}|null>(null); const [deleting,setDeleting]=useState(false);
 const scopedCompetition=competitionId?s.competitions.find(c=>c.id===competitionId):undefined;
 const competitionClosed=Boolean(scopedCompetition&&['completed','archived'].includes(scopedCompetition.status));
 const availableRoles=useMemo<Role[]>(()=>s.currentUser.role==='super_admin'?(competitionScoped?ORG_STAFF:OWNER_STAFF):s.currentUser.role==='comp_admin'?COMP_STAFF:ORG_STAFF,[s.currentUser.role,competitionScoped]);
 const effectiveRoles=competitionClosed?availableRoles.filter(r=>r==='auditor'):availableRoles;
 const identityProvisioningLocked=competitionClosed&&!effectiveRoles.length;
 const api=async(path:string,init:RequestInit={})=>{const u=auth.currentUser;if(!u)throw new Error('IDENTITY_REQUIRED');const token=await u.getIdToken();return fetch(path,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(init.headers||{})}})};
 const loadRemote=async()=>{if(!production)return;setLoading(true);try{const params=new URLSearchParams();if(s.currentUser.role==='super_admin')params.set('organizationId',scopeOrgId);if(competitionId)params.set('competitionId',competitionId);const r=await api(`/api/identity/governance${params.size?`?${params}`:''}`);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(body.code||'IDENTITY_GOVERNANCE_UNAVAILABLE'));setRemote(body);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:(ar?'تعذر تحميل الصلاحيات.':'Could not load access.'));setRemote(null)}finally{setLoading(false)}};
 const loadEntitlements=async()=>{if(!production){setLicensedModules(s.featureFlags.filter(f=>f.organizationId===scopeOrgId&&f.enabled).map(f=>f.key));return}try{const params=new URLSearchParams();if(s.currentUser.role==='super_admin')params.set('organizationId',scopeOrgId);const r=await api(`/api/identity/entitlements${params.size?`?${params}`:''}`);const body=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(body.licensedModules))setLicensedModules(body.licensedModules.map(String));else setLicensedModules([])}catch{setLicensedModules([])}};
 useEffect(()=>{void loadRemote();void loadEntitlements()},[production,scopeOrgId,competitionId,s.featureFlags.length]);

 const devGrants=useMemo(()=>s.roleGrants.filter(g=>g.organizationId===scopeOrgId&&['ACTIVE','SUSPENDED'].includes(g.status)&&(!competitionId||g.competitionId===competitionId)),[s.roleGrants,scopeOrgId,competitionId]);
 const ids=useMemo(()=>new Set(devGrants.map(g=>g.accountId)),[devGrants]);
 const devAccounts=useMemo(()=>s.identityAccounts.filter(a=>a.organizationId===scopeOrgId&&ids.has(a.id)&&!s.roleGrants.some(g=>g.accountId===a.id&&g.role==='super_admin'&&g.status==='ACTIVE')),[s.identityAccounts,s.roleGrants,scopeOrgId,ids]);
 const accounts=production?(remote?.accounts||[]):devAccounts;
 const grants=production?(remote?.grants||[]):devGrants;
 const invitations=production?(remote?.invitations||[]):s.identityInvitations.filter(i=>i.organizationId===scopeOrgId&&i.status!=='REVOKED'&&(!competitionId||i.competitionId===competitionId));
 const sessions=production?(remote?.sessions||[]):s.authSessions.filter(x=>x.organizationId===scopeOrgId&&(!competitionId||(x as any).competitionId===competitionId));
 const moduleGrants=licensedModules;
 const qrValue=oneTimeToken?activationQrValue(oneTimeToken):'';
 const activeSessions=sessions.filter((x:any)=>x.status==='ACTIVE');
 const accountForSession=(session:any)=>accounts.find((a:any)=>a.id===session.accountId);
 const grantForSession=(session:any)=>grants.find((g:any)=>g.accountId===session.accountId&&g.status==='ACTIVE'&&((session.competitionId&&g.competitionId===session.competitionId)||(!session.competitionId&&!g.competitionId)));
 const activeOrgAdmins=grants.filter((g:any)=>g.role==='org_admin'&&g.status==='ACTIVE').length;
 const isSelfAccount=(a:any)=>[a.id,a.uid,a.firebaseUid].filter(Boolean).includes(s.currentUser.id)||normalizeEmail(String(a.email||''))===normalizeEmail(s.currentUser.email||'');
 const isProtectedGrant=(a:any,g:any)=>isSelfAccount(a)||(g.role==='org_admin'&&(s.currentUser.role!=='super_admin'||activeOrgAdmins<=1));

 const create=async()=>{setMessage('');setOneTimeToken('');if(competitionClosed&&role!=='auditor')return setMessage(ar?'المسابقة منتهية؛ لا يمكن إنشاء صلاحيات تشغيلية جديدة. يمكن فقط إضافة مدقق للأرشيف.':'Competition is closed; operational access cannot be created. Only an archive auditor may be added.');const cleanEmail=normalizeEmail(email),cleanName=normalizeSpaces(name);if(!role||!isEmail(cleanEmail)||!cleanName)return setMessage(ar?'تحقق من الاسم والبريد والدور.':'Check name, email and role.');if(production){try{if(s.currentUser.role!=='super_admin'&&!competitionId)return setMessage('COMPETITION_SCOPE_REQUIRED');const r=await api('/api/identity/invitations',{method:'POST',body:JSON.stringify({email:cleanEmail,displayName:cleanName,requestedRole:role,organizationId:s.currentUser.role==='super_admin'?scopeOrgId:undefined,competitionId:competitionScoped?competitionId:undefined,reason:'Authorized scoped role provisioning'})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.code||'INVITATION_FAILED'));setEmail('');setName('');setRole('');if(body.activationToken)setOneTimeToken(body.activationToken);setMessage(ar?'الدعوة جاهزة. سلّم QR للشخص المعني فقط.':'Invitation ready. Share the QR only with the intended person.');await loadRemote()}catch{setMessage('IDENTITY_SERVER_UNAVAILABLE')}return}if(!competitionId)return setMessage('COMPETITION_SCOPE_REQUIRED');const r=await s.createIdentityInvitation({email:cleanEmail,displayName:cleanName,requestedRole:role,competitionId,reason:'Authorized competition role provisioning'});if(!r.ok)return setMessage(r.reason);if(r.activationToken)setOneTimeToken(r.activationToken)};
 const grantsFor=(account:any)=>grants.filter((g:any)=>g.accountId===account.id&&['ACTIVE','SUSPENDED'].includes(g.status));
 const toggle=async(grant:any)=>{if(!production)return;const resume=grant.status==='SUSPENDED';const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/${resume?'resume':'suspend'}`,{method:'POST',body:JSON.stringify({reason:resume?'Authorized competition access restored':'Authorized competition access frozen'})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(resume?(ar?'أُعيدت الصلاحية لهذه المسابقة.':'Competition access restored.'):(ar?'جُمّدت الصلاحية لهذه المسابقة وأُغلقت جلساتها.':'Competition access frozen and its sessions closed.')):String(body.code||'ACCESS_CHANGE_FAILED'));await loadRemote()};
 const reissue=async(grant:any)=>{if(!production)return;setOneTimeToken('');const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/reissue-qr`,{method:'POST',body:'{}'});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.code||'QR_REISSUE_FAILED'));setOneTimeToken(String(body.activationToken||''));setMessage(ar?'أُلغي أي QR سابق وصدر QR جديد لمرة واحدة.':'Any previous QR was invalidated and a new one-time QR was issued.');setTab('invite');await loadRemote()};
 const revoke=async(grant:any)=>{if(!production)return;const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/revoke-sessions`,{method:'POST',body:JSON.stringify({reason:'Secure session handover'})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(ar?`أُغلقت ${body.count||0} جلسة.`:`${body.count||0} session(s) revoked.`):String(body.code||'SESSION_REVOKE_FAILED'));await loadRemote()};
 const remove=async()=>{if(!deleteTarget||!production)return;setDeleting(true);try{const r=await api(`/api/identity/grants/${encodeURIComponent(deleteTarget.grant.id)}`,{method:'DELETE',body:JSON.stringify({reason:'Scoped access removed by authorized administrator'})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.code||'REMOVE_FAILED'));setMessage(ar?'أُلغيت هذه الصلاحية فقط، وبقيت بقية صلاحيات المستخدم كما هي.':'Only this grant was removed; the user’s other grants are unchanged.');setDeleteTarget(null);await loadRemote()}finally{setDeleting(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(qrValue);setMessage(ar?'تم نسخ رابط/رمز التفعيل.':'Activation link copied.')}catch{setMessage(ar?'تعذر النسخ؛ استخدم QR.':'Copy failed; use the QR.')}};

 const tabs:[AccessTab,string,string][]=[
  ['grants',ar?'الفريق والصلاحيات':'Team & grants',String(grants.filter((g:any)=>g.status==='ACTIVE').length)],
  ['sessions',ar?'الجلسات النشطة':'Active sessions',String(activeSessions.length)],
  ['invite',ar?'إضافة مستخدم':'Invite user','+'],
 ];
 return <section className="mizan-surface p-4 sm:p-5 overflow-hidden">
  <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div><div className="mizan-kicker">{ar?'الهوية والصلاحيات':'IDENTITY & ACCESS'}</div><h2 className="text-lg sm:text-xl font-black mt-1">{competitionScoped?(ar?'فريق هذه المسابقة فقط':'This competition team only'):(ar?'صلاحيات هذه الجهة':'Organization access')}</h2><p className="text-[11px] leading-5 text-[#636864] mt-2 max-w-2xl">{competitionScoped?(ar?'كل صلاحية هنا تخص هذه المسابقة وحدها. لا نعرض جميع أدوات الإدارة دفعة واحدة؛ تنقّل بين التبويبات.':'Every grant is scoped to this competition. Use the tabs instead of one long administration page.'):(ar?'الصلاحيات الفعلية والدعوات والوحدات المرخصة تظهر هنا في مكان واحد.':'Actual grants, invitations and licensed modules are shown here in one place.')}</p></div><div className="grid grid-cols-3 gap-2 min-w-0 sm:min-w-64"><Mini n={grants.filter((g:any)=>g.status==='ACTIVE').length} t={ar?'صلاحيات':'Grants'}/><Mini n={invitations.filter((i:any)=>i.status==='READY').length} t={ar?'دعوات':'Invites'}/><Mini n={sessions.filter((x:any)=>x.status==='ACTIVE').length} t={ar?'جلسات':'Sessions'}/></div></div>
  {production&&<div className="mt-4 rounded-xl bg-[#E7EEE9] text-[#214C40] px-4 py-2.5 flex items-center gap-3"><ShieldCheck className="w-4 h-4 shrink-0"/><div className="text-[10px] font-bold flex-1">{ar?'العزل والتجميد والحذف تُفرض من الخادم، وهذه الأرقام تأتي من النطاق المحدد نفسه.':'Isolation, freeze and removal are server-enforced for this exact scope.'}</div><button className="w-11 h-11 grid place-items-center" onClick={()=>void loadRemote()} aria-label={ar?'تحديث':'Refresh'}><RefreshCcw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>}
  {competitionClosed&&<div className="mt-4 rounded-xl border border-[#d8c7a7] bg-[#fbf5e8] px-4 py-3 flex items-start gap-3"><LockKeyhole className="w-4 h-4 text-[#7a5a2f] shrink-0 mt-0.5"/><div><div className="text-xs font-black text-[#604724]">{ar?'المسابقة منتهية — الوصول التشغيلي مقفول':'Competition closed — operational access locked'}</div><p className="text-[10px] leading-5 text-[#6b5b45] mt-1">{ar?'تبقى هذه الصفحة للإدارة والتدقيق فقط. تُحظر كل الصلاحيات التشغيلية بعد الإغلاق، ويمكن لمدير الجهة إضافة مدقق أرشيفي فقط عند الحاجة.':'This page remains visible for administration and audit only. Operational roles stay blocked after closure; an archive auditor may be added when needed.'}</p></div></div>}
  <div className="mt-4 flex gap-2 overflow-x-auto pb-1" role="tablist">{tabs.map(([id,label,count])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={`shrink-0 min-h-11 rounded-xl border px-3 inline-flex items-center gap-2 text-xs font-black ${tab===id?'bg-[#214C40] text-white border-[#214C40]':'bg-white text-[#59615c] border-[#dedcd5]'}`}><span>{label}</span><span className={`rounded-full px-1.5 py-.5 text-[9px] ${tab===id?'bg-white/15':'bg-[#f1efe9]'}`}>{count}</span></button>)}</div>
  {message&&<div className="mt-3 rounded-xl bg-[#f3f1eb] p-3 text-xs font-bold break-words">{message}</div>}

  {tab==='grants'&&<div className="mt-4 space-y-4">
   {!competitionScoped&&<div className="rounded-2xl border border-[#dfddd6] p-4"><div className="flex items-center gap-2"><Layers3 className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'صلاحيات المنصة الممنوحة للجهة':'Platform entitlements for this organization'}</div></div>{moduleGrants.length?<div className="mt-3 flex flex-wrap gap-2">{moduleGrants.map(key=><Badge key={key} variant="emerald">{featureLabel(key,ar)}</Badge>)}</div>:<p className="mt-3 text-[11px] text-[#696f6b]">{ar?'لا توجد وحدات إضافية مرخصة في الحالة المحلية الحالية. صلاحيات المستخدمين الفعلية تظهر أسفلها مباشرة.':'No additional local module entitlements are recorded. Actual user grants are listed below.'}</p>}</div>}
   <div className="divide-y divide-[#e5e3dc]">{accounts.map((a:any)=><div key={a.id} className="py-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black text-sm">{a.displayName}</div><div dir="ltr" className="text-[11px] text-[#656b66] break-all">{a.email}</div></div><Badge variant={a.status==='ACTIVE'?'emerald':'neutral'}>{a.status==='ACTIVE'?(ar?'حساب نشط':'Active'):(ar?'حساب موقوف':'Suspended')}</Badge></div><div className="mt-3 space-y-2">{grantsFor(a).map((g:any)=><div key={g.id} className="rounded-xl bg-[#f7f5ef] p-3 flex flex-wrap items-center gap-2"><div className="flex-1 min-w-[180px]"><div className="text-xs font-black">{ar?arRole(g.role):g.role.replaceAll('_',' ')}</div><div className="text-[10px] text-[#656b66] mt-1">{g.competitionId?(ar?`مسابقة: ${g.competitionId}`:`Competition: ${g.competitionId}`):(ar?'صلاحية على مستوى الجهة':'Organization-level grant')}</div></div><Badge variant={g.status==='ACTIVE'?'emerald':'amber'}>{g.status==='ACTIVE'?(ar?'نشطة':'Active'):(ar?'مجمّدة':'Frozen')}</Badge>{isProtectedGrant(a,g)?<div className="min-h-11 px-3 rounded-xl border border-[#d9dfdb] inline-flex items-center gap-2 text-[10px] font-black text-[#59615c]" title={ar?'هذه الهوية محمية من حذف أو تجميد نفسها، ومدير الجهة الوحيد لا يمكن إسقاطه.':'This identity cannot remove/freeze itself; the last organization admin is protected.'}><LockKeyhole className="w-4 h-4"/>{ar?'محمي':'Protected'}</div>:<><IconButton title={g.status==='ACTIVE'?(ar?'تجميد الصلاحية':'Freeze access'):(ar?'إعادة الصلاحية':'Restore access')} onClick={()=>void toggle(g)}>{g.status==='ACTIVE'?<Pause className="w-4 h-4"/>:<Play className="w-4 h-4"/>}</IconButton>{g.status==='ACTIVE'&&<IconButton title={ar?'إصدار QR جديد':'Reissue QR'} onClick={()=>void reissue(g)}><QrCode className="w-4 h-4"/></IconButton>}<IconButton title={ar?'إغلاق جلسات هذه الصلاحية':'Revoke scoped sessions'} onClick={()=>void revoke(g)}><Laptop2 className="w-4 h-4"/></IconButton><IconButton danger title={ar?'حذف هذه الصلاحية':'Remove this grant'} onClick={()=>setDeleteTarget({account:a,grant:g})}><Trash2 className="w-4 h-4"/></IconButton></>}</div>)}</div></div>)}{!accounts.length&&<div className="py-8 text-center text-xs text-[#696f6b]">{loading?(ar?'جارٍ تحميل الصلاحيات…':'Loading grants…'):(ar?'لا يوجد مستخدمون أو صلاحيات في هذا النطاق بعد.':'No users or grants exist in this scope yet.')}</div>}</div>
  </div>}

  {tab==='invite'&&<div className="mt-4 space-y-3">
   <div className="rounded-2xl border border-[#d7e1dc] bg-[#f7faf8] p-4"><div className="flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-[#2F6555] shrink-0 mt-0.5"/><div><div className="text-sm font-black">{ar?'من يحصل على حساب إداري؟':'Who gets an administrative account?'}</div><p className="text-[11px] leading-6 text-[#5d645f] mt-1">{ar?'هنا تُنشأ حسابات فريق التشغيل والتحكيم فقط. المتسابق وولي الأمر لا يُمنحان حسابًا أو كلمة مرور؛ دخولهما من رابط/QR الرحلة الآمن. ودور دعم ميزان لا ينشئه مدير الجهة، بل مدير المنصة فقط.':'Only judging and operations staff are provisioned here. Participants and guardians use their secure journey link/QR with no account or password. MIZAN support is provisioned only by the platform owner.'}</p></div></div></div>
   <div className="rounded-2xl border border-[#dfddd6] p-4"><div className="flex items-center gap-2"><UserPlus className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'إضافة مستخدم':'Invite user'}</div></div><div className="grid sm:grid-cols-2 gap-2 mt-4"><input disabled={identityProvisioningLocked} autoFocus lang={ar?'ar':'en'} data-mizan-kind={ar?'arabic':'latin'} value={name} onChange={e=>setName(e.target.value)} className="mizan-input disabled:opacity-50" placeholder={ar?'الاسم الحقيقي':'Legal/display name'}/><input disabled={identityProvisioningLocked} type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)} className="mizan-input disabled:opacity-50" placeholder="name@example.com"/><select disabled={identityProvisioningLocked} value={role} onChange={e=>setRole(e.target.value as Role|'')} className="mizan-input sm:col-span-2 disabled:opacity-50"><option value="" disabled>{ar?'اختر الدور':'Choose role'}</option>{effectiveRoles.map(r=><option key={r} value={r}>{ar?arRole(r):r.replaceAll('_',' ')}</option>)}</select></div><Button className="mt-3" disabled={identityProvisioningLocked||!isEmail(email)||!name.trim()||!role||(competitionClosed&&role!=='auditor')} onClick={()=>void create()} icon={<KeyRound className="w-4 h-4"/>}>{ar?'إنشاء QR التفعيل':'Create activation QR'}</Button>{oneTimeToken&&<div className="mt-4 rounded-2xl border border-[#d9e4de] bg-[#F7FAF8] p-4"><div className="flex items-center gap-2 text-[#214C40]"><QrCode className="w-4 h-4"/><div className="text-xs font-black">{ar?'QR تفعيل — لمرة واحدة':'ONE-TIME ACTIVATION QR'}</div></div><div className="mt-4 flex justify-center"><div className="rounded-2xl bg-white p-3 border"><RealQRCode value={qrValue} size={184}/></div></div><button onClick={()=>void copy()} className="mt-3 mx-auto min-h-11 px-3 rounded-xl flex items-center gap-2 text-xs font-bold text-[#214C40]"><Copy className="w-4 h-4"/>{ar?'نسخ رابط احتياطي':'Copy fallback link'}</button></div>}</div>
  </div>}

  {tab==='sessions'&&<div className="mt-4 rounded-2xl border border-[#dfddd6] overflow-hidden"><div className="px-4 py-3 bg-[#faf9f5] border-b border-[#e5e3dc]"><div className="flex items-center gap-2"><Laptop2 className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'الجلسات النشطة الآن':'Active sessions now'}</div></div><p className="text-[10px] leading-5 text-[#656b66] mt-1">{ar?'عرض تشغيلي مباشر للأجهزة التي ما زالت تملك جلسة فعالة في هذا النطاق. إغلاق الجلسة يقطع الوصول فورًا من الخادم.':'Live operational view of devices with an active session in this scope. Revoking a session cuts server access immediately.'}</p></div><div className="divide-y divide-[#e5e3dc]">{activeSessions.map((x:any)=>{const a=accountForSession(x),g=grantForSession(x);return <div key={x.id} className="p-4 flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1 min-w-0"><div className="text-xs font-black">{a?.displayName||x.uid}</div><div className="text-[10px] text-[#656b66] mt-1" dir="ltr">{x.deviceName||x.deviceId}</div><div className="mt-2 flex flex-wrap gap-2"><Badge variant="emerald">{ar?arRole(x.role):String(x.role||'').replaceAll('_',' ')}</Badge><Badge variant="neutral">{x.authenticationAssurance==='MFA'?(ar?'تحقق متعدد':'MFA'):(ar?'تحقق أحادي':'Single factor')}</Badge></div></div><div className="text-[10px] text-[#656b66] sm:text-end"><div>{ar?'آخر نشاط':'Last seen'}</div><div dir="ltr" className="font-mono mt-1">{String(x.lastSeenAt||'—').replace('T',' ').slice(0,19)}</div></div>{g&&<IconButton title={ar?'إغلاق جلسات هذه الصلاحية':'Revoke scoped sessions'} onClick={()=>void revoke(g)}><Laptop2 className="w-4 h-4"/></IconButton>}</div>})}{!activeSessions.length&&<div className="py-10 text-center text-xs text-[#696f6b]">{ar?'لا توجد جلسات نشطة في هذا النطاق.':'No active sessions in this scope.'}</div>}</div></div>}

  <div className="mt-4 rounded-2xl border border-[#dfddd6] overflow-hidden"><button type="button" onClick={()=>setInvitesOpen(v=>!v)} aria-expanded={invitesOpen} className="w-full min-h-12 px-4 flex items-center justify-between gap-3 text-start bg-[#faf9f5] hover:bg-[#f4f2ec]"><div><div className="text-xs font-black">{ar?'دعوات التفعيل':'Activation invites'} <span className="text-[#6a706c]">({invitations.length})</span></div><div className="text-[10px] text-[#6a706c] mt-1">{ar?'مغلقة افتراضيًا حتى لا تزحم إدارة الصلاحيات.':'Collapsed by default to keep access management clean.'}</div></div><ChevronDown className={`w-4 h-4 transition ${invitesOpen?'rotate-180':''}`}/></button>{invitesOpen&&<div className="px-4 divide-y divide-[#e5e3dc]">{invitations.slice(0,20).map((i:any)=><div key={i.id} className="py-3 flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-xs font-black">{i.displayName}</div><div className="text-[10px] text-[#656b66] break-all" dir="ltr">{i.email}</div></div><Badge variant={i.status==='READY'?'emerald':i.status==='EXPIRED'?'amber':'neutral'}>{i.status==='READY'?(ar?'جاهزة':'Ready'):i.status==='ACTIVATED'?(ar?'فُعّلت':'Activated'):i.status==='EXPIRED'?(ar?'منتهية':'Expired'):(ar?'قديمة':'Legacy')}</Badge></div>)}{!invitations.length&&<div className="py-8 text-center text-xs text-[#696f6b]">{ar?'لا توجد دعوات.':'No invitations.'}</div>}</div>}</div>

  <Modal isOpen={!!deleteTarget} onClose={()=>setDeleteTarget(null)} title={ar?'إلغاء الصلاحية':'Remove grant'}><p className="text-sm text-[#565d59] leading-7">{ar?'سيُلغى هذا الدور في هذا النطاق فقط. لن تُمس أي صلاحية للمستخدم في مسابقة أخرى.':'Only this scoped role will be removed; other competition grants stay untouched.'}</p><div className="mt-5 flex gap-2 justify-end"><Button variant="ghost" onClick={()=>setDeleteTarget(null)}>{ar?'تراجع':'Cancel'}</Button><Button disabled={deleting} onClick={()=>void remove()} icon={<Trash2 className="w-4 h-4"/>}>{deleting?'…':(ar?'إلغاء الصلاحية':'Remove')}</Button></div></Modal>
 </section>;
};

const IconButton=({title,onClick,children,danger=false}:{title:string;onClick:()=>void;children:React.ReactNode;danger?:boolean})=><button type="button" title={title} aria-label={title} onClick={onClick} className={`w-11 h-11 rounded-xl border grid place-items-center ${danger?'text-[#94564d] border-[#ead9d5] hover:bg-[#f7ece9]':'text-[#214C40] border-[#d9dfdb] hover:bg-white'}`}>{children}</button>;
const Mini=({n,t}:{n:number;t:string})=><div className="rounded-xl bg-[#f3f1eb] p-3 text-center"><div className="text-lg font-black">{n}</div><div className="text-[10px] text-[#656b66]">{t}</div></div>;
