import React,{useEffect,useMemo,useState} from 'react';
import {KeyRound,ShieldCheck,UserPlus,Laptop2,RefreshCcw,Trash2,QrCode,Copy,Pause,Play,RotateCcw} from 'lucide-react';
import {useAppStore} from '../../lib/store';import {auth} from '../../lib/firebase';import {Button} from '../design-system/Button';import {Badge} from '../design-system/Badge';import {Modal} from '../design-system/Modal';import {RealQRCode} from '../design-system/RealQRCode';import type {Role} from '../../types';import {isEmail,normalizeEmail,normalizeSpaces} from '../../lib/input-validation';
const ORG_STAFF:Role[]=['comp_admin','head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator','auditor','guardian','support_agent'];const COMP_STAFF:Role[]=['head_judge','judge','ops_manager','exception_host','delegation_manager','broadcast_operator','guardian'];const OWNER_STAFF:Role[]=['org_admin','support_agent'];
const arRole=(r:Role)=>({super_admin:'مدير المنصة',org_admin:'مدير الجهة',comp_admin:'مدير المسابقة',head_judge:'رئيس التحكيم',judge:'محكم',ops_manager:'مدير التشغيل',exception_host:'مكتب الاستثناء',delegation_manager:'مسؤول وفد',participant:'متسابق',broadcast_operator:'مشغل الحفل',auditor:'مدقق',guardian:'ولي أمر',support_agent:'دعم'} as Partial<Record<Role,string>>)[r]||r;
type RemoteData={accounts:any[];grants:any[];invitations:any[];sessions:any[]};
export const activationQrValue=(token:string,origin?:string)=>{const base=(origin||window.location.origin).replace(/\/$/,'');const link=`${base}/#a=${encodeURIComponent(token)}`;return new TextEncoder().encode(link).length<=78?link:`MZI1|${token}`};
export const IdentityGovernance:React.FC<{competitionId?:string;organizationId?:string}>=({competitionId,organizationId})=>{
 const s=useAppStore();const ar=s.language==='ar';const production=import.meta.env.VITE_REQUIRE_AUTH==='true';const competitionScoped=Boolean(competitionId);const scopeOrgId=organizationId||s.organization.id;
 const [email,setEmail]=useState('');const [name,setName]=useState('');const [role,setRole]=useState<Role|''>('');const [message,setMessage]=useState('');const [oneTimeToken,setOneTimeToken]=useState('');const [remote,setRemote]=useState<RemoteData|null>(null);const [loading,setLoading]=useState(false);const [deleteTarget,setDeleteTarget]=useState<{account:any;grant:any}|null>(null);const [deleting,setDeleting]=useState(false);
 const availableRoles=useMemo<Role[]>(()=>s.currentUser.role==='super_admin'?OWNER_STAFF:s.currentUser.role==='comp_admin'?COMP_STAFF:ORG_STAFF,[s.currentUser.role]);
 const api=async(path:string,init:RequestInit={})=>{const u=auth.currentUser;if(!u)throw new Error('IDENTITY_REQUIRED');const token=await u.getIdToken();return fetch(path,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(init.headers||{})}})};
 const loadRemote=async()=>{if(!production)return;setLoading(true);try{const params=new URLSearchParams();if(s.currentUser.role==='super_admin')params.set('organizationId',scopeOrgId);if(competitionId)params.set('competitionId',competitionId);const r=await api(`/api/identity/governance${params.size?`?${params}`:''}`);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(body.code||'IDENTITY_GOVERNANCE_UNAVAILABLE'));setRemote(body)}catch(e){setMessage(e instanceof Error?e.message:(ar?'تعذر تحميل الصلاحيات.':'Could not load access.'));setRemote(null)}finally{setLoading(false)}};
 useEffect(()=>{void loadRemote()},[production,scopeOrgId,competitionId]);
 const devGrants=useMemo(()=>s.roleGrants.filter(g=>g.organizationId===scopeOrgId&&['ACTIVE','SUSPENDED'].includes(g.status)&&(!competitionId||g.competitionId===competitionId)),[s.roleGrants,scopeOrgId,competitionId]);const ids=useMemo(()=>new Set(devGrants.map(g=>g.accountId)),[devGrants]);const devAccounts=useMemo(()=>s.identityAccounts.filter(a=>a.organizationId===scopeOrgId&&ids.has(a.id)&&!s.roleGrants.some(g=>g.accountId===a.id&&g.role==='super_admin'&&g.status==='ACTIVE')),[s.identityAccounts,s.roleGrants,scopeOrgId,ids]);
 const accounts=production?(remote?.accounts||[]):devAccounts;const grants=production?(remote?.grants||[]):devGrants;const invitations=production?(remote?.invitations||[]):s.identityInvitations.filter(i=>i.organizationId===scopeOrgId&&i.status!=='REVOKED'&&(!competitionId||i.competitionId===competitionId));const sessions=production?(remote?.sessions||[]):s.authSessions.filter(x=>x.organizationId===scopeOrgId&&(!competitionId||(x as any).competitionId===competitionId));
 const qrValue=oneTimeToken?activationQrValue(oneTimeToken):'';
 const create=async()=>{setMessage('');setOneTimeToken('');const cleanEmail=normalizeEmail(email),cleanName=normalizeSpaces(name);if(!role||!isEmail(cleanEmail)||!cleanName)return setMessage(ar?'تحقق من الاسم والبريد والدور.':'Check name, email and role.');if(production){try{if(s.currentUser.role!=='super_admin'&&!competitionId)return setMessage('COMPETITION_SCOPE_REQUIRED');const r=await api('/api/identity/invitations',{method:'POST',body:JSON.stringify({email:cleanEmail,displayName:cleanName,requestedRole:role,organizationId:s.currentUser.role==='super_admin'?scopeOrgId:undefined,competitionId:s.currentUser.role==='super_admin'?undefined:competitionId,reason:'Authorized scoped role provisioning'})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.code||'INVITATION_FAILED'));setEmail('');setName('');setRole('');if(body.activationToken)setOneTimeToken(body.activationToken);setMessage(ar?'الدعوة جاهزة. سلّم QR للشخص المعني فقط.':'Invitation ready. Share the QR only with the intended person.');await loadRemote()}catch{setMessage('IDENTITY_SERVER_UNAVAILABLE')}return}if(!competitionId)return setMessage('COMPETITION_SCOPE_REQUIRED');const r=await s.createIdentityInvitation({email:cleanEmail,displayName:cleanName,requestedRole:role,competitionId,reason:'Authorized competition role provisioning'});if(!r.ok)return setMessage(r.reason);if(r.activationToken)setOneTimeToken(r.activationToken)};
 const grantsFor=(account:any)=>grants.filter((g:any)=>g.accountId===account.id&&['ACTIVE','SUSPENDED'].includes(g.status));
 const toggle=async(grant:any)=>{if(!production)return;const resume=grant.status==='SUSPENDED';const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/${resume?'resume':'suspend'}`,{method:'POST',body:JSON.stringify({reason:resume?'Authorized competition access restored':'Authorized competition access frozen'})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(resume?(ar?'أُعيدت الصلاحية لهذه المسابقة.':'Competition access restored.'):(ar?'جُمّدت الصلاحية لهذه المسابقة وأُغلقت جلساتها.':'Competition access frozen and its sessions closed.')):String(body.code||'ACCESS_CHANGE_FAILED'));await loadRemote()};
 const revoke=async(grant:any)=>{if(!production)return;const r=await api(`/api/identity/grants/${encodeURIComponent(grant.id)}/revoke-sessions`,{method:'POST',body:JSON.stringify({reason:'Secure session handover'})});const body=await r.json().catch(()=>({}));setMessage(r.ok?(ar?`أُغلقت ${body.count||0} جلسة.`:`${body.count||0} session(s) revoked.`):String(body.code||'SESSION_REVOKE_FAILED'));await loadRemote()};
 const remove=async()=>{if(!deleteTarget||!production)return;setDeleting(true);try{const r=await api(`/api/identity/grants/${encodeURIComponent(deleteTarget.grant.id)}`,{method:'DELETE',body:JSON.stringify({reason:'Scoped access removed by authorized administrator'})});const body=await r.json().catch(()=>({}));if(!r.ok)return setMessage(String(body.code||'REMOVE_FAILED'));setMessage(ar?'أُلغيت هذه الصلاحية فقط، وبقيت بقية صلاحيات المستخدم كما هي.':'Only this grant was removed; the user’s other grants are unchanged.');setDeleteTarget(null);await loadRemote()}finally{setDeleting(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(qrValue);setMessage(ar?'تم نسخ رابط/رمز التفعيل.':'Activation link copied.')}catch{setMessage(ar?'تعذر النسخ؛ استخدم QR.':'Copy failed; use the QR.')}};
 return <section className="mizan-surface p-5 sm:p-6">
  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><div className="mizan-kicker">{ar?'الهوية والصلاحيات':'IDENTITY & ACCESS'}</div><h2 className="text-xl font-black mt-1">{competitionScoped?(ar?'فريق هذه المسابقة فقط':'This competition team only'):(ar?'مستخدمو هذه الجهة':'Organization users')}</h2><p className="text-xs leading-6 text-[#636864] mt-2 max-w-2xl">{competitionScoped?(ar?'أي صلاحية هنا تخص هذه المسابقة وحدها. التجميد والحذف لا يمسان مسابقات أخرى.':'Every grant here belongs only to this competition. Freeze/remove never touches another competition.'):(ar?'الحسابات والدعوات المرتبطة بهذه الجهة تظهر هنا. موظفو كل مسابقة يديرهم مدير الجهة من المسابقة نفسها.':'Accounts and invitations for this organization appear here. Competition staff are managed by the organization from each competition.')}</p></div><div className="grid grid-cols-3 gap-2 min-w-64"><Mini n={grants.filter((g:any)=>g.status==='ACTIVE').length} t={ar?'صلاحيات':'Grants'}/><Mini n={invitations.filter((i:any)=>i.status==='READY').length} t={ar?'دعوات':'Invites'}/><Mini n={sessions.filter((x:any)=>x.status==='ACTIVE').length} t={ar?'جلسات':'Sessions'}/></div></div>
  <div className="mt-5 rounded-2xl border border-[#dfddd6] p-4"><div className="flex items-center gap-2"><UserPlus className="w-4 h-4 text-[#2F6555]"/><div className="text-sm font-black">{ar?'إضافة مستخدم':'Invite user'}</div></div><div className="grid sm:grid-cols-2 gap-2 mt-4"><input lang={ar?'ar':'en'} data-mizan-kind={ar?'arabic':'latin'} value={name} onChange={e=>setName(e.target.value)} className="mizan-input" placeholder={ar?'الاسم الحقيقي':'Legal/display name'}/><input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)} className="mizan-input" placeholder="name@example.com"/><select value={role} onChange={e=>setRole(e.target.value as Role|'')} className="mizan-input sm:col-span-2"><option value="" disabled>{ar?'اختر الدور':'Choose role'}</option>{availableRoles.map(r=><option key={r} value={r}>{ar?arRole(r):r.replaceAll('_',' ')}</option>)}</select></div><Button className="mt-3" disabled={!isEmail(email)||!name.trim()||!role} onClick={()=>void create()} icon={<KeyRound className="w-4 h-4"/>}>{ar?'إنشاء QR التفعيل':'Create activation QR'}</Button>{message&&<div className="mt-3 rounded-xl bg-[#f3f1eb] p-3 text-xs font-bold break-words">{message}</div>}
  {oneTimeToken&&<div className="mt-4 rounded-2xl border border-[#d9e4de] bg-[#F7FAF8] p-4"><div className="flex items-center gap-2 text-[#214C40]"><QrCode className="w-4 h-4"/><div className="text-xs font-black">{ar?'QR تفعيل — لمرة واحدة':'ONE-TIME ACTIVATION QR'}</div></div><div className="mt-4 flex justify-center"><div className="rounded-2xl bg-white p-3 border"><RealQRCode value={qrValue} size={184}/></div></div><button onClick={()=>void copy()} className="mt-3 mx-auto min-h-11 px-3 rounded-xl flex items-center gap-2 text-xs font-bold text-[#214C40]"><Copy className="w-4 h-4"/>{ar?'نسخ رابط احتياطي':'Copy fallback link'}</button></div>}</div>
  <div className="mt-5"><div className="text-sm font-black">{ar?'المستخدمون والصلاحيات':'Users & grants'}</div><div className="mt-3 divide-y divide-[#e5e3dc]">{accounts.map((a:any)=><div key={a.id} className="py-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black text-sm">{a.displayName}</div><div dir="ltr" className="text-[11px] text-[#656b66] break-all">{a.email}</div></div><Badge variant={a.status==='ACTIVE'?'emerald':'neutral'}>{a.status==='ACTIVE'?(ar?'حساب نشط':'Active'):(ar?'حساب موقوف':'Suspended')}</Badge></div><div className="mt-3 space-y-2">{grantsFor(a).map((g:any)=><div key={g.id} className="rounded-xl bg-[#f7f5ef] p-3 flex flex-wrap items-center gap-2"><div className="flex-1 min-w-[180px]"><div className="text-xs font-black">{ar?arRole(g.role):g.role.replaceAll('_',' ')}</div><div className="text-[10px] text-[#656b66] mt-1">{g.competitionId?(ar?`مسابقة: ${g.competitionId}`:`Competition: ${g.competitionId}`):(ar?'صلاحية على مستوى الجهة':'Organization-level grant')}</div></div><Badge variant={g.status==='ACTIVE'?'emerald':'amber'}>{g.status==='ACTIVE'?(ar?'نشطة':'Active'):(ar?'مجمّدة':'Frozen')}</Badge><IconButton title={g.status==='ACTIVE'?(ar?'تجميد الصلاحية':'Freeze access'):(ar?'إعادة الصلاحية':'Restore access')} onClick={()=>void toggle(g)}>{g.status==='ACTIVE'?<Pause className="w-4 h-4"/>:<Play className="w-4 h-4"/>}</IconButton><IconButton title={ar?'إغلاق جلسات هذه الصلاحية':'Revoke scoped sessions'} onClick={()=>void revoke(g)}><Laptop2 className="w-4 h-4"/></IconButton><IconButton danger title={ar?'حذف هذه الصلاحية':'Remove this grant'} onClick={()=>setDeleteTarget({account:a,grant:g})}><Trash2 className="w-4 h-4"/></IconButton></div>)}</div></div>)}{!accounts.length&&<div className="py-8 text-center text-xs text-[#696f6b]">{ar?'لا يوجد مستخدمون في هذا النطاق بعد.':'No users in this scope yet.'}</div>}</div></div>
  <div className="mt-5"><div className="text-sm font-black">{ar?'دعوات التفعيل':'Activation invitations'}</div><div className="mt-3 divide-y divide-[#e5e3dc]">{invitations.slice(0,12).map((i:any)=><div key={i.id} className="py-3 flex items-center justify-between gap-3"><div className="min-w-0"><div className="text-xs font-black">{i.displayName}</div><div className="text-[10px] text-[#656b66] break-all" dir="ltr">{i.email}</div></div><Badge variant={i.status==='READY'?'emerald':i.status==='EXPIRED'?'amber':'neutral'}>{i.status==='READY'?(ar?'جاهزة':'Ready'):i.status==='ACTIVATED'?(ar?'فُعّلت':'Activated'):i.status==='EXPIRED'?(ar?'منتهية':'Expired'):(ar?'قديمة':'Legacy')}</Badge></div>)}{!invitations.length&&<div className="py-6 text-center text-xs text-[#696f6b]">{ar?'لا توجد دعوات معلقة.':'No invitations.'}</div>}</div></div>
  <Modal open={!!deleteTarget} onClose={()=>setDeleteTarget(null)} title={ar?'إلغاء الصلاحية':'Remove grant'}><p className="text-sm text-[#565d59] leading-7">{ar?'سيُلغى هذا الدور في هذا النطاق فقط. لن تُمس أي صلاحية للمستخدم في مسابقة أخرى.':'Only this scoped role will be removed; other competition grants stay untouched.'}</p><div className="mt-5 flex gap-2 justify-end"><Button variant="ghost" onClick={()=>setDeleteTarget(null)}>{ar?'تراجع':'Cancel'}</Button><Button disabled={deleting} onClick={()=>void remove()} icon={<Trash2 className="w-4 h-4"/>}>{deleting?'…':(ar?'إلغاء الصلاحية':'Remove')}</Button></div></Modal>
 </section>;
};
const IconButton=({title,onClick,children,danger=false}:{title:string;onClick:()=>void;children:React.ReactNode;danger?:boolean})=><button type="button" title={title} aria-label={title} onClick={onClick} className={`w-11 h-11 rounded-xl border grid place-items-center ${danger?'text-[#94564d] border-[#ead9d5] hover:bg-[#f7ece9]':'text-[#214C40] border-[#d9dfdb] hover:bg-white'}`}>{children}</button>;
const Mini=({n,t}:{n:number;t:string})=><div className="rounded-xl bg-[#f3f1eb] p-3 text-center"><div className="text-lg font-black">{n}</div><div className="text-[10px] text-[#656b66]">{t}</div></div>;
