import React,{useMemo,useState} from 'react';
import {DatabaseBackup,Fingerprint,MapPin,Network,Play,Radar,ScanLine,ShieldCheck,UsersRound} from 'lucide-react';
import {useAppStore} from '../../lib/store';
import {Badge} from '../design-system/Badge';
import {Button} from '../design-system/Button';
import {attestWitnessAction,createWitnessAction,fetchCustodyCorridor,fetchExposureRadius,fetchIntegrityRuntimeCapabilities,traceExposureCanary} from '../../lib/integrity-server-client';
import type {ExposureRadiusSnapshot,QuestionCustodyCorridorSnapshot,WitnessModeRecord} from '../../types';

type Capability='focus'|'corridor'|'witness'|'radius'|'vault'|'cinema'|'venue'|'canary';
const ITEMS:{id:Capability;icon:any;ar:string;en:string}[]=[
 {id:'focus',icon:ScanLine,ar:'عدسة موضع المصحف',en:'Mushaf Focus Lens'},
 {id:'corridor',icon:Network,ar:'ممر السؤال الصامت',en:'Zero-Knowledge Corridor'},
 {id:'witness',icon:UsersRound,ar:'الشاهد الرقمي',en:'Witness Mode'},
 {id:'radius',icon:Radar,ar:'نطاق كشف السؤال',en:'Exposure Radius'},
 {id:'vault',icon:DatabaseBackup,ar:'خزنة الطوارئ الباردة',en:'Cold Vault'},
 {id:'cinema',icon:Play,ar:'فيلم النزاهة',en:'Integrity Cinema'},
 {id:'venue',icon:MapPin,ar:'اعتماد القاعة',en:'MIZAN Certified Venue'},
 {id:'canary',icon:Fingerprint,ar:'بصمة كشف التسريب',en:'Leakage Canary'},
];

export const IntegrityExperienceLab:React.FC=()=>{
 const s=useAppStore(),ar=s.language==='ar';
 const [selected,setSelected]=useState<Capability>('corridor');
 const current=ITEMS.find(x=>x.id===selected)!;const Icon=current.icon;
 return <section className="mt-6 rounded-[30px] border border-[#ddd9cf] bg-[#f8f6ef] p-4 sm:p-5">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4">
   <div><div className="mizan-kicker">{ar?'النزاهة الحية':'LIVE INTEGRITY'}</div><h3 className="text-lg sm:text-xl font-black mt-1">{ar?'النزاهة التي يمكن رؤيتها دون كشف السر':'Visible integrity without exposing the secret'}</h3><p className="text-[10px] leading-5 text-[#737b76] max-w-2xl mt-1">{ar?'ثماني طبقات تعمل حول التحكيم ولا تزاحم المحكم. تظهر فقط الدليل أو الاستثناء الذي يحتاج قرارًا.':'Eight layers work around judging without crowding JudgeOS. Only evidence or an exception requiring action is surfaced.'}</p></div>
   <Badge variant="emerald">{ar?'8 قدرات مترابطة':'8 CONNECTED CAPABILITIES'}</Badge>
  </div>
  <div className="mt-4 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-2">{ITEMS.map(x=>{const X=x.icon;const active=x.id===selected;return <button key={x.id} onClick={()=>setSelected(x.id)} className={`min-h-[82px] rounded-2xl border p-3 text-start transition ${active?'bg-[#202924] text-white border-[#202924]':'bg-[#fffdf8] border-[#dfdcd3] hover:border-[#aeb9b2]'}`}><X className="w-4 h-4"/><div className="text-[9px] font-black leading-4 mt-2">{ar?x.ar:x.en}</div></button>})}</div>
  <div className="mt-4 rounded-[24px] bg-[#fffdf9] border border-[#dfdcd3] p-4 sm:p-5"><div className="flex items-center gap-3 mb-4"><span className="w-10 h-10 rounded-xl bg-[#e7eee9] text-[#214c40] grid place-items-center"><Icon className="w-5 h-5"/></span><div><div className="text-sm font-black">{ar?current.ar:current.en}</div><div className="text-[9px] text-[#858a86]">{ar?'حالة واحدة · دليل واحد · فعل عند الحاجة':'One state · one proof · action only when needed'}</div></div></div><Detail capability={selected}/></div>
 </section>
}

const Detail=({capability}:{capability:Capability})=>{
 switch(capability){case'focus':return <Focus/>;case'corridor':return <Corridor/>;case'witness':return <Witness/>;case'radius':return <Radius/>;case'vault':return <Vault/>;case'cinema':return <Cinema/>;case'venue':return <Venue/>;case'canary':return <Canary/>}
}
const Empty=({ar,en}:{ar:string;en:string})=>{const s=useAppStore();return <div className="text-xs text-[#737a76] py-2">{s.language==='ar'?ar:en}</div>}

const Focus=()=>{const s=useAppStore(),ar=s.language==='ar';const q=s.activeSession.questionSelection?.questions?.[s.activeSession.currentQuestionIndex] as any;return <div className="grid md:grid-cols-[1fr_auto] gap-3 items-center"><div><div className="text-xs font-black">{ar?'المؤشر لا يلمس حروف القرآن':'The indicator never modifies Quran glyphs'}</div><div className="text-[10px] leading-5 text-[#747b76] mt-1">{ar?'على صفحة المصحف الرسمية يظهر خط جانبي رقيق بمحاذاة سطور الموضع فقط. وإذا لم تتوفر الصفحة الأصلية يعرض ميزان النص العثماني الرسمي دون تقليد بصري مزيف.':'On an official Mushaf page, a restrained side marker aligns to the passage lines only. Without the original page asset, MIZAN shows official Uthmani text and never fabricates a Mushaf-like page.'}</div></div><Badge variant={q?'emerald':'neutral'}>{q?(ar?'فعال أثناء السؤال':'ACTIVE IN JUDGEOS'):(ar?'يظهر مع السؤال':'QUESTION-BOUND')}</Badge></div>}

const Corridor=()=>{const s=useAppStore(),ar=s.language==='ar';const id=s.activeSession.secureRuntimeSessionId;const [data,setData]=useState<QuestionCustodyCorridorSnapshot|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');const load=async()=>{if(!id)return;setBusy(true);try{setData(await fetchCustodyCorridor(id));setErr('')}catch(e){setErr(e instanceof Error?e.message:'UNAVAILABLE')}finally{setBusy(false)}};if(!id)return <Empty ar="لا توجد جلسة سؤال خادمية نشطة الآن. عند بدء جلسة Production سيظهر الممر دون نص السؤال." en="No secure server question session is active. The corridor appears during a production session without question plaintext."/>;return <div><div className="flex items-center justify-between gap-3"><div className="text-xs font-black">{ar?'عمليات التشغيل ترى الحالة فقط — لا ترى السؤال':'Operations see custody state — never the question'}</div><Button size="sm" variant="outline" loading={busy} onClick={load}>{ar?'تحديث':'Refresh'}</Button></div>{err&&<div className="text-[10px] text-[#A34D43] mt-2">{err}</div>}{data&&<div className="mt-3 flex gap-2 overflow-x-auto">{data.questions.map(q=><div key={q.questionIndex} className="min-w-36 rounded-2xl border border-[#dfdcd3] bg-[#fbfaf6] p-3"><div className="text-[9px] text-[#858a86]">{ar?`الموضع ${q.questionIndex+1}`:`Passage ${q.questionIndex+1}`}</div><div className="text-xs font-black mt-1">{q.state}</div><div className="text-[9px] mt-2 text-[#747b76]">{q.approved}/{q.required} {ar?'موافقات':'approvals'} · {q.exposureCount} {ar?'كشف':'reveals'}</div></div>)}</div>}<div className="text-[9px] text-[#8b908c] mt-2">{ar?'نص السؤال: غير متاح للتشغيل':'PLAINTEXT INCLUDED: NO'}</div></div>}

const Witness=()=>{const s=useAppStore(),ar=s.language==='ar';const target=s.activeSession.secureRuntimeSessionId;const [record,setRecord]=useState<WitnessModeRecord|null>(null),[reason,setReason]=useState(ar?'تبديل سؤال طارئ بعد واقعة مادية موثقة':'Emergency question replacement after a witnessed physical event'),[busy,setBusy]=useState(false),[err,setErr]=useState('');const create=async()=>{if(!target)return;setBusy(true);try{setRecord(await createWitnessAction({actionType:'QUESTION_REPLACEMENT',targetRef:`question-replacement:${target}`,reason,requiredWitnesses:2}));setErr('')}catch(e){setErr(e instanceof Error?e.message:'UNAVAILABLE')}finally{setBusy(false)}};const attest=async()=>{if(!record)return;setBusy(true);try{setRecord(await attestWitnessAction(record.id));setErr('')}catch(e){setErr(e instanceof Error?e.message:'UNAVAILABLE')}finally{setBusy(false)}};return <div><div className="grid md:grid-cols-[1fr_auto] gap-2"><input value={reason} onChange={e=>setReason(e.target.value)} className="rounded-xl border border-[#ddd9cf] bg-white px-3 py-2.5 text-xs outline-none"/><Button size="sm" loading={busy} disabled={!target||reason.trim().length<8} onClick={create}>{ar?'فتح واقعة للشهود':'Open witnessed action'}</Button></div>{!target&&<div className="text-[10px] text-[#8b908c] mt-2">{ar?'يحتاج جلسة سؤال خادمية نشطة.':'Requires an active secure question session.'}</div>}{err&&<div className="text-[10px] text-[#A34D43] mt-2">{err}</div>}{record&&<div className="mt-3 flex flex-wrap items-center gap-3"><Badge variant={record.state==='READY'?'emerald':'amber'}>{record.state}</Badge><span className="text-xs font-black">{record.attestations.length}/{record.requiredWitnesses}</span><span className="text-[9px] font-mono text-[#7a817d]">{record.commitmentHash.slice(0,24)}…</span><Button size="sm" variant="outline" loading={busy} onClick={attest}>{ar?'إثبات كشاهد':'Attest as witness'}</Button></div>}</div>}

const Radius=()=>{const s=useAppStore(),ar=s.language==='ar';const id=s.activeSession.secureRuntimeSessionId;const [data,setData]=useState<ExposureRadiusSnapshot|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');const load=async()=>{if(!id)return;setBusy(true);try{setData(await fetchExposureRadius(id));setErr('')}catch(e){setErr(e instanceof Error?e.message:'UNAVAILABLE')}finally{setBusy(false)}};return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div>{data?<><div className={`text-3xl font-black ${data.withinConfiguredRadius?'text-[#214c40]':'text-[#A34D43]'}`}>{data.uniqueExposedRecipients}<span className="text-base text-[#919692]"> / {data.allowedRecipientCount}</span></div><div className="text-[10px] text-[#747b76] mt-1">{data.withinConfiguredRadius?(ar?'وصل النص فقط إلى المستلمين المصرح لهم':'Plaintext stayed within authorized recipients'):(ar?`مستلمون غير متوقعين: ${data.unexpectedRecipientCount}`:`Unexpected recipients: ${data.unexpectedRecipientCount}`)}</div></>:<div className="text-xs font-black">{ar?'كم جهازًا استلم السؤال فعلًا؟':'How many recipients actually received plaintext?'}</div>}{err&&<div className="text-[10px] text-[#A34D43] mt-1">{err}</div>}</div><Button size="sm" variant="outline" disabled={!id} loading={busy} onClick={load}>{ar?'قياس النطاق':'Measure radius'}</Button></div>}

const Vault=()=>{const s=useAppStore(),ar=s.language==='ar';const [ready,setReady]=useState<boolean|null>(null),[busy,setBusy]=useState(false);const check=async()=>{setBusy(true);try{const c=await fetchIntegrityRuntimeCapabilities();setReady(Boolean(c.coldVault))}finally{setBusy(false)}};return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="text-xs font-black">{ar?'حزمة Edge مشفرة — مفاتيح خاصة ممنوعة':'Encrypted Edge package — private keys are forbidden'}</div><div className="text-[10px] text-[#747b76] mt-1">{ar?'تُصدّر من مسار Enterprise المصرح فقط. فحص الحزمة يرفض secret/password/token/master key قبل الإنشاء.':'Export is an authorized Enterprise action. The package builder rejects secret/password/token/master-key material before creation.'}</div>{ready!==null&&<div className="mt-2"><Badge variant={ready?'emerald':'amber'}>{ready?(ar?'الخدمة مهيأة':'SERVICE READY'):(ar?'تحتاج إعداد الخادم':'SERVER SETUP REQUIRED')}</Badge></div>}</div><Button size="sm" variant="outline" loading={busy} onClick={check}>{ar?'فحص الجاهزية':'Check readiness'}</Button></div>}

const Cinema=()=>{const s=useAppStore(),ar=s.language==='ar';const latest=s.integrityCinemaRecords[0];const [busy,setBusy]=useState(false),[err,setErr]=useState('');const build=async()=>{setBusy(true);try{await s.createIntegrityCinema();setErr('')}catch(e){setErr(e instanceof Error?e.message:'FAILED')}finally{setBusy(false)}};return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div>{latest?<><div className="text-3xl font-black">{latest.sceneCount}</div><div className="text-[10px] text-[#747b76]">{ar?'مشهد دليل مرتب زمنيًا · بلا فيديو أو بيانات شخصية زائدة':'evidence scenes in order · no video or unnecessary PII'}</div><div className="text-[9px] font-mono text-[#8b908c] mt-1">{latest.cinemaHash.slice(0,30)}…</div></>:<div className="text-xs font-black">{ar?'حوّل سجل الحدث إلى فيلم أدلة زمني':'Turn the event ledger into an evidence timeline'}</div>}{err&&<div className="text-[10px] text-[#A34D43] mt-1">{err}</div>}</div><Button size="sm" loading={busy} onClick={build}>{ar?'بناء فيلم الأدلة':'Build evidence cinema'}</Button></div>}

const Venue=()=>{const s=useAppStore(),ar=s.language==='ar';const suggested=useMemo(()=>s.devices.find(x=>x.zone)?.zone||(ar?'القاعة الرئيسية':'Main Hall'),[s.devices]);const [zone,setZone]=useState(suggested),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[err,setErr]=useState('');const seal=async()=>{setBusy(true);try{setResult(await s.certifyCurrentVenue({venueZone:zone,printerReady:true}));setErr('')}catch(e){setErr(e instanceof Error?e.message:'FAILED')}finally{setBusy(false)}};const verify=async()=>{const rec=result||s.certifiedVenueSeals.find(x=>x.venueZone===zone);if(!rec)return;setBusy(true);try{const v=await s.verifyCurrentVenueSeal(rec.id,{});setResult({...rec,_verify:v});setErr('')}catch(e){setErr(e instanceof Error?e.message:'FAILED')}finally{setBusy(false)}};const current=result||s.certifiedVenueSeals.find(x=>x.venueZone===zone);return <div><div className="grid sm:grid-cols-[1fr_auto_auto] gap-2"><input value={zone} onChange={e=>setZone(e.target.value)} className="rounded-xl border border-[#ddd9cf] bg-white px-3 py-2.5 text-xs outline-none"/><Button size="sm" loading={busy} onClick={seal}>{ar?'فحص واعتماد القاعة':'Assess & seal venue'}</Button><Button size="sm" variant="outline" disabled={!current} loading={busy} onClick={verify}>{ar?'تحقق من عدم التغيير':'Verify baseline'}</Button></div>{current&&<div className="mt-3 flex flex-wrap gap-3 items-center"><Badge variant={current.status==='CERTIFIED_READY'?'emerald':current.status==='NOT_READY'?'rose':'amber'}>{current.status}</Badge><span className="text-[9px] font-mono text-[#7c837e]">{current.sealHash?.slice(0,28)}…</span>{current._verify&&<Badge variant={current._verify.valid?'emerald':'rose'}>{current._verify.valid?(ar?'لم تتغير القاعة':'BASELINE INTACT'):(ar?'تغيرت البيئة':'BASELINE CHANGED')}</Badge>}</div>}{err&&<div className="text-[10px] text-[#A34D43] mt-2">{err}</div>}</div>}

const Canary=()=>{const s=useAppStore(),ar=s.language==='ar';const [token,setToken]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');const trace=async()=>{setBusy(true);try{setResult(await traceExposureCanary(token.trim()));setErr('')}catch(e){setResult(null);setErr(e instanceof Error?e.message:'INVALID')}finally{setBusy(false)}};return <div><div className="grid md:grid-cols-[1fr_auto] gap-2"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="MZC1.…" className="rounded-xl border border-[#ddd9cf] bg-white px-3 py-2.5 text-xs font-mono outline-none"/><Button size="sm" disabled={!token.trim()} loading={busy} onClick={trace}>{ar?'تتبع البصمة':'Trace canary'}</Button></div>{result&&<div className="mt-3 flex flex-wrap gap-3 items-center"><Badge variant="emerald">{ar?'البصمة صحيحة':'VERIFIED'}</Badge><span className="text-[10px]">{ar?`السؤال ${result.questionIndex+1}`:`Q${result.questionIndex+1}`}</span><span className="text-[9px] font-mono text-[#7b827d]">{result.canaryId}</span></div>}{err&&<div className="text-[10px] text-[#A34D43] mt-2">{err}</div>}<div className="text-[9px] text-[#8b908c] mt-2">{ar?'البصمة خارج نص القرآن ولا تغيّر حرفًا أو صوتًا.':'The canary lives outside Quran content and never changes a character or recitation.'}</div></div>}
