import React,{useEffect,useMemo,useState} from 'react';
import {AudioLines,BadgeCheck,FileCheck2,Layers3,FileKey2,Fingerprint,Gavel,GitBranch,Network,ArrowRightLeft,ShieldCheck,Siren} from 'lucide-react';
import {useAppStore} from '../../lib/store';
import {fetchSecureQuestionCapabilities} from '../../lib/server-question-client';
import {Badge} from '../design-system/Badge';
import {Button} from '../design-system/Button';
import {Pictogram} from '../design-system/Pictogram';

type Feature='silent'|'blackbox'|'court'|'acoustic'|'twin'|'mutashabihat'|'routing'|'appeal'|'anchor'|'entropy'|'breaker'|'passport';
const FEATURES:{id:Feature;icon:any;ar:string;en:string}[]=[
 {id:'silent',icon:FileKey2,ar:'كبسولة السؤال الصامتة',en:'Silent Question Capsule'},
 {id:'blackbox',icon:Fingerprint,ar:'الصندوق الأسود للمسابقة',en:'Competition Black Box'},
 {id:'court',icon:Gavel,ar:'محكمة حساسية العدالة',en:'Fairness Constitutional Court'},
 {id:'acoustic',icon:AudioLines,ar:'جواز القاعة الصوتي',en:'Acoustic Venue Passport'},
 {id:'twin',icon:FileCheck2,ar:'التوأم الرقمي للتلاوة',en:'Recitation Digital Twin'},
 {id:'mutashabihat',icon:GitBranch,ar:'خريطة فخ المتشابهات',en:'Mutashabihat Trap Map'},
 {id:'routing',icon:ArrowRightLeft,ar:'التوجيه الذكي متعدد الروايات',en:'Multi-Riwayah Smart Routing'},
 {id:'appeal',icon:Layers3,ar:'كبسولة الاعتراض',en:'Appeal Capsule'},
 {id:'anchor',icon:BadgeCheck,ar:'المعايرة المرجعية العمياء',en:'Blind Anchor Calibration'},
 {id:'entropy',icon:Network,ar:'رادار أنماط النزاهة',en:'Integrity Entropy Radar'},
 {id:'breaker',icon:Siren,ar:'القاطع العلمي',en:'Scientific Circuit Breaker'},
 {id:'passport',icon:ShieldCheck,ar:'جواز نزاهة ميزان',en:'MIZAN Integrity Passport'}
];

export const IntegrityProtocolLab:React.FC=()=>{const s=useAppStore(),ar=s.language==='ar';const [feature,setFeature]=useState<Feature>('silent');const current=FEATURES.find(x=>x.id===feature)!;const Icon=current.icon;return <section className="mizan-surface p-5 sm:p-6"><div className="flex items-start gap-3"><Pictogram icon={ShieldCheck} size="lg" tone="emerald"/><div><div className="mizan-kicker">MGIP 1.0</div><h2 className="text-xl sm:text-2xl font-black mt-1">{ar?'بروتوكول النزاهة المتقدم':'Advanced Integrity Protocol'}</h2><p className="text-[11px] leading-5 text-[#747b76] mt-1 max-w-3xl">{ar?'اثنتا عشرة طبقة تعمل فوق MIZAN الحالي. لا تغيّر النتيجة الرسمية من وراء البشر، ولا تصنع يقينًا علميًا دون مصدر ودليل.':'Twelve layers extend the existing MIZAN architecture. They never silently mutate an official result or manufacture scientific certainty without evidence.'}</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-2 mt-5">{FEATURES.map(f=>{const F=f.icon;return <button key={f.id} onClick={()=>setFeature(f.id)} className={`min-h-20 rounded-2xl border p-3 text-start transition ${feature===f.id?'bg-[#202924] border-[#202924] text-white':'bg-[#fbfaf6] border-[#dfddd6] hover:border-[#aeb8b1]'}`}><F className="w-4 h-4"/><div className="text-[10px] font-black leading-4 mt-2">{ar?f.ar:f.en}</div></button>})}</div><div className="mt-5 border-t border-[#e3e1da] pt-5"><div className="flex items-center gap-3 mb-4"><span className="w-10 h-10 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><Icon className="w-5 h-5"/></span><div><div className="text-sm font-black">{ar?current.ar:current.en}</div><div className="text-[10px] text-[#7b827d]">{ar?'قدرة واحدة · حالة واحدة · فعل واحد':'One capability · one state · one action'}</div></div></div><FeatureDetail feature={feature}/></div></section>}

const FeatureDetail=({feature}:{feature:Feature})=>{switch(feature){case'silent':return <Silent/>;case'blackbox':return <BlackBox/>;case'court':return <Court/>;case'acoustic':return <Acoustic/>;case'twin':return <Twin/>;case'mutashabihat':return <Trap/>;case'routing':return <Routing/>;case'appeal':return <Appeal/>;case'anchor':return <Anchor/>;case'entropy':return <Entropy/>;case'breaker':return <Breaker/>;case'passport':return <Passport/>}}
const StatusLine=({state,arText,enText}:{state:'ready'|'review'|'blocked';arText:string;enText:string})=>{const s=useAppStore(),ar=s.language==='ar';return <div className="mizan-surface-soft p-4 flex items-center gap-3"><span className={`w-3 h-3 rounded-full ${state==='ready'?'bg-[#2F6555]':state==='review'?'bg-[#A98245]':'bg-[#A34D43]'}`}/><div className="text-xs font-bold flex-1">{ar?arText:enText}</div><Badge variant={state==='ready'?'emerald':state==='review'?'amber':'rose'}>{state==='ready'?(ar?'جاهز':'READY'):state==='review'?(ar?'مراجعة':'REVIEW'):(ar?'محظور':'BLOCKED')}</Badge></div>}

const Silent=()=>{const s=useAppStore(),ar=s.language==='ar';const [ready,setReady]=useState<boolean|null>(null);useEffect(()=>{void fetchSecureQuestionCapabilities().then(x=>setReady(x.ready))},[]);return <div className="space-y-3"><StatusLine state={ready===true?'ready':ready===false?'blocked':'review'} arText={ready?'FairDraw وحل النص والحجز كلها خادمية. JudgeOS لا يستلم النص قبل الحضور والنصاب.':'البيئة الحالية لا تثبت أن الخادم الآمن مهيأ بالكامل.'} enText={ready?'FairDraw, Quran resolution and escrow are server-side; JudgeOS receives no plaintext before presence + quorum.':'This runtime does not prove the secure server question path is fully configured.'}/><p className="text-[10px] text-[#777e79]">{ar?'في الإنتاج لا يوجد رجوع إلى بنك سؤال محلي إذا تعطلت الكبسولة.':'Production has no client-question fallback if the capsule is unavailable.'}</p></div>}

const BlackBox=()=>{const s=useAppStore(),ar=s.language==='ar';const latest=s.competitionBlackBoxes[0];const [busy,setBusy]=useState(false);return <div><StatusLine state={latest?'ready':'review'} arText={latest?`${latest.eventCount} حدثًا مربوطًا في بصمة زمنية.`:'لم تُلتقط لقطة صندوق أسود بعد.'} enText={latest?`${latest.eventCount} events are bound into a reconstructable timeline.`:'No black-box snapshot has been created yet.'}/><Button className="mt-3" loading={busy} onClick={async()=>{setBusy(true);try{await s.createCompetitionBlackBox()}finally{setBusy(false)}}}>{ar?'التقط لقطة أدلة':'Capture evidence snapshot'}</Button>{latest&&<div className="mizan-proof-code mt-3 p-3 rounded-xl bg-[#202924] text-white/65">{latest.headHash}</div>}</div>}

const Court=()=>{const s=useAppStore(),ar=s.language==='ar';const x=s.fairnessCourtRecords[0];return <div><StatusLine state={!s.results.length?'review':x?.status==='REVIEW'?'review':'ready'} arText={!s.results.length?'تحتاج نتائج فعلية قبل اختبار الحساسية.':x?`أقصى حركة ترتيب: ${x.maximumRankMovement} · تغيير الفائز: ${x.winnerChangedInAnyPermittedScenario?'نعم':'لا'}`:'لم تُشغّل محكمة الحساسية بعد.'} enText={!s.results.length?'Actual results are required before sensitivity analysis.':x?`Maximum rank movement: ${x.maximumRankMovement} · winner changed: ${x.winnerChangedInAnyPermittedScenario?'yes':'no'}`:'Sensitivity court has not run yet.'}/><Button className="mt-3" disabled={!s.results.length} onClick={()=>s.runFairnessCourt()}>{ar?'اختبر هشاشة النتيجة':'Test outcome sensitivity'}</Button><p className="text-[10px] text-[#777e79] mt-2">{ar?'غير رسمي ولا يغيّر نتيجة مختومة.':'Non-official; it never mutates a sealed result.'}</p></div>}

const Acoustic=()=>{const s=useAppStore(),ar=s.language==='ar';const [venue,setVenue]=useState('Committee-01');const [noise,setNoise]=useState('');const [noiseMax,setNoiseMax]=useState('');const [snr,setSnr]=useState('');const [snrMin,setSnrMin]=useState('');const [sample,setSample]=useState('16000');const [sampleMin,setSampleMin]=useState('16000');const x=s.acousticVenuePassports[0];const valid=[noise,noiseMax,snr,snrMin,sample,sampleMin].every(v=>Number.isFinite(Number(v)));return <div className="space-y-3"><StatusLine state={x?.status==='PASS'?'ready':x?'review':'review'} arText={x?`آخر جواز: ${x.venueZone} · ${x.status}`:'أدخل قياسات القاعة وحدودها المعتمدة. MIZAN لا يخترع حدودًا صوتية.'} enText={x?`Latest passport: ${x.venueZone} · ${x.status}`:'Enter venue measurements and governance-approved thresholds. MIZAN does not invent audio thresholds.'}/><div className="grid sm:grid-cols-3 gap-2"><Input v={venue} set={setVenue} label={ar?'القاعة':'Venue'}/><Num v={noise} set={setNoise} label={ar?'ضوضاء dB':'Noise dB'}/><Num v={noiseMax} set={setNoiseMax} label={ar?'الحد الأعلى':'Noise max'}/><Num v={snr} set={setSnr} label="SNR dB"/><Num v={snrMin} set={setSnrMin} label={ar?'حد SNR الأدنى':'SNR min'}/><Num v={sample} set={setSample} label="Sample rate"/><Num v={sampleMin} set={setSampleMin} label={ar?'أدنى Sample rate':'Sample min'}/></div><Button disabled={!valid||!venue.trim()} onClick={()=>s.createAcousticVenuePassport({venueZone:venue,measurements:{noiseFloorDb:Number(noise),snrDb:Number(snr),sampleRate:Number(sample)},thresholds:{noiseFloorDbMax:Number(noiseMax),snrDbMin:Number(snrMin),sampleRateMin:Number(sampleMin)}})}>{ar?'أصدر جواز القاعة':'Issue venue passport'}</Button></div>}

const Twin=()=>{const s=useAppStore(),ar=s.language==='ar';const sources=s.quranSourceManifests.filter(x=>x.certificationState==='CERTIFIED'&&x.revocationState!=='REVOKED');const [source,setSource]=useState(sources[0]?.id||'');const [surah,setSurah]=useState('1'),[start,setStart]=useState('1'),[end,setEnd]=useState('1'),[schema,setSchema]=useState('');const [msg,setMsg]=useState('');const latest=s.recitationDigitalTwins[0];return <div className="space-y-3"><StatusLine state={sources.length?'ready':'blocked'} arText={sources.length?'المصدر المعتمد موجود. التوأم سيرتبط ببصمته ولن يولد نصًا قرآنيًا.':'لا يوجد مصدر قرآن معتمد محليًا لبناء التوأم.'} enText={sources.length?'A certified source exists. The twin binds to its hash and never generates Quran text.':'No locally certified Quran source is available for a digital twin.'}/><div className="grid sm:grid-cols-4 gap-2"><select className="mizan-input" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><option key={x.id} value={x.id}>{x.rawi} · v{x.version}</option>)}</select><Num v={surah} set={setSurah} label={ar?'السورة':'Surah'}/><Num v={start} set={setStart} label={ar?'من آية':'Start'}/><Num v={end} set={setEnd} label={ar?'إلى آية':'End'}/><Input v={schema} set={setSchema} label={ar?'نسخة مخطط الفونيم — اختياري':'Phoneme schema — optional'}/></div><Button disabled={!source} onClick={async()=>{try{const r=await s.createRecitationDigitalTwin({sourceManifestId:source,surah:Number(surah),ayahStart:Number(start),ayahEnd:Number(end),phonemeSchemaVersion:schema||undefined});setMsg(r.state)}catch(e){setMsg(e instanceof Error?e.message:'FAILED')}}}>{ar?'أنشئ التوأم':'Build twin'}</Button>{(msg||latest)&&<div className="text-[10px] font-bold text-[#5f6762]">{msg||latest?.state}</div>}</div>}

const Trap=()=>{const s=useAppStore(),ar=s.language==='ar';const source=s.quranSourceManifests.find(x=>x.certificationState==='CERTIFIED');const reading=source?{qiraah:source.qiraah||'',rawi:source.rawi||source.riwaya}:null;const [es,setEs]=useState('1'),[ea,setEa]=useState('1'),[ps,setPs]=useState('2'),[pa,setPa]=useState('1'),[ref,setRef]=useState('');return <div className="space-y-3"><StatusLine state={source?'ready':'blocked'} arText={source?'الخريطة تربط نقطتين داخل سياق قراءة ومصدر محددين.':'يلزم مصدر معتمد قبل تسجيل خريطة متشابهات.'} enText={source?'The map binds two loci to one exact reading/source context.':'A certified source is required before mapping similar-verse traps.'}/><div className="grid sm:grid-cols-5 gap-2"><Num v={es} set={setEs} label={ar?'السورة المتوقعة':'Expected surah'}/><Num v={ea} set={setEa} label={ar?'الآية':'Ayah'}/><Num v={ps} set={setPs} label={ar?'السورة المحتملة':'Possible surah'}/><Num v={pa} set={setPa} label={ar?'الآية':'Ayah'}/><Input v={ref} set={setRef} label={ar?'مرجع خبير':'Expert ref'}/></div><Button disabled={!source||!reading||!ref.trim()} onClick={()=>s.createMutashabihatTrap({sourceManifestId:source!.id,expected:{surah:Number(es),ayah:Number(ea)},possible:{surah:Number(ps),ayah:Number(pa)},qiraah:reading!.qiraah,rawi:reading!.rawi,kind:'EXPERT',reference:ref,approve:s.currentUser.role==='scientific_admin'})}>{ar?'سجّل نقطة التشابه':'Map similar locus'}</Button></div>}

const Routing=()=>{const s=useAppStore(),ar=s.language==='ar';const queue=s.participants.filter(x=>x.status==='checked_in'||x.status==='in_session');const [pid,setPid]=useState(queue[0]?.id||s.participants[0]?.id||'');const [audio,setAudio]=useState(true),[ai,setAi]=useState(false);const last=s.smartRoutingDecisions[0];return <div className="space-y-3"><StatusLine state={last?.status==='NO_ELIGIBLE_COMMITTEE'?'review':last?'ready':'review'} arText={last?last.explanation:'اختيار اللجنة يوازن أهلية الرواية والحمل، ويمكن اشتراط مسار الصوت أو AI المعتمد.'} enText={last?last.explanation:'Committee choice balances reading qualification and load; approved audio/AI paths can be required.'}/><select className="mizan-input" value={pid} onChange={e=>setPid(e.target.value)}>{queue.map(x=><option key={x.id} value={x.id}>{x.code} · {x.riwaya}</option>)}</select><div className="flex gap-4 text-xs"><Check v={audio} set={setAudio} label={ar?'اشترط صوتًا جاهزًا':'Require audio'}/><Check v={ai} set={setAi} label={ar?'اشترط AI مطابقًا':'Require AI scope'}/></div><Button disabled={!pid} onClick={()=>s.routeParticipantByReading(pid,{requireAudio:audio,requireAi:ai})}>{ar?'اختر اللجنة الأنسب':'Route to best eligible committee'}</Button></div>}

const Appeal=()=>{const s=useAppStore(),ar=s.language==='ar';const [aid,setAid]=useState(s.appeals[0]?.id||'');const appeal=s.appeals.find(x=>x.id===aid);const last=s.appealCapsules[0];return <div className="space-y-3"><StatusLine state={last?'ready':'review'} arText={last?'آخر كبسولة تجمع أدلة الاستئناف المسموحة فقط وتستبعد الصوت الخام من الحزمة العامة.':'اختر اعتراضًا لإنشاء ملف أدلة محدود الصلاحية.'} enText={last?'Latest capsule includes only appeal-safe evidence and excludes raw audio from the portable package.':'Choose an appeal to create a privacy-scoped evidence capsule.'}/><select className="mizan-input" value={aid} onChange={e=>setAid(e.target.value)}>{s.appeals.map(x=><option key={x.id} value={x.id}>{x.participantCode} · {x.grounds}</option>)}</select><Button disabled={!appeal} onClick={()=>void s.createAppealCapsule(appeal!.participantId,appeal!.id)}>{ar?'أنشئ كبسولة الاعتراض':'Create appeal capsule'}</Button>{last&&<div className="mizan-proof-code p-3 rounded-xl bg-[#202924] text-white/65">{last.capsuleHash}</div>}</div>}

const Anchor=()=>{const s=useAppStore(),ar=s.language==='ar';const [rows,setRows]=useState('');const last=s.blindAnchorCalibrations[0];const parse=()=>rows.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const [committeeId,judgeId,judgeScore,expertScore,tolerance]=line.split(',').map(x=>x.trim());return {committeeId,judgeId,judgeScore:Number(judgeScore),expertScore:Number(expertScore),tolerance:Number(tolerance)}}).filter(x=>x.committeeId&&x.judgeId&&[x.judgeScore,x.expertScore,x.tolerance].every(Number.isFinite));const samples=parse();return <div className="space-y-3"><StatusLine state={last?.aggregateAgreementRate!==undefined?'ready':'review'} arText={last?`اتفاق مجمع: ${(last.aggregateAgreementRate*100).toFixed(1)}% · غير رسمي ولا يصنف المحكمين فرديًا.`:'ألصق عينات مرجعية معتمدة من البروفة فقط. لا تستخدم درجات طلاب حقيقية كـanchor.'} enText={last?`Aggregate agreement: ${(last.aggregateAgreementRate*100).toFixed(1)}% · non-official and no individual judge ranking.`:'Paste approved rehearsal anchor samples only. Do not use live participant scores as anchors.'}/><textarea className="w-full min-h-24 rounded-xl border border-[#d9d7d0] p-3 font-mono text-[11px]" value={rows} onChange={e=>setRows(e.target.value)} placeholder="committeeId,judgeId,judgeScore,expertScore,tolerance"/><Button disabled={!samples.length} onClick={()=>s.runBlindAnchorCalibration(samples)}>{ar?'شغّل المعايرة العمياء':'Run blind calibration'}</Button></div>}

const Entropy=()=>{const s=useAppStore(),ar=s.language==='ar';const [transfer,setTransfer]=useState(''),[reissue,setReissue]=useState(''),[retest,setRetest]=useState('');const last=s.integrityEntropySignals[0];const valid=[transfer,reissue,retest].every(v=>Number.isFinite(Number(v))&&Number(v)>0);return <div className="space-y-3"><StatusLine state={last?.status==='REVIEW'?'review':'ready'} arText={last?.status==='REVIEW'?`${last.signals.length} نمطًا تجاوز حدود المراجعة — ليست اتهامات.`:'الرادار يبحث عن أنماط تشغيلية فقط. الحدود تحددها الحوكمة ولا يخترعها النظام.'} enText={last?.status==='REVIEW'?`${last.signals.length} operational pattern(s) crossed review thresholds — not accusations.`:'The radar reviews operational patterns only. Governance supplies thresholds; the system does not invent them.'}/><div className="grid sm:grid-cols-3 gap-2"><Num v={transfer} set={setTransfer} label={ar?'حد تكرار النقل':'Transfer threshold'}/><Num v={reissue} set={setReissue} label={ar?'حد إعادة QR':'QR reissue threshold'}/><Num v={retest} set={setRetest} label={ar?'حد الإعادة الكاملة':'Retest threshold'}/></div><Button disabled={!valid} onClick={()=>s.runIntegrityEntropyRadar({reviewThresholds:{REPEATED_TRANSFER:Number(transfer),REISSUE_CLUSTER:Number(reissue),RETEST_CLUSTER:Number(retest)}})}>{ar?'افحص الأنماط':'Scan patterns'}</Button></div>}

const Breaker=()=>{const s=useAppStore(),ar=s.language==='ar';const [reason,setReason]=useState('');const [kind,setKind]=useState<'QURAN_SOURCE'|'AI_CAPABILITY'|'DATASET'|'REFERENCE_AUDIO'>('QURAN_SOURCE');const refs=kind==='QURAN_SOURCE'?s.quranSourceManifests:kind==='AI_CAPABILITY'?s.aiCapabilityValidations:kind==='DATASET'?s.scientificDatasets:s.quranReferenceAudio;const [ref,setRef]=useState('');useEffect(()=>{setRef(refs[0]?.id||'')},[kind]);const allowed=s.currentUser.role==='scientific_admin';const last=s.scientificCircuitBreakers[0];return <div className="space-y-3"><StatusLine state={last?.status==='ACTIVE'?'review':allowed?'ready':'blocked'} arText={allowed?'القاطع يوقف الاستخدام المستقبلي المتأثر ولا يعيد كتابة التاريخ.':'هذه الوظيفة للمسؤول العلمي فقط.'} enText={allowed?'The breaker blocks affected future use without rewriting historical competitions.':'Scientific-admin authority is required.'}/><div className="grid sm:grid-cols-2 gap-2"><select className="mizan-input" value={kind} onChange={e=>setKind(e.target.value as any)}><option value="QURAN_SOURCE">Quran source</option><option value="AI_CAPABILITY">AI capability</option><option value="DATASET">Dataset</option><option value="REFERENCE_AUDIO">Reference audio</option></select><select className="mizan-input" value={ref} onChange={e=>setRef(e.target.value)}>{refs.map((x:any)=><option key={x.id} value={x.id}>{x.name||x.rawi||x.capability||x.reciter||x.id}</option>)}</select></div><textarea className="w-full min-h-20 rounded-xl border border-[#d9d7d0] p-3 text-sm" value={reason} onChange={e=>setReason(e.target.value)} placeholder={ar?'سبب علمي واضح':'Scientific reason'}/><Button disabled={!allowed||!ref||reason.trim().length<8} onClick={()=>s.activateScientificCircuitBreaker({triggerType:kind,triggerRef:ref,reason:reason.trim(),affectedCapabilities:kind==='AI_CAPABILITY'?[(refs.find((x:any)=>x.id===ref) as any)?.capability||'unknown']:[]})}>{ar?'فعّل القاطع العلمي':'Trip scientific circuit breaker'}</Button></div>}

const Passport=()=>{const s=useAppStore(),ar=s.language==='ar';const last=s.mizanIntegrityPassports[0];const [busy,setBusy]=useState(false);return <div className="space-y-3"><StatusLine state={last?'ready':'review'} arText={last?'جواز النزاهة ينشر إثباتات المسابقة العامة دون أسماء المشاركين أو درجات المحكمين أو الصوت الخام.':'لم يصدر جواز نزاهة للمسابقة بعد.'} enText={last?'The integrity passport publishes competition proofs without participant identities, judge scores or raw audio.':'No integrity passport has been issued yet.'}/><Button loading={busy} onClick={async()=>{setBusy(true);try{await s.issueIntegrityPassport()}finally{setBusy(false)}}}>{ar?'أصدر جواز النزاهة':'Issue integrity passport'}</Button>{last&&<div className="mizan-proof-code p-3 rounded-xl bg-[#202924] text-white/65">{last.passportHash}</div>}</div>}

const Input=({v,set,label}:{v:string;set:(x:string)=>void;label:string})=><label className="text-[9px] font-black text-[#777e79]">{label}<input className="mizan-input mt-1" value={v} onChange={e=>set(e.target.value)}/></label>;
const Num=({v,set,label}:{v:string;set:(x:string)=>void;label:string})=><label className="text-[9px] font-black text-[#777e79]">{label}<input type="number" className="mizan-input mt-1" value={v} onChange={e=>set(e.target.value)}/></label>;
const Check=({v,set,label}:{v:boolean;set:(x:boolean)=>void;label:string})=><label className="inline-flex items-center gap-2"><input type="checkbox" checked={v} onChange={e=>set(e.target.checked)}/><span>{label}</span></label>;
