import React,{useEffect,useMemo,useState} from 'react';
import {FileCheck2,CheckCircle2,ChevronRight,FileSearch,Headphones,Database,Printer,ShieldCheck,FileText,WifiOff} from 'lucide-react';
import {fetchKfgqpcOfficialLibrary,type KfgqpcLibraryCapability,type KfgqpcLibraryGroup} from '../../lib/kfgqpc-library';
import {useAppStore} from '../../lib/store';
import {Badge} from '../design-system/Badge';
import {MizanPictogram} from '../design-system/MizanPictogram';
import {Button} from '../design-system/Button';
import {buildKfgqpcPublishingManifest,downloadPublishingManifest} from '../../lib/kfgqpc-publishing';

const groupMeta:Record<KfgqpcLibraryGroup,{ar:string;en:string;icon:any}>={MUSHAF:{ar:'المصحف الرسمي',en:'Official Mushaf',icon:FileCheck2},QURAN_DATA:{ar:'النص والروايات',en:'Quran data',icon:Database},SCIENCE:{ar:'المعرفة العلمية',en:'Scientific references',icon:ShieldCheck},PUBLISHING:{ar:'النشر والصفحات',en:'Publishing & pages',icon:Printer},AUDIO:{ar:'الصوت الرسمي',en:'Official audio',icon:Headphones}};
const tone=(x:KfgqpcLibraryCapability['operationalState'])=>x==='LOCAL_VERIFIED'||x==='SERVICE_READY'?'emerald':x==='LOCAL_BYTES_REQUIRED'?'amber':'neutral';
const stateLabel=(x:KfgqpcLibraryCapability['operationalState'],ar:boolean)=>x==='LOCAL_VERIFIED'?(ar?'الأصل المحلي موثّق':'LOCAL VERIFIED'):x==='SERVICE_READY'?(ar?'الخدمة جاهزة':'SERVICE READY'):x==='LOCAL_BYTES_REQUIRED'?(ar?'يلزم إدخال الأصل':'IMPORT ORIGINAL ASSET'):(ar?'معتمد رسميًا':'OFFICIALLY ACCEPTED');

export const OfficialQuranLibrary:React.FC=()=>{const s=useAppStore(),ar=s.language==='ar';const [data,setData]=useState<Awaited<ReturnType<typeof fetchKfgqpcOfficialLibrary>>|null>(null);const [error,setError]=useState('');const [group,setGroup]=useState<KfgqpcLibraryGroup>('MUSHAF');const [selected,setSelected]=useState('official-mushaf-vector');useEffect(()=>{let live=true;void fetchKfgqpcOfficialLibrary().then(x=>{if(live){setData(x);setError('')}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'KFGQPC_LIBRARY_UNAVAILABLE')});return()=>{live=false}},[]);const items=useMemo(()=>data?.items.filter(x=>x.group===group)||[],[data,group]);const current=data?.items.find(x=>x.id===selected)||items[0];useEffect(()=>{if(items.length&&!items.some(x=>x.id===selected))setSelected(items[0].id)},[group,data]);
 return <div className="space-y-4"><section className="relative overflow-hidden rounded-[28px] border border-[#d9d7cf] bg-[#fbfaf6] p-5 sm:p-7"><div className="absolute inset-y-0 end-0 w-1/3 opacity-[.035] pointer-events-none"><div className="h-full border-s-[28px] border-[#214C40] -skew-x-12"/></div><div className="relative flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div className="flex gap-4"><MizanPictogram kind="quran-source" size="lg" tone="emerald"/><div><div className="mizan-kicker">KFGQPC OFFICIAL LIBRARY</div><h2 className="text-2xl sm:text-3xl font-black mt-1">{ar?'مكتبة مجمع الملك فهد داخل ميزان':'King Fahd Complex inside MIZAN'}</h2><p className="text-[11px] leading-5 text-[#6f7772] mt-2 max-w-2xl">{ar?'مصدر واحد موثوق، بأشكاله المختلفة: الصفحة الأصلية، النص، الروايات، التفسير، الغريب، التجويد، الخطوط، النشر والصوت. الاعتماد العلمي ثابت؛ الجاهزية التشغيلية تظهر منفصلة حتى لا تختلط الثقة بالملف الفعلي.':'One trusted authority across official page masters, text, readings, tafsir, ghareeb, tajweed, fonts, publishing and audio. Scientific authority and operational asset readiness remain visibly separate.'}</p></div></div>{data&&<div className="flex gap-6"><Metric n={data.summary.officiallyAccepted} label={ar?'قدرة رسمية':'OFFICIAL'}/><Metric n={data.summary.localVerified+data.summary.serviceReady} label={ar?'جاهزة للتشغيل':'READY'}/></div>}</div></section>
 <div className="grid xl:grid-cols-[260px_1fr] gap-4"><aside className="mizan-surface p-2 h-fit">{(Object.keys(groupMeta) as KfgqpcLibraryGroup[]).map(id=>{const m=groupMeta[id],Icon=m.icon,count=data?.items.filter(x=>x.group===id).length||0;return <button key={id} onClick={()=>setGroup(id)} className={`w-full flex items-center gap-3 rounded-2xl px-3 py-3 text-start transition ${group===id?'bg-[#202924] text-white':'hover:bg-[#f1efe9] text-[#48504b]'}`}><span className={`w-9 h-9 rounded-xl grid place-items-center ${group===id?'bg-white/10':'bg-[#E7EEE9] text-[#214C40]'}`}><Icon className="w-4 h-4"/></span><span className="flex-1"><span className="block text-xs font-black">{ar?m.ar:m.en}</span><span className={`text-[9px] ${group===id?'text-white/55':'text-[#858b87]'}`}>{count}</span></span><ChevronRight className={`w-3.5 h-3.5 ${ar?'rotate-180':''}`}/></button>})}</aside>
 <section className="mizan-surface p-4 sm:p-5 min-h-[440px]">{error?<div className="h-[360px] grid place-items-center text-center"><div><WifiOff className="w-7 h-7 mx-auto text-[#9B7542]"/><div className="font-black mt-3">{ar?'المكتبة الخادمية غير متاحة':'Server library unavailable'}</div><div className="text-[10px] text-[#7d837f] mt-1 font-mono">{error}</div></div></div>:!data?<div className="h-[360px] grid place-items-center text-xs text-[#777e79]">{ar?'تحميل المصدر الرسمي…':'Loading official authority…'}</div>:<div className="grid lg:grid-cols-[.85fr_1.15fr] gap-5"><div className="space-y-2">{items.map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className={`w-full rounded-2xl border p-4 text-start transition ${current?.id===x.id?'border-[#214C40] bg-[#f2f6f3]':'border-[#e2e0d9] hover:border-[#bfc6c1] bg-[#fffefb]'}`}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black">{ar?x.titleArabic:x.titleEnglish}</div><div className="text-[10px] text-[#777e79] mt-1 line-clamp-2">{ar?x.summaryArabic:x.summaryEnglish}</div></div><Badge variant={tone(x.operationalState) as any}>{stateLabel(x.operationalState,ar)}</Badge></div></button>)}</div>{current&&<AssetDetail item={current} ar={ar}/>}</div>}</section></div></div>}

const AssetDetail=({item,ar}:{item:KfgqpcLibraryCapability;ar:boolean})=>{const s=useAppStore(),[busy,setBusy]=useState(false);const Visual=item.visualMode==='AUDIO'?Headphones:item.visualMode==='VECTOR_PAGE'||item.visualMode==='PUBLICATION_IMAGE'?FileSearch:item.id==='official-fonts'?FileText:item.group==='PUBLISHING'?Printer:FileCheck2;const source=s.quranSourceManifests.find(x=>x.certificationState==='CERTIFIED'&&x.revocationState!=='REVOKED');const exportManifest=async()=>{setBusy(true);try{const m=await buildKfgqpcPublishingManifest({competitionId:s.competition.id,assetId:item.id,sourcePackageId:source?.id,sourcePackageHash:source?.packageHash,purpose:item.id==='publication-images'?'APPEAL_EVIDENCE':item.id==='desktop-publishing'?'OFFICIAL_BOOKLET':'EMERGENCY_PACKET'});downloadPublishingManifest(m)}finally{setBusy(false)}};return <div className="rounded-[26px] bg-[#202924] text-white p-5 sm:p-6 min-h-[390px] flex flex-col"><div className="flex items-start justify-between gap-3"><span className="w-12 h-12 rounded-2xl bg-white/8 grid place-items-center"><Visual className="w-5 h-5"/></span><span className="inline-flex items-center gap-1.5 text-[9px] font-black tracking-[.14em] text-[#9fceb9]"><CheckCircle2 className="w-3.5 h-3.5"/>{ar?'مجمع الملك فهد · معتمد':'KFGQPC · CERTIFIED'}</span></div><div className="mt-7"><div className="text-[10px] text-white/45 font-black">{String(item.order).padStart(2,'0')}</div><h3 className="text-2xl font-black mt-1">{ar?item.titleArabic:item.titleEnglish}</h3><p className="text-xs leading-6 text-white/62 mt-3">{ar?item.summaryArabic:item.summaryEnglish}</p></div><div className="mt-6 grid sm:grid-cols-2 gap-3"><DarkBlock title={ar?'يستخدم في':'USED BY'} values={item.uses}/><DarkBlock title={ar?'قاعدة النزاهة':'GUARDRAIL'} values={[item.guardrail]}/></div><div className="mt-auto pt-6 flex flex-wrap items-center justify-between gap-3 border-t border-white/10"><div><div className="text-[9px] text-white/40">{ar?'الحالة التشغيلية':'OPERATIONAL STATE'}</div><div className="text-xs font-black mt-1">{stateLabel(item.operationalState,ar)}</div></div><div className="flex gap-2">{item.group==='PUBLISHING'&&<Button size="sm" variant="outline" loading={busy} onClick={()=>void exportManifest()}>{ar?'بيان نشر موثّق':'Provenance manifest'}</Button>}<a href={item.officialReference} target="_blank" rel="noreferrer" className="rounded-xl border border-white/15 px-3 py-2 text-[10px] font-black hover:bg-white/5">{ar?'المرجع الرسمي':'Official reference'}</a></div></div></div>}
const DarkBlock=({title,values}:{title:string;values:string[]})=><div className="rounded-2xl bg-white/[.045] p-4"><div className="text-[9px] font-black text-white/40">{title}</div><div className="mt-2 space-y-1.5">{values.map(v=><div key={v} className="text-[10px] leading-4 text-white/75 flex gap-2"><span className="mt-1.5 w-1 h-1 rounded-full bg-[#77a48f] shrink-0"/>{v}</div>)}</div></div>;
const Metric=({n,label}:{n:number;label:string})=><div className="text-end"><div className="text-3xl font-black tabular-nums">{n}</div><div className="text-[9px] font-black tracking-[.12em] text-[#777e79]">{label}</div></div>;
