import React,{useEffect,useState} from 'react';
import {Activity,Database,Download,Radio,ShieldCheck,WifiOff} from 'lucide-react';
import {fetchQuranIntelligenceHealth,type QuranIntelligenceHealth} from '../../lib/quran-intelligence';
import {Badge} from '../design-system/Badge';

const labels:Record<string,[string,string]>={spatial:['الموضع','Position'],waqf:['الوقف','Waqf'],waqfScience:['علم الوقف','Waqf science'],tajweed:['التجويد','Tajweed'],vector:['هندسة الكلمة','Word vector'],alignment:['التتبع','Alignment']};
export const QuranIntelligenceHealthConsole:React.FC<{ar:boolean}>=({ar})=>{const [data,setData]=useState<QuranIntelligenceHealth|null>(null),[state,setState]=useState<'loading'|'ready'|'offline'>('loading');
 useEffect(()=>{let live=true;const load=()=>void fetchQuranIntelligenceHealth().then(x=>{if(live){setData(x);setState('ready')}}).catch(()=>{if(live)setState('offline')});load();const timer=window.setInterval(load,30000);return()=>{live=false;window.clearInterval(timer)}},[]);
 const pct=data?.summary.totalLayers?Math.round(data.summary.readyLayers/data.summary.totalLayers*100):0;
 return <section className="overflow-hidden rounded-[26px] border border-[#ddd9cf] bg-[linear-gradient(145deg,#fbfaf6,#f0f4f0)] shadow-[0_14px_42px_rgba(31,58,49,.055)]"><div className="p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e6eee9] text-[#214C40]"><Activity className="h-4.5 w-4.5"/></span><div><div className="mizan-kicker">QURAN INTELLIGENCE HEALTH</div><h2 className="mt-1 text-base font-black">{ar?'صحة الطبقات القرآنية':'Quran layer health'}</h2><p className="mt-1 text-[10px] text-[#636864]">{ar?'لوحة هادئة تكشف الجاهز فقط؛ ولا تحوّل غياب المصدر إلى نجاح وهمي.':'A quiet readiness view: missing official material is never promoted to false readiness.'}</p></div></div><div className="flex items-center gap-3"><div className="text-end"><div className="text-3xl font-black tabular-nums text-[#214C40]">{state==='ready'?`${pct}%`:'—'}</div><div className="text-[8px] font-black tracking-wide text-[#676d69]">{ar?'جاهزية الطبقات':'LAYER READINESS'}</div></div><Badge variant={state==='ready'?'emerald':'amber'}>{state==='ready'?(ar?'مراقبة حية':'LIVE HEALTH'):(ar?'الخادم غير متاح':'SERVER OFFLINE')}</Badge></div></div>
 {state==='ready'&&data&&<><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{data.readings.map(r=><div key={r.reading} className="rounded-2xl border border-white/90 bg-white/72 p-3.5"><div className="flex items-center justify-between gap-2"><div><div className="text-[11px] font-black">{readingLabel(r.reading,ar)}</div><div className="mt-0.5 text-[8px] text-[#686d6a]">{r.ready}/{r.total} {ar?'طبقات جاهزة':'layers ready'}</div></div><span className={`h-2.5 w-2.5 rounded-full ${r.ready===r.total?'bg-[#2F6555]':r.ready?'bg-[#a8844b]':'bg-[#c8c5bd]'}`}/></div><div className="mt-3 grid grid-cols-3 gap-1.5">{Object.entries(r.layers).map(([k,v])=><div key={k} className={`rounded-lg px-2 py-1.5 text-center text-[8px] font-black ${v?'bg-[#eaf2ed] text-[#214C40]':'bg-[#f4f2ec] text-[#6a6e6b]'}`}>{(labels[k]||[k,k])[ar?0:1]}</div>)}</div></div>)}</div><div className="mt-3 grid gap-2 md:grid-cols-3"><Note icon={Download} title={ar?'المجمع':'KFGQPC'} text={ar?'الاستيراد ينتظر رجوع المصدر الرسمي؛ لا mirror غير رسمي.':'Acquisition waits for the official source; no unofficial mirror.'}/><Note icon={Radio} title={ar?'الظل الذكي':'Silent shadow'} text={data.alignmentBackendConfigured?(ar?'المحرك موصول؛ القرار والدرجة للبشر فقط.':'Backend connected; score authority remains human.'):(ar?'الـorchestration جاهز والمحرك الصوتي بانتظار الربط.':'Orchestration is ready; acoustic backend awaits connection.')}/><Note icon={Database} title={ar?'مرونة القاعة':'Venue resilience'} text={ar?'صفحات المصحف المستخدمة تُحفظ محليًا عند توفرها لتقليل أثر انقطاع الشبكة.':'Used Mushaf pages are cached locally when available to reduce venue network risk.'}/></div></>}
 {state==='offline'&&<div className="mt-4 flex items-center gap-3 rounded-2xl border border-[#e1d5c1] bg-[#fbf6ed] p-4 text-[10px] text-[#725d3f]"><WifiOff className="h-4 w-4 shrink-0"/>{ar?'تعذر قراءة حالة الخادم الآن. لا نغيّر أي حالة اعتماد محلية بسبب ذلك.':'Server health is unavailable. No local certification state is changed.'}</div>}
 <div className="mt-3 flex items-center gap-2 text-[8px] text-[#686d6a]"><ShieldCheck className="h-3 w-3"/>{ar?'لا fallback بين الروايات · لا تقدير بيانات مفقودة · المصدر قبل البرمجيات':'No cross-reading fallback · no inferred missing data · source before software'}</div></div></section>}
const Note=({icon:Icon,title,text}:{icon:React.ComponentType<{className?:string}>;title:string;text:string})=><div className="rounded-xl border border-[#e4e1d9] bg-white/62 p-3"><div className="flex items-center gap-2 text-[9px] font-black"><Icon className="h-3.5 w-3.5 text-[#2F6555]"/>{title}</div><p className="mt-1.5 text-[8px] leading-4 text-[#666b67]">{text}</p></div>;
function readingLabel(v:string,ar:boolean){const x:Record<string,[string,string]>={hafs:['حفص','Hafs'],warsh:['ورش','Warsh'],shubah:['شعبة','Shu\'bah'],qaloun:['قالون','Qalun'],'douri-abu-amr':['الدوري عن أبي عمرو','Al-Duri Abu Amr'],'sousi-abu-amr':['السوسي عن أبي عمرو','Al-Susi Abu Amr']};return (x[v]||[v,v])[ar?0:1]}
