import React,{useEffect,useMemo,useState} from 'react';
import { uiToken, rehearsalCheckLabel } from '../../lib/ui-language';
import {CheckCircle2,Clock3,WandSparkles,ShieldCheck,Settings2,ScanSearch,PlayCircle} from 'lucide-react';
import {useAppStore} from '../../lib/store';
import {getCompetitionPolicy} from '../../lib/competition-config';
import {buildPreflight,simulateRuleEffects,PreflightCheck} from '../../lib/readiness';
import {detectContradictions} from '../../lib/policy-compiler';
import {MizanPictogram} from '../design-system/MizanPictogram';
import {Button} from '../design-system/Button';
import {Badge} from '../design-system/Badge';
import {Pictogram} from '../design-system/Pictogram';
import {fetchRuntimeHealth,questionEscrowAssuranceFromHealth,type MizanRuntimeHealth} from '../../lib/runtime-capabilities';

type Tab='preflight'|'simulator'|'rehearsal'|'replay';
export const ReadinessLab:React.FC<{onNavigate?:(target:'field'|'integrations')=>void}>=({onNavigate})=>{
 const s=useAppStore(); const ar=s.language==='ar'; const [tab,setTab]=useState<Tab>('preflight');
 const tabs:[Tab,any,string][]=[['preflight',ShieldCheck,ar?'الجاهزية':'Preflight'],['simulator',WandSparkles,ar?'المحاكي':'Simulator'],['rehearsal',PlayCircle,ar?'البروفة':'Rehearsal'],['replay',Clock3,ar?'إعادة المحاكاة':'Replay']];
 return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto">{tabs.map(([id,Icon,label])=><button key={id} onClick={()=>setTab(id)} className={`min-h-11 shrink-0 inline-flex items-center gap-2 px-3 rounded-xl text-xs font-black border ${tab===id?'bg-[#214C40] text-white border-[#214C40]':'bg-white text-[#5f6862] border-[#dedcd5]'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>{tab==='preflight'&&<Preflight s={s} ar={ar} onNavigate={onNavigate}/>} {tab==='simulator'&&<Simulator s={s} ar={ar}/>} {tab==='rehearsal'&&<Rehearsal s={s} ar={ar}/>} {tab==='replay'&&<Replay s={s} ar={ar}/>}</div>
};

const Preflight=({s,ar,onNavigate}:{s:ReturnType<typeof useAppStore>;ar:boolean;onNavigate?: (t:'field'|'integrations')=>void})=>{
 const p=getCompetitionPolicy(s.competition); const [runtime,setRuntime]=useState<MizanRuntimeHealth>();
 useEffect(()=>{const controller=new AbortController();void fetchRuntimeHealth(controller.signal).then(setRuntime);return()=>controller.abort()},[]);
 const escrowAssurance=questionEscrowAssuranceFromHealth(runtime);
 const report=useMemo(()=>buildPreflight({competition:s.competition,policy:p,integrations:s.integrations,devices:s.devices,judges:s.judges,committees:s.committees,quranSources:s.quranSourceManifests,aiValidations:s.aiCapabilityValidations,backups:s.backups,isOffline:s.isOffline,questionEscrowAssurance:escrowAssurance}),[s.competition,p,s.integrations,s.devices,s.judges,s.committees,s.quranSourceManifests,s.aiCapabilityValidations,s.backups,s.isOffline,escrowAssurance]);
 const fix=(c:PreflightCheck)=>{if(c.fix==='backup'){s.createBackup();return}if(c.fix==='field'){onNavigate?.('field');return}if(c.fix==='integrations'){onNavigate?.('integrations');return}if(c.fix==='competition_dna'){window.dispatchEvent(new CustomEvent('mizan:open-competition-dna'));return}if(c.fix==='scientific'){window.dispatchEvent(new CustomEvent('mizan:open-scientific'));return}};
 return <section className="mizan-surface p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div className="flex gap-3 items-start"><Pictogram icon={ShieldCheck}/><div><div className="mizan-kicker">{ar?'فحص ما قبل التشغيل':'MIZAN PREFLIGHT'}</div><h2 className="text-xl font-black mt-1">{ar?'بوابة الجاهزية':'Readiness Gate'}</h2><div className="text-[10px] text-[#666d68] mt-1">{ar?(runtime?.questionEscrowConfigured?'حجز السؤال الخادمي: مهيأ فعليًا':'حجز السؤال الخادمي: غير مهيأ بعد'):(runtime?.questionEscrowConfigured?'Server question escrow: configured':'Server question escrow: not configured')}</div></div></div><div className="flex items-end gap-3"><div className="text-5xl font-black tabular-nums">{report.score}%</div><Badge variant={report.blocker?'rose':report.warning?'amber':'emerald'}>{report.blocker?(ar?'مانع':'BLOCKER'):report.warning?(ar?'تنبيه':'WARNING'):(ar?'جاهزة':'READY')}</Badge></div></div><div className="grid sm:grid-cols-2 mt-5 border-t border-[#e5e3dc]">{report.checks.map(c=><div key={c.id} className="py-3 sm:px-3 border-b border-[#e8e6df] flex items-start gap-3"><span className={`mt-1 w-2.5 h-2.5 rounded-full shrink-0 ${c.status==='ready'?'bg-[#2F6555]':c.status==='warning'?'bg-[#9B7542]':'bg-[#A34D43]'}`}/><div className="min-w-0 flex-1"><div className="text-xs font-black">{ar?c.labelAr:c.labelEn}</div>{c.status!=='ready'&&<div className="text-[10px] leading-4 text-[#646965] mt-1">{ar?c.consequenceAr:c.consequenceEn}</div>}</div>{c.status!=='ready'&&c.fix!=='none'&&<button onClick={()=>fix(c)} className="w-11 h-11 rounded-xl grid place-items-center hover:bg-[#efede7] text-[#5d665f]" title={ar?'إصلاح':'Fix'} aria-label={ar?'إصلاح':'Fix'}><Settings2 className="w-3.5 h-3.5"/></button>}</div>)}</div><ContradictionRadar s={s} ar={ar}/><p className="text-[10px] text-[#686d6a] mt-4">{ar?'التحذير لا يساوي مانعًا. المانع العلمي/النزاهة يحتاج معالجة أو تجاوزًا مصرحًا ومسجلًا في بيئة الإنتاج.':'A warning is not a blocker. Scientific/integrity blockers require correction or an authorized audited production override.'}</p></section>
};

const Simulator=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const rules=s.competition.ruleSet;const [judges,setJudges]=useState(rules.judgesCountPerPanel);const [pass,setPass]=useState(rules.minimumPassingScore);const focus=rules.criteria.find(x=>/taj|تجويد/i.test(`${x.id} ${x.name} ${x.nameArabic}`))||rules.criteria[0];const [weight,setWeight]=useState(focus?.weight||1);const sim=useMemo(()=>simulateRuleEffects({competition:s.competition,judges,minimumScore:pass,focusCriterionId:focus?.id,focusWeight:weight}),[s.competition,judges,pass,focus?.id,weight]);return <section className="mizan-surface p-5 sm:p-6"><div className="flex gap-3"><Pictogram icon={WandSparkles}/><div><div className="mizan-kicker">{ar?'غير رسمي · محاكاة اصطناعية':'NON-OFFICIAL · SYNTHETIC'}</div><h2 className="text-xl font-black mt-1">{ar?'محاكي القواعد':'Rule Simulator'}</h2><p className="text-xs text-[#646965] mt-1">{ar?'يشرح الأثر؛ لا يقرر ما هو الصحيح علميًا أو شرعيًا.':'Explains consequences; it never decides scientific or religious correctness.'}</p></div></div><div className="grid sm:grid-cols-3 gap-3 mt-5"><Range label={ar?'عدد المحكمين':'Judges'} value={judges} min={1} max={9} step={1} set={setJudges}/><Range label={ar?'حد التأهل':'Passing'} value={pass} min={0} max={100} step={.25} set={setPass}/><Range label={`${ar?'وزن':'Weight'} · ${ar?focus?.nameArabic:focus?.name}`} value={weight} min={0} max={10} step={.25} set={setWeight}/></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-5"><Metric n={sim.ties} t={ar?'حالات ضمن درجات متساوية':'scores in ties'}/><Metric n={`${sim.qualificationRate}%`} t={ar?'يتجاوز الحد':'above threshold'}/><Metric n={`${sim.focusInfluencePercent}%`} t={ar?'تأثير نسبي':'relative influence'}/><Metric n={sim.dropExtremes?(ar?'مفعّل':'ON'):(ar?'متوقف':'OFF')} t={ar?'حذف الأطراف':'drop extremes'}/></div></section>};

const Replay=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [filter,setFilter]=useState('all');const rows=s.flightRecorderEntries.filter(x=>filter==='all'||x.stream===filter).slice(-80).reverse();const streams=['all',...Array.from(new Set(s.flightRecorderEntries.map(x=>x.stream)))];useEffect(()=>{void s.buildFlightRecorder()},[]);return <section className="mizan-surface p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><Pictogram icon={Clock3}/><div><div className="mizan-kicker">{ar?'إعادة المحاكاة':'MIZAN REPLAY'}</div><h2 className="text-xl font-black mt-1">{ar?'إعادة بناء اليوم':'Reconstruct the day'}</h2></div></div></div><div className="flex gap-1.5 overflow-x-auto mt-5">{streams.map(x=><button key={x} onClick={()=>setFilter(x)} className={`shrink-0 px-2.5 min-h-9 rounded-xl text-[10px] font-black ${filter===x?'bg-[#214C40] text-white':'bg-[#f1efe9] text-[#69716c]'}`}>{x==='all'?(ar?'الكل':'All'):uiToken(x,ar)}</button>)}</div><div className="mt-4 divide-y divide-[#e6e4dd]">{rows.slice(0,30).map(x=><div key={x.id} className="py-3 grid grid-cols-[72px_1fr_auto] gap-3 items-center"><span className="text-[10px] font-mono text-[#656b66]">{new Date(x.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><span className="text-xs font-bold">{ar?x.summaryArabic:x.summaryEnglish}</span><Badge variant="neutral">{uiToken(x.stream,ar)}</Badge></div>)}{!rows.length&&<div className="py-10 text-center"><CheckCircle2 className="w-5 h-5 mx-auto text-[#2F6555]"/><div className="text-xs text-[#656b66] mt-2">{ar?'ابنِ السجل لإعادة المحاكاة':'Rebuild the recorder to start Replay'}</div></div>}</div></section>};

const Range=({label,value,min,max,step,set}:{label:string;value:number;min:number;max:number;step:number;set:(n:number)=>void})=><label className="mizan-surface-soft p-3"><span className="text-[10px] font-black text-[#636864]">{label}</span><div className="text-xl font-black mt-1">{value}</div><input aria-label={label} className="w-full mt-2 accent-[#214C40]" type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>;
const Metric=({n,t}:{n:string|number;t:string})=><div className="mizan-surface-soft p-3"><div className="text-2xl font-black">{n}</div><div className="text-[10px] text-[#646965] mt-1">{t}</div></div>;


const ContradictionRadar=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const issues=useMemo(()=>detectContradictions({competition:s.competition,quranSources:s.quranSourceManifests,aiValidations:s.aiCapabilityValidations,availableQualifiedJudges:s.judges.filter(j=>j.isReady).length,committeeSeesDelegation:false,certificateProofRequired:true}),[s.competition,s.quranSourceManifests,s.aiCapabilityValidations,s.judges]);const blockers=issues.filter(x=>x.severity==='BLOCKER'),reviews=issues.filter(x=>x.severity==='REVIEW');return <div className="mt-5 rounded-2xl bg-[#f7f5ef] p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><ScanSearch className="w-4 h-4 text-[#53615a]"/><strong className="text-xs">{ar?'رادار التعارض':'Contradiction Radar'}</strong></div><div className="flex gap-2"><Badge variant={blockers.length?'rose':'neutral'}>{blockers.length} {ar?'مانع':'BLOCKER'}</Badge><Badge variant={reviews.length?'amber':'neutral'}>{reviews.length} {ar?'مراجعة':'REVIEW'}</Badge></div></div>{issues.length?<div className="mt-3 divide-y divide-[#e3e0d7]">{issues.slice(0,5).map(i=><div key={i.id} className="py-2.5 flex items-start gap-3"><span className={`mt-1.5 w-2 h-2 rounded-full ${i.severity==='BLOCKER'?'bg-[#a5544b]':i.severity==='REVIEW'?'bg-[#9a713a]':'bg-[#75807a]'}`}/><div className="min-w-0"><div className="text-xs font-black">{ar?(i.titleAr||i.title):i.title}</div><div className="text-[10px] text-[#646965] mt-1">{(ar?(i.flowAr||i.affectedWorkflow):i.affectedWorkflow)} · {ar?(i.whyAr||i.why):i.why}</div></div></div>)}</div>:<div className="text-xs font-black text-[#2F6555] mt-3">{ar?'لا تعارض':'READY'}</div>}</div>};

const Rehearsal=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [busy,setBusy]=useState(false);const rec=s.rehearsals[0];const run=async()=>{setBusy(true);try{await s.runOperationalRehearsal()}finally{setBusy(false)}};return <section className="mizan-surface p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex gap-3"><MizanPictogram kind="rehearsal"/><div><div className="mizan-kicker">{ar?'البروفة التشغيلية':'OPERATIONAL REHEARSAL'}</div><h2 className="text-xl font-black mt-1">{rec?.status?uiToken(rec.status,ar):(ar?'لم تُشغّل بعد':'NOT RUN')}</h2><p className="text-xs text-[#646965] mt-1">{ar?'سجلات البروفة منفصلة عن الرسمي. لا تظهر نتيجة ناجحة إلا بعد تشغيل الفحوص فعلًا.':'DEMO records stay isolated. PASS is only emitted after checks actually run.'}</p></div></div><Button loading={busy} onClick={()=>void run()} icon={<PlayCircle className="w-4 h-4"/>}>{ar?'تشغيل البروفة':'Run rehearsal'}</Button></div>{rec&&<div className="mt-5 divide-y divide-[#e5e3dc]">{rec.checks.map(c=>{const L=rehearsalCheckLabel(c.id,c.name,c.impact,ar);return <div key={c.id} className="py-3 flex items-start gap-3"><span className={`mt-1 w-2.5 h-2.5 rounded-full ${c.status==='PASS'?'bg-[#2F6555]':c.status==='WARNING'?'bg-[#9B7542]':'bg-[#A34D43]'}`}/><div><div className="text-xs font-black">{L.name} · <span className="text-[#656b66]">{uiToken(c.status,ar)}</span></div><div className="text-[10px] text-[#646965] mt-1">{L.impact}{!ar&&c.evidence.length?` · ${c.evidence.join(' · ')}`:''}</div>{c.status==='FAIL'&&c.fix&&!ar&&<div className="text-[10px] font-bold text-[#8f554d] mt-1">{c.fix}</div>}</div></div>})}</div>}</section>};
const EmptyReadiness=({text}:{text:string})=><div className="py-10 text-center text-xs text-[#656b66]">{text}</div>;
