import React, { useState } from 'react';
import {
  Activity, Award, BadgeCheck, Building2, CheckCircle2, ChevronLeft, ChevronRight, FileCheck2, FileSearch,
  Fingerprint, Globe2, Gavel, Headphones, KeyRound, Layers3, Microscope, Plane, Plus, QrCode, Search,
  ShieldCheck, Sparkles, UsersRound, WalletCards, XCircle
} from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { getCompetitionPolicy } from '../../lib/competition-config';
import { QURAN_SOURCE_FIXTURES } from '../../lib/quran-vault';
import { Badge } from '../design-system/Badge';
import { Button } from '../design-system/Button';

const isAr=(l:string)=>l==='ar';

export const SuperAdminConsole: React.FC = () => {
 const {language,competition,participants,judges,auditLogs}=useAppStore(); const ar=isAr(language);
 return <PortalFrame kicker="MIZAN PLATFORM" title={ar?'منصة ميزان':'MIZAN Platform'} subtitle={ar?'صحة المنصة والجهات دون التدخل الخفي في نتائج المسابقات.':'Platform health and organizations without hidden result intervention.'}>
   <div className="grid sm:grid-cols-4 gap-3">
    <Metric icon={Building2} value="1" label={ar?'جهة نشطة':'Organization'}/><Metric icon={Activity} value="1" label={ar?'مسابقة حية':'Live competition'}/><Metric icon={Gavel} value={judges.length} label={ar?'محكمون':'Judges'}/><Metric icon={FileSearch} value={auditLogs.length} label={ar?'أحداث تدقيق':'Audit events'}/>
   </div>
   <div className="mizan-surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="mizan-kicker">TENANT</div><div className="font-extrabold mt-1">{ar?'الأمانة العامة لجائزة القرآن الكريم الدولية':'Global Quran Award Authority'}</div></div><Badge>Enterprise</Badge></div><div className="grid sm:grid-cols-3 gap-3 mt-5"><Info label={ar?'الإقامة البيانية':'Data residency'} value="eu-west-locked"/><Info label={ar?'المسابقة الحالية':'Current competition'} value={ar?competition.nameArabic:competition.name}/><Info label={ar?'المشاركون':'Participants'} value={String(participants.length)}/></div></div>
   <div className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-[#2F6555]"/><h2 className="font-extrabold">{ar?'حوكمة السوبر أدمن':'Super Admin governance'}</h2></div><div className="mt-4 grid sm:grid-cols-3 gap-3 text-xs"><Guard text={ar?'لا تعديل سري للنتائج':'No silent result edits'}/><Guard text={ar?'كل دخول حساس مدقق':'Sensitive access audited'}/><Guard text={ar?'السلطة العلمية مستقلة':'Scientific authority stays independent'}/></div></div>
 </PortalFrame>
}

export const OrganizationHome: React.FC = () => {
 const {language,competition,competitions,switchRole,selectCompetition,createCompetition}=useAppStore(); const ar=isAr(language); const [creating,setCreating]=useState(false); const [name,setName]=useState('');
 const create=()=>{ if(!name.trim())return; createCompetition(name,name,'international-hifz'); setCreating(false);setName(''); switchRole('comp_admin'); };
 return <PortalFrame kicker={ar?'الجهة':'ORGANIZATION'} title={ar?'مسابقات الجهة':'Organization competitions'} subtitle={ar?'كل مسابقة مستقلة بشروطها وتحكيمها وسياساتها ومسارها.':'Each competition owns its rules, judging policy, workflow and public experience.'}>
  <div className="flex items-center justify-between gap-4"><div className="grid grid-cols-3 gap-3 flex-1 max-w-xl"><Metric icon={Building2} value={competitions.length} label={ar?'مسابقات':'Competitions'}/><Metric icon={UsersRound} value="12" label={ar?'مستخدمًا مفوضًا':'Authorized users'}/><Metric icon={Globe2} value="2" label={ar?'لغتان نشطتان':'Languages'}/></div><Button onClick={()=>setCreating(v=>!v)} icon={<Plus className="w-4 h-4"/>}>{ar?'مسابقة':'Competition'}</Button></div>
  {creating&&<div className="mizan-surface p-5"><div className="grid sm:grid-cols-[1fr_auto] gap-3 items-end"><label><span className="text-xs font-bold text-[#6d746f]">{ar?'اسم المسابقة':'Competition name'}</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} className="mt-2 w-full rounded-xl border border-[#ddd] px-3 py-2.5 text-sm"/></label><Button disabled={!name.trim()} onClick={create}>{ar?'إنشاء':'Create'}</Button></div></div>}
  <div className="space-y-2">{competitions.map(c=><button key={c.id} onClick={()=>{selectCompetition(c.id);switchRole('comp_admin')}} className={`w-full mizan-surface p-5 text-start transition hover:border-[#bfc9c3] ${competition.id===c.id?'ring-2 ring-[#214C40]/10':''}`}><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><Badge variant={c.status==='live'?'emerald':'neutral'}>{c.status}</Badge><span className="text-[10px] text-[#7c827e]">{c.edition}</span></div><h2 className="text-lg font-black mt-3 truncate">{ar?c.nameArabic:c.name}</h2><p className="text-xs text-[#777e79] mt-1 truncate">{c.timezone} · {c.categories.length} {ar?'فئات':'categories'}</p></div><Layers3 className="w-5 h-5 text-[#2F6555] shrink-0"/></div></button>)}</div>
 </PortalFrame>
}

export const ScientificStudio: React.FC = () => {
 const {language,competition}=useAppStore(); const ar=isAr(language); const policy=getCompetitionPolicy(competition);
 const source=QURAN_SOURCE_FIXTURES[0];
 const capabilities=[
  {name:ar?'عرض المصدر للتحكيم البشري':'Human judging source',status:'requires-approval'},
  {name:ar?'محاذاة موضع التلاوة':'Quran alignment',status:'not-certified'},
  {name:ar?'رصد الحفظ بالذكاء الاصطناعي':'AI memorization watch',status:'not-certified'},
  {name:ar?'تحليل التجويد آليًا':'AI Tajweed',status:'not-certified'}
 ];
 return <PortalFrame kicker={ar?'الحوكمة العلمية':'SCIENTIFIC GOVERNANCE'} title={ar?'المصدر واللائحة قبل التقنية':'Source and rules before technology'} subtitle={ar?'لا نص قرآني من نموذج لغوي، ولا ادعاء اعتماد قبل أن تعتمد الجهة المصدر والنموذج رسميًا.':'No LLM-generated Quran text and no certification claim before the institution formally approves the source and capability.'}>
  <div className="grid lg:grid-cols-[1.1fr_.9fr] gap-4">
   <div className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Fingerprint className="w-5 h-5 text-[#2F6555]"/><h2 className="font-extrabold">Quran Source Vault</h2></div><div className="mt-5 divide-y divide-[#e5e3dc]"><Row title={ar?'المصدر الحالي':'Current source'} value={ar?source.nameArabic:source.nameEnglish}/><Row title={ar?'الرواية':'Riwaya'} value={source.riwaya}/><Row title={ar?'الحالة':'Status'} value={ar?'بيانات تطوير — يلزم اعتماد مؤسسي قبل الإنتاج':'Development fixture — institutional approval required'}/><Row title={ar?'قاعدة الإنتاج':'Production rule'} value={ar?'مصدر معتمد وموقّع فقط':'Approved, versioned vault only'}/></div><div className="mt-4 rounded-xl bg-[#F2EADC] text-[#725630] p-3 text-xs">{ar?'المستودع لا يزعم أن بيانات التطوير الحالية مصحف معتمد. عند الإنتاج يُستبدل المصدر ببيانات الجهة العلمية مع checksum ومراجعين وإصدار ثابت.':'This repository does not claim its development fixture is an approved Mushaf. Production must import the institution-approved corpus with checksum, reviewers and immutable version.'}</div></div>
   <div className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Microscope className="w-5 h-5 text-[#2F6555]"/><h2 className="font-extrabold">AI Capability Registry</h2></div><div className="mt-4 space-y-2">{capabilities.map(c=><div key={c.name} className="flex items-center justify-between py-2 gap-4"><span className="text-sm font-semibold">{c.name}</span><Badge variant="neutral" dot={false}>{c.status==='requires-approval'?(ar?'يلزم اعتماد':'Requires approval'):(ar?'غير معتمد':'Not certified')}</Badge></div>)}</div><div className="rounded-xl bg-[#E7EEE9] text-[#214C40] text-xs p-3 mt-4">{ar?'حتى بعد الاعتماد: AI يوصي بالمراجعة فقط، ولا يخصم من الدرجة.':'Even after validation, AI recommends review only and cannot deduct a score.'}</div></div>
  </div>
  <div className="mizan-surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="mizan-kicker">RULESET</div><h2 className="font-extrabold mt-1">{competition.ruleSet.name}</h2></div><Badge variant="neutral" dot={false}>{competition.ruleSet.version}</Badge></div><div className="grid sm:grid-cols-3 gap-3 mt-5">{competition.ruleSet.criteria.map(c=><Info key={c.id} label={ar?c.nameArabic:c.name} value={`${c.maxScore}`}/>)}</div><div className="text-xs text-[#777e79] mt-4">{ar?`نمط المحكمين: ${policy.judging.mode}`:`Judge mode: ${policy.judging.mode}`}</div></div>
 </PortalFrame>
}

export const DelegationPortal: React.FC = () => {
 const {language,participants,competition,registerParticipant}=useAppStore(); const ar=isAr(language); const [q,setQ]=useState(''); const [adding,setAdding]=useState(false); const [name,setName]=useState(''); const [email,setEmail]=useState('');
 const list=participants.filter(p=>`${p.fullName} ${p.fullNameArabic} ${p.code}`.toLowerCase().includes(q.toLowerCase())).slice(0,8);
 const addNominee=()=>{ if(!name.trim()||!email.trim()) return; const c=competition.categories[0]; registerParticipant({competitionId:competition.id,organizationId:competition.organizationId,fullName:name,fullNameArabic:name,email,phone:'',country:'',nationality:'',nationalIdOrPassport:'',dateOfBirth:'2010-01-01',gender:'male',categoryId:c?.id||'',riwaya:c?.riwaya||'',delegationId:'delegation-current',institution:'',specialNeeds:false,documents:[]} as any); setName('');setEmail('');setAdding(false); };
 return <PortalFrame kicker={ar?'بوابة الوفد':'DELEGATION'} title={ar?'وفدي':'My delegation'} subtitle={ar?'ترشيح ومتابعة الوثائق والوصول دون رؤية بيانات الوفود الأخرى.':'Nomination, documents and arrival without seeing other delegations.'}>
  <div className="flex items-center justify-between gap-4"><div className="grid grid-cols-3 gap-3 flex-1 max-w-xl"><Metric icon={UsersRound} value={participants.length} label={ar?'مرشح':'Nominees'}/><Metric icon={BadgeCheck} value={participants.filter(p=>p.status==='approved'||p.status==='in_queue'||p.status==='tested').length} label={ar?'معتمد':'Approved'}/><Metric icon={Plane} value={participants.filter(p=>!!p.arrivalSlot).length} label={ar?'موعد وصول':'Arrival set'}/></div><Button onClick={()=>setAdding(v=>!v)} icon={<Plus className="w-4 h-4"/>}>{ar?'مرشح':'Nominee'}</Button></div>
  {adding&&<div className="mizan-surface p-5"><div className="grid sm:grid-cols-[1fr_1fr_auto] gap-3 items-end"><label><span className="text-xs font-bold text-[#6d746f]">{ar?'الاسم':'Name'}</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-[#ddd] px-3 py-2.5 text-sm"/></label><label><span className="text-xs font-bold text-[#6d746f]">{ar?'البريد':'Email'}</span><input value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[#ddd] px-3 py-2.5 text-sm"/></label><Button disabled={!name.trim()||!email.trim()} onClick={addNominee}>{ar?'إضافة':'Add'}</Button></div></div>}
  <div className="mizan-surface overflow-hidden"><div className="p-4 border-b border-[#e4e2db]"><div className="relative max-w-sm"><Search className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-[#89908b]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-xl border border-[#ddd] ps-10 pe-3 py-2.5 text-sm" placeholder={ar?'بحث':'Search'}/></div></div><div className="divide-y divide-[#e5e3dc]">{list.map(p=><div key={p.id} className="p-4 flex items-center gap-4"><div className="w-10 h-10 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center text-xs font-black">{p.code.replace('A-','')}</div><div className="flex-1 min-w-0"><div className="text-sm font-bold truncate">{ar?p.fullNameArabic:p.fullName}</div><div className="text-[11px] text-[#7b827d] mt-1">{p.country||'—'} · {p.arrivalSlot||'—'}</div></div><Badge variant={p.status==='approved'||p.status==='tested'?'emerald':'neutral'}>{p.status}</Badge></div>)}</div></div>
 </PortalFrame>
}
export const AuditorConsole: React.FC = () => {
 const {language,auditLogs,competition}=useAppStore(); const ar=isAr(language); const [q,setQ]=useState(''); const logs=auditLogs.filter(x=>`${x.action} ${x.humanSummaryArabic} ${x.humanSummaryEnglish}`.toLowerCase().includes(q.toLowerCase()));
 return <PortalFrame kicker={ar?'التدقيق':'AUDIT'} title={ar?'سجل قابل للتتبع':'Trace every sensitive decision'} subtitle={ar?'واجهة قراءة فقط؛ لا تعديل للبيانات من مسار التدقيق.':'Read-only by design; audit access does not mutate competition data.'}>
  <div className="mizan-surface overflow-hidden"><div className="p-4 flex items-center justify-between gap-3 border-b border-[#e5e3dc]"><div className="relative max-w-sm flex-1"><Search className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-[#89908b]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-xl border border-[#ddd] ps-10 pe-3 py-2.5 text-sm" placeholder={ar?'بحث في السجل':'Search audit'}/></div><Badge variant="neutral" dot={false}>{competition.ruleSet.version}</Badge></div><div className="divide-y divide-[#e5e3dc] max-h-[620px] overflow-y-auto">{logs.map(log=><div key={log.id} className="p-4 sm:px-5"><div className="flex items-center justify-between gap-3"><div className="text-xs font-black text-[#3a423d]">{ar?log.humanSummaryArabic:log.humanSummaryEnglish}</div><span className="text-[10px] text-[#878d89] shrink-0">{new Date(log.timestamp).toLocaleString(ar?'ar-KW':'en-US')}</span></div><div className="text-[10px] text-[#7b827d] mt-1.5 font-mono">{log.action} · {log.actorRole} · {log.currentStateHash}</div></div>)}</div></div>
 </PortalFrame>
}

export const ExceptionDesk: React.FC = () => {
 const {language,participants,checkInParticipant}=useAppStore(); const ar=isAr(language); const [q,setQ]=useState(''); const [last,setLast]=useState<string|null>(null);
 const matches=q?participants.filter(p=>`${p.code} ${p.fullName} ${p.fullNameArabic} ${p.nationalIdOrPassport}`.toLowerCase().includes(q.toLowerCase())).slice(0,5):[];
 return <PortalFrame kicker="MIZAN EXCEPTION DESK" title={ar?'الطبيعي مؤتمت. أنت للحالات غير الطبيعية.':'Routine is automated. You handle exceptions.'} subtitle={ar?'ابحث بكود أو اسم أو هوية، ثم نفذ إجراءً واحدًا واضحًا.':'Search by code, name or ID, then take one clear action.'}>
   <div className="mizan-surface p-5 sm:p-7 max-w-3xl"><div className="relative"><Search className="w-5 h-5 absolute start-4 top-1/2 -translate-y-1/2 text-[#89908b]"/><input autoFocus value={q} onChange={e=>{setQ(e.target.value);setLast(null)}} placeholder={ar?'كود، اسم، أو هوية':'Code, name or ID'} className="w-full rounded-2xl border border-[#d9d7d0] bg-white ps-12 pe-4 py-4 text-base font-semibold"/></div>{last&&<div className="mt-4 rounded-xl bg-[#E7EEE9] text-[#214C40] px-4 py-3 text-sm font-bold flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>{last}</div>}<div className="mt-4 divide-y divide-[#e5e3dc]">{matches.map(p=><div key={p.id} className="py-4 flex items-center gap-4"><div className="w-11 h-11 rounded-xl bg-[#f0eee8] grid place-items-center font-black text-xs">{p.code}</div><div className="flex-1 min-w-0"><div className="font-bold text-sm">{ar?p.fullNameArabic:p.fullName}</div><div className="text-[11px] text-[#7b827d] mt-1">{p.country} · {p.status}</div></div><Button size="sm" onClick={()=>{const r=checkInParticipant(p.id,'exception_host');if(r)setLast(ar?`تم تسجيل حضور ${r.code}`:`${r.code} checked in`)}} icon={<QrCode className="w-4 h-4"/>}>{ar?'حضور':'Check-in'}</Button></div>)}</div>{q&&matches.length===0&&<div className="text-center py-10 text-sm text-[#7b827d]"><XCircle className="w-6 h-6 mx-auto mb-2"/>{ar?'لم نجد مشاركًا مطابقًا':'No matching participant'}</div>}</div>
 </PortalFrame>
}

const PortalFrame=({kicker,title,subtitle,children}:{kicker:string;title:string;subtitle:string;children:React.ReactNode})=><div className="max-w-[1250px] mx-auto px-4 sm:px-6 py-7 space-y-5"><div><div className="mizan-kicker">{kicker}</div><h1 className="text-3xl sm:text-4xl font-black tracking-tight mt-1">{title}</h1><p className="text-sm text-[#747b76] mt-2 max-w-2xl">{subtitle}</p></div>{children}</div>;
const Metric=({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:string|number;label:string})=><div className="mizan-surface p-4"><Icon className="w-4 h-4 text-[#2F6555]"/><div className="text-2xl font-black mt-4">{value}</div><div className="text-[11px] text-[#777e79] mt-1">{label}</div></div>;
const Info=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-[#f1efe9] p-4"><div className="text-[10px] font-black text-[#7d847f]">{label}</div><div className="text-xs font-bold mt-1 break-words">{value}</div></div>;
const Guard=({text}:{text:string})=><div className="rounded-xl bg-[#E7EEE9] text-[#214C40] p-3 flex items-center gap-2 font-bold"><BadgeCheck className="w-4 h-4 shrink-0"/>{text}</div>;
const Row=({title,value}:{title:string;value:string})=><div className="py-3 flex items-center justify-between gap-4"><span className="text-xs text-[#737a75]">{title}</span><span className="text-xs font-bold text-[#303733] text-end">{value}</span></div>;
