import React,{useMemo,useState} from 'react';
import { BadgeCheck, Binary, Braces, CheckCircle2, Clock3, Download, FileKey2, Fingerprint, GitBranch, KeyRound, Network, RadioTower, ShieldCheck, TriangleAlert, UsersRound } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import type { FederationAttestationRecord, InvariantCheckResult } from '../../types';
import { Badge } from '../design-system/Badge';
import { Button } from '../design-system/Button';
import { Pictogram } from '../design-system/Pictogram';

type Tool='time'|'quorum'|'invariants'|'graph'|'proof'|'mesh'|'federation'|'protocol';
const tools:{id:Tool;icon:React.ComponentType<{className?:string}>;ar:string;en:string}[]=[
 {id:'time',icon:Clock3,ar:'الزمن',en:'Time'}, {id:'quorum',icon:UsersRound,ar:'النصاب',en:'Quorum'}, {id:'invariants',icon:ShieldCheck,ar:'الثوابت',en:'Invariants'}, {id:'graph',icon:GitBranch,ar:'الدليل',en:'Evidence'}, {id:'proof',icon:Fingerprint,ar:'الإثبات',en:'Proof'}, {id:'mesh',icon:RadioTower,ar:'Mesh',en:'Mesh'}, {id:'federation',icon:FileKey2,ar:'الاتحاد',en:'Federation'}, {id:'protocol',icon:Braces,ar:'البروتوكول',en:'Protocol'}
];

export const TrustProtocolLab:React.FC=()=>{const s=useAppStore();const ar=s.language==='ar';const [tool,setTool]=useState<Tool>('invariants');return <div className="space-y-4">
 <div className="mizan-surface p-3"><div className="grid grid-cols-4 lg:grid-cols-8 gap-1.5">{tools.map(t=>{const active=tool===t.id;return <button key={t.id} onClick={()=>setTool(t.id)} aria-pressed={active} className={`min-h-[84px] rounded-2xl grid place-items-center content-center gap-2 transition border ${active?'bg-[#1f342c] text-white border-[#1f342c]':'bg-[#fbfaf6] text-[#59615c] border-transparent hover:border-[#d6d5ce]'}`}><Pictogram icon={t.icon} size="sm" tone={active?'ink':'emerald'}/><span className="text-[10px] font-black">{ar?t.ar:t.en}</span></button>})}</div></div>
 {tool==='time'&&<TimeMachine s={s} ar={ar}/>} {tool==='quorum'&&<Quorum s={s} ar={ar}/>} {tool==='invariants'&&<Invariants s={s} ar={ar}/>} {tool==='graph'&&<Evidence s={s} ar={ar}/>} {tool==='proof'&&<Proof s={s} ar={ar}/>} {tool==='mesh'&&<Mesh s={s} ar={ar}/>} {tool==='federation'&&<Federation s={s} ar={ar}/>} {tool==='protocol'&&<Protocol s={s} ar={ar}/>}</div>};

const TimeMachine=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [delta,setDelta]=useState(1);const [arrival,setArrival]=useState(30);const [absent,setAbsent]=useState('');const [base,setBase]=useState(()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)});const latest=s.timeMachineScenarios[0];const run=()=>{const d=new Date(base);if(!Number.isNaN(d.getTime()))s.runTimeMachine({baseTimestamp:d.toISOString(),committeeDelta:delta,arrivalRatePerHour:arrival,absentJudgeIds:absent?[absent]:[],networkMode:s.isOffline?'local_mesh':'normal'})};return <section className="mizan-surface p-5 sm:p-6"><Head icon={Clock3} title="MIZAN Time Machine" subtitle={ar?'اختر دقيقة من اليوم واختبر مستقبلًا بديلًا دون لمس التاريخ الرسمي.':'Choose a minute and test an alternate future without touching official history.'}/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-5"><Field label={ar?'اللحظة':'Moment'}><input className="mizan-input" type="datetime-local" value={base} onChange={e=>setBase(e.target.value)}/></Field><Field label={ar?'فرق اللجان':'Panel delta'}><input className="mizan-input" type="number" min="-7" max="20" value={delta} onChange={e=>setDelta(Number(e.target.value))}/></Field><Field label={ar?'وصول/ساعة':'Arrivals / hour'}><input className="mizan-input" type="number" min="1" value={arrival} onChange={e=>setArrival(Number(e.target.value))}/></Field><Field label={ar?'محكم غائب':'Absent judge'}><select className="mizan-input" value={absent} onChange={e=>setAbsent(e.target.value)}><option value="">—</option>{s.judges.map(j=><option value={j.id} key={j.id}>{ar?j.nameArabic:j.name}</option>)}</select></Field></div><Button className="mt-3" onClick={run}>{ar?'شغّل البديل':'Run alternate'}</Button>{latest&&<><div className="mt-4 text-[10px] font-black text-[#7b827d]">{new Date(latest.baseTimestamp).toLocaleString()} · {latest.label}</div><div className="mt-3 grid lg:grid-cols-[1fr_auto_1fr] items-stretch gap-2"><TimelineSide label={ar?'الواقع عند اللحظة':'Baseline'} data={latest.baseline}/><div className="hidden lg:grid place-items-center text-[#9aa09c]"><Binary className="w-5 h-5"/></div><TimelineSide label={ar?'المستقبل البديل':'Alternate'} data={latest.alternative} accent/></div><div className="mt-3 flex flex-wrap gap-2"><Delta n={latest.delta.averageWaitMinutes} label={ar?'د انتظار':'min wait'}/><Delta n={latest.delta.finishMinutes} label={ar?'د نهاية':'min finish'}/><Badge variant="neutral">NON-OFFICIAL</Badge></div></>}</section>};

const Quorum=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [msg,setMsg]=useState('');const seal=s.quorumActions.find(q=>q.action==='results_seal'&&q.entityId===s.competition.id);const reveal=s.quorumActions.find(q=>q.action==='ceremony_reveal'&&q.entityId===s.competition.id);const requestReveal=async()=>{const q=await s.requestCeremonyReveal();setMsg(q?'':ar?'اختم النتائج أولًا.':'Seal results first.')};return <div className="grid lg:grid-cols-2 gap-4"><QuorumCard title={ar?'ختم النتائج':'Result seal'} q={seal} ar={ar} currentId={s.currentUser.id} currentRole={s.currentUser.role} onApprove={()=>seal&&s.approveQuorumAction(seal.id)} emptyAction={<Button onClick={()=>void s.sealResults()}>{ar?'ابدأ الختم':'Start seal'}</Button>}/><QuorumCard title={ar?'كشف الحفل':'Ceremony reveal'} q={reveal} ar={ar} currentId={s.currentUser.id} currentRole={s.currentUser.role} onApprove={()=>reveal&&s.approveQuorumAction(reveal.id)} onExecute={()=>reveal&&s.executeQuorumAction(reveal.id)} emptyAction={<Button variant="outline" onClick={requestReveal}>{ar?'طلب الكشف':'Request reveal'}</Button>}/>{msg&&<div className="lg:col-span-2 text-xs font-bold text-[#8a693f]">{msg}</div>}</div>};

const Invariants=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [rows,setRows]=useState<InvariantCheckResult[]>([]);const [busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{setRows(await s.runInvariantChecks())}finally{setBusy(false)}};return <section className="mizan-surface p-5 sm:p-6"><Head icon={ShieldCheck} title="Integrity Invariants" subtitle={ar?'قواعد لا يملك أي دور حق كسرها.':'Rules no role is allowed to break.'}/><Button className="mt-5" loading={busy} onClick={run}>{ar?'افحص الآن':'Check now'}</Button><div className="mt-4 grid md:grid-cols-2 gap-2">{rows.map(r=><div key={r.key} className={`rounded-2xl border p-4 flex items-start gap-3 ${r.status==='violation'?'border-[#e7c9c4] bg-[#f8efed]':r.status==='warning'?'border-[#ead9bc] bg-[#f7f0e4]':'border-[#e0dfd7] bg-[#fbfaf6]'}`}><span className={`w-9 h-9 rounded-xl grid place-items-center shrink-0 ${r.status==='violation'?'bg-[#f0d9d5] text-[#9a4b42]':r.status==='warning'?'bg-[#efe3cd] text-[#8a693f]':'bg-[#e7eee9] text-[#214c40]'}`}>{r.status==='violation'?<TriangleAlert className="w-4 h-4"/>:<CheckCircle2 className="w-4 h-4"/>}</span><div className="min-w-0"><div className="text-xs font-black">{ar?r.titleArabic:r.titleEnglish}</div><div className="text-[10px] text-[#7c837e] mt-1 truncate">{r.evidence[0]}</div></div></div>)}</div>{s.invariantViolations.length>0&&<div className="mt-4 text-[10px] font-bold text-[#9a4b42]">{s.invariantViolations.length} {ar?'عملية مُنعت وحُفظ أثرها':'blocked operation(s) preserved in audit'}</div>}</section>};

const Evidence=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [selected,setSelected]=useState('');const trace=selected?s.traceEvidence(selected):null;const resultNodes=s.evidenceNodes.filter(n=>['result','certificate','ai_capability','question','fairdraw'].includes(n.type));return <section className="mizan-surface p-5 sm:p-6"><Head icon={GitBranch} title={ar?'Scientific Evidence Graph':'Scientific Evidence Graph'} subtitle={ar?'من النتيجة إلى القاعدة والمصدر والاعتماد.':'Trace a result back to rules, sources and authority.'}/><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void s.rebuildEvidenceGraph()}>{ar?'بناء الرسم':'Build graph'}</Button>{s.evidenceNodes.length>0&&<Badge variant="neutral">{s.evidenceNodes.length} nodes</Badge>}</div>{resultNodes.length>0&&<select className="mizan-input mt-4" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{ar?'اختر أثرًا':'Select evidence'}</option>{resultNodes.map(n=><option key={n.id} value={n.id}>{n.type} · {n.label}</option>)}</select>}{trace&&<div className="mt-4 grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{trace.nodes.map(n=><div key={n.id} className="rounded-2xl bg-[#f4f2ec] p-4"><div className="text-[9px] font-black uppercase text-[#79807c]">{n.type}</div><div className="text-xs font-black mt-2 truncate">{n.label}</div><div className="text-[10px] text-[#777e79] mt-1 truncate">{n.authority||n.status}</div></div>)}</div>}</section>};

const Proof=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [rid,setRid]=useState('');const [verified,setVerified]=useState<boolean|null>(null);const results=s.results.filter(r=>['sealed','published'].includes(r.status));const proof=s.publicResultProofs.find(p=>p.resultId===rid);const download=()=>{if(!proof)return;const blob=new Blob([JSON.stringify(proof,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mizan-result-proof-${proof.disclosed.participantCode}.json`;a.click();URL.revokeObjectURL(a.href)};return <section className="mizan-surface p-5 sm:p-6"><Head icon={Fingerprint} title={ar?'Selective Result Proof':'Selective Result Proof'} subtitle={ar?'أثبت انتماء نتيجة واحدة للمجموعة المختومة دون كشف البقية.':'Prove one result belongs to the sealed set without disclosing the others.'}/><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void s.buildPublicResultRoot()}>{ar?'التزام النتائج':'Commit results'}</Button>{s.publicResultRoots[0]&&<Badge variant="emerald">SHA-256 · {s.publicResultRoots[0].resultCount}</Badge>}</div>{results.length>0&&<select className="mizan-input mt-4" value={rid} onChange={e=>{setRid(e.target.value);setVerified(null)}}><option value="">{ar?'اختر نتيجة':'Select result'}</option>{results.map(r=><option key={r.id} value={r.id}>{r.participantCode} · {r.finalScore}</option>)}</select>}{proof&&<div className="mt-4 rounded-2xl bg-[#f4f2ec] p-4"><div className="mizan-proof-code">{proof.merkleRoot}</div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={async()=>setVerified(await s.verifyPublicResultProof(proof))}>{ar?'تحقق':'Verify'}</Button><Button size="sm" variant="outline" icon={<Download className="w-4 h-4"/>} onClick={download}>{ar?'تنزيل':'Download'}</Button>{verified!==null&&<Badge variant={verified?'emerald':'rose'}>{verified?'VERIFIED':'FAILED'}</Badge>}</div></div>}<p className="text-[10px] text-[#838a85] mt-4">Merkle selective disclosure · not a zk-SNARK / zero-knowledge claim.</p></section>};

const Mesh=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const mesh=s.localMeshSessions[0];return <section className="mizan-surface p-5 sm:p-6"><Head icon={RadioTower} title="MIZAN Local Mesh" subtitle={ar?'استمرار محلي مع sequence وdedupe وتعارضات قابلة للمصالحة.':'Local continuity with sequence, dedupe and auditable reconciliation.'}/>{!mesh?<Button className="mt-5" onClick={s.startLocalMesh}>{ar?'ابدأ Mesh':'Start mesh'}</Button>:<><div className="mt-5 grid grid-cols-3 gap-2"><Small value={mesh.nodes.length} label="NODES"/><Small value={mesh.events.length} label="EVENTS"/><Small value={mesh.conflicts.filter(c=>c.status==='open').length} label="CONFLICTS"/></div><div className="mt-3 flex flex-wrap gap-2"><Badge variant={mesh.transportStatus==='connected'?'emerald':'neutral'}>{mesh.transportMode||'journal_only'}</Badge><Button size="sm" variant="outline" onClick={()=>void s.appendLocalMeshEvent(mesh.id,'HEARTBEAT',{at:new Date().toISOString()},undefined,'heartbeat')}>{ar?'حدث':'Event'}</Button><Button size="sm" onClick={()=>s.reconcileLocalMesh(mesh.id)}>{ar?'مصالحة':'Reconcile'}</Button></div><p className="mt-4 text-[10px] leading-5 text-[#7c837e]">{ar?'BroadcastChannel حقيقي يعمل لنوافذ نفس الأصل عند السماح به. الأجهزة المستقلة ميدانيًا تحتاج Edge/LAN موثوقًا؛ لا ندّعي P2P وهميًا.':'Real BroadcastChannel works for same-origin windows where enabled. Independent field devices require trusted Edge/LAN transport; no fake P2P claim.'}</p></>}</section>};

const Federation=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [subject,setSubject]=useState(s.participants[0]?.id||'');const [claim,setClaim]=useState<FederationAttestationRecord['claim']>('identity_verified');const [status,setStatus]=useState('');const latest=s.federationAttestations.find(a=>a.subjectRef===subject);const issue=async()=>{const p=s.participants.find(x=>x.id===subject);if(!p)return;await s.issueFederationAttestation({subjectRef:p.id,subjectKind:'participant',issuer:s.organization.name,claim,value:'true',expiresInDays:365});setStatus('')};return <section className="mizan-surface p-5 sm:p-6"><Head icon={FileKey2} title={ar?'Delegation Passport Federation':'Delegation Passport Federation'} subtitle={ar?'شارك الادعاء الموثق لا الوثيقة الخاصة نفسها.':'Share a verified claim, not the private document itself.'}/><div className="mt-5 grid sm:grid-cols-2 gap-2"><select className="mizan-input" value={subject} onChange={e=>setSubject(e.target.value)}>{s.participants.map(p=><option key={p.id} value={p.id}>{p.code} · {ar?p.fullNameArabic:p.fullName}</option>)}</select><select className="mizan-input" value={claim} onChange={e=>setClaim(e.target.value as FederationAttestationRecord['claim'])}><option value="identity_verified">identity_verified</option><option value="age_verified">age_verified</option><option value="delegation_authorized">delegation_authorized</option><option value="guardian_consent_verified">guardian_consent_verified</option><option value="travel_document_verified">travel_document_verified</option><option value="organization_nomination">organization_nomination</option></select></div><div className="mt-3 flex flex-wrap gap-2"><Button onClick={issue}>{ar?'إصدار claim':'Issue claim'}</Button>{latest&&<Button variant="outline" onClick={async()=>{const v=await s.verifyFederationAttestation(latest.id);setStatus(v.valid?'VERIFIED':`FAILED · ${v.reason}`)}}>{ar?'تحقق':'Verify'}</Button>}{latest&&<Button variant="ghost" onClick={()=>s.revokeFederationAttestation(latest.id)}>{ar?'إلغاء':'Revoke'}</Button>}{status&&<Badge variant={status==='VERIFIED'?'emerald':'rose'}>{status}</Badge>}</div>{latest&&<div className="mt-4 rounded-2xl bg-[#f4f2ec] p-4 text-[10px]"><div className="font-black">{latest.claim} · {latest.status}</div><div className="mt-2 mizan-proof-code">{latest.signatureRef}</div></div>}<p className="mt-4 text-[10px] text-[#838a85]">{ar?'توقيع المتصفح هنا Development Adapter وموسوم بذلك. PKI المؤسسي الحقيقي يعمل فقط عند تهيئة مفاتيح الخادم.':'Browser signature is explicitly a Development Adapter. Institutional PKI is only active when server keys are configured.'}</p></section>};

const Protocol=({s,ar}:{s:ReturnType<typeof useAppStore>;ar:boolean})=>{const [ok,setOk]=useState<boolean|null>(null);const pkg=s.protocolPackages[0];const download=()=>{if(!pkg)return;const json=s.exportMizanProtocolPackage(pkg.id);if(!json)return;const blob=new Blob([json],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mizan-protocol-${s.competition.id}.json`;a.click();URL.revokeObjectURL(a.href)};return <section className="mizan-surface p-5 sm:p-6"><Head icon={Braces} title="MIZAN Protocol 1.0" subtitle={ar?'حزمة محمولة تربط القواعد والنتائج والمصدر والأثر دون الاعتماد على الواجهة.':'A portable package binding policy, results, source governance and audit independent of the UI.'}/><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void s.generateMizanProtocolPackage()}>{ar?'أنشئ الحزمة':'Generate package'}</Button>{pkg&&<Button variant="outline" onClick={async()=>setOk((await s.verifyMizanProtocolPackage(pkg)).valid)}>{ar?'تحقق':'Verify'}</Button>}{pkg&&<Button variant="outline" icon={<Download className="w-4 h-4"/>} onClick={download}>{ar?'تنزيل':'Download'}</Button>}{ok!==null&&<Badge variant={ok?'emerald':'rose'}>{ok?'VERIFIED':'FAILED'}</Badge>}</div>{pkg&&<div className="mt-4 rounded-2xl bg-[#202924] text-white p-4"><div className="mizan-proof-code text-white/70">{pkg.packageHash}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4 text-[9px]"><DarkMini label="Genome" value={pkg.genomeHash.slice(0,10)}/><DarkMini label="Results" value={pkg.resultRoot?.slice(0,10)||'—'}/><DarkMini label="Evidence" value={pkg.evidenceGraphHash?.slice(0,10)||'—'}/><DarkMini label="Audit" value={pkg.auditHead?.replace('SHA256:','').slice(0,10)||'—'}/></div></div>}</section>};

const Head=({icon,title,subtitle}:{icon:React.ComponentType<{className?:string}>;title:string;subtitle:string})=><div className="flex items-start gap-3"><Pictogram icon={icon} size="md"/><div><h2 className="font-black">{title}</h2><p className="text-[11px] text-[#757d78] mt-1">{subtitle}</p></div></div>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><label><span className="mizan-field-label">{label}</span>{children}</label>;
const Small=({value,label}:{value:string|number;label:string})=><div className="rounded-2xl bg-[#f4f2ec] p-4"><div className="text-2xl font-black">{value}</div><div className="text-[10px] text-[#777e79] mt-1">{label}</div></div>;
const Delta=({n,label}:{n:number;label:string})=><span className={`rounded-full px-3 py-1.5 text-[10px] font-black ${n<=0?'bg-[#e7eee9] text-[#214c40]':'bg-[#f2eadc] text-[#8a693f]'}`}>{n>0?'+':''}{n} {label}</span>;
const TimelineSide=({label,data,accent=false}:{label:string;data:{committees:number;participantsInScope:number;averageWaitMinutes:number;projectedFinishTime:string;maxWaitMinutes:number};accent?:boolean})=><div className={`rounded-2xl p-4 ${accent?'bg-[#e8efeb]':'bg-[#f4f2ec]'}`}><div className="text-[10px] font-black text-[#727a75]">{label}</div><div className="grid grid-cols-3 gap-2 mt-3"><Small value={`${data.averageWaitMinutes}m`} label="AVG"/><Small value={data.projectedFinishTime} label="END"/><Small value={data.committees} label="PANELS"/></div></div>;
const QuorumCard=({title,q,ar,currentId,currentRole,onApprove,onExecute,emptyAction}:{title:string;q:any;ar:boolean;currentId:string;currentRole:string;onApprove:()=>void;onExecute?:()=>void;emptyAction:React.ReactNode})=>{const approved=q?.approvals?.some((a:any)=>a.actorId===currentId);const canApprove=q?.requiredRoleGroups?.flat().includes(currentRole)&&!approved;return <section className="mizan-surface p-5"><Head icon={KeyRound} title={title} subtitle={ar?'سلطتان مستقلتان. لا باب خلفي.':'Two independent authorities. No backdoor.'}/>{!q?<div className="mt-5">{emptyAction}</div>:<><div className="mt-5 grid grid-cols-2 gap-2"><Approval ok={q.approvals.some((a:any)=>a.actorRole==='head_judge')} label={ar?'رئيس التحكيم':'Head Judge'}/><Approval ok={q.approvals.some((a:any)=>['comp_admin','org_admin'].includes(a.actorRole))} label={ar?'الإدارة':'Authority'}/></div><div className="mt-4 flex gap-2">{canApprove&&<Button onClick={onApprove}>{ar?'اعتماد':'Approve'}</Button>}{onExecute&&q.status==='ready'&&<Button variant="outline" onClick={onExecute}>{ar?'تنفيذ':'Execute'}</Button>}<Badge variant={q.status==='executed'?'emerald':q.status==='ready'?'amber':'neutral'}>{q.status}</Badge></div></>}</section>};
const Approval=({ok,label}:{ok:boolean;label:string})=><div className={`rounded-xl p-3 flex items-center gap-2 ${ok?'bg-[#e7eee9] text-[#214c40]':'bg-[#f2f0ea] text-[#747b76]'}`}>{ok?<CheckCircle2 className="w-4 h-4"/>:<KeyRound className="w-4 h-4"/>}<span className="text-xs font-black">{label}</span></div>;
const DarkMini=({label,value}:{label:string;value:string})=><div className="rounded-xl border border-white/10 p-3"><div className="text-white/35">{label}</div><div className="font-mono mt-1 text-white/80">{value}</div></div>;
