import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
const canonical=(v:unknown):string=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;const o=v as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`};
const hash=(v:string|Buffer)=>crypto.createHash('sha256').update(v).digest('hex');
const forbiddenKey=/private.?key|master.?key|secret|password|token|credential/i;
export interface ColdVaultPackage{version:'MIZAN-COLD-VAULT-1';competitionId:string;createdAt:string;createdBy:string;contents:string[];cipher:{algorithm:'AES-256-GCM';iv:string;tag:string;ciphertext:string};payloadHash:string;packageHash:string;privateKeysIncluded:false;assurance:'PORTABLE_ENCRYPTED_EDGE_PACKAGE'}
export class ColdVaultRepository{
 constructor(private root:string){fs.mkdirSync(root,{recursive:true,mode:0o700})}
 private assertMinimum(payload:Record<string,unknown>){const walk=(v:unknown,p='root')=>{if(!v||typeof v!=='object')return;for(const [k,x] of Object.entries(v as Record<string,unknown>)){if(forbiddenKey.test(k))throw new Error(`COLD_VAULT_FORBIDDEN_SECRET:${p}.${k}`);walk(x,`${p}.${k}`)}};walk(payload)}
 export(input:{competitionId:string;createdBy:string;payload:Record<string,unknown>;transferKey:Buffer}){if(input.transferKey.length!==32)throw new Error('COLD_VAULT_KEY_MUST_BE_32_BYTES');this.assertMinimum(input.payload);const plain=Buffer.from(canonical(input.payload)),payloadHash=hash(plain),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',input.transferKey,iv);cipher.setAAD(Buffer.from(`${input.competitionId}|${payloadHash}`));const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();const core={version:'MIZAN-COLD-VAULT-1' as const,competitionId:input.competitionId,createdAt:new Date().toISOString(),createdBy:input.createdBy,contents:Object.keys(input.payload).sort(),cipher:{algorithm:'AES-256-GCM' as const,iv:iv.toString('base64url'),tag:tag.toString('base64url'),ciphertext:ciphertext.toString('base64url')},payloadHash,privateKeysIncluded:false as const,assurance:'PORTABLE_ENCRYPTED_EDGE_PACKAGE' as const};const pkg:ColdVaultPackage={...core,packageHash:hash(canonical(core))};const file=path.join(this.root,`cold-vault-${input.competitionId.replace(/[^A-Za-z0-9._-]/g,'_')}-${Date.now()}.json`);fs.writeFileSync(file,JSON.stringify(pkg,null,2),{encoding:'utf8',mode:0o600});return {package:pkg,file}}
 verify(pkg:ColdVaultPackage){const {packageHash,...core}=pkg;return {valid:hash(canonical(core))===packageHash,privateKeysIncluded:pkg.privateKeysIncluded===false}}
 restorePreview(pkg:ColdVaultPackage,key:Buffer){const ok=this.verify(pkg);if(!ok.valid)throw new Error('COLD_VAULT_PACKAGE_HASH_MISMATCH');const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(pkg.cipher.iv,'base64url'));decipher.setAAD(Buffer.from(`${pkg.competitionId}|${pkg.payloadHash}`));decipher.setAuthTag(Buffer.from(pkg.cipher.tag,'base64url'));const plain=Buffer.concat([decipher.update(Buffer.from(pkg.cipher.ciphertext,'base64url')),decipher.final()]);if(hash(plain)!==pkg.payloadHash)throw new Error('COLD_VAULT_PAYLOAD_HASH_MISMATCH');const payload=JSON.parse(plain.toString('utf8')) as Record<string,unknown>;return {ok:true,contents:Object.keys(payload).sort(),questionPlaintextPresent:Object.keys(payload).some(k=>/plaintext/i.test(k))}}
}
