import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
const canonical=(v:unknown):string=>{if(v===undefined)return 'null';if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;const o=v as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`};
const hash=(v:string|Buffer)=>crypto.createHash('sha256').update(v).digest('hex');
const forbiddenKey=/private.?key|master.?key|secret|password|token|credential|service.?account|refresh.?token/i;
const forbiddenValue=/(-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|sk-[A-Za-z0-9_-]{16,}|AIza[0-9A-Za-z_-]{20,})/;
const forbiddenContentKey=/question.?plaintext|unsealed.?question|raw.?judge.?audio|biometric/i;
export interface ColdVaultPackage{version:'MIZAN-COLD-VAULT-1';competitionId:string;createdAt:string;createdBy:string;recoveryPointAt:string;contents:string[];contentPolicy:'MINIMUM_CONTINUITY_ONLY';cipher:{algorithm:'AES-256-GCM';iv:string;tag:string;ciphertext:string};payloadHash:string;packageHash:string;privateKeysIncluded:false;assurance:'PORTABLE_ENCRYPTED_EDGE_PACKAGE';restorePolicy:{offlineRequired:true;testRestoreRequired:true;keyExternalToPackage:true}}
export interface ColdVaultRestoreReceipt{version:1;competitionId:string;packageHash:string;testedAt:string;testedBy:string;payloadHash:string;contents:string[];questionPlaintextPresent:false;integrityVerified:true;receiptHash:string}
export class ColdVaultRepository{
 constructor(private root:string){fs.mkdirSync(root,{recursive:true,mode:0o700})}
 private assertMinimum(payload:Record<string,unknown>){const walk=(v:unknown,p='root')=>{if(typeof v==='string'){if(forbiddenValue.test(v))throw new Error(`COLD_VAULT_FORBIDDEN_SECRET_VALUE:${p}`);return}if(!v||typeof v!=='object')return;for(const [k,x] of Object.entries(v as Record<string,unknown>)){if(forbiddenKey.test(k))throw new Error(`COLD_VAULT_FORBIDDEN_SECRET:${p}.${k}`);if(forbiddenContentKey.test(k))throw new Error(`COLD_VAULT_FORBIDDEN_HIGH_RISK_CONTENT:${p}.${k}`);walk(x,`${p}.${k}`)}};walk(payload)}
 export(input:{competitionId:string;createdBy:string;payload:Record<string,unknown>;transferKey:Buffer;recoveryPointAt?:string}){if(input.transferKey.length!==32)throw new Error('COLD_VAULT_KEY_MUST_BE_32_BYTES');if(!input.competitionId.trim())throw new Error('COLD_VAULT_COMPETITION_REQUIRED');this.assertMinimum(input.payload);const plain=Buffer.from(canonical(input.payload)),payloadHash=hash(plain),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',input.transferKey,iv);cipher.setAAD(Buffer.from(`${input.competitionId}|${payloadHash}`));const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();const core={version:'MIZAN-COLD-VAULT-1' as const,competitionId:input.competitionId,createdAt:new Date().toISOString(),createdBy:input.createdBy,recoveryPointAt:input.recoveryPointAt||new Date().toISOString(),contents:Object.keys(input.payload).sort(),contentPolicy:'MINIMUM_CONTINUITY_ONLY' as const,cipher:{algorithm:'AES-256-GCM' as const,iv:iv.toString('base64url'),tag:tag.toString('base64url'),ciphertext:ciphertext.toString('base64url')},payloadHash,privateKeysIncluded:false as const,assurance:'PORTABLE_ENCRYPTED_EDGE_PACKAGE' as const,restorePolicy:{offlineRequired:true as const,testRestoreRequired:true as const,keyExternalToPackage:true as const}};const pkg:ColdVaultPackage={...core,packageHash:hash(canonical(core))};const file=path.join(this.root,`cold-vault-${input.competitionId.replace(/[^A-Za-z0-9._-]/g,'_')}-${Date.now()}.json`);fs.writeFileSync(file,JSON.stringify(pkg,null,2),{encoding:'utf8',mode:0o600});return {package:pkg,file}}
 verify(pkg:ColdVaultPackage){if(!pkg||pkg.version!=='MIZAN-COLD-VAULT-1')return {valid:false,privateKeysIncluded:false};const {packageHash,...core}=pkg;return {valid:hash(canonical(core))===packageHash,privateKeysIncluded:pkg.privateKeysIncluded===false,keyExternalToPackage:pkg.restorePolicy?.keyExternalToPackage===true}}
 restorePreview(pkg:ColdVaultPackage,key:Buffer){const ok=this.verify(pkg);if(!ok.valid)throw new Error('COLD_VAULT_PACKAGE_HASH_MISMATCH');const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(pkg.cipher.iv,'base64url'));decipher.setAAD(Buffer.from(`${pkg.competitionId}|${pkg.payloadHash}`));decipher.setAuthTag(Buffer.from(pkg.cipher.tag,'base64url'));const plain=Buffer.concat([decipher.update(Buffer.from(pkg.cipher.ciphertext,'base64url')),decipher.final()]);if(hash(plain)!==pkg.payloadHash)throw new Error('COLD_VAULT_PAYLOAD_HASH_MISMATCH');const payload=JSON.parse(plain.toString('utf8')) as Record<string,unknown>;this.assertMinimum(payload);return {ok:true,contents:Object.keys(payload).sort(),questionPlaintextPresent:false as const,payload}}
 testRestore(pkg:ColdVaultPackage,key:Buffer,testedBy:string){const preview=this.restorePreview(pkg,key);const core={version:1 as const,competitionId:pkg.competitionId,packageHash:pkg.packageHash,testedAt:new Date().toISOString(),testedBy,payloadHash:pkg.payloadHash,contents:preview.contents,questionPlaintextPresent:false as const,integrityVerified:true as const};const receipt:ColdVaultRestoreReceipt={...core,receiptHash:hash(canonical(core))};const file=path.join(this.root,`cold-vault-restore-${pkg.competitionId.replace(/[^A-Za-z0-9._-]/g,'_')}-${Date.now()}.json`);fs.writeFileSync(file,JSON.stringify(receipt,null,2),{encoding:'utf8',mode:0o600});return {receipt,file}}
}
