import {KFGQPC_OFFICIAL_PACKAGES} from './kfgqpc-official-sources';
import {KFGQPC_DEVELOPER_ASSETS} from './kfgqpc-developer-assets';
import {KFGQPC_OFFICIAL_AUDIO} from './kfgqpc-official-audio';

export type KfgqpcLibraryCapabilityId=
  |'official-mushaf-vector'|'smart-uthmanic-text'|'hafs-package'|'warsh-package'|'shubah-package'|'qalun-package'|'douri-abu-amr-package'|'sousi-abu-amr-package'
  |'tafseer-muyassar'|'ghareeb-muyassar'|'tajweed-muyassar'|'official-fonts'|'desktop-publishing'|'publication-images'|'official-audio';
export type KfgqpcOperationalState='OFFICIALLY_ACCEPTED'|'LOCAL_BYTES_REQUIRED'|'LOCAL_VERIFIED'|'SERVICE_READY';
export interface KfgqpcLibraryCapability{
  id:KfgqpcLibraryCapabilityId;order:number;group:'MUSHAF'|'QURAN_DATA'|'SCIENCE'|'PUBLISHING'|'AUDIO';titleArabic:string;titleEnglish:string;summaryArabic:string;summaryEnglish:string;
  authority:'King Fahd Glorious Quran Printing Complex';authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف';authorityState:'PRIMARY_OFFICIAL_AUTHORITY';scientificState:'CERTIFIED';operationalState:KfgqpcOperationalState;
  officialReference:string;sourceIds:string[];uses:string[];guardrail:string;visualMode?:'VECTOR_PAGE'|'UTHMANIC_TEXT'|'PUBLICATION_IMAGE'|'AUDIO';
}
const AUTH='King Fahd Glorious Quran Printing Complex' as const, AR='مجمع الملك فهد لطباعة المصحف الشريف' as const, REF='https://qurancomplex.gov.sa/en/techquran/dev/';
const pkg=(id:string)=>KFGQPC_OFFICIAL_PACKAGES.find(x=>x.id===id)!;
const mk=(x:Omit<KfgqpcLibraryCapability,'authority'|'authorityArabic'|'authorityState'|'scientificState'>):KfgqpcLibraryCapability=>({...x,authority:AUTH,authorityArabic:AR,authorityState:'PRIMARY_OFFICIAL_AUTHORITY',scientificState:'CERTIFIED'});

export function buildKfgqpcOfficialLibrary(localPackageState?:(id:string)=>string):KfgqpcLibraryCapability[]{
 const local=(id:string)=>localPackageState?.(id)==='CERTIFIED'?'LOCAL_VERIFIED' as const:'LOCAL_BYTES_REQUIRED' as const;
 const capabilities:KfgqpcLibraryCapability[]=[
  mk({id:'official-mushaf-vector',order:1,group:'MUSHAF',titleArabic:'مصحف المدينة الرسمي للطباعة',titleEnglish:'Official Madinah Mushaf vector master',summaryArabic:'الأصل البصري الرسمي عالي الجودة للصفحة، لا صفحة مصممة داخل MIZAN.',summaryEnglish:'Official high-quality visual page master; not a MIZAN-redrawn page.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-madinah-print-vector'],uses:['Official Mushaf Surface','print fallback','ceremony/appeal visual evidence'],guardrail:'Never reconstruct a missing page from another riwayah.',visualMode:'VECTOR_PAGE'}),
  mk({id:'smart-uthmanic-text',order:2,group:'QURAN_DATA',titleArabic:'النص العثماني للأجهزة الذكية',titleEnglish:'Uthmanic text for smart devices',summaryArabic:'نص رسمي للعرض والبحث مع بيانات الصفحة والسطر.',summaryEnglish:'Official display/search text with page and line metadata.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-hafs-smart-device-v6'],uses:['JudgeOS text surface','search','page-line binding'],guardrail:'This text surface does not claim to reproduce the full printed page.',visualMode:'UTHMANIC_TEXT'}),
  mk({id:'hafs-package',order:3,group:'QURAN_DATA',titleArabic:'حفص عن عاصم',titleEnglish:"Hafs 'an Asim",summaryArabic:'حزمة المطورين الرسمية بالرسم العثماني.',summaryEnglish:'Official Uthmanic developer package.',operationalState:local(pkg('kfgqpc-hafs-uthmanic-v13').id),officialReference:REF,sourceIds:[pkg('kfgqpc-hafs-uthmanic-v13').id],uses:['FairDraw','server passage resolution','scientific comparison'],guardrail:'Exact official package only.'}),
  mk({id:'warsh-package',order:4,group:'QURAN_DATA',titleArabic:'ورش عن نافع',titleEnglish:"Warsh 'an Nafi'",summaryArabic:'حزمة مستقلة؛ لا تُشتق من حفص.',summaryEnglish:'Independent official package; never derived from Hafs.',operationalState:local(pkg('kfgqpc-warsh-uthmanic-v6').id),officialReference:REF,sourceIds:[pkg('kfgqpc-warsh-uthmanic-v6').id],uses:['FairDraw','server passage resolution','reading-aware judging'],guardrail:'No Hafs fallback.'}),
  mk({id:'shubah-package',order:5,group:'QURAN_DATA',titleArabic:'شعبة عن عاصم',titleEnglish:"Shu'bah 'an Asim",summaryArabic:'حزمة رسم عثماني مستقلة مع بصماتها الرسمية.',summaryEnglish:'Independent official Uthmanic package with published checksums.',operationalState:local(pkg('kfgqpc-shubah-uthmanic-v4').id),officialReference:REF,sourceIds:[pkg('kfgqpc-shubah-uthmanic-v4').id],uses:['FairDraw','server passage resolution'],guardrail:'Reading isolation is mandatory.'}),
  mk({id:'qalun-package',order:6,group:'QURAN_DATA',titleArabic:'قالون عن نافع',titleEnglish:"Qalun 'an Nafi'",summaryArabic:'حزمة رسم عثماني مستقلة.',summaryEnglish:'Independent official Uthmanic package.',operationalState:local(pkg('kfgqpc-qaloun-uthmanic-v5').id),officialReference:REF,sourceIds:[pkg('kfgqpc-qaloun-uthmanic-v5').id],uses:['FairDraw','server passage resolution'],guardrail:'Reading isolation is mandatory.'}),
  mk({id:'douri-abu-amr-package',order:7,group:'QURAN_DATA',titleArabic:'الدوري عن أبي عمرو',titleEnglish:"Al-Duri 'an Abi Amr",summaryArabic:'مفصول بنيويًا عن الدوري عن الكسائي.',summaryEnglish:"Structurally distinct from Al-Duri 'an Al-Kisa'i.",operationalState:local(pkg('kfgqpc-douri-abu-amr-uthmanic-v3').id),officialReference:REF,sourceIds:[pkg('kfgqpc-douri-abu-amr-uthmanic-v3').id],uses:['FairDraw','server passage resolution'],guardrail:'Al-Duri Abu Amr can never satisfy Al-Duri Al-Kisa’i.'}),
  mk({id:'sousi-abu-amr-package',order:8,group:'QURAN_DATA',titleArabic:'السوسي عن أبي عمرو',titleEnglish:"Al-Susi 'an Abi Amr",summaryArabic:'حزمة رسم عثماني مستقلة.',summaryEnglish:'Independent official Uthmanic package.',operationalState:local(pkg('kfgqpc-sousi-abu-amr-uthmanic-v3').id),officialReference:REF,sourceIds:[pkg('kfgqpc-sousi-abu-amr-uthmanic-v3').id],uses:['FairDraw','server passage resolution'],guardrail:'Reading isolation is mandatory.'}),
  mk({id:'tafseer-muyassar',order:9,group:'SCIENCE',titleArabic:'التفسير الميسر',titleEnglish:'Tafseer Muyassar',summaryArabic:'تفسير رسمي مرتبط بالآية للاستخدام التفسيري والتعليمي.',summaryEnglish:'Official ayah-aligned tafsir for explanatory/learning contexts.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-tafseer-muyassar'],uses:['post-session explanation','training','scientific context'],guardrail:'Never changes scoring unless competition policy explicitly defines a human-reviewed criterion.'}),
  mk({id:'ghareeb-muyassar',order:10,group:'SCIENCE',titleArabic:'الميسر في غريب القرآن',titleEnglish:'Muyassar of Ghareeb Al-Quran',summaryArabic:'شرح رسمي للكلمات القرآنية على مستوى الكلمة.',summaryEnglish:'Official word-level Quranic explanation data.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-muyassar-ghareeb'],uses:['word context','digital twin enrichment','training'],guardrail:'Explanatory evidence only.'}),
  mk({id:'tajweed-muyassar',order:11,group:'SCIENCE',titleArabic:'التجويد الميسر',titleEnglish:'Al-Tajweed al-Muyassar',summaryArabic:'مرجع رسمي لقواعد التجويد؛ ليس نموذج AI تلقائيًا.',summaryEnglish:'Official Tajweed reference; not an automatically certified AI engine.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-tajweed-muyassar'],uses:['rule provenance','scientific review','training'],guardrail:'Reference authority does not certify model detection capability.'}),
  mk({id:'official-fonts',order:12,group:'PUBLISHING',titleArabic:'الخطوط الحاسوبية الرسمية',titleEnglish:'Official Quran computer fonts',summaryArabic:'خطوط مرتبطة بإصدارات المجمع لعرض ونشر النص كما تسمح الحزمة.',summaryEnglish:'Official computer fonts for Quran display/publishing within package scope.',operationalState:'LOCAL_BYTES_REQUIRED',officialReference:REF,sourceIds:['kfgqpc-computer-fonts'],uses:['Official Mushaf Surface','print/export','research'],guardrail:'Font choice follows the exact riwayah/source package; no visual substitution across readings.'}),
  mk({id:'desktop-publishing',order:13,group:'PUBLISHING',titleArabic:'النشر الحاسوبي لمصحف المدينة',titleEnglish:'Madinah Mushaf desktop publishing',summaryArabic:'مسار إخراج رسمي للأوراق والكتيبات وحزم الطوارئ.',summaryEnglish:'Official publishing path for print sheets, booklets and emergency packets.',operationalState:'OFFICIALLY_ACCEPTED',officialReference:REF,sourceIds:['kfgqpc-desktop-publishing'],uses:['question print fallback','official booklets','emergency packet'],guardrail:'Generated material must retain source/version provenance.'}),
  mk({id:'publication-images',order:14,group:'PUBLISHING',titleArabic:'صور إصدارات المجمع',titleEnglish:'KFGQPC publication images',summaryArabic:'مرجع بصري رسمي لصفحات الإصدارات عند توفر خدمة/أصل الصفحة.',summaryEnglish:'Official visual reference for publication pages when the service/asset is available.',operationalState:'OFFICIALLY_ACCEPTED',officialReference:'https://qurancomplex.gov.sa/en/techquran/techquran-apps/techquran-apps-publishios/',sourceIds:['kfgqpc-publication-images'],uses:['Official Mushaf Surface','appeal visual reference','public education'],guardrail:'A publication image never replaces the structured Quran source used by FairDraw.',visualMode:'PUBLICATION_IMAGE'}),
  mk({id:'official-audio',order:16,group:'AUDIO',titleArabic:'المصاحف الصوتية الرسمية',titleEnglish:'Official audio Mushafs',summaryArabic:'تسجيلات المجمع حسب الرواية والقارئ؛ تستخدم فقط عند مطابقة النطاق.',summaryEnglish:'KFGQPC recordings by reading/reciter; playback requires exact scope matching.',operationalState:KFGQPC_OFFICIAL_AUDIO.some(x=>x.availability==='OFFICIAL_RELEASE_CONFIRMED')?'SERVICE_READY':'OFFICIALLY_ACCEPTED',officialReference:'https://qurancomplex.gov.sa/category/kfgqpc-quran-audio/',sourceIds:KFGQPC_OFFICIAL_AUDIO.map(x=>x.id),uses:['opening ayah prompt','judge calibration','scientific alignment'],guardrail:'No TTS and no cross-riwayah audio fallback.',visualMode:'AUDIO'})
 ];
 return capabilities.sort((a,b)=>a.order-b.order);
}

export function kfgqpcLibrarySummary(localPackageState?:(id:string)=>string){
 const items=buildKfgqpcOfficialLibrary(localPackageState);return {authority:AR,protocol:'MIZAN-KFGQPC-OFFICIAL-LIBRARY-1',officiallyAccepted:items.length,localVerified:items.filter(x=>x.operationalState==='LOCAL_VERIFIED').length,serviceReady:items.filter(x=>x.operationalState==='SERVICE_READY').length,requiresLocalBytes:items.filter(x=>x.operationalState==='LOCAL_BYTES_REQUIRED').length,groups:[...new Set(items.map(x=>x.group))]};
}
