import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {KFGQPC_R2_FREE_TIER_BYTES,configuredR2SafetyLimit,kfgqpcActualStorageReport,type KfgqpcActualStorageReport} from './kfgqpc-delivery';
import type {R2ObjectInfo} from './r2-private';
import {isOfficialKfgqpcUrl} from './kfgqpc-authority';

export type KfgqpcIngestStatus='VERIFIED'|'QUARANTINED'|'UNVERIFIED'|'OFFICIAL_AUDIO_UNAVAILABLE';
export interface KfgqpcChecksumExpectation{md5?:string;sha1?:string;sha256?:string}
export interface KfgqpcChecksumResult{md5:string;sha1:string;sha256:string;status:'VERIFIED'|'QUARANTINED';mismatches:string[]}
export interface KfgqpcPackageManifest{
  schemaVersion:'MIZAN-KFGQPC-MANIFEST-1';sourceAuthority:'King Fahd Glorious Quran Printing Complex';sourceUrl:string;downloadedAt?:string;packageName:string;packageVersion?:string;reading?:string;rawi?:string;tariq?:string;reciter?:string;fileCount:number;totalBytes:number;officialChecksum?:KfgqpcChecksumExpectation;computedChecksum?:KfgqpcChecksumResult;sha256:string;ingestedAt:string;r2Prefix:string;status:KfgqpcIngestStatus;notes?:string[];
}

// Compatibility export: every HTTPS subdomain of qurancomplex.gov.sa is accepted as KFGQPC-owned.
export const KFGQPC_AUTHORITY_HOSTS=new Set(['qurancomplex.gov.sa','www.qurancomplex.gov.sa','qc-dev.qurancomplex.gov.sa','download.qurancomplex.gov.sa','fonts.qurancomplex.gov.sa','dm.qurancomplex.gov.sa']);
export function assertOfficialKfgqpcUrl(value:string){if(!isOfficialKfgqpcUrl(value))throw new Error('KFGQPC_SOURCE_URL_NOT_OFFICIAL');return new URL(value).toString()}
const norm=(v?:string)=>String(v||'').trim().toLowerCase();
export function hashFile(file:string){const data=fs.readFileSync(file);return {md5:crypto.createHash('md5').update(data).digest('hex'),sha1:crypto.createHash('sha1').update(data).digest('hex'),sha256:crypto.createHash('sha256').update(data).digest('hex')}}
export function verifyFileChecksums(file:string,expected:KfgqpcChecksumExpectation={}):KfgqpcChecksumResult{const computed=hashFile(file),mismatches:string[]=[];for(const alg of ['md5','sha1','sha256'] as const){if(expected[alg]&&norm(expected[alg])!==norm(computed[alg]))mismatches.push(alg.toUpperCase())}return {...computed,status:mismatches.length?'QUARANTINED':'VERIFIED',mismatches}}
export function listFilesRecursive(root:string){const out:string[]=[];const walk=(dir:string)=>{for(const name of fs.readdirSync(dir)){const file=path.join(dir,name),st=fs.statSync(file);if(st.isDirectory())walk(file);else if(st.isFile())out.push(file)}};walk(root);return out.sort()}
export function hashDirectory(root:string){const files=listFilesRecursive(root);const h=crypto.createHash('sha256');let totalBytes=0;for(const file of files){const rel=path.relative(root,file).split(path.sep).join('/'),data=fs.readFileSync(file);totalBytes+=data.length;h.update(rel);h.update('\0');h.update(crypto.createHash('sha256').update(data).digest());h.update('\0')}return {sha256:h.digest('hex'),fileCount:files.length,totalBytes,files}}
export function validateMushafDeliveryPages(root:string){const missing:number[]=[];const found:string[]=[];for(let page=1;page<=604;page++){const stem=String(page).padStart(3,'0');const candidates=['avif','webp','png'].map(ext=>path.join(root,`${stem}.${ext}`));const file=candidates.find(x=>fs.existsSync(x)&&fs.statSync(x).isFile());if(file)found.push(file);else missing.push(page)}const extras=listFilesRecursive(root).filter(x=>/\.(?:avif|webp|png)$/i.test(x)&&!found.includes(x));return {valid:missing.length===0&&found.length===604,foundCount:found.length,missing,extras}}
export function assertUploadFitsBudget(existing:R2ObjectInfo[],newBytes:number,env:NodeJS.ProcessEnv=process.env){const current=kfgqpcActualStorageReport(existing,env),safety=configuredR2SafetyLimit(env),projected=current.totalBytes+Math.max(0,newBytes);if(projected>=KFGQPC_R2_FREE_TIER_BYTES)throw new Error('R2_FREE_TIER_BUDGET_EXCEEDED');if(projected>=safety)throw new Error('R2_SAFETY_LIMIT_EXCEEDED');return {current,projectedBytes:projected,safetyLimitBytes:safety,freeTierBytes:KFGQPC_R2_FREE_TIER_BYTES}}
export function storageReport(objects:R2ObjectInfo[],env:NodeJS.ProcessEnv=process.env):KfgqpcActualStorageReport{return kfgqpcActualStorageReport(objects,env)}
export function buildPackageManifest(input:Omit<KfgqpcPackageManifest,'schemaVersion'|'sourceAuthority'|'ingestedAt'>):KfgqpcPackageManifest{assertOfficialKfgqpcUrl(input.sourceUrl);return {schemaVersion:'MIZAN-KFGQPC-MANIFEST-1',sourceAuthority:'King Fahd Glorious Quran Printing Complex',ingestedAt:new Date().toISOString(),...input}}

export interface KfgqpcDeliveryCatalogDataset{id:string;status:KfgqpcIngestStatus;r2Prefix:string;fileCount?:number;totalBytes?:number;sha256?:string;reading?:string;rawi?:string;reciter?:string;note?:string}
export interface KfgqpcDeliveryCatalog{schemaVersion:'MIZAN-R2-CATALOG-1';authority:'King Fahd Glorious Quran Printing Complex';generatedAt:string;state:'READY';datasets:KfgqpcDeliveryCatalogDataset[];storage:KfgqpcActualStorageReport;unavailableAudio:string[];unverifiedAudio:string[]}
export const KFGQPC_REQUIRED_DELIVERY_DATASETS=['hafs','warsh','shubah','qalun','duri-data','susi-data','tafsir','ghareeb','tajweed','mushaf-pages','audio-hafs','audio-shubah','audio-qalun','audio-susi'] as const;
export function buildReadyDeliveryCatalog(input:{datasets:KfgqpcDeliveryCatalogDataset[];storage:KfgqpcActualStorageReport}){const byId=new Map(input.datasets.map(x=>[x.id,x]));const missing=KFGQPC_REQUIRED_DELIVERY_DATASETS.filter(id=>byId.get(id)?.status!=='VERIFIED');if(missing.length)throw new Error(`R2_DELIVERY_CATALOG_INCOMPLETE:${missing.join(',')}`);if(!input.storage.withinSafetyLimit||!input.storage.withinFreeTier)throw new Error('R2_DELIVERY_CATALOG_STORAGE_LIMIT');const warsh=byId.get('audio-warsh'),duri=byId.get('audio-duri');if(warsh&&!['OFFICIAL_AUDIO_UNAVAILABLE','VERIFIED'].includes(warsh.status))throw new Error('R2_WARSH_AUDIO_STATUS_INVALID');if(duri&&!['UNVERIFIED','VERIFIED'].includes(duri.status))throw new Error('R2_DURI_AUDIO_STATUS_INVALID');return {schemaVersion:'MIZAN-R2-CATALOG-1' as const,authority:'King Fahd Glorious Quran Printing Complex' as const,generatedAt:new Date().toISOString(),state:'READY' as const,datasets:input.datasets,storage:input.storage,unavailableAudio:warsh?.status==='OFFICIAL_AUDIO_UNAVAILABLE'?['audio-warsh']:[],unverifiedAudio:duri?.status==='UNVERIFIED'?['audio-duri']:[]}}
