export type KfgqpcAudioAvailability='OFFICIAL_RELEASE_CONFIRMED'|'OFFICIAL_RECORDING_CONFIRMED_DOWNLOAD_MAPPING_PENDING'|'IN_PROGRESS_OR_HISTORICAL_NOTICE';
export interface KfgqpcOfficialAudioCatalogItem {
  id:string;authority:'King Fahd Glorious Quran Printing Complex';authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف';authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY';qiraah:string;rawi:string;tariq?:string;reciter:string;reciterArabic:string;availability:KfgqpcAudioAvailability;officialReference:string;usageNote:string;
}

const ref='https://qurancomplex.gov.sa/en/kfgqpc/kfq-structure/';
export const KFGQPC_OFFICIAL_AUDIO:KfgqpcOfficialAudioCatalogItem[]=[
 {id:'kfgqpc-audio-hafs-hudhaifi',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",reciter:'Ali ibn Abdulrahman Al-Hudhaifi',reciterArabic:'الشيخ د. علي بن عبدالرحمن الحذيفي',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC audio Mushaf; ingest the original audio files and verify file hashes before APPROVED_REFERENCE.'},
 {id:'kfgqpc-audio-hafs-muaiqly',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",reciter:'Maher bin Hamad Al-Muaiqly',reciterArabic:'الشيخ د. ماهر بن حمد المعيقلي',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:'https://qurancomplex.gov.sa/category/kfgqpc-quran-audio/recite/hafs/',usageNote:'Official KFGQPC downloadable Hafs audio Mushaf. Bind exact downloaded audio bytes and hashes before APPROVED_REFERENCE.'},
 {id:'kfgqpc-audio-hafs-ibrahim-akhdar',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",reciter:'Ibrahim bin Al-Akhdar Al-Qayyim',reciterArabic:'الشيخ إبراهيم بن الأخضر القيم',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC audio Mushaf; ingest original bytes before local approval.'},
 {id:'kfgqpc-audio-hafs-muhammad-ayyub',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",reciter:'Muhammad Ayyub',reciterArabic:'الشيخ محمد أيوب',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC audio Mushaf; ingest original bytes before local approval.'},
 {id:'kfgqpc-audio-hafs-abdullah-basfar',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",reciter:'Abdullah bin Ali Basfar',reciterArabic:'الشيخ عبدالله بن علي بصفر',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC audio Mushaf; ingest original bytes before local approval.'},
 {id:'kfgqpc-audio-hafs-imad-hafiz',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",tariq:'Qasr al-Munfasil recording scope',reciter:'Imad bin Zuhair Hafiz',reciterArabic:'الشيخ عماد بن زهير حافظ',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC Hafs recording with Qasr al-Munfasil scope; preserve exact reading scope.'},
 {id:'kfgqpc-audio-hafs-khalid-muhanna',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Hafs 'an Asim",tariq:'Qasr al-Munfasil recording scope',reciter:'Khalid bin Sulaiman Al-Muhanna',reciterArabic:'الشيخ د. خالد بن سليمان المهنا',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC Hafs recording with Qasr al-Munfasil scope; preserve exact reading scope.'},
 {id:'kfgqpc-audio-qalun-hudhaifi',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Nafi'",rawi:"Qalun 'an Nafi'",reciter:'Ali ibn Abdulrahman Al-Hudhaifi',reciterArabic:'الشيخ د. علي بن عبدالرحمن الحذيفي',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC Qalun audio Mushaf.'},
 {id:'kfgqpc-audio-warsh-dawsari',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Nafi'",rawi:"Warsh 'an Nafi'",reciter:'Ibrahim bin Saeed Al-Dawsari',reciterArabic:'الشيخ د. إبراهيم بن سعيد الدوسري',availability:'OFFICIAL_RECORDING_CONFIRMED_DOWNLOAD_MAPPING_PENDING',officialReference:ref,usageNote:'KFGQPC confirms the Warsh audio Mushaf. MIZAN must ingest/verify the actual current files and ayah mapping before APPROVED_REFERENCE.'},
 {id:'kfgqpc-audio-shubah-hudhaifi',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Asim",rawi:"Shu'bah 'an Asim",reciter:'Ali ibn Abdulrahman Al-Hudhaifi',reciterArabic:'الشيخ د. علي بن عبدالرحمن الحذيفي',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:ref,usageNote:'Official KFGQPC Shu\'bah audio Mushaf.'},
 {id:'kfgqpc-audio-susi-siddiqi',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Abu Amr",rawi:"Al-Susi 'an Abi Amr",reciter:'Uthman Al-Siddiqi',reciterArabic:'الشيخ د. عثمان الصديقي',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:'https://qurancomplex.gov.sa/category/kfgqpc-quran-audio/recite/',usageNote:'Official KFGQPC downloadable Al-Susi an Abi Amr audio Mushaf; bind exact downloaded audio bytes and hashes before APPROVED_REFERENCE.'},
 {id:'kfgqpc-audio-duri-abi-amr-juhani',authority:'King Fahd Glorious Quran Printing Complex',authorityArabic:'مجمع الملك فهد لطباعة المصحف الشريف',authorityTrust:'PRIMARY_OFFICIAL_AUTHORITY',qiraah:"Qira'at Abu Amr",rawi:"Al-Duri 'an Abi Amr",reciter:'Abdullah bin Awad Al-Juhani',reciterArabic:'الشيخ د. عبدالله بن عواد الجهني',availability:'OFFICIAL_RELEASE_CONFIRMED',officialReference:'https://qurancomplex.gov.sa/category/kfgqpc-quran-audio/recite/',usageNote:'Official KFGQPC downloadable Al-Duri an Abi Amr audio Mushaf. Never confuse it with Al-Duri an Al-Kisa\'i; bind exact downloaded audio bytes and hashes before APPROVED_REFERENCE.'}
];
