import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

export type CommercialRole='super_admin'|'operator_owner'|'operator_admin'|'org_admin'|'storage_admin'|'billing_admin';
export type CommercialActor={uid:string;role:string;organizationId:string;operatorId?:string};
export type LicenseState='active'|'grace_period'|'suspended'|'expired'|'archived';
export type StorageProvider='mizan'|'cloudflare_r2'|'amazon_s3'|'google_cloud_storage'|'azure_blob';
export type CompetitionCommercialState='draft'|'registration_open'|'registration_closed'|'judging'|'completed'|'archived';

export interface PlanRecord{
 id:string;name:string;currency:string;priceMinor:number;billingPeriod:'monthly'|'annual'|'custom';active:boolean;
 limits:{licensedOrganizations:number;activeCompetitions:number;annualParticipants:number;storageBytes:number;branches:number;videoBytes?:number};
 features:Record<string,boolean>;createdAt:string;updatedAt:string;
}
export interface OperatorRecord{id:string;name:string;status:'active'|'suspended';pricingTier:string;whiteLabelLevel:'mizan'|'co_branded'|'full';createdAt:string}
export interface OrganizationRecord{
 id:string;tenantId:string;licenseId:string;officialName:string;shortName:string;organizationType:string;country:string;
 legalEmail?:string;legalPhone?:string;website?:string;legalRegistration?:string;primaryContact?:string;operatorId?:string;
 operational:{phone?:string;notificationEmail?:string;contactName?:string;address?:string};status:'active'|'suspended'|'archived';createdAt:string;updatedAt:string;
}
export interface LicenseRecord{
 id:string;organizationId:string;planId:string;startsAt:string;expiresAt:string;status:LicenseState;graceUntil?:string;
 overrides?:Partial<{activeCompetitions:number;annualParticipants:number;storageBytes:number;branches:number}>;
 whiteLabelEnabled:boolean;brandingLevel:'mizan'|'co_branded'|'full';customDomainEnabled:boolean;uploadsDisabled?:boolean;
 temporaryStorageBoost?:{bytes:number;expiresAt:string;reason:string};createdAt:string;updatedAt:string;
}
export interface CreditLedgerRow{id:string;operatorId:string;kind:'purchase'|'consume'|'refund'|'admin_adjustment'|'expire';quantity:number;balanceAfter:number;reason:string;reference?:string;createdAt:string;actorId:string}
export interface ParticipantUsageRow{id:string;tenantId:string;organizationId:string;competitionId:string;participantId:string;year:number;createdAt:string}
export interface CompetitionUsageRow{id:string;tenantId:string;organizationId:string;organizerOrganizationId:string;state:CompetitionCommercialState;updatedAt:string}
export interface StorageObjectRecord{id:string;tenantId:string;organizationId:string;competitionId?:string;fileType:string;mimeType:string;sizeBytes:number;provider:StorageProvider;storageKey:string;category:'audio'|'video'|'image'|'document'|'other';state:'reserved'|'stored'|'migrating'|'deleted';checksum?:string;createdAt:string;deletedAt?:string}
export interface StorageAccountRecord{id:string;tenantId:string;organizationId:string;provider:Exclude<StorageProvider,'mizan'>;container:string;region?:string;endpoint?:string;connectionStatus:'pending_test'|'connected'|'degraded'|'disconnected'|'migrating';lastTestedAt?:string;lastTestResult?:string;secretReference:string;isPrimary:boolean;createdAt:string;updatedAt:string}
export interface StorageMigrationRecord{id:string;tenantId:string;organizationId:string;source:StorageProvider;destination:StorageProvider;status:'queued'|'running'|'paused'|'completed'|'failed';totalFiles:number;completedFiles:number;failedFiles:number;sourceDeletionPolicy:'retain'|'delete_after_verification';createdAt:string;updatedAt:string}
export interface ChangeRequestRecord{id:string;organizationId:string;tenantId:string;field:keyof Pick<OrganizationRecord,'officialName'|'country'|'operatorId'|'legalEmail'|'legalPhone'>;currentValue:string;requestedValue:string;reason:string;attachmentRef?:string;status:'pending'|'approved'|'rejected'|'needs_information';submittedBy:string;createdAt:string;decidedAt?:string;decidedBy?:string;decisionNote?:string}
export interface AuditRow{id:string;sequence:number;timestamp:string;actorId:string;actorRole:string;tenantId?:string;organizationId?:string;action:string;entityType:string;entityId:string;reason?:string;previousHash:string;hash:string}

interface State{
 version:1;sequence:number;plans:PlanRecord[];operators:OperatorRecord[];organizations:OrganizationRecord[];licenses:LicenseRecord[];
 creditLedger:CreditLedgerRow[];participantUsage:ParticipantUsageRow[];competitions:CompetitionUsageRow[];storageObjects:StorageObjectRecord[];
 storageAccounts:StorageAccountRecord[];storageMigrations:StorageMigrationRecord[];changeRequests:ChangeRequestRecord[];audit:AuditRow[];
}

const now=()=>new Date().toISOString();
const clean=(v:unknown,max=200)=>String(v??'').trim().slice(0,max);
const positive=(v:unknown)=>Math.max(0,Math.floor(Number(v)||0));
const canonical=(value:unknown):string=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;const o=value as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`};
const hash=(value:unknown)=>crypto.createHash('sha256').update(canonical(value)).digest('hex');
const safeId=(prefix:string,sequence:number)=>`${prefix}-${String(sequence).padStart(6,'0')}`;
const activeCompetitionStates=new Set<CompetitionCommercialState>(['registration_open','registration_closed','judging']);
const storageCategory=(mime:string):StorageObjectRecord['category']=>mime.startsWith('audio/')?'audio':mime.startsWith('video/')?'video':mime.startsWith('image/')?'image':mime==='application/pdf'||mime.includes('document')?'document':'other';

export class SecretVault{
 private key:Buffer;
 constructor(private file:string,masterKey:string){if(masterKey.length<24)throw new Error('STORAGE_SECRET_MASTER_KEY_REQUIRED');this.key=crypto.createHash('sha256').update(masterKey).digest();fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700})}
 private read():Record<string,string>{try{return JSON.parse(fs.readFileSync(this.file,'utf8'))}catch{return {}}}
 put(secret:Record<string,string>){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',this.key,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(secret),'utf8'),cipher.final()]);const ref=`sec_${crypto.randomUUID()}`;const rows=this.read();rows[ref]=Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64url');this.write(rows);return ref}
 get(ref:string){const raw=this.read()[ref];if(!raw)throw new Error('STORAGE_SECRET_NOT_FOUND');const b=Buffer.from(raw,'base64url'),iv=b.subarray(0,12),tag=b.subarray(12,28),data=b.subarray(28);const decipher=crypto.createDecipheriv('aes-256-gcm',this.key,iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8')) as Record<string,string>}
 remove(ref:string){const rows=this.read();delete rows[ref];this.write(rows)}
 private write(rows:Record<string,string>){const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(rows),{mode:0o600});fs.renameSync(tmp,this.file)}
}

export type StorageProbe=(account:StorageAccountRecord,secret:Record<string,string>)=>Promise<{upload:boolean;read:boolean;remove:boolean;code?:string;availableBytes?:number}>;

export class SaaSPlatformRepository{
 constructor(private file:string,private vault?:SecretVault,private probe?:StorageProbe){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});if(!fs.existsSync(file))this.write(this.empty())}
 private empty():State{return {version:1,sequence:0,plans:[],operators:[],organizations:[],licenses:[],creditLedger:[],participantUsage:[],competitions:[],storageObjects:[],storageAccounts:[],storageMigrations:[],changeRequests:[],audit:[]}}
 private read():State{try{const s=JSON.parse(fs.readFileSync(this.file,'utf8')) as State;return {...this.empty(),...s}}catch{return this.empty()}}
 private write(s:State){const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(s,null,2),{mode:0o600});fs.renameSync(tmp,this.file)}
 private mutate<T>(fn:(s:State)=>T):T{const s=this.read(),out=fn(s);this.write(s);return out}
 private next(s:State,prefix:string){s.sequence++;return safeId(prefix,s.sequence)}
 private audit(s:State,actor:CommercialActor,input:{tenantId?:string;organizationId?:string;action:string;entityType:string;entityId:string;reason?:string}){const previous=s.audit.at(-1)?.hash||'GENESIS';const base={id:this.next(s,'AUD'),sequence:s.audit.length+1,timestamp:now(),actorId:actor.uid,actorRole:actor.role,...input,previousHash:previous};const row:AuditRow={...base,hash:hash(base)};s.audit.push(row);return row}
 private super(actor:CommercialActor){if(actor.role!=='super_admin')throw new Error('SUPER_ADMIN_REQUIRED')}
 private orgScope(actor:CommercialActor,organizationId:string){if(actor.role==='super_admin')return;const org=this.read().organizations.find(x=>x.id===organizationId);if(!org)throw new Error('ORGANIZATION_NOT_FOUND');if(['operator_owner','operator_admin'].includes(actor.role)&&actor.operatorId&&org.operatorId===actor.operatorId)return;if(actor.organizationId!==organizationId)throw new Error('CROSS_TENANT_ACCESS_BLOCKED')}
 private planLimits(s:State,license:LicenseRecord){const p=s.plans.find(x=>x.id===license.planId);if(!p)throw new Error('PLAN_NOT_FOUND');const boost=license.temporaryStorageBoost&&Date.parse(license.temporaryStorageBoost.expiresAt)>Date.now()?license.temporaryStorageBoost.bytes:0;return {activeCompetitions:license.overrides?.activeCompetitions??p.limits.activeCompetitions,annualParticipants:license.overrides?.annualParticipants??p.limits.annualParticipants,storageBytes:(license.overrides?.storageBytes??p.limits.storageBytes)+boost,branches:license.overrides?.branches??p.limits.branches}}

 seedInitialPlan(actor:CommercialActor,input?:Partial<PlanRecord>){this.super(actor);return this.mutate(s=>{if(s.plans.length)return s.plans[0];const t=now();const p:PlanRecord={id:this.next(s,'PLAN'),name:clean(input?.name||'Basic',80),currency:clean(input?.currency||'KWD',3).toUpperCase(),priceMinor:positive(input?.priceMinor),billingPeriod:input?.billingPeriod||'annual',active:true,limits:{licensedOrganizations:positive(input?.limits?.licensedOrganizations||1),activeCompetitions:positive(input?.limits?.activeCompetitions||3),annualParticipants:positive(input?.limits?.annualParticipants||2500),storageBytes:positive(input?.limits?.storageBytes||10*1024**3),branches:positive(input?.limits?.branches||3)},features:{external_storage:false,white_label:false,video:false,...input?.features},createdAt:t,updatedAt:t};s.plans.push(p);this.audit(s,actor,{action:'PLAN_CREATED',entityType:'plan',entityId:p.id});return p})}
 upsertPlan(actor:CommercialActor,input:Partial<PlanRecord>){this.super(actor);return this.mutate(s=>{const t=now(),existing=input.id?s.plans.find(x=>x.id===input.id):undefined;const p:PlanRecord={id:existing?.id||this.next(s,'PLAN'),name:clean(input.name||existing?.name,80),currency:clean(input.currency||existing?.currency||'KWD',3).toUpperCase(),priceMinor:positive(input.priceMinor??existing?.priceMinor),billingPeriod:input.billingPeriod||existing?.billingPeriod||'annual',active:input.active??existing?.active??true,limits:{licensedOrganizations:positive(input.limits?.licensedOrganizations??existing?.limits.licensedOrganizations??1),activeCompetitions:positive(input.limits?.activeCompetitions??existing?.limits.activeCompetitions??3),annualParticipants:positive(input.limits?.annualParticipants??existing?.limits.annualParticipants??2500),storageBytes:positive(input.limits?.storageBytes??existing?.limits.storageBytes??10*1024**3),branches:positive(input.limits?.branches??existing?.limits.branches??3),videoBytes:input.limits?.videoBytes??existing?.limits.videoBytes},features:{...(existing?.features||{}),...(input.features||{})},createdAt:existing?.createdAt||t,updatedAt:t};if(!p.name)throw new Error('PLAN_NAME_REQUIRED');if(existing)Object.assign(existing,p);else s.plans.push(p);this.audit(s,actor,{action:existing?'PLAN_UPDATED':'PLAN_CREATED',entityType:'plan',entityId:p.id});return p})}
 deletePlan(actor:CommercialActor,id:string){this.super(actor);return this.mutate(s=>{const index=s.plans.findIndex(x=>x.id===id);if(index<0)throw new Error('PLAN_NOT_FOUND');if(s.licenses.some(x=>x.planId===id))throw new Error('PLAN_IN_USE');const [plan]=s.plans.splice(index,1);this.audit(s,actor,{action:'PLAN_DELETED',entityType:'plan',entityId:id,reason:plan.name});return {id,name:plan.name}})}
 createOperator(actor:CommercialActor,input:{name:string;pricingTier?:string;whiteLabelLevel?:OperatorRecord['whiteLabelLevel']}){this.super(actor);return this.mutate(s=>{const op:OperatorRecord={id:this.next(s,'OP'),name:clean(input.name,120),status:'active',pricingTier:clean(input.pricingTier||'standard',40),whiteLabelLevel:input.whiteLabelLevel||'mizan',createdAt:now()};if(!op.name)throw new Error('OPERATOR_NAME_REQUIRED');s.operators.push(op);this.audit(s,actor,{action:'OPERATOR_CREATED',entityType:'operator',entityId:op.id});return op})}
 creditBalance(s:State,operatorId:string){return s.creditLedger.filter(x=>x.operatorId===operatorId).reduce((n,x)=>n+x.quantity,0)}
 adjustCredits(actor:CommercialActor,operatorId:string,quantity:number,reason:string,kind:CreditLedgerRow['kind']='admin_adjustment'){this.super(actor);if(!Number.isInteger(quantity)||quantity===0)throw new Error('CREDIT_QUANTITY_INVALID');if(clean(reason).length<3)throw new Error('REASON_REQUIRED');return this.mutate(s=>{const op=s.operators.find(x=>x.id===operatorId);if(!op)throw new Error('OPERATOR_NOT_FOUND');const balance=this.creditBalance(s,operatorId)+quantity;if(balance<0)throw new Error('INSUFFICIENT_LICENSE_CREDITS');const row:CreditLedgerRow={id:this.next(s,'CR'),operatorId,kind,quantity,balanceAfter:balance,reason:clean(reason,300),createdAt:now(),actorId:actor.uid};s.creditLedger.push(row);this.audit(s,actor,{action:'LICENSE_CREDITS_ADJUSTED',entityType:'operator',entityId:operatorId,reason});return row})}
 createOrganization(actor:CommercialActor,input:{officialName:string;shortName:string;organizationType:string;country:string;legalEmail?:string;legalPhone?:string;website?:string;legalRegistration?:string;primaryContact?:string;operatorId?:string;planId:string;startsAt:string;expiresAt:string}){return this.mutate(s=>{const operatorId=input.operatorId||(actor.role.startsWith('operator_')?actor.operatorId:undefined);if(actor.role!=='super_admin'&&(!['operator_owner','operator_admin'].includes(actor.role)||!operatorId||operatorId!==actor.operatorId))throw new Error('ORGANIZATION_CREATE_NOT_ALLOWED');if(operatorId){const op=s.operators.find(x=>x.id===operatorId&&x.status==='active');if(!op)throw new Error('OPERATOR_NOT_ACTIVE');if(this.creditBalance(s,operatorId)<1)throw new Error('INSUFFICIENT_LICENSE_CREDITS')}
 const plan=s.plans.find(x=>x.id===input.planId&&x.active);if(!plan)throw new Error('PLAN_NOT_FOUND');if(!clean(input.officialName)||!clean(input.shortName)||!clean(input.country))throw new Error('ORGANIZATION_IDENTITY_REQUIRED');if(Date.parse(input.expiresAt)<=Date.parse(input.startsAt))throw new Error('LICENSE_DATES_INVALID');const orgId=this.next(s,'MZ-ORG'),tenantId=this.next(s,'MZ-TEN'),licenseId=this.next(s,'MZ-LIC'),t=now();const org:OrganizationRecord={id:orgId,tenantId,licenseId,officialName:clean(input.officialName,180),shortName:clean(input.shortName,80),organizationType:clean(input.organizationType,80),country:clean(input.country,2).toUpperCase(),legalEmail:clean(input.legalEmail,180)||undefined,legalPhone:clean(input.legalPhone,40)||undefined,website:clean(input.website,240)||undefined,legalRegistration:clean(input.legalRegistration,100)||undefined,primaryContact:clean(input.primaryContact,120)||undefined,operatorId,status:'active',operational:{},createdAt:t,updatedAt:t};const license:LicenseRecord={id:licenseId,organizationId:orgId,planId:plan.id,startsAt:new Date(input.startsAt).toISOString(),expiresAt:new Date(input.expiresAt).toISOString(),status:'active',whiteLabelEnabled:false,brandingLevel:'mizan',customDomainEnabled:false,createdAt:t,updatedAt:t};s.organizations.push(org);s.licenses.push(license);if(operatorId){const balance=this.creditBalance(s,operatorId)-1;s.creditLedger.push({id:this.next(s,'CR'),operatorId,kind:'consume',quantity:-1,balanceAfter:balance,reason:`Organization ${org.id}`,reference:org.id,createdAt:t,actorId:actor.uid})}this.audit(s,actor,{tenantId,organizationId:org.id,action:'ORGANIZATION_CREATED',entityType:'organization',entityId:org.id,reason:operatorId?'operator license credit consumed':'direct MIZAN customer'});return {organization:org,license,creditBalance:operatorId?this.creditBalance(s,operatorId):undefined}})}
 migrateLegacyTenants(actor:CommercialActor,tenants:{orgId:string;displayNameArabic?:string;displayName?:string;status?:string}[],planId:string){this.super(actor);return this.mutate(s=>{let migrated=0;for(const old of tenants){if(s.organizations.some(x=>x.id===old.orgId))continue;const t=now(),tenantId=this.next(s,'MZ-TEN'),licenseId=this.next(s,'MZ-LIC');s.organizations.push({id:old.orgId,tenantId,licenseId,officialName:clean(old.displayNameArabic||old.displayName||old.orgId),shortName:clean(old.displayNameArabic||old.displayName||old.orgId,80),organizationType:'legacy',country:'KW',operational:{},status:old.status==='suspended'?'suspended':'active',createdAt:t,updatedAt:t});s.licenses.push({id:licenseId,organizationId:old.orgId,planId,startsAt:t,expiresAt:new Date(Date.now()+365*86400_000).toISOString(),status:'active',whiteLabelEnabled:false,brandingLevel:'mizan',customDomainEnabled:false,createdAt:t,updatedAt:t});this.audit(s,actor,{tenantId,organizationId:old.orgId,action:'LEGACY_ORGANIZATION_MIGRATED',entityType:'organization',entityId:old.orgId});migrated++}return {migrated}})}
 updateOperational(actor:CommercialActor,organizationId:string,patch:OrganizationRecord['operational']){this.orgScope(actor,organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===organizationId);if(!org)throw new Error('ORGANIZATION_NOT_FOUND');org.operational={...org.operational,...Object.fromEntries(Object.entries(patch||{}).map(([k,v])=>[k,clean(v,240)]))};org.updatedAt=now();this.audit(s,actor,{tenantId:org.tenantId,organizationId,action:'ORGANIZATION_OPERATIONAL_PROFILE_UPDATED',entityType:'organization',entityId:organizationId});return org})}
 requestIdentityChange(actor:CommercialActor,organizationId:string,input:{field:ChangeRequestRecord['field'];requestedValue:string;reason:string;attachmentRef?:string}){this.orgScope(actor,organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===organizationId);if(!org)throw new Error('ORGANIZATION_NOT_FOUND');if(!['officialName','country','operatorId','legalEmail','legalPhone'].includes(input.field))throw new Error('IDENTITY_FIELD_NOT_REQUESTABLE');const current=clean((org as unknown as Record<string,unknown>)[input.field]);if(!clean(input.requestedValue)||clean(input.reason).length<5)throw new Error('CHANGE_REQUEST_INCOMPLETE');const row:ChangeRequestRecord={id:this.next(s,'REQ'),organizationId,tenantId:org.tenantId,field:input.field,currentValue:current,requestedValue:clean(input.requestedValue,240),reason:clean(input.reason,500),attachmentRef:clean(input.attachmentRef,240)||undefined,status:'pending',submittedBy:actor.uid,createdAt:now()};s.changeRequests.push(row);this.audit(s,actor,{tenantId:org.tenantId,organizationId,action:'ORGANIZATION_IDENTITY_CHANGE_REQUESTED',entityType:'change_request',entityId:row.id,reason:row.reason});return row})}
 decideChange(actor:CommercialActor,id:string,decision:'approved'|'rejected'|'needs_information',note:string){this.super(actor);return this.mutate(s=>{const r=s.changeRequests.find(x=>x.id===id);if(!r||r.status!=='pending')throw new Error('CHANGE_REQUEST_NOT_PENDING');if(decision!=='approved'&&clean(note).length<3)throw new Error('DECISION_NOTE_REQUIRED');r.status=decision;r.decidedAt=now();r.decidedBy=actor.uid;r.decisionNote=clean(note,500)||undefined;if(decision==='approved'){const org=s.organizations.find(x=>x.id===r.organizationId);if(!org)throw new Error('ORGANIZATION_NOT_FOUND');(org as unknown as Record<string,unknown>)[r.field]=r.requestedValue;org.updatedAt=now()}this.audit(s,actor,{tenantId:r.tenantId,organizationId:r.organizationId,action:`ORGANIZATION_CHANGE_${decision.toUpperCase()}`,entityType:'change_request',entityId:r.id,reason:note});return r})}
 setCompetitionState(actor:CommercialActor,input:{organizationId:string;competitionId:string;organizerOrganizationId?:string;state:CompetitionCommercialState}){this.orgScope(actor,input.organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===input.organizationId),license=s.licenses.find(x=>x.organizationId===input.organizationId);if(!org||!license)throw new Error('LICENSE_NOT_FOUND');const organizer=input.organizerOrganizationId||input.organizationId;if(organizer!==input.organizationId)throw new Error('INDEPENDENT_ORGANIZER_REQUIRES_LICENSE');const existing=s.competitions.find(x=>x.id===input.competitionId&&x.organizationId===input.organizationId);if(activeCompetitionStates.has(input.state)&&(!existing||!activeCompetitionStates.has(existing.state))){const count=s.competitions.filter(x=>x.organizationId===input.organizationId&&activeCompetitionStates.has(x.state)).length;if(count>=this.planLimits(s,license).activeCompetitions)throw new Error('ACTIVE_COMPETITION_LIMIT_REACHED')}const row:CompetitionUsageRow=existing||{id:clean(input.competitionId,120),tenantId:org.tenantId,organizationId:org.id,organizerOrganizationId:organizer,state:'draft',updatedAt:now()};row.state=input.state;row.updatedAt=now();if(!existing)s.competitions.push(row);this.audit(s,actor,{tenantId:org.tenantId,organizationId:org.id,action:'COMPETITION_STATE_CHANGED',entityType:'competition',entityId:row.id,reason:row.state});return row})}
 recordParticipant(actor:CommercialActor,input:{organizationId:string;competitionId:string;participantId:string;year?:number}){this.orgScope(actor,input.organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===input.organizationId),license=s.licenses.find(x=>x.organizationId===input.organizationId);if(!org||!license)throw new Error('LICENSE_NOT_FOUND');const competition=s.competitions.find(x=>x.id===input.competitionId&&x.organizationId===org.id);if(!competition||competition.state==='draft')throw new Error('PARTICIPANT_USAGE_REQUIRES_PUBLISHED_COMPETITION');const year=input.year||new Date().getUTCFullYear();const duplicate=s.participantUsage.find(x=>x.organizationId===org.id&&x.participantId===input.participantId&&x.year===year);if(duplicate)return duplicate;const used=s.participantUsage.filter(x=>x.organizationId===org.id&&x.year===year).length;if(used>=this.planLimits(s,license).annualParticipants)throw new Error('ANNUAL_PARTICIPANT_LIMIT_REACHED');const row:ParticipantUsageRow={id:this.next(s,'PU'),tenantId:org.tenantId,organizationId:org.id,competitionId:input.competitionId,participantId:clean(input.participantId,120),year,createdAt:now()};s.participantUsage.push(row);return row})}
 reserveUpload(actor:CommercialActor,input:{organizationId:string;competitionId?:string;fileType:string;mimeType:string;sizeBytes:number;provider?:StorageProvider}){this.orgScope(actor,input.organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===input.organizationId),license=s.licenses.find(x=>x.organizationId===input.organizationId);if(!org||!license)throw new Error('LICENSE_NOT_FOUND');if(license.uploadsDisabled)throw new Error('UPLOADS_DISABLED_BY_PLATFORM');const size=positive(input.sizeBytes);if(!size)throw new Error('FILE_SIZE_REQUIRED');const mode=input.provider||'mizan';const used=s.storageObjects.filter(x=>x.organizationId===org.id&&x.provider==='mizan'&&x.state==='stored').reduce((n,x)=>n+x.sizeBytes,0),reserved=s.storageObjects.filter(x=>x.organizationId===org.id&&x.provider==='mizan'&&x.state==='reserved').reduce((n,x)=>n+x.sizeBytes,0);if(mode==='mizan'&&used+reserved+size>this.planLimits(s,license).storageBytes)throw new Error('STORAGE_QUOTA_REACHED');const id=this.next(s,'FILE'),key=`tenants/${org.tenantId}/competitions/${clean(input.competitionId||'_shared',120)}/${id}`;const row:StorageObjectRecord={id,tenantId:org.tenantId,organizationId:org.id,competitionId:clean(input.competitionId,120)||undefined,fileType:clean(input.fileType,60),mimeType:clean(input.mimeType,120),sizeBytes:size,provider:mode,storageKey:key,category:storageCategory(input.mimeType),state:'reserved',createdAt:now()};s.storageObjects.push(row);return row})}
 finalizeUpload(actor:CommercialActor,id:string,input:{organizationId:string;checksum:string}){this.orgScope(actor,input.organizationId);return this.mutate(s=>{const o=s.storageObjects.find(x=>x.id===id&&x.organizationId===input.organizationId);if(!o||o.state!=='reserved')throw new Error('UPLOAD_RESERVATION_NOT_FOUND');if(!clean(input.checksum))throw new Error('UPLOAD_CHECKSUM_REQUIRED');o.state='stored';o.checksum=clean(input.checksum,128);return o})}
 configureStorage(actor:CommercialActor,organizationId:string,input:{provider:Exclude<StorageProvider,'mizan'>;container:string;region?:string;endpoint?:string;secret:Record<string,string>}){if(!['super_admin','org_admin','storage_admin'].includes(actor.role))throw new Error('STORAGE_ADMIN_REQUIRED');this.orgScope(actor,organizationId);if(!this.vault)throw new Error('STORAGE_SECRET_VAULT_NOT_CONFIGURED');return this.mutate(s=>{const org=s.organizations.find(x=>x.id===organizationId),license=s.licenses.find(x=>x.organizationId===organizationId),plan=license&&s.plans.find(x=>x.id===license.planId);if(!org||!license||!plan)throw new Error('LICENSE_NOT_FOUND');if(!plan.features.external_storage)throw new Error('EXTERNAL_STORAGE_NOT_INCLUDED');if(!clean(input.container)||!input.secret||!Object.keys(input.secret).length)throw new Error('STORAGE_CONFIGURATION_INCOMPLETE');const ref=this.vault!.put(Object.fromEntries(Object.entries(input.secret).map(([k,v])=>[clean(k,80),clean(v,1000)])));const t=now(),row:StorageAccountRecord={id:this.next(s,'SA'),tenantId:org.tenantId,organizationId:org.id,provider:input.provider,container:clean(input.container,180),region:clean(input.region,80)||undefined,endpoint:clean(input.endpoint,300)||undefined,connectionStatus:'pending_test',secretReference:ref,isPrimary:false,createdAt:t,updatedAt:t};s.storageAccounts.push(row);this.audit(s,actor,{tenantId:org.tenantId,organizationId:org.id,action:'STORAGE_ACCOUNT_CONFIGURED',entityType:'storage_account',entityId:row.id});return {...row,secretReference:'stored_securely'}})}
 async testStorage(actor:CommercialActor,organizationId:string,accountId:string){if(!['super_admin','org_admin','storage_admin'].includes(actor.role))throw new Error('STORAGE_ADMIN_REQUIRED');this.orgScope(actor,organizationId);if(!this.vault||!this.probe)throw new Error('STORAGE_PROBE_NOT_CONFIGURED');const s=this.read(),account=s.storageAccounts.find(x=>x.id===accountId&&x.organizationId===organizationId);if(!account)throw new Error('STORAGE_ACCOUNT_NOT_FOUND');let result;try{result=await this.probe(account,this.vault.get(account.secretReference))}catch{result={upload:false,read:false,remove:false,code:'PROVIDER_UNAVAILABLE'}}return this.mutate(next=>{const row=next.storageAccounts.find(x=>x.id===accountId)!;row.lastTestedAt=now();row.lastTestResult=result.upload&&result.read&&result.remove?'upload_read_delete_verified':result.code||(!result.upload?'upload_permission_missing':!result.read?'read_permission_missing':'delete_permission_missing');row.connectionStatus=result.upload&&result.read&&result.remove?'connected':'degraded';row.isPrimary=row.connectionStatus==='connected';row.updatedAt=now();this.audit(next,actor,{tenantId:row.tenantId,organizationId:row.organizationId,action:'STORAGE_CONNECTION_TESTED',entityType:'storage_account',entityId:row.id,reason:row.lastTestResult});return {...row,secretReference:'stored_securely'}})}
 startMigration(actor:CommercialActor,organizationId:string,destination:StorageProvider,deleteAfterVerification=false){this.orgScope(actor,organizationId);return this.mutate(s=>{const org=s.organizations.find(x=>x.id===organizationId);if(!org)throw new Error('ORGANIZATION_NOT_FOUND');if(destination!=='mizan'&&!s.storageAccounts.some(x=>x.organizationId===organizationId&&x.provider===destination&&x.connectionStatus==='connected'))throw new Error('DESTINATION_STORAGE_NOT_READY');const total=s.storageObjects.filter(x=>x.organizationId===organizationId&&x.provider==='mizan'&&x.state==='stored').length;const t=now(),m:StorageMigrationRecord={id:this.next(s,'MIG'),tenantId:org.tenantId,organizationId,status:'queued',source:'mizan',destination,totalFiles:total,completedFiles:0,failedFiles:0,sourceDeletionPolicy:deleteAfterVerification?'delete_after_verification':'retain',createdAt:t,updatedAt:t};s.storageMigrations.push(m);this.audit(s,actor,{tenantId:org.tenantId,organizationId,action:'STORAGE_MIGRATION_QUEUED',entityType:'storage_migration',entityId:m.id});return m})}
 usage(actor:CommercialActor,organizationId:string){this.orgScope(actor,organizationId);const s=this.read(),org=s.organizations.find(x=>x.id===organizationId),license=s.licenses.find(x=>x.organizationId===organizationId);if(!org||!license)throw new Error('ORGANIZATION_NOT_FOUND');const objects=s.storageObjects.filter(x=>x.organizationId===organizationId&&x.state==='stored'),byCategory=Object.fromEntries(['audio','video','image','document','other'].map(c=>[c,objects.filter(x=>x.category===c).reduce((n,x)=>n+x.sizeBytes,0)]));const mizanUsed=objects.filter(x=>x.provider==='mizan').reduce((n,x)=>n+x.sizeBytes,0),externalUsed=objects.filter(x=>x.provider!=='mizan').reduce((n,x)=>n+x.sizeBytes,0),reserved=s.storageObjects.filter(x=>x.organizationId===organizationId&&x.state==='reserved').reduce((n,x)=>n+x.sizeBytes,0),limits=this.planLimits(s,license),year=new Date().getUTCFullYear();return {organization:org,license:{...license,limits},usage:{activeCompetitions:s.competitions.filter(x=>x.organizationId===organizationId&&activeCompetitionStates.has(x.state)).length,annualParticipants:s.participantUsage.filter(x=>x.organizationId===organizationId&&x.year===year).length,mizanStorageBytes:mizanUsed,externalStorageBytes:externalUsed,reservedBytes:reserved,byCategory},storageAccounts:s.storageAccounts.filter(x=>x.organizationId===organizationId).map(x=>({...x,secretReference:undefined})),migrations:s.storageMigrations.filter(x=>x.organizationId===organizationId),changeRequests:s.changeRequests.filter(x=>x.organizationId===organizationId)}}
 dashboard(actor:CommercialActor){this.super(actor);const s=this.read(),near=Date.now()+30*86400_000;return {counts:{organizations:s.organizations.length,activeOrganizations:s.organizations.filter(x=>x.status==='active').length,suspendedOrganizations:s.organizations.filter(x=>x.status==='suspended').length,operators:s.operators.length,activeOperators:s.operators.filter(x=>x.status==='active').length,activeCompetitions:s.competitions.filter(x=>activeCompetitionStates.has(x.state)).length,participantsThisYear:s.participantUsage.filter(x=>x.year===new Date().getUTCFullYear()).length,licensesExpiringSoon:s.licenses.filter(x=>x.status==='active'&&Date.parse(x.expiresAt)<=near).length,pendingChangeRequests:s.changeRequests.filter(x=>x.status==='pending').length},storage:{mizanBytes:s.storageObjects.filter(x=>x.provider==='mizan'&&x.state==='stored').reduce((n,x)=>n+x.sizeBytes,0),externalBytes:s.storageObjects.filter(x=>x.provider!=='mizan'&&x.state==='stored').reduce((n,x)=>n+x.sizeBytes,0)},organizations:s.organizations.map(o=>{const l=s.licenses.find(x=>x.organizationId===o.id),p=l&&s.plans.find(x=>x.id===l.planId),u=s.storageObjects.filter(x=>x.organizationId===o.id&&x.provider==='mizan'&&x.state==='stored').reduce((n,x)=>n+x.sizeBytes,0);return {...o,license:l&&{...l,planName:p?.name,limits:this.planLimits(s,l)},storageUsedBytes:u,activeCompetitions:s.competitions.filter(x=>x.organizationId===o.id&&activeCompetitionStates.has(x.state)).length,participants:s.participantUsage.filter(x=>x.organizationId===o.id&&x.year===new Date().getUTCFullYear()).length,operatorName:s.operators.find(x=>x.id===o.operatorId)?.name}}),operators:s.operators.map(o=>({...o,creditBalance:this.creditBalance(s,o.id),organizations:s.organizations.filter(x=>x.operatorId===o.id).length})),plans:s.plans,changeRequests:s.changeRequests,creditLedger:s.creditLedger.slice(-200).reverse(),audit:s.audit.slice(-200).reverse()}}
 operatorDashboard(actor:CommercialActor){if(!['operator_owner','operator_admin'].includes(actor.role)||!actor.operatorId)throw new Error('OPERATOR_REQUIRED');const s=this.read(),op=s.operators.find(x=>x.id===actor.operatorId);if(!op)throw new Error('OPERATOR_NOT_FOUND');const organizations=s.organizations.filter(x=>x.operatorId===op.id);return {operator:op,creditBalance:this.creditBalance(s,op.id),organizations:organizations.map(o=>({organization:o,license:s.licenses.find(x=>x.organizationId===o.id),usage:this.usage({...actor,operatorId:op.id},o.id).usage})),creditLedger:s.creditLedger.filter(x=>x.operatorId===op.id).slice(-100).reverse()}}
 verifyAudit(){const s=this.read();let previous='GENESIS';for(const row of s.audit){const {hash:rowHash,...base}=row;if(row.previousHash!==previous||hash(base)!==rowHash)return {valid:false,sequence:row.sequence};previous=row.hash}return {valid:true,rows:s.audit.length}}
}
