import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import type { EscrowActor } from './question-escrow';

export type WitnessActionType='QUESTION_REPLACEMENT'|'FULL_RETEST'|'PASS_REISSUE'|'EMERGENCY_UNSEAL'|'RESULT_OVERRIDE';
export interface WitnessAttestation{uid:string;role:string;attestedAt:string;evidenceRef?:string;previousHash:string;attestationHash:string}
export interface WitnessActionRecord{version:2;id:string;organizationId:string;competitionId:string;actionType:WitnessActionType;targetRef:string;reason:string;initiatedBy:string;createdAt:string;expiresAt:string;requiredWitnesses:number;allowedWitnessRoles:string[];requireDistinctRoles:boolean;attestations:WitnessAttestation[];state:'PENDING'|'READY'|'EXPIRED'|'REVOKED';commitmentHash:string;evidenceHash:string}
const canonical=(v:unknown):string=>{if(v===undefined)return 'null';if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;const o=v as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`};
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');const safe=(v:string)=>v.replace(/[^A-Za-z0-9._-]/g,'_').slice(0,150);
const attestationHash=(r:Pick<WitnessActionRecord,'id'|'actionType'|'targetRef'>,x:Omit<WitnessAttestation,'attestationHash'>)=>hash(canonical({recordId:r.id,actionType:r.actionType,targetRef:r.targetRef,...x}));
const evidenceHash=(r:Omit<WitnessActionRecord,'evidenceHash'>)=>hash(canonical({commitmentHash:r.commitmentHash,state:r.state,attestations:r.attestations}));
export class WitnessModeRepository{
 constructor(private root:string){fs.mkdirSync(root,{recursive:true,mode:0o700})}
 private file(id:string){return path.join(this.root,`witness-${safe(id)}.json`)}
 private normalize(raw:any):WitnessActionRecord{if(raw.version===2)return raw;const attestations:WitnessAttestation[]=(raw.attestations||[]).reduce((acc:WitnessAttestation[],x:any)=>{const previousHash=acc.at(-1)?.attestationHash||raw.commitmentHash;const base={uid:String(x.uid),role:String(x.role),attestedAt:String(x.attestedAt),previousHash};acc.push({...base,attestationHash:attestationHash(raw,base)});return acc},[]);const upgraded={...raw,version:2,requireDistinctRoles:true,attestations} as Omit<WitnessActionRecord,'evidenceHash'>;return {...upgraded,evidenceHash:evidenceHash(upgraded)}}
 private read(id:string){const f=this.file(id);if(!fs.existsSync(f))throw new Error('WITNESS_ACTION_NOT_FOUND');const r=this.normalize(JSON.parse(fs.readFileSync(f,'utf8')));if(r.state==='PENDING'&&Date.parse(r.expiresAt)<=Date.now()){r.state='EXPIRED';r.evidenceHash=evidenceHash({...r,evidenceHash:undefined} as any);this.write(r)}this.assertIntegrity(r);return r}
 private write(r:WitnessActionRecord){const f=this.file(r.id),tmp=`${f}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(r,null,2),{encoding:'utf8',mode:0o600});fs.renameSync(tmp,f)}
 private assertIntegrity(r:WitnessActionRecord){let previous=r.commitmentHash;for(const a of r.attestations){if(a.previousHash!==previous)throw new Error('WITNESS_ATTESTATION_CHAIN_INVALID');const {attestationHash:got,...base}=a;if(attestationHash(r,base)!==got)throw new Error('WITNESS_ATTESTATION_HASH_INVALID');previous=got}const expected=evidenceHash({...r,evidenceHash:undefined} as any);if(expected!==r.evidenceHash)throw new Error('WITNESS_EVIDENCE_HASH_INVALID')}
 create(input:{actor:EscrowActor;actionType:WitnessActionType;targetRef:string;reason:string;expiresAt:string;requiredWitnesses?:number;allowedWitnessRoles?:string[];requireDistinctRoles?:boolean}){if(!['head_judge','comp_admin','org_admin'].includes(input.actor.role))throw new Error('WITNESS_INITIATOR_ROLE_REQUIRED');if(!input.actor.competitionId)throw new Error('WITNESS_COMPETITION_REQUIRED');if(!input.reason.trim())throw new Error('WITNESS_REASON_REQUIRED');if(!input.targetRef.trim())throw new Error('WITNESS_TARGET_REQUIRED');if(Date.parse(input.expiresAt)<=Date.now())throw new Error('WITNESS_EXPIRY_REQUIRED');const id=crypto.randomUUID(),required=Math.max(1,Math.min(3,input.requiredWitnesses||2)),allowed=input.allowedWitnessRoles||['operations','auditor','head_judge','comp_admin','org_admin'];const core={version:2 as const,id,organizationId:input.actor.organizationId,competitionId:input.actor.competitionId,actionType:input.actionType,targetRef:input.targetRef,reason:input.reason.trim(),initiatedBy:input.actor.uid,createdAt:new Date().toISOString(),expiresAt:input.expiresAt,requiredWitnesses:required,allowedWitnessRoles:allowed,requireDistinctRoles:input.requireDistinctRoles??required>1};const commitmentHash=hash(canonical(core));const base:Omit<WitnessActionRecord,'evidenceHash'>={...core,attestations:[],state:'PENDING',commitmentHash};const r:WitnessActionRecord={...base,evidenceHash:evidenceHash(base)};this.write(r);return r}
 attest(id:string,actor:EscrowActor,evidenceRef?:string){const r=this.read(id);if(r.state!=='PENDING')throw new Error(`WITNESS_ACTION_${r.state}`);if(actor.organizationId!==r.organizationId||actor.competitionId!==r.competitionId)throw new Error('WITNESS_SCOPE_MISMATCH');if(actor.uid===r.initiatedBy)throw new Error('WITNESS_INITIATOR_CANNOT_WITNESS');if(!r.allowedWitnessRoles.includes(actor.role))throw new Error('WITNESS_ROLE_NOT_ALLOWED');if(r.attestations.some(x=>x.uid===actor.uid))throw new Error('WITNESS_ALREADY_ATTESTED');if(r.requireDistinctRoles&&r.attestations.some(x=>x.role===actor.role))throw new Error('WITNESS_ROLE_DIVERSITY_REQUIRED');const previousHash=r.attestations.at(-1)?.attestationHash||r.commitmentHash;const evidence=evidenceRef?.trim();const base={uid:actor.uid,role:actor.role,attestedAt:new Date().toISOString(),...(evidence?{evidenceRef:evidence}:{}),previousHash};const a:WitnessAttestation={...base,attestationHash:attestationHash(r,base)};r.attestations.push(a);if(r.attestations.length>=r.requiredWitnesses)r.state='READY';r.evidenceHash=evidenceHash({...r,evidenceHash:undefined} as any);this.write(r);return r}
 revoke(id:string,actor:EscrowActor,reason:string){const r=this.read(id);if(!['head_judge','comp_admin','org_admin'].includes(actor.role))throw new Error('WITNESS_REVOKE_ROLE_REQUIRED');if(actor.organizationId!==r.organizationId||actor.competitionId!==r.competitionId)throw new Error('WITNESS_SCOPE_MISMATCH');if(!reason.trim())throw new Error('WITNESS_REVOKE_REASON_REQUIRED');if(r.state==='REVOKED')return r;r.state='REVOKED';r.evidenceHash=evidenceHash({...r,evidenceHash:undefined} as any);this.write(r);return r}
 verifyReady(id:string,input:{organizationId:string;competitionId:string;actionType:WitnessActionType;targetRef:string}){const r=this.read(id);if(r.organizationId!==input.organizationId||r.competitionId!==input.competitionId||r.actionType!==input.actionType||r.targetRef!==input.targetRef)throw new Error('WITNESS_ACTION_MISMATCH');if(r.state!=='READY')throw new Error(`WITNESS_ACTION_NOT_READY:${r.state}`);if(r.requireDistinctRoles&&new Set(r.attestations.map(x=>x.role)).size<r.requiredWitnesses)throw new Error('WITNESS_ROLE_DIVERSITY_REQUIRED');return r}
 status(id:string,actor:EscrowActor){const r=this.read(id);if(actor.organizationId!==r.organizationId||actor.competitionId!==r.competitionId)throw new Error('WITNESS_SCOPE_MISMATCH');return r}
}
