import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import type { EscrowActor } from './question-escrow';

export type WitnessActionType='QUESTION_REPLACEMENT'|'FULL_RETEST'|'PASS_REISSUE'|'EMERGENCY_UNSEAL'|'RESULT_OVERRIDE';
export interface WitnessActionRecord{version:1;id:string;organizationId:string;competitionId:string;actionType:WitnessActionType;targetRef:string;reason:string;initiatedBy:string;createdAt:string;expiresAt:string;requiredWitnesses:number;allowedWitnessRoles:string[];attestations:{uid:string;role:string;attestedAt:string}[];state:'PENDING'|'READY'|'EXPIRED'|'REVOKED';commitmentHash:string}
const canonical=(v:unknown):string=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;const o=v as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`};
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');const safe=(v:string)=>v.replace(/[^A-Za-z0-9._-]/g,'_').slice(0,150);
export class WitnessModeRepository{
 constructor(private root:string){fs.mkdirSync(root,{recursive:true,mode:0o700})}
 private file(id:string){return path.join(this.root,`witness-${safe(id)}.json`)}
 private read(id:string){const f=this.file(id);if(!fs.existsSync(f))throw new Error('WITNESS_ACTION_NOT_FOUND');const r=JSON.parse(fs.readFileSync(f,'utf8')) as WitnessActionRecord;if(r.state==='PENDING'&&Date.parse(r.expiresAt)<=Date.now()){r.state='EXPIRED';this.write(r)}return r}
 private write(r:WitnessActionRecord){const f=this.file(r.id),tmp=`${f}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(r,null,2),{encoding:'utf8',mode:0o600});fs.renameSync(tmp,f)}
 create(input:{actor:EscrowActor;actionType:WitnessActionType;targetRef:string;reason:string;expiresAt:string;requiredWitnesses?:number;allowedWitnessRoles?:string[]}){if(!['head_judge','comp_admin','org_admin'].includes(input.actor.role))throw new Error('WITNESS_INITIATOR_ROLE_REQUIRED');if(!input.actor.competitionId)throw new Error('WITNESS_COMPETITION_REQUIRED');if(!input.reason.trim())throw new Error('WITNESS_REASON_REQUIRED');if(Date.parse(input.expiresAt)<=Date.now())throw new Error('WITNESS_EXPIRY_REQUIRED');const id=crypto.randomUUID(),required=Math.max(1,Math.min(3,input.requiredWitnesses||2)),allowed=input.allowedWitnessRoles||['operations','auditor','head_judge','comp_admin','org_admin'];const core={version:1 as const,id,organizationId:input.actor.organizationId,competitionId:input.actor.competitionId,actionType:input.actionType,targetRef:input.targetRef,reason:input.reason.trim(),initiatedBy:input.actor.uid,createdAt:new Date().toISOString(),expiresAt:input.expiresAt,requiredWitnesses:required,allowedWitnessRoles:allowed};const r:WitnessActionRecord={...core,attestations:[],state:'PENDING',commitmentHash:hash(canonical(core))};this.write(r);return r}
 attest(id:string,actor:EscrowActor){const r=this.read(id);if(r.state!=='PENDING')throw new Error(`WITNESS_ACTION_${r.state}`);if(actor.organizationId!==r.organizationId||actor.competitionId!==r.competitionId)throw new Error('WITNESS_SCOPE_MISMATCH');if(actor.uid===r.initiatedBy)throw new Error('WITNESS_INITIATOR_CANNOT_WITNESS');if(!r.allowedWitnessRoles.includes(actor.role))throw new Error('WITNESS_ROLE_NOT_ALLOWED');if(!r.attestations.some(x=>x.uid===actor.uid))r.attestations.push({uid:actor.uid,role:actor.role,attestedAt:new Date().toISOString()});if(r.attestations.length>=r.requiredWitnesses)r.state='READY';this.write(r);return r}
 verifyReady(id:string,input:{organizationId:string;competitionId:string;actionType:WitnessActionType;targetRef:string}){const r=this.read(id);if(r.organizationId!==input.organizationId||r.competitionId!==input.competitionId||r.actionType!==input.actionType||r.targetRef!==input.targetRef)throw new Error('WITNESS_ACTION_MISMATCH');if(r.state!=='READY')throw new Error(`WITNESS_ACTION_NOT_READY:${r.state}`);return r}
 status(id:string,actor:EscrowActor){const r=this.read(id);if(actor.organizationId!==r.organizationId||actor.competitionId!==r.competitionId)throw new Error('WITNESS_SCOPE_MISMATCH');return r}
}
