import React, { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Crown, RotateCcw, X } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Button } from '../design-system/Button';

export const CeremonyView: React.FC<{onClose?:()=>void}> = ({onClose}) => {
 const {language,results,competition}=useAppStore(); const ar=language==='ar'; const [stage,setStage]=useState(0);
 const winners=useMemo(()=>[3,2,1].map(rank=>results.find(r=>r.rank===rank)).filter(Boolean),[results]);
 const current=stage>0?winners[stage-1]:null;
 const PrevIcon=ar?ChevronRight:ChevronLeft; const NextIcon=ar?ChevronLeft:ChevronRight;
 return <div className="fixed inset-0 z-50 bg-[#101a16] text-white bg-islamic-subtle overflow-hidden flex flex-col p-5 sm:p-8">
   <header className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl border border-white/10 bg-white/[.05] grid place-items-center font-black text-[#d9e6df]">م</span><div><div className="text-[10px] font-black tracking-[.18em] text-white/40">MIZAN CEREMONY</div><div className="text-sm font-bold mt-1">{ar?competition.nameArabic:competition.name}</div></div></div>{onClose&&<button onClick={onClose} className="w-10 h-10 rounded-xl grid place-items-center hover:bg-white/10 text-white/55" aria-label="close"><X className="w-5 h-5"/></button>}</header>
   <main className="flex-1 grid place-items-center px-3"><div className="w-full max-w-5xl text-center">
    {stage===0?<div className="max-w-3xl mx-auto"><div className="text-[11px] font-black tracking-[.2em] text-[#b9cfc4]">{ar?'إعلان النتائج الرسمية':'OFFICIAL RESULT REVEAL'}</div><h1 className="text-4xl sm:text-6xl lg:text-7xl font-black tracking-tight mt-5 leading-[1.12]">{ar?'لحظة التتويج':'The moment of recognition'}</h1><p className="text-sm text-white/45 mt-5">{ar?'لا تظهر أي نتيجة قبل أمر الكشف من مشغل الحفل.':'No result is exposed before the reveal control is triggered.'}</p><Button className="mt-8 !bg-[#d8c39b] !text-[#1d2a24] hover:!bg-[#e2cfaa]" size="lg" onClick={()=>setStage(1)} icon={<NextIcon className="w-4 h-4"/>}>{ar?'ابدأ':'Begin'}</Button></div>
    :current?<div className="max-w-4xl mx-auto animate-in fade-in zoom-in-95 duration-500"><div className={`mx-auto grid place-items-center rounded-full ${current.rank===1?'w-20 h-20 bg-[#d8c39b] text-[#1d2a24]':'w-14 h-14 border border-white/15 text-[#b9cfc4]'}`}>{current.rank===1?<Crown className="w-9 h-9"/>:<span className="text-2xl font-black">{current.rank}</span>}</div><div className="text-[11px] font-black tracking-[.2em] text-[#b9cfc4] mt-7">{current.rank===1?(ar?'المركز الأول':'FIRST PLACE'):current.rank===2?(ar?'المركز الثاني':'SECOND PLACE'):(ar?'المركز الثالث':'THIRD PLACE')}</div><h2 className="text-4xl sm:text-6xl font-black mt-5 tracking-tight">{ar?current.participantNameArabic:current.participantName}</h2><div className="text-lg text-white/45 mt-3">{current.country}</div><div className="mt-7 inline-flex items-baseline gap-1 rounded-2xl border border-white/10 bg-white/[.04] px-6 py-3"><span className="text-3xl font-black">{current.finalScore.toFixed(2)}</span><span className="text-sm text-white/40">%</span></div></div>:<div className="text-white/50">{ar?'لا توجد نتيجة لهذا المركز':'No result for this rank'}</div>}
   </div></main>
   <footer className="flex items-center justify-between gap-3"><div className="text-[10px] text-white/25">MIZAN · Sealed results</div><div className="flex gap-2">{stage>0&&<button onClick={()=>setStage(Math.max(0,stage-1))} className="w-10 h-10 rounded-xl border border-white/10 grid place-items-center hover:bg-white/10 text-white/60"><PrevIcon className="w-4 h-4"/></button>}{stage>0&&stage<winners.length&&<button onClick={()=>setStage(stage+1)} className="w-10 h-10 rounded-xl bg-[#d8c39b] text-[#1d2a24] grid place-items-center hover:bg-[#e2cfaa]"><NextIcon className="w-4 h-4"/></button>}{stage===winners.length&&stage>0&&<button onClick={()=>setStage(0)} className="w-10 h-10 rounded-xl border border-white/10 grid place-items-center hover:bg-white/10 text-white/60"><RotateCcw className="w-4 h-4"/></button>}</div></footer>
 </div>
}
