import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BadgeCheck, Check, FileCheck2, UserRound } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { getCompetitionPolicy } from '../../lib/competition-config';
import { Button } from '../design-system/Button';
import { normalizeFieldValue, isValidEmail } from '../../lib/input-normalize';
import { searchCountries, countryStoredValue } from '../../lib/countries';
import { localizedCountry } from '../../lib/ui-language';
import type { Participant } from '../../types';

export const RegistrationFlow: React.FC<{onSuccess?:(participant:Participant)=>void}> = ({onSuccess}) => {
 const store=useAppStore(); const {language,competition,registerParticipant,recordConsent}=store; const ar=language==='ar'; const policy=getCompetitionPolicy(competition);
 const [step,setStep]=useState(0); const [submitted,setSubmitted]=useState<any>(null); const [termsAccepted,setTermsAccepted]=useState(false); const [privacyAccepted,setPrivacyAccepted]=useState(false); const [guardianAccepted,setGuardianAccepted]=useState(false); const [guardianName,setGuardianName]=useState('');
 const [form,setForm]=useState({fullNameArabic:'',fullName:'',email:'',phone:'',country:'Kuwait (الكويت)',nationality:'كويتي',nationalIdOrPassport:'',dateOfBirth:'2010-01-01',gender:'male' as 'male'|'female',categoryId:competition.categories[0]?.id||'',riwaya:competition.categories[0]?.riwaya||'حفص عن عاصم'});
 const category=competition.categories.find(c=>c.id===form.categoryId); const age=Math.floor((Date.now()-new Date(form.dateOfBirth).getTime())/31557600000); const minor=Number.isFinite(age)&&age<18; const guardianRequired=minor&&policy.registration.requireGuardianForMinors;
 const steps=[{ar:'بياناتي',en:'Profile'},{ar:'مشاركتي',en:'Entry'},{ar:'مراجعة',en:'Review'}];
 const fieldValue=(id:string)=>({fullNameArabic:form.fullNameArabic,fullName:form.fullName,email:form.email,phone:form.phone,country:form.country,nationality:form.nationality,dateOfBirth:form.dateOfBirth,gender:form.gender,identity:form.nationalIdOrPassport} as Record<string,string>)[id]??'';
 const requiredProfileFields=policy.registration.fields.filter(f=>f.visible&&f.required);
 // البريد (إن كان ظاهرًا وله قيمة) لا يُقبل إلا بصيغة صحيحة قبل المتابعة.
 const emailField=policy.registration.fields.find(f=>f.visible&&f.type==='email');
 const emailOk=!emailField||(!emailField.required&&!form.email.trim())||isValidEmail(form.email);
 const canNext=step===0?(requiredProfileFields.every(f=>String(fieldValue(f.id)).trim().length>0)&&emailOk):step===1?!!form.categoryId:true;
 const submit=()=>{if(!termsAccepted||!privacyAccepted||(guardianRequired&&(!guardianAccepted||!guardianName.trim())))return;const p=registerParticipant({...form,competitionId:competition.id,organizationId:competition.organizationId,institution:'',status:'submitted' as any,delegationId:undefined,specialNeeds:false,photoUrl:undefined,documents:[] } as any);recordConsent(p.id,'terms',policy.version,true);recordConsent(p.id,'privacy',policy.version,true);if(policy.judging.requireAudioRecording)recordConsent(p.id,'audio_recording',policy.version,true);if(policy.privacy.allowAiProcessing)recordConsent(p.id,'ai_processing',policy.version,true);if(guardianRequired)recordConsent(p.id,'guardian',policy.version,true,guardianName);setSubmitted(p)};
 if(submitted) return <div className="max-w-xl mx-auto px-4 py-16"><div className="mizan-surface p-8 text-center"><span className="w-14 h-14 rounded-full bg-[#E7EEE9] text-[#214C40] grid place-items-center mx-auto"><BadgeCheck className="w-7 h-7"/></span><div className="mizan-kicker mt-5">{submitted.code}</div><h1 className="text-2xl font-black mt-2">{submitted.status==='approved'?(ar?'تم قبول مشاركتك':'Participation approved'):(ar?'تم استلام طلبك':'Application received')}</h1><p className="text-sm text-[#636864] mt-2">{submitted.status==='approved'?(ar?'تمت مطابقة الشروط الموضوعية وتحديد نافذة حضورك تلقائيًا.':'Objective eligibility passed and your arrival window was assigned automatically.'):(ar?'هذه الحالة تحتاج مراجعة وفق سياسة المسابقة.':'This case requires review under the competition policy.')}</p><Button className="mt-6" onClick={()=>{if(onSuccess)onSuccess(submitted);else window.location.hash=`#journey?comp=${encodeURIComponent(competition.id)}&key=${encodeURIComponent(submitted.journeyAccessToken||'')}`}}>{ar?'العودة لمشاركتي':'Open my journey'}</Button></div></div>;
 return <div className="max-w-2xl mx-auto px-4 sm:px-6 py-7"><div className="mb-6"><div className="mizan-kicker">{ar?'التسجيل الإلكتروني':'ONLINE REGISTRATION'}</div><h1 className="text-3xl font-black mt-1">{ar?competition.nameArabic:competition.name}</h1><div className="flex items-center gap-1.5 mt-5">{steps.map((s,i)=><React.Fragment key={i}><span className={`w-8 h-8 rounded-full grid place-items-center text-xs font-black ${i<=step?'bg-[#214C40] text-white':'bg-[#e9e7e1] text-[#696f6b]'}`}>{i<step?<Check className="w-4 h-4"/>:i+1}</span>{i<steps.length-1&&<span className={`h-px flex-1 ${i<step?'bg-[#2F6555]':'bg-[#dcdad3]'}`}/>}</React.Fragment>)}</div></div>
  <div className="mizan-surface p-6 sm:p-8 min-h-[420px]">
   {step===0&&<div className="space-y-5"><Title icon={UserRound} title={ar?'بياناتك':'Your profile'} sub={ar?'تظهر فقط الحقول التي اختارتها هذه المسابقة.':'Only fields enabled by this competition are shown.'}/><div className="grid sm:grid-cols-2 gap-4">{policy.registration.fields.filter(f=>f.visible).map(f=>{
 const label=(ar?f.labelArabic:f.labelEnglish)+(f.required?' *':''); const value=fieldValue(f.id);
 const set=(raw:string)=>{ const map:Record<string,string>={fullNameArabic:'fullNameArabic',fullName:'fullName',email:'email',phone:'phone',country:'country',nationality:'nationality',dateOfBirth:'dateOfBirth',gender:'gender',identity:'nationalIdOrPassport'}; const key=map[f.id]; if(key)setForm(prev=>({...prev,[key]:normalizeFieldValue(f.id,f.type,raw)})); };
 // الدولة: قائمة كل دول العالم مع بحث سريع، بدل قائمة ثابتة قصيرة.
 if(f.id==='country'||f.id==='nationality'){const key=f.id;return <CountryField key={f.id} label={label} value={value} ar={ar} onChange={(v)=>setForm(prev=>({...prev,[key]:v}))}/>;}
 if(f.type==='select') return <label key={f.id} className="block"><span className="block text-xs font-black text-[#686f6a] mb-2">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border border-[#dcdad2] bg-white px-3 py-3 text-sm">{f.options?.map(o=><option key={o.value} value={o.value}>{ar?o.labelArabic:o.labelEnglish}</option>)}</select></label>;
 const invalid=f.type==='email'&&f.required&&value.trim().length>0&&!isValidEmail(value);
 return <div key={f.id}><Input label={label} type={f.type==='email'?'email':f.type==='date'?'date':f.type==='phone'?'tel':'text'} value={value} onChange={set} dir={f.id==='fullNameArabic'?'rtl':f.id==='fullName'||f.type==='email'?'ltr':undefined}/>{invalid&&<span className="mt-1 block text-[10px] font-bold text-[#A34D43]">{ar?'صيغة البريد غير صحيحة':'Invalid email format'}</span>}</div>;
 })}</div></div>}
   {step===1&&<div className="space-y-5"><Title icon={FileCheck2} title={ar?'اختر مشاركتك':'Choose your entry'} sub={ar?'الفئة هي التي تحدد النطاق والرواية وشروط الأهلية.':'Category controls scope, riwaya and eligibility.'}/><div className="space-y-2">{competition.categories.length?competition.categories.map(c=><button key={c.id} onClick={()=>setForm({...form,categoryId:c.id,riwaya:c.riwaya})} className={`w-full p-4 rounded-2xl border text-start transition ${form.categoryId===c.id?'border-[#214C40] bg-[#E7EEE9]':'border-[#deddd6] bg-white hover:bg-[#f7f5ef]'}`}><div className="font-black text-sm">{ar?c.nameArabic:c.name}</div><div className="text-[11px] text-[#636864] mt-1">{c.memorizationScope} · {c.riwaya}</div></button>):<div role="status" className="rounded-2xl border border-[#e0cfb4] bg-[#F5EDE2] p-5 text-center"><div className="text-sm font-black text-[#725630]">{ar?'لم تُنشر فئات التسجيل بعد':'Registration categories are not published yet'}</div><p className="text-xs text-[#77654a] mt-2">{ar?'راجع رابط المسابقة لاحقًا أو تواصل مع الجهة المنظمة.':'Please check this competition link later or contact the organizer.'}</p></div>}</div><div className="rounded-xl bg-[#f1efe9] p-3 text-xs text-[#656d68]">{policy.registration.autoApproveEligible?(ar?'إذا استوفيت الشروط الموضوعية يمكن اعتمادك تلقائيًا.':'Eligible applications may be auto-approved.'):(ar?'كل الطلبات تمر على مراجعة بشرية في هذه المسابقة.':'This competition requires human application review.')}</div></div>}
   {step===2&&<div className="space-y-5"><Title icon={BadgeCheck} title={ar?'مراجعة واحدة':'One final review'} sub={ar?'لن تعيد إدخال هذه البيانات في الاستقبال أو اللجنة أو الشهادة.':'These details will not be re-entered at gate, committee or certificate.'}/><div className="divide-y divide-[#e5e3dc]"><ReviewRow label={ar?'الاسم':'Name'} value={ar?form.fullNameArabic:form.fullName}/><ReviewRow label={ar?'الفئة':'Category'} value={ar?category?.nameArabic||'—':category?.name||'—'}/><ReviewRow label={ar?'الرواية':'Riwaya'} value={form.riwaya}/><ReviewRow label={ar?'البريد':'Email'} value={form.email}/></div><div className="rounded-2xl bg-[#f3f1eb] p-4 space-y-3"><Consent checked={termsAccepted} onChange={setTermsAccepted} label={ar?'أوافق على شروط المسابقة بالإصدار الحالي.':'I accept the current competition rules.'}/><Consent checked={privacyAccepted} onChange={setPrivacyAccepted} label={ar?'أوافق على سياسة الخصوصية والاحتفاظ بالبيانات.':'I accept the privacy and retention policy.'}/>{guardianRequired&&<div className="pt-2 border-t border-[#ddd] space-y-3"><input value={guardianName} onChange={e=>setGuardianName(e.target.value)} placeholder={ar?'اسم ولي الأمر':'Guardian name'} className="w-full rounded-xl border border-[#d8d6cf] bg-white px-3 py-2.5 text-sm"/><Consent checked={guardianAccepted} onChange={setGuardianAccepted} label={ar?'موافقة ولي الأمر على المشاركة.':'Guardian consent to participate.'}/></div>}</div></div>}
   <div className="mt-8 pt-5 border-t border-[#e5e3dc] flex items-center justify-between"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} icon={ar?<ArrowRight className="w-4 h-4"/>:<ArrowLeft className="w-4 h-4"/>}>{ar?'رجوع':'Back'}</Button>{step<2?<Button disabled={!canNext} onClick={()=>setStep(s=>s+1)} icon={ar?<ArrowLeft className="w-4 h-4"/>:<ArrowRight className="w-4 h-4"/>}>{ar?'التالي':'Next'}</Button>:<Button disabled={!termsAccepted||!privacyAccepted||(guardianRequired&&(!guardianAccepted||!guardianName.trim()))} onClick={submit}>{ar?'إرسال الطلب':'Submit'}</Button>}</div>
  </div>
 </div>
}
const Input=({label,value,onChange,type='text',dir}:{label:string;value:string;onChange:(v:string)=>void;type?:string;dir?:'rtl'|'ltr'})=><label className="block"><span className="block text-xs font-black text-[#686f6a] mb-2">{label}</span><input type={type} dir={dir} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[#dcdad2] bg-white px-3 py-3 text-sm"/></label>;

/* حقل الدولة: قائمة كل دول العالم مع بحث سريع (عربي/إنجليزي/رمز). القيمة تُخزَّن ثنائية اللغة. */
const CountryField:React.FC<{label:string;value:string;ar:boolean;onChange:(v:string)=>void}>=({label,value,ar,onChange})=>{
 const [open,setOpen]=useState(false); const [q,setQ]=useState('');
 const results=useMemo(()=>searchCountries(q).slice(0,60),[q]);
 const shown=value?localizedCountry(value,ar):(ar?'اختر الدولة':'Select country');
 return <label className="block relative"><span className="block text-xs font-black text-[#686f6a] mb-2">{label}</span>
  <button type="button" onClick={()=>setOpen(o=>!o)} className="w-full rounded-xl border border-[#dcdad2] bg-white px-3 py-3 text-sm text-start flex items-center justify-between gap-2">
   <span className={value?'':'text-[#9a9f9b]'}>{shown}</span>
   <ArrowLeft className={`w-4 h-4 shrink-0 transition ${open?'-rotate-90':'rotate-90'}`}/>
  </button>
  {open&&<div className="absolute z-20 mt-1 w-full rounded-xl border border-[#dcdad2] bg-white shadow-lg overflow-hidden">
   <input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث عن دولة…':'Search country…'} className="w-full border-b border-[#eceae3] px-3 py-2.5 text-sm outline-none"/>
   <div className="max-h-64 overflow-y-auto">
    {results.length===0&&<div className="px-3 py-3 text-xs text-[#9a9f9b]">{ar?'لا توجد نتيجة':'No match'}</div>}
    {results.map(c=><button key={c.code} type="button" onClick={()=>{onChange(countryStoredValue(c));setOpen(false);setQ('')}} className="w-full text-start px-3 py-2.5 text-sm hover:bg-[#f3f1eb] flex items-center justify-between gap-3"><span>{ar?c.ar:c.en}</span><span className="text-[10px] text-[#9a9f9b]">{c.code}</span></button>)}
   </div>
  </div>}
 </label>;
};
const Title=({icon:Icon,title,sub}:{icon:React.ComponentType<{className?:string}>;title:string;sub:string})=><div className="flex items-start gap-3"><span className="w-10 h-10 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center"><Icon className="w-5 h-5"/></span><div><h2 className="text-xl font-black">{title}</h2><p className="text-xs text-[#646965] mt-1">{sub}</p></div></div>;
const ReviewRow=({label,value}:{label:string;value:string})=><div className="py-3 flex items-center justify-between gap-4"><span className="text-xs text-[#646965]">{label}</span><span className="text-sm font-bold text-end">{value}</span></div>;

const Consent=({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string})=><label className="mizan-consent text-xs font-semibold text-[#4f5752]"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="w-4 h-4 accent-[#214C40]"/><span>{label}</span></label>;
