import React, {useEffect, useMemo, useState} from 'react';
import { Clock3, RadioTower, UsersRound, X } from 'lucide-react';
import { useAppStore } from '../../lib/store';

export const WaitingBoard:React.FC<{onClose?:()=>void}>=({onClose})=>{
 const {language,participants,committees,competition}=useAppStore(); const ar=language==='ar'; const [now,setNow]=useState(new Date());
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(t)},[]);
 const waiting=useMemo(()=>participants.filter(p=>p.status==='in_queue').sort((a,b)=>(a.queueNumber||9999)-(b.queueNumber||9999)),[participants]);
 const called=committees.map(c=>({committee:c,p:participants.find(p=>p.id===c.currentParticipantId)})).filter(x=>x.p);
 const next=waiting.slice(0,6);
 return <div className="fixed inset-0 z-50 bg-[#11211b] text-white font-arabic overflow-auto">
   <div className="min-h-screen p-5 sm:p-8 lg:p-10 flex flex-col">
    <header className="flex items-start justify-between gap-5"><div><div className="text-[10px] font-black tracking-[.2em] text-white/45">MIZAN WAIT</div><h1 className="text-2xl sm:text-3xl font-black mt-1">{ar?'قاعة الانتظار':'Waiting Hall'}</h1><div className="text-xs text-white/45 mt-1">{ar?competition.nameArabic:competition.name}</div></div><div className="flex items-center gap-3"><div className="text-end"><div className="text-xl font-black tabular-nums">{now.toLocaleTimeString(ar?'ar-KW':'en-GB',{hour:'2-digit',minute:'2-digit'})}</div><div className="text-[10px] text-white/35">{ar?'تحديث تلقائي':'Auto-updating'}</div></div>{onClose&&<button onClick={onClose} className="w-10 h-10 rounded-xl hover:bg-white/10 grid place-items-center text-white/55"><X className="w-5 h-5"/></button>}</div></header>
    <main className="my-auto py-10 grid xl:grid-cols-[1.25fr_.75fr] gap-5">
      <section className="rounded-[30px] border border-white/10 bg-white/[.045] p-5 sm:p-7"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.17em] text-white/40">{ar?'يُرجى التوجه':'NOW CALLING'}</div><h2 className="text-xl font-black mt-1">{ar?'إلى اللجنة':'Proceed to panel'}</h2></div><RadioTower className="w-5 h-5 text-[#b9cec4]"/></div>{called.length?<div className="grid sm:grid-cols-2 gap-3 mt-6">{called.slice(0,4).map(({committee,p})=><div key={committee.id} className="rounded-[24px] bg-[#dbe7df] text-[#16372d] p-5"><div className="flex items-center justify-between gap-3"><div className="text-5xl font-black tracking-tight">{p!.code}</div><div className="w-14 h-14 rounded-2xl bg-[#17382e] text-white grid place-items-center text-lg font-black">{committee.code}</div></div><div className="mt-4 text-xs font-extrabold opacity-70">{ar?'الرجاء التوجه الآن':'Please proceed now'}</div></div>)}</div>:<div className="py-14 text-center text-white/35 text-sm">{ar?'لا يوجد استدعاء حاليًا':'No active call'}</div>}</section>
      <section className="rounded-[30px] border border-white/10 bg-white/[.03] p-5 sm:p-7"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.17em] text-white/40">NEXT</div><h2 className="text-xl font-black mt-1">{ar?'اقترب دورهم':'Coming up'}</h2></div><UsersRound className="w-5 h-5 text-white/45"/></div><div className="mt-5 divide-y divide-white/8">{next.map((p,i)=><div key={p.id} className="py-3 flex items-center gap-3"><div className="w-8 text-[10px] font-black text-white/30 tabular-nums">{String(i+1).padStart(2,'0')}</div><div className="flex-1 text-2xl font-black tracking-tight">{p.code}</div><div className="text-xs font-bold text-white/45">{committees.find(c=>c.id===p.assignedCommitteeId)?.code||'—'}</div></div>)}{!next.length&&<div className="py-10 text-center text-xs text-white/30">{ar?'قائمة الانتظار فارغة':'Queue is clear'}</div>}</div></section>
    </main>
    <footer className="grid sm:grid-cols-3 gap-2"><Stat icon={UsersRound} n={waiting.length} t={ar?'ينتظرون':'Waiting'}/><Stat icon={Clock3} n={committees.filter(c=>c.status==='testing').length} t={ar?'لجان تعمل':'Active panels'}/><div className="rounded-2xl border border-white/8 px-4 py-3 text-[11px] text-white/40 flex items-center">{ar?'تُعرض الأكواد فقط احترامًا للخصوصية. تعمل على أي تلفاز أو شاشة متصلة بمتصفح.':'Codes only by default for privacy. Runs on any TV or display with a browser.'}</div></footer>
   </div>
 </div>
}
const Stat=({icon:Icon,n,t}:{icon:any;n:number;t:string})=><div className="rounded-2xl border border-white/8 px-4 py-3 flex items-center gap-3"><Icon className="w-4 h-4 text-[#b9cec4]"/><div><div className="text-xl font-black">{n}</div><div className="text-[10px] text-white/35">{t}</div></div></div>;
