import React, { useMemo, useState } from 'react';
import { localizedCountry } from '../../lib/ui-language';
import { Award, BadgeCheck, CalendarClock, Check, Clock3, FileText, MapPin, QrCode, ShieldCheck } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { getCompetitionPolicy } from '../../lib/competition-config';
import { Badge } from '../design-system/Badge';
import { Button } from '../design-system/Button';
import { RegistrationFlow } from '../public/RegistrationFlow';
import { RealQRCode, makeMizanPassPayload } from '../design-system/RealQRCode';
import { TearOffQueueTicket } from '../design-system/TearOffQueueTicket';

// Shared so the visible labels and the spoken ones can never drift apart.
const STEP_LABELS=[{ar:'التسجيل',en:'Register'},{ar:'القبول',en:'Approve'},{ar:'الحضور',en:'Arrive'},{ar:'الاختبار',en:'Recite'},{ar:'الشهادة',en:'Certificate'}];

export const ParticipantDashboard: React.FC = () => {
 const store=useAppStore(); const {language,currentUser,participants,results,certificates,participantPassport,competition,checkInParticipant}=store; const ar=language==='ar';
 const [showRegistration,setShowRegistration]=useState(false); const [showAppeal,setShowAppeal]=useState(false); const [appealText,setAppealText]=useState(''); const [showCert,setShowCert]=useState(false);
 const participant=participants.find(p=>p.email===currentUser.email)||participants[0];
 const policy=getCompetitionPolicy(competition);
 const result=results.find(r=>r.participantId===participant?.id);
 const cert=certificates.find(c=>c.participantId===participant?.id);
 if(showRegistration) return <RegistrationFlow onSuccess={()=>setShowRegistration(false)}/>;
 if(!participant) return <div className="max-w-xl mx-auto px-4 py-16 text-center"><h1 className="text-2xl font-black">{ar?'ابدأ مشاركتك':'Start your participation'}</h1><Button className="mt-5" onClick={()=>setShowRegistration(true)}>{ar?'تسجيل':'Register'}</Button></div>;
 const step=statusStep(participant.status);
 const committee=store.committees.find(c=>c.id===participant.assignedCommitteeId);
 const resultVisible=policy.results.visibility==='immediate'||policy.results.visibility==='private_only'||result?.status==='published'||result?.status==='sealed';
 const passPayload=makeMizanPassPayload(participant.code);
 const queueEstimate=store.getQueueEstimate(participant.id);
 return <div className="max-w-3xl mx-auto px-4 sm:px-6 py-7 space-y-4">
  <section className="mizan-surface p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><div className="mizan-code">{participant.code}<small>{ar?'رقم وصولك':'your arrival code'}</small></div><h1 className="text-2xl sm:text-3xl font-black mt-2">{ar?participant.fullNameArabic:participant.fullName}</h1><p className="text-xs text-[#646965] mt-1">{localizedCountry(participant.country,ar)} · {participant.riwaya}</p></div><Badge>{statusText(participant.status,ar)}</Badge></div><div className="mt-7 flex items-center gap-1.5" role="list" aria-label={ar?'مراحل رحلتك':'Your journey'}>{[1,2,3,4,5].map(n=>{const state=n<step?'done':n===step?'current':'upcoming';return <React.Fragment key={n}><span role="listitem" aria-current={state==='current'?'step':undefined} aria-label={`${STEP_LABELS[n-1][ar?'ar':'en']} — ${ar?(state==='done'?'مكتملة':state==='current'?'أنت هنا':'لاحقًا'):(state==='done'?'done':state==='current'?'you are here':'upcoming')}`} className="mizan-step" data-state={state}>{state==='done'?<Check className="w-4 h-4"/>:n}</span>{n<5&&<span className="mizan-step-rule" data-done={n<step||undefined} aria-hidden="true"/>}</React.Fragment>})}</div><div className="mt-2 grid grid-cols-5" aria-hidden="true">{STEP_LABELS.map((l,i)=><span key={l.en} className="mizan-step-label" data-state={i+1===step?'current':undefined}>{ar?l.ar:l.en}</span>)}</div></section>

  {participant.status==='approved'&&<section className="mizan-surface p-6 sm:p-8 text-center"><div className="w-12 h-12 rounded-2xl bg-[#E7EEE9] text-[#214C40] grid place-items-center mx-auto"><QrCode className="w-6 h-6"/></div><h2 className="text-xl font-black mt-4">{ar?'بطاقتك جاهزة':'Your pass is ready'}</h2><div className="mt-5 w-44 h-44 border-8 border-white outline outline-1 outline-[#deddd6] bg-white rounded-2xl mx-auto grid place-items-center overflow-hidden"><RealQRCode value={passPayload} size={160} label={ar?'رمز دخول ميزان':'MIZAN entry pass'}/></div><div className="mt-3 text-[10px] font-mono text-[#656a66]">{participant.code}</div><div className="mt-5 flex flex-wrap items-center justify-center gap-4 text-xs text-[#626a65]"><span className="flex items-center gap-1.5"><CalendarClock className="w-4 h-4"/>{participant.arrivalSlot||'09:10–09:30'}</span><span className="flex items-center gap-1.5"><MapPin className="w-4 h-4"/>{competition.venueName}</span></div>{policy.operations.selfCheckIn&&<Button className="mt-6" onClick={()=>checkInParticipant(participant.id,'mobile_self')}>{ar?'أنا وصلت':'I’m here'}</Button>}</section>}

  {participant.status==='in_queue'&&<section className="mizan-surface p-7 text-center"><TearOffQueueTicket number={participant.originalQueueNumber||participant.queueNumber||1} committee={committee?.code} ar={ar}/><div className="mizan-kicker mt-2">{ar?'حالة الدور':'QUEUE STATUS'}</div><div className="text-4xl font-black mt-2">{queueEstimate?.ahead??0}</div><div className="text-sm font-bold mt-2">{(queueEstimate?.ahead||0)===0?(ar?'أنت التالي':'You’re next'):(ar?'متسابق أمامك':'ahead')}</div>{queueEstimate&&<div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f1efe9] p-3"><div className="text-lg font-black">~{queueEstimate.estimatedWaitMinutes}</div><div className="text-[10px] text-[#646965]">{ar?'دقيقة تقديريًا':'estimated min'}</div></div><div className="rounded-xl bg-[#f1efe9] p-3"><div className="text-lg font-black">{new Date(queueEstimate.expectedTurnAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><div className="text-[10px] text-[#646965]">{ar?'وقت متوقع':'estimated turn'}</div></div></div>}<div className="mt-2 text-[10px] text-[#696f6b]">{ar?'يتغير التقدير مع حركة اللجان.':'Estimate updates with live flow.'}</div><div className="mt-4 text-xs font-bold text-[#626a65]">{committee?.code||'—'} · {ar?committee?.nameArabic:committee?.name}</div></section>}

  {participant.status==='in_session'&&<section className="mizan-surface p-7 text-center bg-[#fffefb]"><span className="inline-flex w-3 h-3 rounded-full bg-[#2F6555] animate-pulse"/><h2 className="text-2xl font-black mt-4">{ar?'اختبارك جارٍ الآن':'Your recitation is in progress'}</h2><p className="text-xs text-[#646965] mt-2">{ar?'المحكم يستمع. لا تحتاج إلى أي إجراء.':'The judges are listening. No action is required from you.'}</p></section>}

  {(participant.status==='tested'||participant.status==='certified'||participant.status==='appealed')&&<section className="mizan-surface p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><div><div className="mizan-kicker">{ar?'بعد الاختبار':'AFTER RECITATION'}</div><h2 className="text-xl font-black mt-1">{resultVisible&&result?(ar?'نتيجتك':'Your result'):(ar?'تم حفظ تقييمك':'Assessment secured')}</h2></div><ShieldCheck className="w-6 h-6 text-[#2F6555]"/></div>{resultVisible&&result?<div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f1efe9] p-5 text-center"><div className="text-3xl font-black">{result.finalScore.toFixed(2)}</div><div className="text-[10px] text-[#646965] mt-1">{ar?'الدرجة':'Score'}</div></div><div className="rounded-2xl bg-[#f1efe9] p-5 text-center"><div className="text-3xl font-black">#{result.rank||'—'}</div><div className="text-[10px] text-[#646965] mt-1">{ar?'الترتيب':'Rank'}</div></div></div>:<p className="text-sm text-[#646965] mt-4">{ar?'سياسة هذه المسابقة تؤجل إظهار النتائج حتى الموعد المعتمد.':'This competition delays result visibility until the approved release point.'}</p>}<div className="mt-5 flex flex-wrap gap-4 text-xs font-bold text-[#214C40]">{policy.appeals.enabled&&resultVisible&&<button onClick={()=>setShowAppeal(true)} className="hover:underline">{ar?'تقديم اعتراض وفق اللائحة':'Appeal under competition policy'}</button>}<button onClick={()=>{const receipt=store.getFairnessReceipt(participant.id);if(!receipt)return;const blob=new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mizan-fairness-${participant.code}.json`;a.click();URL.revokeObjectURL(a.href)}} className="hover:underline">{ar?'إيصال النزاهة':'Fairness receipt'}</button></div></section>}

  {participantPassport.filter(x=>x.participantId===participant.id).length>0&&<section className="mizan-surface p-5"><div className="mizan-kicker">{ar?'سجل مشاركات ميزان':'MIZAN PASSPORT'}</div><div className="mt-3 space-y-2">{participantPassport.filter(x=>x.participantId===participant.id).slice(0,3).map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl bg-[#f3f1eb] p-3"><BadgeCheck className="w-4 h-4 text-[#2F6555]"/><div className="flex-1 min-w-0"><div className="text-xs font-bold truncate">{x.competitionName}</div><div className="text-[10px] text-[#656b66] mt-1">{x.year} · {x.categoryName}</div></div><Badge variant={x.verified?'emerald':'neutral'}>{x.verified?(ar?'موثق':'Verified'):(ar?'غير موثق':'Unverified')}</Badge></div>)}</div></section>}

  {cert&&<section className="mizan-surface p-6 flex items-center gap-4"><span className="w-12 h-12 rounded-2xl bg-[#F2EADC] text-[#89673a] grid place-items-center"><Award className="w-6 h-6"/></span><div className="flex-1"><div className="font-black">{ar?'الشهادة جاهزة':'Certificate ready'}</div><div className="text-[11px] text-[#646965] mt-1">{cert.certificateNumber}</div></div><Button variant="outline" onClick={()=>setShowCert(true)} icon={<FileText className="w-4 h-4"/>}>{ar?'فتح':'Open'}</Button></section>}


  {showAppeal&&<div role="dialog" aria-modal="true" aria-label={ar?'الشهادة':'Certificate'} className="fixed inset-0 z-50 bg-black/25 backdrop-blur-sm grid place-items-center p-4"><div className="mizan-surface p-6 w-full max-w-lg"><div className="flex items-center justify-between gap-4"><div><div className="mizan-kicker">{ar?'اعتراض':'APPEAL'}</div><h3 className="text-xl font-black mt-1">{ar?'طلب مراجعة علمية':'Scientific review request'}</h3></div><button onClick={()=>setShowAppeal(false)} className="text-xs text-[#777]">{ar?'إغلاق':'Close'}</button></div><textarea value={appealText} onChange={e=>setAppealText(e.target.value)} className="mt-5 w-full min-h-32 rounded-xl border border-[#ddd] p-3 text-sm resize-none" placeholder={ar?'اذكر الموضع أو سبب طلب المراجعة باختصار':'Briefly state the segment or reason for review'}/><div className="mt-4 flex justify-end"><Button disabled={!appealText.trim()} onClick={()=>{store.submitAppeal(participant.id,'scoring_miscalculation',appealText);setShowAppeal(false);setAppealText('')}}>{ar?'إرسال':'Submit'}</Button></div></div></div>}
  {showCert&&cert&&<div role="dialog" aria-modal="true" aria-label={ar?'الشهادة':'Certificate'} className="fixed inset-0 z-50 bg-[#16241f]/85 backdrop-blur-sm grid place-items-center p-4"><div className="bg-[#fffefb] text-[#171b18] rounded-[28px] border border-[#dfded7] p-8 w-full max-w-2xl text-center shadow-lg"><div className="mizan-kicker">{ar?'شهادة موثقة من ميزان':'MIZAN VERIFIED CERTIFICATE'}</div><div className="w-12 h-12 rounded-2xl bg-[#F2EADC] text-[#89673a] grid place-items-center mx-auto mt-5"><Award className="w-6 h-6"/></div><h2 className="text-2xl font-black mt-4">{ar?cert.participantNameArabic:cert.participantName}</h2><p className="text-sm text-[#616762] mt-2">{ar?cert.competitionNameArabic:cert.competitionName}</p><div className="mt-6 rounded-xl bg-[#f1efe9] p-4 text-xs font-mono">{cert.certificateNumber}</div><div className="mt-6 flex justify-center gap-2"><Button variant="outline" onClick={()=>setShowCert(false)}>{ar?'إغلاق':'Close'}</Button><Button onClick={()=>window.print()}>{ar?'طباعة':'Print'}</Button></div></div></div>}

  <button onClick={()=>setShowRegistration(true)} className="w-full text-center text-[11px] text-[#696f6b] py-2">{ar?'طلب تسجيل جديد / للتجربة':'New registration / demo'}</button>
 </div>
}
const statusStep=(s:string)=>s==='draft'||s==='submitted'||s==='under_review'?1:s==='approved'?2:s==='checked_in'||s==='in_queue'?3:s==='in_session'?4:5;
const statusText=(s:string,ar:boolean)=>({submitted:ar?'قيد الاستلام':'Submitted',under_review:ar?'قيد المراجعة':'Under review',approved:ar?'مقبول':'Approved',checked_in:ar?'تم الحضور':'Checked in',in_queue:ar?'بالانتظار':'Waiting',in_session:ar?'داخل اللجنة':'In session',tested:ar?'اكتمل الاختبار':'Completed',certified:ar?'معتمد':'Certified',appealed:ar?'اعتراض':'Appeal'} as Record<string,string>)[s]||s;
