import React, { useEffect, useState } from 'react';
import { Check, Keyboard, QrCode, ScanLine, X } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Button } from '../design-system/Button';
import { Participant } from '../../types';

export const KioskMode: React.FC<{onClose?:()=>void}> = ({onClose}) => {
 const {language,checkInParticipant,committees}=useAppStore(); const ar=language==='ar'; const [code,setCode]=useState(''); const [done,setDone]=useState<Participant|null>(null); const [error,setError]=useState(false);
 useEffect(()=>{if(!done)return;const t=setTimeout(()=>{setDone(null);setCode('');setError(false)},4500);return()=>clearTimeout(t)},[done]);
 const submit=()=>{const p=checkInParticipant(code.trim(),'kiosk_qr');if(p){setDone(p);setError(false)}else setError(true)};
 const committee=done?committees.find(c=>c.id===done.assignedCommitteeId):null;
 return <div className="fixed inset-0 z-50 bg-[#16241f] text-white bg-islamic-subtle p-5 sm:p-8 flex flex-col">
   <div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-white/8 border border-white/10 grid place-items-center font-black text-[#dbe7df]">م</span><div><div className="font-black">MIZAN Gate</div><div className="text-[10px] text-white/50">{ar?'حضور ذاتي':'Self check-in'}</div></div></div>{onClose&&<button onClick={onClose} className="w-10 h-10 rounded-xl grid place-items-center hover:bg-white/10 text-white/60" aria-label="close"><X className="w-5 h-5"/></button>}</div>
   <div className="my-auto max-w-lg w-full mx-auto">
    {!done?<div className="text-center"><div className="w-44 h-44 rounded-[32px] border border-white/15 bg-white/[.035] grid place-items-center mx-auto relative"><QrCode className="w-20 h-20 text-[#b9cec4] stroke-[1.3]"/><span className="absolute start-7 end-7 h-px bg-[#b9cec4]/60 shadow-[0_0_14px_rgba(185,206,196,.5)]"/></div><h1 className="text-3xl font-black mt-7">{ar?'امسح بطاقتك':'Scan your pass'}</h1><p className="text-sm text-white/50 mt-2">{ar?'لا يوجد تسجيل جديد هنا. فقط أثبت وصولك.':'No forms here. Just confirm arrival.'}</p><div className="mt-8 max-w-sm mx-auto"><div className="flex gap-2"><div className="relative flex-1"><Keyboard className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-white/40"/><input value={code} onChange={e=>{setCode(e.target.value);setError(false)}} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder={ar?'أو أدخل الكود':'Or enter code'} className="w-full rounded-xl border border-white/15 bg-white/[.06] ps-10 pe-3 py-3 text-sm text-white placeholder:text-white/30 outline-none focus:border-[#8faf9f]"/></div><Button variant="secondary" disabled={!code.trim()} onClick={submit} icon={<ScanLine className="w-4 h-4"/>}>{ar?'تحقق':'Go'}</Button></div>{error&&<div className="text-xs text-[#e3afa7] mt-2">{ar?'لم نجد هذه البطاقة. اطلب مساعدة مكتب الاستثناء.':'Pass not found. Please use the exception desk.'}</div>}</div></div>
    :<div className="rounded-[32px] border border-white/12 bg-white/[.055] p-8 text-center"><span className="w-16 h-16 rounded-full bg-[#dbe7df] text-[#214C40] grid place-items-center mx-auto"><Check className="w-8 h-8"/></span><div className="mizan-kicker !text-white/45 mt-6">{done.code}</div><h1 className="text-3xl font-black mt-2">{ar?`أهلًا ${done.fullNameArabic}`:`Welcome ${done.fullName}`}</h1><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-black/10 p-4"><div className="text-[10px] text-white/40">{ar?'أمامك':'Ahead'}</div><div className="text-3xl font-black mt-1">{Math.max(0,(done.queueNumber||1)-1)}</div></div><div className="rounded-2xl bg-black/10 p-4"><div className="text-[10px] text-white/40">{ar?'اللجنة':'Committee'}</div><div className="text-lg font-black mt-2">{committee?.code||'—'}</div></div></div><p className="text-xs text-white/45 mt-5">{ar?'توجه إلى منطقة الانتظار. سنخبرك عندما يقترب دورك.':'Proceed to the waiting area. We will notify you when your turn approaches.'}</p></div>}
   </div>
   <div className="text-center text-[10px] text-white/25">MIZAN · Quiet automation</div>
 </div>
}
