import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, Clock3, Gauge, Mic2, RadioTower, Server, UsersRound, WifiOff, Sparkles, ChevronDown } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Badge } from '../design-system/Badge';
import { Button } from '../design-system/Button';
import { Pictogram } from '../design-system/Pictogram';
import { QueueJustice } from './QueueJustice';
import { ContinuityRecovery } from './ContinuityRecovery';
import { fetchCustodyCorridor } from '../../lib/integrity-server-client';
import { GlobalSynchronizedRound } from '../admin/GlobalSynchronizedRound';
import type { QuestionCustodyCorridorSnapshot } from '../../types';

export const CommandCenter: React.FC = () => {
 const s=useAppStore(); const {language,participants,committees,incidents,isOffline,reviewCases,notifications,devices,runSimulation}=s; const ar=language==='ar';
 const [expanded,setExpanded]=useState(false); const [insight,setInsight]=useState<'why-delay'|'who-missing'|'system'|'certs'>('why-delay');
 const [corridor,setCorridor]=useState<QuestionCustodyCorridorSnapshot|null>(null);
 useEffect(()=>{let live=true;const id=s.activeSession.secureRuntimeSessionId;if(!id){setCorridor(null);return}const load=()=>void fetchCustodyCorridor(id).then(x=>live&&setCorridor(x)).catch(()=>live&&setCorridor(null));load();const timer=window.setInterval(load,5000);return()=>{live=false;window.clearInterval(timer)}},[s.activeSession.secureRuntimeSessionId]);
 const waiting=participants.filter(p=>p.status==='in_queue').length; const testing=participants.filter(p=>p.status==='in_session').length; const done=participants.filter(p=>p.status==='tested'||p.status==='certified').length;
 const sim=useMemo(()=>runSimulation(committees.length,30),[committees.length,participants.length]);
 const alerts=[...incidents.filter(i=>i.status!=='resolved').map(i=>({id:i.id,title:i.title,kind:'incident'})),...reviewCases.filter(r=>r.status==='pending').map(r=>({id:r.id,title:ar?`مراجعة ${r.participantCode}`:`Review ${r.participantCode}`,kind:'review'})),...devices.filter(d=>d.status==='offline'||d.status==='degraded').map(d=>({id:d.id,title:d.name,kind:'device'}))];
 const elastic=s.elasticityRecommendations[0];
 return <div className="max-w-[1450px] mx-auto px-4 sm:px-6 py-7 space-y-4">
  <section className="mizan-surface p-6 sm:p-8"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-5"><div className="flex items-center gap-4"><Pictogram icon={alerts.length?AlertTriangle:BadgeCheck} size="lg" tone={alerts.length?'amber':'emerald'}/><div><div className="mizan-kicker">{ar?'مركز العمليات':'MIZAN COMMAND'}</div><h1 className="text-2xl sm:text-4xl font-black mt-1">{alerts.length?(ar?`${alerts.length} حالات تحتاجك`:`${alerts.length} exceptions need you`):(ar?'كل شيء يعمل طبيعيًا':'Everything is operating normally')}</h1><p className="text-xs text-[#636864] mt-2">{alerts.length?(ar?'الروتين يعمل وحده. ركّز هنا.':'Routine is automated. Focus here.'):(ar?'لا تدخل مطلوب.':'No intervention required.')}</p></div></div><Button variant="outline" onClick={()=>setExpanded(v=>!v)} icon={<ChevronDown className={`w-4 h-4 transition ${expanded?'rotate-180':''}`}/>}>{ar?'التدفق':'Flow'}</Button></div></section>

  {alerts.length>0&&<section className="mizan-surface p-5 sm:p-6"><div className="mizan-kicker">{ar?'الحالات الاستثنائية':'EXCEPTIONS'}</div><div className="mt-2 divide-y divide-[#e5e3dc]">{alerts.slice(0,8).map(x=><div key={`${x.kind}-${x.id}`} className="py-3 flex items-center gap-3"><span className="w-2 h-2 rounded-full bg-[#9B7542]"/><div className="text-sm font-bold flex-1">{x.title}</div><Badge variant="neutral">{x.kind}</Badge></div>)}</div></section>}

  <ContinuityRecovery/>

  {s.activeSession.secureRuntimeSessionId&&<section className="mizan-surface px-5 py-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="text-[10px] font-black text-[#656a66]">{ar?'عهدة السؤال':'QUESTION CUSTODY'}</div><div className="text-sm font-black mt-1">{ar?'التشغيل يرى الحالة فقط — لا يرى نص السؤال':'Operations see state only — never question plaintext'}</div></div><Badge variant={corridor?.plaintextIncluded===false?'emerald':'amber'}>{ar?'النص غير متاح للتشغيل':'NO PLAINTEXT'}</Badge></div><div className="mt-4 flex gap-2 overflow-x-auto">{(corridor?.questions||[]).map(q=><div key={q.questionIndex} className="min-w-[150px] rounded-2xl bg-[#F5F2EA] px-4 py-3"><div className="text-[9px] text-[#6a6e6a]">{ar?`السؤال ${q.questionIndex+1}`:`Question ${q.questionIndex+1}`}</div><div className="mt-1 text-xs font-black">{ar?(q.state==='SEALED'?'مختوم':q.state==='PRESENCE_VERIFIED'?'الحضور مثبت':q.state==='QUORUM_PENDING'?'بانتظار النصاب':'تم الكشف'):q.state}</div><div className="mt-2 text-[9px] text-[#626864]">{q.approved}/{q.required} {ar?'موافقات':'approvals'}</div></div>)}{!corridor&&<div className="text-[10px] text-[#686e6a] py-2">{ar?'جاري قراءة حالة العهدة من الخادم…':'Reading server custody state…'}</div>}</div></section>}

  {waiting>=3&&<section className="mizan-surface p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><Pictogram icon={UsersRound} size="sm"/><div><div className="font-black text-sm">{ar?'موازنة اللجان':'Committee balance'}</div><div className="text-[11px] text-[#646965] mt-1">{elastic?(ar?elastic.reasonArabic:elastic.reasonEnglish):(ar?'تحليل مؤهل ومحكوم بالتعارضات.':'Constraint-aware load analysis.')}</div></div></div>{elastic?.status==='proposed'?<div className="flex gap-2"><Button size="sm" onClick={()=>s.decideCommitteeElasticity(elastic.id,true)}>{ar?'اعتماد':'Approve'}</Button><Button size="sm" variant="outline" onClick={()=>s.decideCommitteeElasticity(elastic.id,false)}>{ar?'رفض':'Dismiss'}</Button></div>:<Button size="sm" variant="outline" onClick={()=>s.recommendCommitteeElasticity()}>{ar?'حلل':'Analyze'}</Button>}</section>}

  {expanded&&<>
   <section className="mizan-surface p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><div className="mizan-kicker">{ar?'نبض الموقع':'VENUE PULSE'}</div><h2 className="font-extrabold mt-1">{ar?'نبض المكان':'Venue flow'}</h2></div><Badge variant="neutral">{ar?'مجمّع فقط':'Aggregated only'}</Badge></div><div className="grid grid-cols-5 gap-1.5 mt-4"><Pulse n={participants.filter(p=>p.status==='checked_in').length} t={ar?'بوابة':'Gate'}/><Pulse n={waiting} t={ar?'انتظار':'Wait'}/><Pulse n={testing} t={ar?'لجان':'Panels'}/><Pulse n={reviewCases.filter(r=>r.status==='pending').length} t={ar?'مراجعة':'Review'}/><Pulse n={done} t={ar?'خروج':'Exit'}/></div></section>
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={UsersRound} value={participants.length} label={ar?'في النظام':'Participants'}/><Metric icon={Clock3} value={waiting} label={ar?'ينتظرون':'Waiting'}/><Metric icon={Mic2} value={testing} label={ar?'الآن':'Testing'}/><Metric icon={BadgeCheck} value={done} label={ar?'مكتمل':'Completed'}/></div>
   <div className="grid xl:grid-cols-[1.25fr_.75fr] gap-4">
    <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><div><div className="mizan-kicker">{ar?'اللجان':'COMMITTEES'}</div><h2 className="font-extrabold mt-1">{ar?'الحمل الآن':'Live load'}</h2></div><span className="text-xs text-[#646965]">~{sim.averageWaitMinutes}m</span></div><div className="space-y-2">{committees.map(c=>{const q=participants.filter(p=>p.assignedCommitteeId===c.id&&p.status==='in_queue').length;return <div key={c.id} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 rounded-2xl border border-[#e1dfd8] p-3.5"><div className="w-10 h-10 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center font-black text-xs">{c.code}</div><div className="min-w-0"><div className="text-sm font-bold truncate">{ar?c.nameArabic:c.name}</div><div className="mt-2 h-1.5 rounded-full bg-[#eceae4] overflow-hidden"><div className="h-full bg-[#2F6555] rounded-full" style={{width:`${Math.min(100,(q/8)*100)}%`}}/></div></div><div className="text-end"><div className="text-lg font-black">{q}</div><div className="text-[10px] text-[#666b67]">{ar?'ينتظر':'queue'}</div></div></div>})}</div></section>
    <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Gauge className="w-5 h-5 text-[#2F6555]"/><h2 className="font-extrabold">{ar?'النواة':'Core'}</h2></div><div className="mt-4 space-y-2"><Health icon={Server} label={ar?'النواة':'Core'} ok/><Health icon={RadioTower} label={ar?'التوجيه':'Routing'} ok/><Health icon={Mic2} label={ar?'التحكيم':'Judging'} ok/><Health icon={WifiOff} label={ar?'دون إنترنت':'Offline'} ok note={isOffline?(ar?'نشط':'active'):undefined}/></div></section>
   </div>
   <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles className="w-4 h-4 text-[#2F6555]"/><h2 className="font-extrabold">{ar?'ملخص التشغيل':'MIZAN Insight'}</h2></div><div className="flex gap-2 overflow-x-auto mt-4">{([['why-delay',ar?'التأخير':'Delay'],['who-missing',ar?'الغياب':'Missing'],['system',ar?'النظام':'System'],['certs',ar?'الإشعارات':'Notify']] as const).map(([id,label])=><button key={id} onClick={()=>setInsight(id)} className={`shrink-0 px-3 py-2 rounded-xl text-xs font-bold border ${insight===id?'bg-[#214C40] text-white border-[#214C40]':'bg-white border-[#dedcd5] text-[#68716b]'}`}>{label}</button>)}</div><div className="mt-4 rounded-2xl bg-[#f3f1eb] p-4 text-sm font-semibold leading-7">{insight==='why-delay'?(ar?`أبطأ لجنة: ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.code||'—'} · ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.averageSessionMinutes||0} د.`:`Slowest: ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.code||'—'} · ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.averageSessionMinutes||0}m.`):insight==='who-missing'?(ar?`${participants.filter(p=>!p.checkedInAt&&['approved','submitted','under_review'].includes(p.status)).length} لم يصلوا.`:`${participants.filter(p=>!p.checkedInAt&&['approved','submitted','under_review'].includes(p.status)).length} have not arrived.`):insight==='system'?(ar?`${devices.filter(d=>d.status==='online').length}/${devices.length} أجهزة · ${isOffline?'محلي':'متصل'}.`:`${devices.filter(d=>d.status==='online').length}/${devices.length} devices · ${isOffline?'local':'connected'}.`):(ar?`${notifications.filter(n=>n.status==='failed').length} متعثر.`:`${notifications.filter(n=>n.status==='failed').length} failed.`)}</div></section>
   <QueueJustice/>
   <GlobalSynchronizedRound/>
  </>}
 </div>
}
const Metric=({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:number;label:string})=><div className="mizan-surface p-4"><Icon className="w-4 h-4 text-[#2F6555]"/><div className="text-3xl font-black mt-4">{value}</div><div className="text-[11px] text-[#646965] mt-1">{label}</div></div>;
const Health=({icon:Icon,label,ok,note}:{icon:React.ComponentType<{className?:string}>;label:string;ok:boolean;note?:string})=><div className="rounded-xl bg-[#f1efe9] p-3 flex items-center gap-3"><span className={`w-8 h-8 rounded-lg grid place-items-center ${ok?'bg-[#E7EEE9] text-[#214C40]':'bg-[#F4E6E3] text-[#A34D43]'}`}><Icon className="w-4 h-4"/></span><div><div className="text-xs font-bold">{label}</div><div className="text-[10px] text-[#656b66] mt-0.5">{note||(ok?'جاهز':'يحتاج انتباه')}</div></div></div>;

const Pulse=({n,t}:{n:number;t:string})=><div className="rounded-xl bg-[#f1efe9] p-2 sm:p-3 text-center min-w-0"><div className="text-xl sm:text-2xl font-black tabular-nums">{n}</div><div className="text-[9px] sm:text-[10px] text-[#646965] truncate mt-1">{t}</div></div>;
