import React, { useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, Clock3, Gauge, Mic2, RadioTower, Server, UsersRound, WifiOff, Sparkles } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Badge } from '../design-system/Badge';

export const CommandCenter: React.FC = () => {
 const {language,participants,committees,incidents,isOffline,reviewCases,notifications,devices,runSimulation}=useAppStore(); const ar=language==='ar'; const [insight,setInsight]=useState<'why-delay'|'who-missing'|'system'|'certs'>('why-delay');
 const waiting=participants.filter(p=>p.status==='in_queue').length; const testing=participants.filter(p=>p.status==='in_session').length; const done=participants.filter(p=>p.status==='tested'||p.status==='certified').length;
 const sim=useMemo(()=>runSimulation(committees.length,30),[committees.length,participants.length]);
 const alerts=[...incidents.filter(i=>i.status!=='resolved').map(i=>({id:i.id,title:i.title,kind:'incident'})),...reviewCases.filter(r=>r.status==='pending').map(r=>({id:r.id,title:ar?`مراجعة ${r.participantCode}`:`Review ${r.participantCode}`,kind:'review'}))];
 return <div className="max-w-[1450px] mx-auto px-4 sm:px-6 py-7 space-y-5">
  <div className="flex items-end justify-between gap-4"><div><div className="mizan-kicker">MIZAN COMMAND</div><h1 className="text-3xl sm:text-4xl font-black mt-1">{ar?'المسابقة تحت السيطرة':'Competition under control'}</h1><p className="text-sm text-[#747b76] mt-2">{ar?'نعرض الاستثناءات، لا الضجيج.':'Only exceptions get your attention.'}</p></div><Badge variant={alerts.length?'amber':'emerald'}>{alerts.length?`${alerts.length} ${ar?'تحتاج انتباه':'need attention'}`:(ar?'كل شيء طبيعي':'All normal')}</Badge></div>

  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={UsersRound} value={participants.length} label={ar?'في النظام':'Participants'}/><Metric icon={Clock3} value={waiting} label={ar?'ينتظرون':'Waiting'}/><Metric icon={Mic2} value={testing} label={ar?'يختبرون الآن':'Testing now'}/><Metric icon={BadgeCheck} value={done} label={ar?'مكتمل':'Completed'}/></div>

  <div className="grid xl:grid-cols-[1.25fr_.75fr] gap-4">
   <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><div><div className="mizan-kicker">{ar?'اللجان':'COMMITTEES'}</div><h2 className="font-extrabold mt-1">{ar?'الحمل الحقيقي الآن':'Live workload'}</h2></div><span className="text-xs text-[#777e79]">{ar?`متوسط الانتظار ${sim.averageWaitMinutes} د`:`Avg wait ${sim.averageWaitMinutes}m`}</span></div><div className="space-y-2">{committees.map(c=>{const q=participants.filter(p=>p.assignedCommitteeId===c.id&&p.status==='in_queue').length; return <div key={c.id} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 rounded-2xl border border-[#e1dfd8] p-3.5"><div className="w-10 h-10 rounded-xl bg-[#E7EEE9] text-[#214C40] grid place-items-center font-black text-xs">{c.code}</div><div className="min-w-0"><div className="text-sm font-bold truncate">{ar?c.nameArabic:c.name}</div><div className="mt-2 h-1.5 rounded-full bg-[#eceae4] overflow-hidden"><div className="h-full bg-[#2F6555] rounded-full" style={{width:`${Math.min(100,(q/8)*100)}%`}}/></div></div><div className="text-end"><div className="text-lg font-black">{q}</div><div className="text-[10px] text-[#7d847f]">{ar?'ينتظر':'queue'}</div></div></div>})}</div></section>
   <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><AlertTriangle className={`w-5 h-5 ${alerts.length?'text-[#9B7542]':'text-[#2F6555]'}`}/><h2 className="font-extrabold">{ar?'الاستثناءات':'Exceptions'}</h2></div><div className="mt-4 space-y-1">{alerts.length?alerts.slice(0,8).map(x=><div key={x.id} className="py-3 border-b border-[#e6e4dd] last:border-0"><div className="text-xs font-bold">{x.title}</div><div className="text-[10px] text-[#7d847f] mt-1">{x.kind==='review'?(ar?'تحكيم يحتاج قرارًا':'Judging review'):(ar?'حادث تشغيلي':'Operational incident')}</div></div>):<div className="text-center py-10"><BadgeCheck className="w-7 h-7 text-[#2F6555] mx-auto"/><div className="text-xs font-bold mt-2">{ar?'لا توجد حالات غير طبيعية':'No active exceptions'}</div></div>}</div></section>
  </div>


  <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles className="w-4 h-4 text-[#2F6555]"/><div><div className="mizan-kicker">MIZAN INSIGHT</div><h2 className="font-extrabold mt-1">{ar?'إجابة من بيانات المسابقة، لا تخمين':'Answers from competition data, not guesses'}</h2></div></div><div className="flex gap-2 overflow-x-auto mt-4">{([['why-delay',ar?'ليش التأخير؟':'Why delays?'],['who-missing',ar?'من لم يصل؟':'Who is missing?'],['system',ar?'هل النظام سليم؟':'System health'],['certs',ar?'الإشعارات؟':'Notifications']] as const).map(([id,label])=><button key={id} onClick={()=>setInsight(id)} className={`shrink-0 px-3 py-2 rounded-xl text-xs font-bold border ${insight===id?'bg-[#214C40] text-white border-[#214C40]':'bg-white border-[#dedcd5] text-[#68716b]'}`}>{label}</button>)}</div><div className="mt-4 rounded-2xl bg-[#f3f1eb] p-4 text-sm font-semibold leading-7">{insight==='why-delay'?(ar?`أبطأ لجنة الآن: ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.code||'—'} · متوسط الجلسة ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.averageSessionMinutes||0} دقيقة.`:`Slowest panel: ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.code||'—'} · ${[...committees].sort((a,b)=>b.averageSessionMinutes-a.averageSessionMinutes)[0]?.averageSessionMinutes||0} min average.`):insight==='who-missing'?(ar?`${participants.filter(p=>!p.checkedInAt&&['approved','submitted','under_review'].includes(p.status)).length} مشاركًا لم يسجلوا حضورهم بعد.`:`${participants.filter(p=>!p.checkedInAt&&['approved','submitted','under_review'].includes(p.status)).length} participants have not checked in yet.`):insight==='system'?(ar?`${devices.filter(d=>d.status==='online').length}/${devices.length} أجهزة متصلة · ${isOffline?'العمل المحلي مفعل':'السحابة متصلة'}.`:`${devices.filter(d=>d.status==='online').length}/${devices.length} devices online · ${isOffline?'local continuity active':'cloud connected'}.`):(ar?`${notifications.filter(n=>n.status==='failed').length} إشعار متعثر من ${notifications.length}.`:`${notifications.filter(n=>n.status==='failed').length} failed of ${notifications.length} notifications.`)}</div><div className="text-[10px] text-[#858b87] mt-2">{ar?'هذه الطبقة حسابية محلية؛ عند ربط Copilot يمكن تفسير أعمق مع بقاء الصلاحيات خارج النموذج.':'This local layer is deterministic; a connected Copilot can add explanation while authorization remains outside the model.'}</div></section>
  <section className="mizan-surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="mizan-kicker">SYSTEM HEALTH</div><h2 className="font-extrabold mt-1">{ar?'الأساس يعمل حتى لو تعطلت الإضافات':'Core survives optional service failures'}</h2></div><Gauge className="w-5 h-5 text-[#2F6555]"/></div><div className="grid sm:grid-cols-4 gap-2 mt-5"><Health icon={Server} label={ar?'النواة':'Core'} ok/><Health icon={RadioTower} label={ar?'التوجيه':'Routing'} ok/><Health icon={Mic2} label={ar?'الصوت':'Audio'} ok/><Health icon={WifiOff} label={ar?'استمرارية دون إنترنت':'Offline continuity'} ok={true} note={isOffline?(ar?'نشط الآن':'active now'):undefined}/></div></section>
 </div>
}
const Metric=({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:number;label:string})=><div className="mizan-surface p-4"><Icon className="w-4 h-4 text-[#2F6555]"/><div className="text-3xl font-black mt-4">{value}</div><div className="text-[11px] text-[#777e79] mt-1">{label}</div></div>;
const Health=({icon:Icon,label,ok,note}:{icon:React.ComponentType<{className?:string}>;label:string;ok:boolean;note?:string})=><div className="rounded-xl bg-[#f1efe9] p-3 flex items-center gap-3"><span className={`w-8 h-8 rounded-lg grid place-items-center ${ok?'bg-[#E7EEE9] text-[#214C40]':'bg-[#F4E6E3] text-[#A34D43]'}`}><Icon className="w-4 h-4"/></span><div><div className="text-xs font-bold">{label}</div><div className="text-[10px] text-[#7b827d] mt-0.5">{note|| (ok?'OK':'Attention')}</div></div></div>;
