import React, {useMemo, useState} from 'react';
import { BatteryWarning, BadgeCheck, RotateCcw, ShieldAlert, WifiOff, MonitorX, MicOff, Siren, LockKeyhole, TriangleAlert } from 'lucide-react';
import { useAppStore } from '../../lib/store';
import { Button } from '../design-system/Button';
import { Badge } from '../design-system/Badge';
import type { ContinuityIncidentRecord } from '../../types';

const incidentIcon:Record<ContinuityIncidentRecord['type'],React.ComponentType<{className?:string}>>={POWER_LOSS:BatteryWarning,NETWORK_LOSS:WifiOff,DEVICE_FAILURE:MonitorX,BROWSER_CRASH:MonitorX,AUDIO_FAILURE:MicOff,VENUE_EVACUATION:Siren,UNKNOWN:ShieldAlert};
const arDecision=(x:string)=>({RESUME_SAME_SESSION_SAME_QUESTION:'استكمال نفس الجلسة ونفس السؤال',RESUME_SAME_SESSION_NEXT_QUESTION:'استكمال نفس الجلسة من الموضع التالي',RESTORE_LOCKED_PANEL:'استعادة الأحكام المقفلة كما هي',HEAD_JUDGE_ADJUDICATION:'قرار موثق من رئيس التحكيم',FULL_RETEST_LAST_RESORT:'إعادة كاملة — حل أخير فقط'} as Record<string,string>)[x]||x;
const incidentLabel=(x:string,ar:boolean)=>({POWER_LOSS:ar?'انقطاع كهرباء':'Power loss',NETWORK_LOSS:ar?'انقطاع شبكة':'Network loss',DEVICE_FAILURE:ar?'تعطل جهاز':'Device failure',BROWSER_CRASH:ar?'تعطل المتصفح':'Browser failure',AUDIO_FAILURE:ar?'تعطل الصوت':'Audio failure',VENUE_EVACUATION:ar?'إخلاء القاعة':'Venue evacuation',UNKNOWN:ar?'حالة غير متوقعة':'Unexpected incident'} as Record<string,string>)[x]||x;

export const ContinuityRecovery:React.FC=()=>{
 const s=useAppStore();const ar=s.language==='ar';
 const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const [retestReason,setRetestReason]=useState('');const [approvalReason,setApprovalReason]=useState('');
 const open=useMemo(()=>s.continuityIncidents.filter(x=>x.status!=='RESOLVED'),[s.continuityIncidents]);
 const latest=open[0];
 const proposals=latest?s.sessionRecoveries.filter(x=>x.incidentId===latest.id&&x.status==='PROPOSED'):[];
 const retest=proposals.find(x=>x.decision==='FULL_RETEST_LAST_RESORT');
 const recovery=proposals.find(x=>x.decision!=='FULL_RETEST_LAST_RESORT');
 const cp=latest?s.sessionCheckpoints.find(x=>x.id===latest.lastCheckpointId):undefined;
 const canApproveRetest=['comp_admin','org_admin'].includes(s.currentUser.role);
 const canRequestRetest=s.currentUser.role==='head_judge'&&recovery?.decision==='HEAD_JUDGE_ADJUDICATION'&&!retest;
 const report=async(type:ContinuityIncidentRecord['type'])=>{setBusy(type);const r=await s.reportSessionInterruption(type,ar?'سُجل من مركز العمليات':'Reported from operations');setBusy('');setMsg(r?(ar?'جُمّدت آخر حالة موثقة. لا إعادة سؤال ولا مسح للأحكام.':'Last trusted state frozen. No redraw and no locked judgment is erased.'):(ar?'لا توجد جلسة نشطة لحفظها.':'No active session to checkpoint.'))};
 const plan=async()=>{if(!latest)return;setBusy('plan');const r=await s.proposeSessionRecovery(latest.id);setBusy('');setMsg(r?(ar?`الخطة: ${arDecision(r.decision)}`:`Recovery: ${r.decision}`):(ar?'تعذر بناء خطة الاستعادة.':'Could not build recovery plan.'))};
 const apply=async()=>{if(!recovery)return;setBusy('apply');const r=await s.applySessionRecovery(recovery.id,recovery.decision==='HEAD_JUDGE_ADJUDICATION'?(ar?'اعتماد الاستكمال من آخر نقطة يمكن إثباتها مع حفظ كل الأدلة السابقة':'Resume from the last provable state while preserving all prior evidence'):undefined);setBusy('');setMsg(r.ok?(ar?'تمت الاستعادة دون تغيير السؤال المكشوف أو الأحكام المقفلة.':'Recovered without changing the revealed question or locked submissions.'):r.reason)};
 const requestRetest=()=>{if(!latest||retestReason.trim().length<10)return;setBusy('retest-request');const r=s.requestFullRetestLastResort(latest.id,retestReason.trim());setBusy('');setMsg(r?(ar?'تم تسجيل اقتراح الإعادة الكاملة. لن تنفذ قبل موافقة سلطة ثانية مستقلة.':'Full retest proposed. It will not execute before independent second approval.'):(ar?'الإعادة الكاملة غير متاحة ما دام يوجد مسار استعادة موثوق.':'Full retest is unavailable while a trustworthy recovery path exists.'));if(r)setRetestReason('')};
 const approveRetest=async()=>{if(!retest||approvalReason.trim().length<10)return;setBusy('retest-approve');const r=await s.approveFullRetestLastResort(retest.id,approvalReason.trim());setBusy('');setMsg(r.ok?(ar?`بدأت محاولة جديدة ${r.retestSessionId}، وبقيت المحاولة الأصلية محفوظة بالكامل.`:`New attempt ${r.retestSessionId} started; the original attempt remains fully preserved.`):r.reason);if(r.ok)setApprovalReason('')};
 return <section className="mizan-surface p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="mizan-kicker">{ar?'استمرارية الاختبار':'SESSION CONTINUITY'}</div><h2 className="font-black mt-1">{latest?(ar?'هناك جلسة تحتاج استعادة':'A session needs recovery'):(ar?'الانقطاع لا يعيد الاختبار':'Failure does not reset the participant')}</h2><p className="text-[11px] leading-6 text-[#747b76] mt-2 max-w-2xl">{ar?'الكهرباء أو الشبكة أو تعطل الجهاز لا يمنح سؤالًا جديدًا تلقائيًا. السؤال المكشوف يبقى نفسه، وأحكام المحكمين المقفلة تبقى مقفلة. الإعادة الكاملة استثناء بموافقتين مستقلتين فقط.':'Power, network or device failure never grants a fresh question automatically. The revealed question and locked human judgments remain preserved. A full retest is an exceptional two-authority path only.'}</p></div><Badge variant={latest?'amber':'emerald'}>{latest?(ar?'استعادة':'Recovery'):(ar?'محمي':'Protected')}</Badge></div>
 {!latest&&s.activeSession.participant&&<div className="mt-4 flex flex-wrap gap-2">{([['POWER_LOSS',BatteryWarning,ar?'كهرباء':'Power'],['NETWORK_LOSS',WifiOff,ar?'شبكة':'Network'],['DEVICE_FAILURE',MonitorX,ar?'جهاز':'Device'],['AUDIO_FAILURE',MicOff,ar?'صوت':'Audio'],['VENUE_EVACUATION',Siren,ar?'إخلاء':'Evacuation']] as const).map(([type,Icon,label])=><Button key={type} size="sm" variant="outline" disabled={!!busy} onClick={()=>void report(type)} icon={<Icon className="w-4 h-4"/>}>{label}</Button>)}</div>}
 {latest&&<div className="mt-4 rounded-2xl border border-[#dedbd3] p-4"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-[#F2EADC] text-[#8a6537] grid place-items-center">{React.createElement(incidentIcon[latest.type],{className:'w-5 h-5'})}</span><div className="flex-1"><div className="text-sm font-black">{incidentLabel(latest.type,ar)}</div><div className="text-[10px] text-[#7b827d] mt-1">{new Date(latest.occurredAt).toLocaleString(ar?'ar-KW':'en-US')} · {latest.sessionId}</div></div><Badge variant="amber">{latest.status}</Badge></div>
 {cp&&<div className="grid grid-cols-3 gap-2 mt-4"><Mini t={ar?'المرحلة':'Phase'} v={cp.phase}/><Mini t={ar?'السؤال':'Question'} v={String(cp.questionIndex+1)}/><Mini t={ar?'نقطة الحفظ':'Checkpoint'} v={`#${cp.sequence}`}/></div>}
 <div className="mt-4 flex flex-wrap gap-2">{!recovery&&!retest&&<Button size="sm" disabled={!!busy} onClick={()=>void plan()} icon={<RotateCcw className="w-4 h-4"/>}>{ar?'بناء خطة الاستعادة':'Plan recovery'}</Button>}{recovery&&!retest&&<><div className="flex-1 min-w-56 rounded-xl bg-[#E7EEE9] px-3 py-2"><div className="text-[10px] font-black text-[#214C40]">{ar?arDecision(recovery.decision):recovery.decision}</div><div className="text-[9px] text-[#60766e] mt-1">{ar?'نفس المتسابق · لا سحب جديد · الأحكام المقفلة محفوظة':'Same participant · no redraw · locked submissions preserved'}</div></div><Button size="sm" disabled={!!busy||recovery.decision==='HEAD_JUDGE_ADJUDICATION'&&s.currentUser.role!=='head_judge'} onClick={()=>void apply()} icon={<BadgeCheck className="w-4 h-4"/>}>{ar?'استعادة':'Recover'}</Button></>}</div>
 {canRequestRetest&&<div className="mt-4 rounded-xl border border-[#e3d5c7] bg-[#fbf7f0] p-4"><div className="flex gap-2"><TriangleAlert className="w-4 h-4 text-[#8a6537] shrink-0 mt-0.5"/><div><div className="text-xs font-black">{ar?'فقط إذا تعذر إثبات نقطة عادلة للاستكمال':'Only if a fair resume point cannot be proven'}</div><p className="text-[10px] leading-5 text-[#7a7065] mt-1">{ar?'رئيس التحكيم يستطيع اقتراح إعادة كاملة، لكنه لا يستطيع تنفيذها. يلزم مدير المسابقة أو المؤسسة كشخص ثانٍ مستقل، وتبقى المحاولة الأصلية محفوظة.':'The Head Judge may propose a full retest but cannot execute it. A different Competition/Organization Admin must approve, and the original attempt remains preserved.'}</p></div></div><textarea value={retestReason} onChange={e=>setRetestReason(e.target.value)} className="mizan-input mt-3 min-h-20 resize-none" placeholder={ar?'لماذا أصبحت الاستعادة غير قابلة للإثبات؟':'Why is recovery no longer provable?'}/><Button className="mt-2" size="sm" variant="outline" disabled={!!busy||retestReason.trim().length<10} onClick={requestRetest} icon={<LockKeyhole className="w-4 h-4"/>}>{ar?'اقتراح إعادة كاملة بموافقتين':'Propose two-authority full retest'}</Button></div>}
 {retest&&<div className="mt-4 rounded-xl border border-[#e1d6ca] p-4"><div className="flex items-start gap-3"><LockKeyhole className="w-5 h-5 text-[#7a5f3d] shrink-0"/><div className="flex-1"><div className="text-xs font-black">{ar?'إعادة كاملة معلّقة — تحتاج سلطة ثانية':'Full retest pending — second authority required'}</div><div className="text-[10px] leading-5 text-[#777269] mt-1">{retest.reason}</div><div className="text-[9px] text-[#8b8780] mt-2">{ar?'المحاولة الأصلية لا تُحذف ولا تُستبدل.':'The original attempt is never deleted or overwritten.'}</div></div></div>{canApproveRetest?<><textarea value={approvalReason} onChange={e=>setApprovalReason(e.target.value)} className="mizan-input mt-3 min-h-20 resize-none" placeholder={ar?'سبب موافقتك المستقلة بعد مراجعة الأدلة':'Independent approval reason after reviewing the evidence'}/><Button className="mt-2" size="sm" disabled={!!busy||approvalReason.trim().length<10} onClick={()=>void approveRetest()} icon={<BadgeCheck className="w-4 h-4"/>}>{ar?'أعتمد الإعادة الاستثنائية':'Approve exceptional retest'}</Button></>:<div className="mt-3 text-[10px] font-bold text-[#7b827d]">{ar?'بانتظار مدير المسابقة/المؤسسة المختلف عن صاحب الاقتراح.':'Waiting for a different Competition/Organization Admin.'}</div>}</div>}
 </div>}
 {msg&&<div aria-live="polite" className="mt-3 text-[11px] font-bold text-[#59645e]">{msg}</div>}
 </section>
}
const Mini=({t,v}:{t:string;v:string})=><div className="rounded-xl bg-[#f3f1eb] p-3 min-w-0"><div className="text-[9px] text-[#7d847f]">{t}</div><div className="text-[10px] font-black mt-1 truncate">{v}</div></div>;
