import React, {useState} from 'react';
import { signInWithEmailAndPassword, sendPasswordResetEmail } from 'firebase/auth';
import { LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { auth } from '../../lib/firebase';
import { Button } from '../design-system/Button';

export const AuthPortal:React.FC=()=>{
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const signIn=async()=>{setBusy(true);setMessage('');try{await signInWithEmailAndPassword(auth,email,password);}catch(e:any){setMessage(e?.code==='auth/invalid-credential'?'بيانات الدخول غير صحيحة / Invalid credentials':'تعذر تسجيل الدخول / Sign-in failed');}finally{setBusy(false)}};
 const reset=async()=>{if(!email)return setMessage('أدخل البريد أولًا / Enter your email first');setBusy(true);try{await sendPasswordResetEmail(auth,email);setMessage('تم إرسال رابط الاستعادة / Reset link sent');}catch{setMessage('تعذر إرسال الرابط / Could not send reset link');}finally{setBusy(false)}};
 return <div className="min-h-screen bg-[#f7f5ef] grid place-items-center p-5"><div className="w-full max-w-md"><div className="text-center"><div className="w-14 h-14 rounded-2xl bg-[#214C40] text-white grid place-items-center font-black text-xl mx-auto">م</div><div className="mizan-kicker mt-6">MIZAN SECURE ACCESS</div><h1 className="text-3xl font-black mt-2">دخول آمن</h1><p className="text-xs text-[#737a75] mt-2">Identity and tenant permissions are enforced before operational access.</p></div><div className="mizan-surface p-6 mt-7"><label className="block"><span className="text-[10px] font-black text-[#767d78]">EMAIL</span><div className="relative mt-2"><Mail className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-[#8b918d]"/><input autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-[#ddd] ps-10 pe-3 py-3 text-sm"/></div></label><label className="block mt-4"><span className="text-[10px] font-black text-[#767d78]">PASSWORD</span><div className="relative mt-2"><LockKeyhole className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-[#8b918d]"/><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&signIn()} className="w-full rounded-xl border border-[#ddd] ps-10 pe-3 py-3 text-sm"/></div></label>{message&&<div className="mt-4 rounded-xl bg-[#f3f1eb] px-3 py-2.5 text-xs font-semibold">{message}</div>}<Button className="w-full mt-5" disabled={busy||!email||!password} onClick={signIn} icon={<ShieldCheck className="w-4 h-4"/>}>{busy?'…':'Sign in'}</Button><button onClick={reset} className="w-full mt-4 text-xs font-bold text-[#45675b]">Forgot password?</button></div><p className="text-[10px] text-[#858b87] text-center mt-5">MFA and step-up policies are tenant-controlled. Firebase provider enrollment must be configured by the deploying organization.</p></div></div>
}
